### PR TITLE
[Merge Account] Remove the initial route from state after successful merge

### LINKED ISSUE #59764: [$250] Android - App returns to Merge accounts flow when using back button after merging account
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.24-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://github.com/Expensify/App/pull/56911
**Email or phone of affected tester (no customers):** applausetester+t16@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Samsung Galaxy Z Fold 4 / Android 14
**App Component:** User Settings

## Action Performed:
1. Launch Expensify app.
2. Go to Settings > Security.
3. Tap Merge account.
4. Enter email of another account.
5. Mark "I understand this is not reversible" checkbox.
6. Click Next.
7. Enter magic code.
8. On success page, use device back button.

## Expected Result:
App will return to Security page.

## Actual Result:
App returns to Merge accounts flow.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ccac7e3b-38e9-4d9e-ac98-ddfc84070d70

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021915068856610252811</li>
        <li>Upwork Job ID: 1915068856610252811</li>
        <li>Last Price Increase: 2025-04-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

### LINKED ISSUE #60757: Settings-Error message mentions two-factor authentication code instead of magic code
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.32-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/59911
**Email or phone of affected tester (no customers):** applausetester+ag2304.3@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Windows 10/ Chrome, Samsung S23FE/ Android 14
**App Component:** User Settings

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Log in with any Expensifail account
3. Go to Account > Security
4. Click on Merge account
5. Enter any email that has a valid Expensify account
6. Mark "I understand this is not reversible" checkbox.
7. Click Next
8. Enter the incorrect magic code

## Expected Result:
The error message should mention the magic code in its text.

## Actual Result:
The error message mentions "two-factor authentication code" instead of magic code.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/155ee889-363f-4938-9f07-8829453e1aab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

### PR DESCRIPTION
**Pull request by allroundexperts**
### Explanation of Change

Remove the initial route from state after successful merge

fixes https://github.com/Expensify/App/issues/59764
fixes https://github.com/Expensify/App/issues/60757

### Fixed Issues

$ https://github.com/Expensify/App/issues/59764
$ https://github.com/Expensify/App/issues/60757
PROPOSAL: N/A

### Tests

**Test 1**

1. Launch Expensify app.
2. Go to Settings > Security.
3. Tap Merge account.
4. Enter email of another account.
5. Mark "I understand this is not reversible" checkbox.
6. Click Next.
7. Enter magic code.
8. On success page, use device back button.

Verify that you don't end up on the Merge account details page

** Test 2**

1. Open the app, Go to Account > Security
2. Click on Merge account
3. Enter any email that has a valid Expensify account
4. Mark "I understand this is not reversible" checkbox.
5. Click Next and Enter the incorrect magic code

Verify that the error message shown reads: "Incorrect or invalid magic code. Please try again or request a new code."

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

Same as above

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/f2416e48-470e-4b32-b57e-e39fb1960d14

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/7c41c805-a174-4e82-b0bb-ffb5772dcb7b

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/b7614d9d-cb96-4594-90e7-667cb1bc4e3c

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/d7b12493-73dd-4efe-8d38-ba88ec39f0f1

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/4b8656af-7e07-4e76-9a18-61a9452ed5fd

Screenshot 2025-04-24 at 3 46 10 AM

</details>

<details>
<summary>MacOS: Desktop</summary>

N/A
</details>

### CODE REVIEW

File: src/pages/settings/Security/MergeAccounts/MergeResultPage.tsx [hunk 1]
```diff
@@ -228,6 +228,14 @@ function MergeResultPage() {
         };
     }, [setRootStatusBarEnabled, login, translate, userEmailOrPhone, styles]);
 
+    useEffect(() => {
```
Comment (arosiclair) [inline src/pages/settings/Security/MergeAccounts/MergeResultPage.tsx:231]: Can you add a comment here explaining why we need to do this (to prevent users from navigating back after the merge)?

**Comment by allroundexperts** [comment]
> @allroundexperts Testing failed on web on pressing browser back button.
> 
>  29.04.2025_21.35.06_REC.mp4

@parasharrajat This is to be tested on the success page. On error page, the back button should work as usual.

**Comment by allroundexperts** [comment]
> Also, notice this weird navigation history.
> 
> Steps:
> 
> 1. Add an email, Go to validate code step.
> 2. GO back from browser button.
> 3. Change email, go to validate code,
> 4. Now press browser back button a few times to notice both flow will be repeated.
> 
>  29.04.2025_21.39.14_REC.mp4

Not sure if this is a bug. It's taking you back to the pages that you visited.

**Comment by arosiclair** [comment]
> > Also, notice this weird navigation history.
> > Steps:
> > 
> > 1. Add an email, Go to validate code step.
> > 2. GO back from browser button.
> > 3. Change email, go to validate code,
> > 4. Now press browser back button a few times to notice both flow will be repeated.
> > 
> > 29.04.2025_21.39.14_REC.mp4
> 
> Not sure if this is a bug. It's taking you back to the pages that you visited.

Definitely looks like a bug. Why are we pushing so many copies of the email page onto the stack? Let's try to fix that so there's only one.

**Comment by allroundexperts** [comment]
> Definitely looks like a bug. Why are we pushing so many copies of the email page onto the stack? Let's try to fix that so there's only one.

Done.

**Comment by allroundexperts** [comment]
> > https://github.com/Expensify/App/pull/60751#issuecomment-2839475784
> 
> 
> 
> This does not look solved. I can still see email page history. 

Screen recording please?

**Comment by allroundexperts** [comment]
@parasharrajat What's the latest here?

**Comment by allroundexperts** [comment]
Please do so. Let's try to finish this today.

**Comment by allroundexperts** [comment]
@parasharrajat Can you please prioritise the review here? It's been 20 hours since your last comment.

**Comment by allroundexperts** [comment]
Let's not block this PR because of this. We can handle it as a follow up.

**Comment by arosiclair** [comment]
> Can we improve this behavior also where navigating forward, the previous validate code screen is shown?

I think this behavior is fine since nothing is broken after navigating like this.

> BUG: Android: Wrong animation for the result page.

Agree this should animate in from the right. Is that something we can fix @allroundexperts?

> May be BUG: I noticed this twice on android that the merge accounts button does not react to click on initial click.

Are you also seeing this @allroundexperts?

**Comment by arosiclair** [comment]
Alright can you conclude your review @parasharrajat?

**Comment by allroundexperts** [comment]
@parasharrajat I have already mentioned that. This is clearly a bug of navigation that SWM should solve. Let's not block this PR because of that.

**Comment by WojtekBoman** [comment]
@allroundexperts This code snippet should solve the animation problem

```diff
diff --git a/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx b/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
index bd13b29b1dd..f8c0b519c99 100644
--- a/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
+++ b/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
@@ -2,6 +2,7 @@ import type {ParamListBase} from '@react-navigation/routers';
 import React from 'react';
 import createPlatformStackNavigator from '@libs/Navigation/PlatformStackNavigation/createPlatformStackNavigator';
 import Animations from '@libs/Navigation/PlatformStackNavigation/navigationOptions/animation';
+import type {PlatformStackNavigationOptions} from '@libs/Navigation/PlatformStackNavigation/types';
 import type {
     AddPersonalBankAccountNavigatorParamList,
     AddUnreportedExpensesParamList,
@@ -47,6 +48,12 @@ import useModalStackScreenOptions from './useModalStackScreenOptions';
 
 type Screens = Partial<Record<Screen, () => React.ComponentType>>;
 
+const OPTIONS_PER_SCREEN: Partial<Record<Screen, PlatformStackNavigationOptions>> = {
+    [SCREENS.SETTINGS.MERGE_ACCOUNTS.MERGE_RESULT]: {
+        animationTypeForReplace: 'push',
+    },
+};
+
 /**
  * Create a modal stack navigator with an array of sub-screens.
  *
@@ -66,6 +73,7 @@ function createModalStackNavigator<ParamList extends ParamListBase>(screens: Scr
                         key={name}
                         name={name}
                         getComponent={(screens as Required<Screens>)[name as Screen]}
+                        options={OPTIONS_PER_SCREEN[name as Screen]}
                     />
                 ))}
             </ModalStackNavigator.Navigator>
~
~
~
~
~
~
~
~
~
~


```

**Comment by allroundexperts** [comment]
@parasharrajat I applied the suggestion and it fixed the issue.

https://github.com/user-attachments/assets/a8169b57-06b7-4b9f-aacf-0da11b914b79

**Comment by allroundexperts** [comment]
Bump here @parasharrajat

**Comment by allroundexperts** [comment]
> Android: This is related to double click issue. After entering a wrong code, it takes 2 clicks to submit next code. First click on Merge accounts button hide the keyboard. 
> 
> 
> 
> 
> 
> https://github.com/user-attachments/assets/d3ada0a2-1bba-4fee-8954-512dfb5b6693
> 
> 
> 
> 

This is not related to the bugs we're solving in this PR. Let's not block it because of this.

**Review by parasharrajat — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.


:ribbon: :eyes: :ribbon:  C+ reviewed

**Review by arosiclair — APPROVED** [review]
