### PR TITLE
Fixed Create Group button showing without selections

### LINKED ISSUE #1418: [Consumer UI Refresh] Create Group confirmation button visible without attendees selected
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
Desktop & iOS - v1.0.1-419

**Action Performed (reproducible steps):**
1. Open Global Create
2. Select New Group
3. Notice the `Create Group` confirmation button is visible when attendees aren't selected

**Expected Result:**

image

**Actual Result:**

image

**Notes**
 CC: @lucas-neuhaus-dev @marcaaron @shawnborton

### PR DESCRIPTION
**Pull request by lucas-neuhaus-dev**
@trjExpensify @marcaaron 

### Details
Stopped rendering the `Create Group` button when there is no contact selected.
Left the check for `userLogins.length < 1` in the `createGroup()` function. A cheap double check is never a bad idea.

### Fixed Issues
Fixes #1418 

### Tests
1. Open `New Group` via the `Create Menu`;
2. Check if, when there is no contact selected, the `Create Group` button does not show;
3. Check if the button shows otherwise.

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

#### Web
web

#### Desktop
desktop

#### iOS
ios

### CODE REVIEW

**Review by Julesssss — APPROVED** [review]

**Comment by Julesssss** [comment]
LGTM, verified on web, Android & mobile web

File: src/pages/NewGroupPage.js [hunk 1]
```diff
@@ -236,21 +236,23 @@ class NewGroupPage extends Component {
...
-                                styles.w100,
-                                hovered && styles.buttonSuccessHovered,
-                            ]}
-                        >
-                            <Text style={[styles.buttonText, styles.buttonSuccessText]}>
-                                Create Group
-                            </Text>
-                        </Pressable>
-                    </View>
+                    {this.state.selectedOptions?.length > 0 && (
```
Comment (marcaaron) [inline src/pages/NewGroupPage.js:239]: NAB, `selectedOptions` will always have a value so there is no need for the optional chain.

Comment (Julesssss) [reply src/pages/NewGroupPage.js:239]: Damn, good spot.
