### PR TITLE
Fix: mWeb/Web Safari - Selecting attachment

### LINKED ISSUE #1159: When uploading a document, if you try to upload the same document more than once the preview doesn't appear.
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:** 

Webapp the current version on Expensify.cash (don't see a version listed)

**Action Performed (reproducible steps):**

Click the attachment button and select a file. Whether you upload it to the chat or close it doesn't matter. Try uploading the same document again and the preview doesn't show up.

**Expected Result:**

To show the preview and upload button every time any file even if a duplicate file it uploaded

**Actual Result:**

Nothing occurs

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/32753063/103524765-f2934080-4e32-11eb-9baa-97ba7185adaf.mov

### LINKED ISSUE #2109: [PAYMENT DUE 20 APRIL + BONUS FOR CREATING ISSUE] - mWeb/Web Safari - Selecting add attachment does not open the file picker
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Selecting "Add Attachment" from the chat menu should open the Browser's file picker

## Actual Result:
After pressing on "Add Attachment" the menu closes and focus is brought back to the chat input field

## Action Performed:
1. Start the local dev server
2. Open or start a chat
3. Press on the plus button (+) inside the input field
4. Select "Add Attachment"

## Workaround:
Use a different browser

## Platform:
Where is this issue occurring?

Web❌ 
 iOS 
 Android
 Desktop App 
 Mobile Web ❌

**Version Number:** expensify.cash@1.0.6-3
using the code in the `master` branch

**Notes/Photos/Videos:**  

https://user-images.githubusercontent.com/12156624/112666303-b5a07e00-8e64-11eb-8d35-0cb0634f7920.mp4

- first part Safari
- second part Chrome

### PR DESCRIPTION
**Pull request by kidroca**
@Julesssss

### Details
Safari does not show the attachment picker if the button used to trigger file input disappears as soon as it's clicked
Added small updates to the `CreateMenu` components that preserve existing functionality but also allow to
trigger an action before the CreateMenu popover closes

### Fixed Issues
Fixes #2109 and also fixes: #1159

### Tests
This bug affected mobile Safari, mobile Chrome and Desktop Safari

1. From the home screen
2. Select the plus (+) button
3. Select "Upload Photo"
4. The file picker should appear
  - check the screenshots
  - on mobile I had no problem no a physical devices, but on the Simulator, the keyboard would try to appear and the file picking options would hide under. Pressing done would review them, but this is an issue with autofocus handling. 
5. You can try to select the same file twice to see that #1159 is fixed

### QA Steps
Same as above

Note: there are changes to the Create Menu component - the component used to show the "New Chat", "Group Chat" options on the home screen FAB, and the Attachment Picker component which is also used on "Edit Photo" for the profile picture. 
I've verified they still work, but you should probably test it as well

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [x] iOS
- [x] Android

#### Web
image

image

#### Mobile Web (iPhone 8 Simulator Safari)
image

#### Mobile Web (iPhone 11 Pro Safari) 
image

#### Mobile Web (Android Pixel 2 Chrome)
image

### CODE REVIEW

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -300,6 +299,14 @@ class ReportActionCompose extends React.Component {
     }
 }
 
+const CREATE_MENU_ITEMS = {
+    ATTACHMENT: {
+        icon: Paperclip,
+        text: 'Upload Photo',
+        onSelected: () => {},
+    },
+};
```
Comment (kidroca) [inline src/pages/home/report/ReportActionCompose.js:308]: I don't know where to put this, it doesn't feel right to have it at the top. Maybe in a separate file...

**Comment by kidroca** [comment]
It might be better to wait for  #2114 to be merged as it also made changes to the Attachment Picker

**Comment by tgolen** [comment]
OK, looks like that other PR would be good to merge first. Would you mind adding `[HOLD PR#2114]` to the beginning of the title of this PR? Then when the other PR has been merged, you can remove the HOLD and add a comment here to let me know it's ready for review again.

**Comment by Julesssss** [comment]
Other PR is now merged, removing the hold.

File: src/pages/home/report/ReportActionCompose.js (hunk 1 above)
Comment (Julesssss) [reply src/pages/home/report/ReportActionCompose.js:308]: Good point, but it's probably fine to match our existing usages for now.

File: src/pages/home/report/ReportActionCompose.js [hunk 2]
```diff
@@ -217,20 +218,18 @@ class ReportActionCompose extends React.Component {
...
-                                                    },
-                                                ]}
+                                                onItemSelected={(item) => {
+                                                    if (item.text === CREATE_MENU_ITEMS.ATTACHMENT.text) {
+                                                        setTimeout(() => {
+                                                            openPicker({
+                                                                onPicked: file => displayFileInModal({file}),
+                                                            });
+
+                                                            this.setMenuVisibility(false);
```
Comment (Julesssss) [inline src/pages/home/report/ReportActionCompose.js:228]: Wouldn't we want to hide LHN for every menu item, rather than just the ATTACHMENT?

File: src/components/CreateMenu.js [hunk 3]
```diff
@@ -21,7 +21,7 @@ const propTypes = {
         PropTypes.shape({
             icon: PropTypes.func.isRequired,
             text: PropTypes.string.isRequired,
-            onSelected: PropTypes.func.isRequired,
+            onSelected: PropTypes.func,
```
Comment (Julesssss) [inline src/components/CreateMenu.js:24]: It's not clear to me why this change is necessary, would you mind explaining?

**Review by Julesssss — CHANGES_REQUESTED** [review]

File: src/pages/home/report/ReportActionCompose.js (hunk 2 above)
Comment (kidroca) [reply src/pages/home/report/ReportActionCompose.js:228]: Yep, will update
`this.setMenuVisibility(false);` - this is the Create menu modal though not LHN

File: src/components/CreateMenu.js (hunk 3 above)
Comment (kidroca) [reply src/components/CreateMenu.js:24]: Initially I thought I could use something like this: 

```jsx
menuItems={[
    {
        icon: Paperclip,
        text: 'Upload Photo',
    },
]}
```

I'll revert it back to required though

File: src/components/AttachmentPicker/index.js [hunk 4]
```diff
@@ -35,11 +35,18 @@ class AttachmentPicker extends React.Component {
                 <input
                     hidden
                     type="file"
+                    accept="audio/*;video/*;image/*;application/pdf"
```
[the remark this answers is not in the document]
Comment (kidroca) [reply src/components/AttachmentPicker/index.js:18]: If we fine tune it - it can filter/suggest files based on this attribute: 
image

I don't think it does anything at the moment, with or without it there are no restrictions but I'll just remove it to be safe

**Comment by kidroca** [comment]
Updated
@tgolen @Julesssss synced with master and resolved conflicts, addressed requested changes, this is ready for review

**Comment by kidroca** [comment]
Hey sorry I've just noticed but I need to also update the usage of the Attachment Picker on the ProfilePage:
https://github.com/Expensify/Expensify.cash/blob/5ab2683945ae684708bd3505a2810461a047e21e/src/pages/settings/ProfilePage/index.js#L196

```jsx
        const menuItems = [
            {
                icon: Upload,
                text: 'Upload Photo',
                onSelected: () => {
                    setTimeout(() => {
                        openPicker({
                            onPicked: setAvatar,
                        });
                    }, 10);
                },
            },
        ];
```

I should remove the timeout and update the handling there as well

**Comment by kidroca** [comment]
Updated

When I originally added this logic, I tested on Android and I missed the fact that calling 
`openPicker` before the first modal closes would not work on iOS native. on iOS the first
modal needs to close and only then you can call `openPicker`

But the tricky part is on mobile web and Safari invoking an action after the first modal
closes is ignored by the browser because the button that triggers `input.click()` is no longer in the DOM

That's why I've added a configuration for this behavior in CreateMenu 
- on web/mWeb/desktop: menu item `onSelected` actions would be triggered before the modal closes
- on mobile native actions would be triggered after the menu modal closes (same as previous)
- no negative side effects or degradations noticed - tried all the places CreateMenu is used (settings/profile, FAB, chat compose)

File: src/components/CreateMenu/BaseCreateMenu.js [hunk 5]
```diff
@@ -26,54 +26,53 @@ const propTypes = {
     ).isRequired,
 
     ...windowDimensionsPropTypes,
+
+    // Trigger the item `onSelected` action immediately after press or after the modal hides
+    invokeActionImmediately: PropTypes.bool,
```
Comment (tgolen) [inline src/components/CreateMenu/BaseCreateMenu.js:31]: I think the name of this isn't great... It's not clear to me when you would want the action to be triggered when clicking, or when the modal is closed. What would you think about using two separate props?

- `invokeActionWhenSelected`
- `invokeActionWhenModalClosed`

That would make it very explicit and I think that might clean up a little bit of the logic as well.

File: src/pages/settings/ProfilePage/index.js [hunk 6]
```diff
@@ -193,11 +193,9 @@ class ProfilePage extends Component {
                 icon: Upload,
                 text: 'Upload Photo',
                 onSelected: () => {
-                    setTimeout(() => {
```
Comment (tgolen) [inline src/pages/settings/ProfilePage/index.js:196]: Thanks for removing this! It was making me cringe 😁

**Review by tgolen — CHANGES_REQUESTED** [review]

File: src/components/CreateMenu/BaseCreateMenu.js (hunk 5 above)
Comment (kidroca) [reply src/components/CreateMenu/BaseCreateMenu.js:31]: Will update this tomorrow

Comment (kidroca) [reply src/components/CreateMenu/BaseCreateMenu.js]: I've addressed this by adding an `executeActionMode` prop restricted to 2 values - on press or after modal hides
If you provide a wrong value by mistake you'll get a prop type warning (and an error)
IDE Intellisense would pickup and show supported options:
image

I didn't go with two separate props as you could set them both to `true` or both to `false` and it shouldn't be possible to configure to invoke `onSelect` twice - when pressed and after close, or never

Comment (kidroca) [reply src/components/CreateMenu/BaseCreateMenu.js]: I'm leaving the comment unresolved so you can verify this works for you

**Comment by kidroca** [comment]
Updated

**Comment by Julesssss** [comment]
Would you mind reminding me why we need the native iOS menu? Is this still the case for safari mobile web, even though we launch the next Modal before the first closes?

Screenshot 2021-04-07 at 15 40 13

**Comment by kidroca** [comment]
> Would you mind reminding me why we need the native iOS menu here instead of our custom CreateMenu?

You are seeing a screenshot of the second modal - the popup that appears after you select "Upload Photo" from the options in the CreateMenu. It's appearance is handled by the browser.
I didn't take a screenshot of the Create Menu as it only has 1 option at the moment
My screenshot captures the Menu that prior this PR would not appear on mobile web

Maybe I should add a video for clarity. I'll do that when I get the chance

**Comment by Julesssss** [comment]
> Maybe I should add a video for clarity. I'll do that when I get the chance

No need, I'm with you. That's my screenshot btw. 

Gotcha, so it's simply because we have more control on mobile (we can show document picker/image picker/camera). Whereas on web we delegate this to the browser, which displays the native context menu?

**Comment by kidroca** [comment]
> Gotcha, so it's simply because we have more control on mobile (we can show document picker/image picker/camera). Whereas on web we delegate this to the browser, which displays the native context menu?

Correct

To completely cover the topic, there's an alternative:

You can have a `<input type="file" capture="camera" />` which would directly start the camera. But this means we need to implement another 2nd modal with the options "Camera" and "Browse" -> camera would trigger the camera, while "Browse" would prompt you to select by popping yet another popup (the one in your screenshot). I guess you see how this would not be a great improvement.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture

**Comment by kidroca** [comment]
@Julesssss @tgolen 
Are you waiting for more changes? I don't think there's anything more I need to do here
@tgolen I've left this unresolved so you can verify the solution suits you: https://github.com/Expensify/Expensify.cash/pull/2229#discussion_r608513268

**Comment by tgolen** [comment]
Thanks for the bump, I will get it reviewed again now!

File: src/components/CreateMenu/BaseCreateMenu.js [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+    // State that determines whether to display the create menu or not
+    isVisible: PropTypes.bool.isRequired,
+
+    // Callback to fire when a CreateMenu item is selected
+    onItemSelected: PropTypes.func.isRequired,
+
+    // Menu items to be rendered on the list
+    menuItems: PropTypes.arrayOf(
+        PropTypes.shape({
+            icon: PropTypes.func.isRequired,
```
Comment (tgolen) [inline src/components/CreateMenu/BaseCreateMenu.js:22]: Each of these need inline comments too

File: src/components/CreateMenu/BaseCreateMenu.js [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+            text: PropTypes.string.isRequired,
+            onSelected: PropTypes.func.isRequired,
+        }),
+    ).isRequired,
+
+    /* Configures when menu item actions are triggered: as soon as pressed or after the modal is closed.
+    * On mobile native we need to wait for the modals to close, while on web as soon as clicked */
+    actionExecutionStrategy: PropTypes.oneOf(['ON_PRESS', 'AFTER_MODAL_CLOSE']),
```
Comment (tgolen) [inline src/components/CreateMenu/BaseCreateMenu.js:30]: I like this idea (much better than two separate props). Can you please make these constants that live in `CONST.js`?

**Review by tgolen — CHANGES_REQUESTED** [review]

File: src/components/CreateMenu/BaseCreateMenu.js (hunk 7 above)
Comment (kidroca) [reply src/components/CreateMenu/BaseCreateMenu.js:22]: Yeah, no prob, I'm actually not the original author, I just moved CreateMenu.js -> CreateMenu/BaseCreateMenu.js, but I'll do my best to describe these

File: src/components/CreateMenu/BaseCreateMenu.js (hunk 8 above)
Comment (kidroca) [reply src/components/CreateMenu/BaseCreateMenu.js:30]: Actually taking a new look and I'll need to change this one last time for the best. I'll post a note on the code below

File: src/components/CreateMenu/BaseCreateMenu.js [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+                item.onSelected();
+                this.onModalHide = () => {};
+                break;
+            case 'AFTER_MODAL_CLOSE':
+                this.onModalHide = () => item.onSelected();
+                break;
+            default:
+                throw new Error(`Unexpected "actionExecutionStrategy" value: ${this.props.actionExecutionStrategy}`);
+        }
+    }
```
Comment (kidroca) [inline src/components/CreateMenu/BaseCreateMenu.js:59]: `case 'ON_PRESS':` 
This is only performed on web, right - so this can be moved to the web version - index.js 

`case 'AFTER_MODAL_CLOSE'` 
This is only performed on native and can also be moved - index.native.js

This the "base" component does not need to know/implement the actual strategies. But the strategies are applied from the platform specific implementation. No confusing props, no confusing constans, the behavior would be clearly described in the platform specific implementation. 

It's as simple as moving one case to the web versions and the other to the native version

Comment (kidroca) [reply src/components/CreateMenu/BaseCreateMenu.js]: Leaving this unresolved so you can confirm this works for you

**Comment by kidroca** [comment]
Updated

File: src/components/CreateMenu/BaseCreateMenu.js [hunk 10]
```diff
@@ -0,0 +1,48 @@
...
+import PropTypes from 'prop-types';
+import Popover from '../Popover';
+import styles from '../../styles/styles';
+import withWindowDimensions, {windowDimensionsPropTypes} from '../withWindowDimensions';
+import MenuItem from '../MenuItem';
+import createMenuPropTypes from './CreateMenuPropTypes';
+
+const propTypes = {
+    // Callback fired when the menu is completely closed
+    onModalHide: PropTypes.func,
```
Comment (tgolen) [inline src/components/CreateMenu/BaseCreateMenu.js:12]: I think this prop has a name that is incorrect according to the comment and the component name. I think `onHide` or `onMenuHide` would be more appropriate.

File: src/components/MenuItem.js [hunk 11]
```diff
@@ -17,7 +17,7 @@ const propTypes = {
     onPress: PropTypes.func.isRequired,
 
     // Icon to display on the left side of component
-    icon: PropTypes.func.isRequired,
+    icon: PropTypes.elementType.isRequired,
```
Comment (tgolen) [inline src/components/MenuItem.js:20]: I've never seen `elementType` used before, and I'm a little unclear on how it's supposed to be used. The only hint I can find in the React docs is:

```
// A React element type (ie. MyComponent).
```

Which doesn't make a whole lot of sense... (I would expect to see "MyComponent" in their example somewhere). Ref: https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes
but for this particular instance, I think `PropTypes.node` might be a better propType?

**Review by tgolen — CHANGES_REQUESTED** [review]

File: src/components/MenuItem.js (hunk 11 above)
Comment (kidroca) [reply src/components/MenuItem.js:20]: `PropType.elementType` stands for either a stateless func component or a class component constructor e.g. not just any function but a specifically a react component.

It does sound a bit confusing but it exactly represents the requirement.

PropType.node would raise a warning as it stands for an evaluated/rendered content e.g. it's used when you have a prop like this:
```jsx
 menuItems={[
   {
     icon: <Paperclip />,
     text: 'Upload Photo',
     onSelect: () => {},
```

While with `PropType.elementType` the signature is this:

```jsx
 menuItems={[
   {
     icon: Paperclip,
     text: 'Upload Photo',
     onSelect: () => {},
```

The latter would allow you to easily pass more props to `Paperclip` if needed e.g. fill, stroke, other svg props

File: src/components/CreateMenu/BaseCreateMenu.js (hunk 10 above)
Comment (kidroca) [reply src/components/CreateMenu/BaseCreateMenu.js:12]: I'll update it. It's not something that is exposed to the consumers `CreateMenu` though

File: src/components/MenuItem.js (hunk 11 above)
Comment (tgolen) [reply src/components/MenuItem.js:20]: OK, neat! Thanks for explaining that subtle difference. Let's keep it `element` in that case!

Comment (kidroca) [reply src/components/MenuItem.js:20]: Here I've followed this to the actual usage. It's used like an element:

https://github.com/Expensify/Expensify.cash/blob/d3f1d28478357e2a66b155e660def191d6ed79a8/src/components/Icon/index.js#L31-L38

**Comment by kidroca** [comment]
Updated

**Review by tgolen — APPROVED** [review]

**Comment by kidroca** [comment]
Updated
Resolved merge conflicts

**Comment by kidroca** [comment]
The test stage fails at "Install cocoapods". There are no changes in package or pods in this PR though

**Review by Julesssss — APPROVED** [review]
LGTM. The test was failing due to a missing Airship dependency, which has now been resolved. After re-running the test it succeeded.
