### PR TITLE
Fix custom columns blocker #2

### LINKED ISSUE #77850: [Due for payment 2025-12-26] Reports - Filters reset after changing columns
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** sdkpsdkpdsokpsdkm@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Reports.
5. Apply any filter (eg, from:me) and search.
6. Click Columns.
7. Make some changes to the selection > Save.

## Expected Result:
Filters will not reset after changing columns.

## Actual Result:
Filters are reset after changing columns.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/4d04ae4d-9472-4dd7-8819-7ae5e8879c5b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @brianlee-expensify</details>

### LINKED ISSUE #77859: [Due for payment 2025-12-26] Web - Reports - Resetted filter is applied again after resetting columns.
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** ibellicotest+2230@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Exploratory - Significant User Experience Deterioration
**Device used:** Windows 11 / Chrome
**App Component:** Search

## Action Performed:
Prerequisite: Account has at least one workspace.
1.  Open the staging.new.expensify.com website.
2. Open any workspace chat.
3. Create a manual expense.
4. Navigate to "Reports" > "Expenses"
5. Tap on "Filters"
6. Tap on "Group By" and select any option. (For example: From)
7. Save the selection and tap on "View Results"
8. Once on "Expenses" again, tap on "Columns"
9. Uncheck some of the columns and tap on "Save"
10. Expand the expense displayed on results.
11. Note that columns were correctly cleared.
12. Tap on the "Group By" exposed filter and reset it.
13. Note that exposed filter disappeared and no filter is applied.
14. Tap on "Columns" > "Reset Columns" and select "Save"
15. Note that when you land on "Expenses" again, the "Group By" filter is applied again.

## Expected Result:
Cleared filter shouldn´t be applied again after resetting the columns selection.

## Actual Result:
Cleared filter is applied once again after resetting the columns selection.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/cbeb7f02-e6aa-496b-8639-4ca1f082c241

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

### LINKED ISSUE #77867: Reports - Search query contains columns: when opening recent search
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** sodijsdoinjsosjoidjiso@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Reports > Reports.
3. Type anything in the search field and hit Enter.
4. Click Columns.
5. Make some changes to the selection > Save.
6. Click Expenses tab.
7. Click on the search field.
8. Click on the recent search from Step 3.
9. Click Expenses tab.
10. Click on the search field.
11. Click on the recent search from Step 3.

## Expected Result:
Search query will not contain columns:

## Actual Result:
Search query contains columns: when opening recent search.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/d3fc84a3-8da6-4a3f-a7d1-43530e445b0a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #77868: [Due for payment 2025-12-26] Reports - Date width does not auto adjust after updating expense date, date is out of view
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** sdsjdoisjoinjoijsoijsd@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Expenses.
5. Click on the expense.
6. Change the date to 2024 and save it.
7. Close the expense report.

## Expected Result:
Date width will auto adjust so that the entire date will fit in the column.

## Actual Result:
Date width does not auto adjust after updating expense date. Date year is out of view.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/496598b7-c311-4ea5-b310-d0afe0bb2968

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

### LINKED ISSUE #77869: [Due for payment 2025-12-26] Reports - "Reset filters" appears, is not clickable after customising columns when no filter is applied
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** djoidjfoidjodfijofdi@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Expenses.
5. Click Columns.
6. Make some changes to the selection > Save.
7. Click Filters.
8. Click Reset filters.

## Expected Result:
"Reset filters" should not appear after customising columns because no filter is applied.

## Actual Result:
"Reset filters" appears and is not clickable after customising columns when no filter is applied.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/40b59541-1777-4c12-b5c9-3953deb77954

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

### PR DESCRIPTION
**Pull request by JS00001**
### Explanation of Change
Fixes several deploy blockers related to custom columns

### Fixed Issues
$ https://github.com/Expensify/App/issues/77869
$ https://github.com/Expensify/App/issues/77850 
$ https://github.com/Expensify/App/issues/77859
$ https://github.com/Expensify/App/issues/77843
$ https://github.com/Expensify/App/issues/77868
$ https://github.com/Expensify/App/issues/77867

### Tests
Same as linked issues

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
Same as linked

- [x] Verify that no errors appear in the JS console

### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If new assets were added or existing ones were modified, I verified that:
    - [x] The assets are optimized and compressed (for SVG files, run `npm run compress-svg`)
    - [x] The assets load correctly across all supported platforms.
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I verified that similar component doesn't exist in the codebase
- [x] I verified that all props are defined accurately and each prop has a `/** comment above it */`
- [x] I verified that each file is named correctly
- [x] I verified that each component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
- [x] I verified that the only data being stored in component state is data necessary for rendering and nothing else
- [x] In component if we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
- [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
- [x] I verified that component internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
- [x] I verified that all JSX used for rendering exists in the render method
- [x] I verified that each component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

### CODE REVIEW

File: src/libs/SearchUIUtils.ts [hunk 1]
```diff
@@ -2055,12 +2056,8 @@ function getSortedTransactionData(
             const aReport = a.report;
             const bReport = b.report;
 
-            if (!aReport || !bReport) {
-                return 0;
-            }
-
-            const aValue = getReportStatusTranslation({stateNum: aReport.stateNum, statusNum: aReport.statusNum, translate});
-            const bValue = getReportStatusTranslation({stateNum: bReport.stateNum, statusNum: bReport.statusNum, translate});
+            const aValue = getReportStatusTranslation({stateNum: aReport?.stateNum, statusNum: aReport?.statusNum, translate});
```
Comment (JS00001) [inline src/libs/SearchUIUtils.ts:2059]: This fixes the sorting issue: https://github.com/Expensify/App/issues/77843

File: src/libs/SearchUIUtils.ts [hunk 2]
```diff
@@ -936,7 +936,8 @@ function shouldShowYear(
     for (const key of Object.keys(data)) {
         if (!checkOnlyReports && isTransactionEntry(key)) {
             const item = data[key];
-            if (item.created && DateUtils.doesDateBelongToAPastYear(item.created)) {
+            const transactionCreated = getTransactionCreatedDate(item);
```
Comment (JS00001) [inline src/libs/SearchUIUtils.ts:939]: This fixes the date issue: https://github.com/Expensify/App/issues/77868

File: src/pages/Search/SearchAdvancedFiltersPage.tsx [hunk 3]
```diff
@@ -24,6 +24,10 @@ function SearchAdvancedFiltersPage() {
                 return false;
             }
 
+            if (key === CONST.SEARCH.SYNTAX_ROOT_KEYS.COLUMNS) {
```
Comment (JS00001) [inline src/pages/Search/SearchAdvancedFiltersPage.tsx:27]: This fixes columns being included in the reset condition: https://github.com/Expensify/App/issues/77869

File: src/pages/Search/SearchPage.tsx [hunk 4]
```diff
@@ -177,6 +194,15 @@ function SearchPage({route}: SearchPageProps) {
         formattedAmount: totalFormattedAmount,
     });
 
+    const formValues = queryJSON
```
[the remark this answers is not in the document]
Comment (JS00001) [reply src/pages/Search/SearchPage.tsx:197]: should use react compiler

**Comment by QichenZhu** [comment]
Reports - "Reset filters" appears, is not clickable after customising columns when no filter is applied #77869

https://github.com/user-attachments/assets/806b5935-da44-49fb-9099-b1114258ceb3

Reports - Filters reset after changing columns #77850

https://github.com/user-attachments/assets/17b9594c-b088-48a8-907f-1d16cb45ae62

Web - Reports - Resetted filter is applied again after resetting columns. #77859

https://github.com/user-attachments/assets/936cad90-b575-4788-966f-f169e47abcec

Reports - Unreported expenses are not grouped together when sorted by Status #77843

https://github.com/user-attachments/assets/1d4f7cd4-258b-4d7c-a1e7-589c7884b8a9

Reports - Date width does not auto adjust after updating expense date, date is out of view #77868

https://github.com/user-attachments/assets/f17e94c3-60ba-4cc8-9d66-19a6e8c1d691

**Review by luacmartins — APPROVED** [review]
LGTM

**Comment by IuliiaHerets** [comment]
@JS00001 QA team faced this PR on Web with an [original issue](https://github.com/Expensify/App/issues/77843)
