### PR TITLE
[NO QA]Feature: Critical Error Handling

### LINKED ISSUE #3339: [HOLD for payment + bonus on Jun 18] Feature: Critical Error Handling | Prevent white screens on startup
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

Upwork link: https://www.upwork.com/jobs/~016c9065afb6e3f521
___

## Details
ATM there's no handling for critical JS errors - when such an error happens - the app stops working.
This leads to 2 major problems:
  - for end users - If this happens during startup they end up on a white screen and wonder: is the app still loading;
will it recover on its own, should I force close and try again...
  - for developers - we don't have a clue about the problem - we'll only notice it after people start complaining, we might have problems recreating the issue 

Related to this slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1621712412159500

## Expected Result:
If the app crashes
- Capture some information
- Provide the end user some feedback and the option to retry - restart

## Actual Result:
If the app crashes during startup you'll just see a blank white screen
image

## Action Performed:
N/A

## Workaround:
N/A

## Platform:
Where is this issue occurring?

- [x] Web
- [x] iOS
- [x] Android
- [x] Desktop App
- [x] Mobile Web

## Proposal
Implement exception handling at the root of the app by either creating a dedicated `ErrorBoundary` component and wrap the app here:
https://github.com/Expensify/Expensify.cash/blob/4f28e5e1f3949ba1c938158cde081adbd6aa9de7/src/App.js#L6-L11
Or just implement the `componentDidCatch` in the `<Expensify />` component 
The implementation would roughly follow the pattern here: https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries and use the E.cash `Log` service to log the exception to the server

Furthermore in case of exception the UI can be updated to display some feedback to the user like: 
> Oops something unexpected happened
Luckily we've captured this in our logs 
Would you like to retry?
[Restart]

**Version Number: 1.0.61-7**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by kidroca**
@Jag96 

### Details

Created a new `ErrorBoundary` component
This component can serve to warp the whole app, or specific parts like documented here: https://reactjs.org/docs/error-boundaries.html#where-to-place-error-boundaries

`@react-native-firebase/crashlytics` is available only for iOS and Android so a platform specific component was created to handle the logging - Android and iOS would log to E.cash server and crashlytics, while desktop and web would log only to the E.cash server (Reference: https://github.com/invertase/react-native-firebase/issues/1530)

Wrapped the main component `Expensify` with `ErrorBoundary`
For the moment we're not rendering fallback UI, but just log the error that crashed React to the server and crashlytics

### Fixed Issues

Fixes #3339

### Tests
To test this you can trigger an exception in the render method of some component
In my sample video (iOS screenshots section) I've changed `ReportScreen` to throw an error when a specific report is opened

### QA Steps
N/A

### Tested On
I've verified the app starts and works on these platforms

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Mobile Web
image

#### Desktop
image

#### iOS
https://user-images.githubusercontent.com/12156624/121593372-869daf80-ca44-11eb-8d2c-7b587ffaf6fc.mov

#### Android
image

### CODE REVIEW

File: tests/unit/loginTest.js [hunk 1]
```diff
@@ -9,6 +9,11 @@ import React from 'react';
 import renderer from 'react-test-renderer';
 import App from '../../src/App';
 
+jest.mock('@react-native-firebase/crashlytics', () => ({
+    log: jest.fn(),
+    recordError: jest.fn(),
+}));
+
```
Comment (kidroca) [inline tests/unit/loginTest.js:16]: This test started to fail because as a `native` test it imports the `ErrorBoundary/index.native.js` file and that file tries to load `@react-native-firebase/crashlytics`

**Comment by kidroca** [comment]
Here's a sample content logged to the server on error:

```
[alrt] [App] A Crash was intercepted by the main error boundary | Context:  [{"message":"[info] [NetworkConnection] listenForReconnect called - {}","timestamp":"2021-06-10T21:32:41.909Z"},{"message":"[NetworkConnection] NetInfo isConnected: true","timestamp":"2021-06-10T21:32:41.974Z"},{"message":"[info] [PusherConnectionManager] Attempting to authorize Pusher - {}","timestamp":"2021-06-10T21:32:42.658Z"},{"message":"[info] [PusherConnectionManager] connected event - {}","timestamp":"2021-06-10T21:32:42.659Z"},{"message":"[info] [PusherConnectionManager] Attempting to authorize Pusher - {}","timestamp":"2021-06-10T21:32:42.660Z"},{"message":"[NetworkConnection] NetInfo isConnected: true","timestamp":"2021-06-10T21:32:42.881Z"},{"message":"[info] [PusherConnectionManager] Pusher authenticated successfully - {}","timestamp":"2021-06-10T21:32:44.306Z"},{"message":"[info] [PusherConnectionManager] Pusher authenticated successfully - {}","timestamp":"2021-06-10T21:32:44.307Z"},{"message":"[info] [Report] successfully fetched report data - {}","timestamp":"2021-06-10T21:32:44.721Z"},{"message":"[info] [NetworkConnection] stopListeningForReconnect called - {}","timestamp":"2021-06-10T21:32:50.108Z"}] - {"error":{},"errorInfo":{"componentStack":"
    at ReportScreen (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:261999:81)
    at StaticContainer (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:27865:16)
    at EnsureSingleNavigator (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:27513:23)
    at SceneView (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:27752:21)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at Background (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:34048:20)
    at Screen (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:35217:107)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at NativeScreen (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:176589:81)
    at AnimatedComponent (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:195457:32)
    at AnimatedComponentWrapper
    at MaybeScreen (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:32895:23)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at MaybeScreenContainer (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:32881:22)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at AnimatedComponent (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:161863:83)
    at AnimatedComponentWrapper
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at AnimatedComponent (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:161863:83)
    at AnimatedComponentWrapper
    at Dummy (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:32815:23)
    at DrawerView (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:33080:81)
    at DrawerViewBase (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:32556:21)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at SafeAreaProviderCompat (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:35166:23)
    at DrawerView (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:32777:26)
    at DrawerNavigator (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:31778:31)
    at MainDrawerNavigator (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:251550:69)
    at withOnyx (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:148923:85)
    at WithWindowDimensions (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:248567:83)
    at StaticContainer (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:27865:16)
    at EnsureSingleNavigator (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:27513:23)
    at SceneView (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:27752:21)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at CardSheet (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:42498:22)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at AnimatedComponent (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:195457:32)
    at AnimatedComponentWrapper
    at Dummy (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:40970:23)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at AnimatedComponent (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:195457:32)
    at AnimatedComponentWrapper
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at Card (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:41684:81)
    at CardContainer (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:42207:20)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at NativeScreen (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:176589:81)
    at AnimatedComponent (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:195457:32)
    at AnimatedComponentWrapper
    at MaybeScreen (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:41532:23)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at MaybeScreenContainer (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:41520:22)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at Background (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:35468:20)
    at CardStack (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:42766:81)
    at SafeAreaProviderCompat (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:36586:23)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at StackView (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:43178:81)
    at CustomRootStackNavigator (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:251852:23)
    at AuthScreens (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:251241:81)
    at withOnyx (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:148923:85)
    at WithWindowDimensions (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:248567:83)
    at AppNavigator (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:251907:16)
    at EnsureSingleNavigator (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:27513:23)
    at BaseNavigationContainer (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:27140:27)
    at ThemeProvider (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:37335:20)
    at NavigationContainerInner (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:37016:25)
    at NavigationRoot (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:252229:81)
    at Expensify (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:237802:81)
    at withOnyx (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:148923:85)
    at BaseErrorBoundary (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:240229:81)
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at NativeSafeAreaView (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:176002:23)
    at SafeAreaProvider (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:176183:24)
    at App
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at div
    at http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:186665:25
    at AppContainer (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:177100:24)"},"stack":"\"Error\
    at Logger.alert (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:78400:43)\
    at Object../src/components/ErrorBoundary/index.js._BaseErrorBoundary__WEBPACK_IMPORTED_MODULE_0__.default.defaultProps.logError (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:240288:53)\
    at BaseErrorBoundary.componentDidCatch (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:240241:18)\
    at BaseErrorBoundary.callback (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:136128:95)\
    at callCallback (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:134988:325)\
    at commitUpdateQueue (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:134989:207)\
    at commitLifeCycles (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:136235:1)\
    at commitLayoutEffects (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:136765:465)\
    at HTMLUnknownElement.callCallback (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:133463:119)\
    at Object.invokeGuardedCallbackDev (http://localhost:8080/app-b56b3e19460f756d6cb5.bundle.js:133483:45)\""}
```

Produced by 

```js
Log.alert(errorMessage, 10, {error, errorInfo});
```

**Comment by kidroca** [comment]
Updated

As per my last commit messages, I've spotted some small issues

> update parameters because the error message is not logging
The error logs as "{}" in the log, probably because it's a special object
Updated to pass the error message instead

> refactor: remove stack trace and set captured messages
The stack trace is not interesting as it just traces to
the moment we call `Log.alert` in `logError`
Also the `errorInfo` contains the actual stack from React

I'm done making any more updates, until the review passes

File: src/App.js [hunk 2]
```diff
@@ -1,12 +1,16 @@
...
+
 import CustomStatusBar from './components/CustomStatusBar';
 import Expensify from './Expensify';
+import ErrorBoundary from './components/ErrorBoundary';
 
 const App = () => (
     <SafeAreaProvider>
         <CustomStatusBar />
-        <Expensify />
+        <ErrorBoundary errorMessage="[App] A Crash was intercepted by the main error boundary">
```
Comment (Jag96) [inline src/App.js:11]: Can we update the errorMessage to be `E.cash crash caught by error boundary`? We can also remove the `[App]` from the message as well.

File: src/components/ErrorBoundary/index.native.js [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+import BaseErrorBoundary from './BaseErrorBoundary';
+import Log from '../../libs/Log';
+
+BaseErrorBoundary.defaultProps.logError = (errorMessage, error, errorInfo) => {
+    // Log the error to the server
+    Log.alert(errorMessage, 0, {error: error.message, errorInfo}, false);
+
+    /* On native we also log the error to crashlytics
+    * Since the error was handled we need to manually tell crashlytics about it */
+    crashlytics().log(`errorInfo: ${errorInfo}`);
```
Comment (Jag96) [inline src/components/ErrorBoundary/index.native.js:12]: Looking at the logs in crashlytics, it looks like this only logs a string.
image

As a comparison, here's what we see if we stringify the errorInfo in crashlytics under `logs`:
image

I think we can just stringify the log we send to crashlytics, even though we're also logging that on the server it'll only help make it easier to tie the error in crashlytics to our logs since the crashlytics stack trace isn't particularly helpful
image

File: tests/unit/loginTest.js (hunk 1 above)
Comment (Jag96) [reply tests/unit/loginTest.js:16]: Sounds good, can you leave a comment above it just to clarify that?

**Review by Jag96 — CHANGES_REQUESTED** [review]
Such a great improvement! I added a few comments and some screenshots after testing

**Comment by kidroca** [comment]
Thanks, 
The requested changes are applied

**Review by NikkiWines — APPROVED** [review]
This looks good to me, leaving the final review to @Jag96

**Review by Jag96 — APPROVED** [review]
Looks good and tests well 👍
