### PR TITLE
fixed Sidebar theme

### LINKED ISSUE #1967: LHN background color is not correct.
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
There are a couple of styling issues. 

- [ ] LHN Bg color.
- [ ] LHN Chat hover style.

## Expected Result:

Screenshot_2021-03-20 Expensify cash - Chat with friends to send and receive money

## Actual Result:
Screenshot_2021-03-20 Expensify cash - Chat with friends to send and receive money(1)

## Platform:

 Web
 iOS
 Android
 Desktop App
 Mobile Web

### PR DESCRIPTION
**Pull request by parasharrajat**
Please review @marcaaron. As these changes are directly linked to your code.

### Details
` <SafeAreaInsetsContext.Consumer>` does not have styling support but in `ScreenWrapper` component was passing parent style prop to it. I have moved it to the child `View` which is working without regression.

### Fixed Issues
Fixes #1967 

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

|Before|After|
|-----|-------|
| image| image |

CC @shawnborton

### CODE REVIEW

**Comment by shawnborton** [comment]
Looks good but would love to see screenshots of all of the platforms, especially iOS.

File: src/components/ScreenWrapper.js [hunk 1]
```diff
@@ -46,6 +46,7 @@ const ScreenWrapper = props => (
             return (
                 <View
                     style={[
+                        ...props.style,
                         styles.flex1,
                         paddingStyle,
```
Comment (Luke9389) [inline src/components/ScreenWrapper.js:51]: This may create duplicate styles. We can use [_.union](https://underscorejs.org/#union) to avoid this. We've already included it in our package.json, so you can just `import _ from 'underscore';` and use it here.

**Review by Luke9389 — CHANGES_REQUESTED** [review]

File: src/components/ScreenWrapper.js (hunk 1 above)
Comment (parasharrajat) [reply src/components/ScreenWrapper.js:51]: Oh yeah.

**Comment by parasharrajat** [comment]
@shawnborton Unfortunately, I don't have IOS. Here are screenshots for other platforms. As per your query, the Statusbar is transparent and its color depends on the screen below.
## Desktop
Screenshot_20210323_005459
## Mobile Web
Screenshot_2021-03-23 Expensify cash - Chat with friends to send and receive money
## Android
Screenshot_2021-03-23-01-16-29-250_com expensify chat

File: src/components/ScreenWrapper.js [hunk 2]
```diff
@@ -43,13 +43,14 @@ const ScreenWrapper = props => (
                 paddingStyle.paddingBottom = paddingBottom;
             }
 
+            const wrapperStyles = _.union([
+                props.style,
+                styles.flex1,
+                paddingStyle,
+            ]);
```
Comment (Luke9389) [inline src/components/ScreenWrapper.js:50]: Does it work to put this directly into the styles key instead of making a variable for it?

**Comment by parasharrajat** [comment]
@Luke9389 Updated.
@shawnborton  Any comments on the screenshots above.
Thanks.

**Comment by shawnborton** [comment]
Let me pull this down and test on iOS for you.

**Comment by shawnborton** [comment]
Looks good on iOS!

**Review by Luke9389 — APPROVED** [review]

**Comment by Luke9389** [comment]
@parasharrajat nice work on this PR! Sorry that my reviews may have felt a bit... nit-picky. In the future, please know that if I ask a question on a review, I really don't know the answer. So don't feel like I'm asking you rhetorical questions, or that I'm hinting at something. I'll always be direct 😄. Anyway, good job, and thank you! 🙇‍♂️

**Comment by parasharrajat** [comment]
@Luke9389. I actually like the nit-picky reviews. it helps in decision-making. Eventually, a review is a kind of second personality's point of view. So tackling all these reviews is making me good at making decisions related to code. I am sure it will help in the long run when we have to work over a lib for developers and not for consumers. :+1:

**Comment by laurenreidexpensify** [comment]
@parasharrajat I will make a plan to get you paid for this PR as a bonus on your next Upwork payment 👍🏽

**Comment by parasharrajat** [comment]
@laurenreidexpensify Amazing. Thanks

**Comment by laurenreidexpensify** [comment]
Okay as that was merged on Tues 23 March, will pay you on 30 March as per the 7 day regression test 👍🏽
