### PR TITLE
fix: Incomplete reports would cause the app to crash on startup

### LINKED ISSUE #2497: [Hold for payment 5/7] Blank screen after creating an account
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
User proceeds to expensify.cash chat list

## Actual Result:
User is redirected to a blank screen and a JS error can be seen in the console

## Action Performed:
1. Start from logged out state and proceed to create a new account
2. While logged out, type and login with brand new email address so it can trigger sign up flow
3. Get validation link from e-mail. On dev I'm copying the email link and appending it to localhost - e.g. http://localhost:8080/setpassword/10024706/EHOHMPGWM
4. Type new password and click "set password"
5. User is redirected to a blank screen and a JS error can be seen in the console

## Workaround:
Refreshing the page manually would fix the issue and the chat list would load

## Platform:
Where is this issue occurring?
The issue is confirmed in:

 Web ✔️ 
 Android ✔️
 iOS
 Desktop App 
 Mobile Web

The other environments are probably affected as well

**Version Number:** 1.0.21-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/12156624/115445533-a7a10b80-a21e-11eb-822a-e3e1d4101e9f.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by kidroca**
<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>
@marcaaron

Added filtering so that only valid reports are processed by findLastAccessedReport
Updated getInitialReport to getInitialReportScreenParams and moved to utils

This is a follow up to address the issue found in #2575

Fixes #2497

### CODE REVIEW

File: src/libs/reportUtils.js [hunk 1]
```diff
@@ -24,19 +25,33 @@ function isReportMessageAttachment(reportMessageText) {
...
+ * This will ensure the initialParams are only set once for the ReportScreen.
+ */
+const getInitialReportScreenParams = _.once((reports) => {
+    const last = findLastAccessedReport(reports);
+
+    // Fallback to empty if for some reason reportID cannot be derived - prevents the app from crashing
+    const reportID = lodashGet(last, 'reportID', '');
+    return {reportID};
+});
+
```
Comment (kidroca) [inline src/libs/reportUtils.js:51]: Moved this here as it became a bit bigger and needs to be declared above the component 

Because this is now exported - It will be an issue if this is used anywhere else but inside `MainDrawerNavigator` so maybe it should be moved there after all...

File: src/libs/reportUtils.js [hunk 2]
```diff
@@ -1,5 +1,6 @@
 import _ from 'underscore';
 import Str from 'expensify-common/lib/str';
+import lodashGet from 'lodash/get';
```
Comment (kidroca) [inline src/libs/reportUtils.js:3]: `underscore` has the same functionality and syntax if you update the package

```js
_.get(item, path, defaultValue);
```

Comment (marcaaron) [reply src/libs/reportUtils.js:3]: Interesting! We should consider it, but not necessary for now since we have a lot of the lodash usages already.

**Review by marcaaron — COMMENTED** [review]
Looks good but agree about putting the method back to the `MainDrawerNavigator`

File: src/libs/reportUtils.js [hunk 3]
```diff
@@ -24,19 +25,33 @@ function isReportMessageAttachment(reportMessageText) {
...
  * Given a collection of reports returns the most recently accessed one
  *
- * @param {Record<String, {lastVisitedTimestamp}>|Array<{lastVisitedTimestamp}>} reports
+ * @param {Record<String, {lastVisitedTimestamp, reportID}>|Array<{lastVisitedTimestamp, reportID}>} reports
  * @returns {Object}
  */
-function getLastAccessedReport(reports) {
+function findLastAccessedReport(reports) {
     return _.chain(reports)
         .toArray()
```
[the remark this answers is not in the document]
Comment (kidroca) [reply src/libs/reportUtils.js:33]: Yes, very necessary the `reports` is actually an object like

```js
{
    report_71734617: {
        reportID: 71734617, reportName: 'expense3@kidroca.com',
    },
    report_71403849: {
        reportID: 71403849, reportName: 'expense2@kidroca.com, expense3@kidroca.com',
    },
    report_73013597: {
        reportID: 73013597, reportName: 'expensify12@kidroca.com',
    },
};
```

**Comment by kidroca** [comment]
Updated

**Comment by kidroca** [comment]
BTW I noticed that the Sidebar component uses Onyx to get the currently viewed report, while the Report Screen would use routing information

https://github.com/Expensify/Expensify.cash/blob/6c7a420a565ff8eab9e2fc5c05d60304f68d9f39/src/pages/home/sidebar/SidebarLinks.js#L100

These might need to be updated so they either use only nav routing or onyx. I think with the latest updates you can be sure that the data provided by navigation is accurate

File: src/libs/reportUtils.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/libs/reportUtils.js:32]: I think `_.filter()` will do the array conversion for us e.g.

Screen Shot 2021-04-30 at 7 42 59 AM

**Review by marcaaron — APPROVED** [review]
LGTM

**Comment by kidroca** [comment]
> What exactly did you mean by this?

The `ReportScreen` have to set the current reportID namely because of others usages that rely on Onyx to get the currently viewed report, they can just as easily get it from react-navigation

It's not really about improvement but about consistency you can get the it from Onyx or from navigation and right now we're doing both - We should not be doing the same thing in two different ways as it can be confusing

File: src/libs/reportUtils.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (kidroca) [reply src/libs/reportUtils.js:32]: 👍 Interesting, didn't expect it

**Comment by marcaaron** [comment]
>It's not really about improvement but about consistency

I'd say consistency is a kind of improvement we value 🙃 

>others usages that rely on Onyx to get the currently viewed report, they can just as easily get it from react-navigation

I guess this is the part I'm curious about. Is there some way to access the route params via the navigation object?

**Comment by kidroca** [comment]
> I guess this is the part I'm curious about. Is there some way to access the route params via the navigation object?

A screen would receive them naturally from props the way ReportScreen works 
You can also use the useRoute hook - https://reactnavigation.org/docs/use-route

I guess you might say "What about usages like in `Report.js` and `User.js`" (The only such usages BTW)

https://github.com/Expensify/Expensify.cash/blob/a2d2f4ecd42aa9f2912db7dac92583498532c218/src/libs/actions/User.js#L144

I don't think you need the reportID here - this would get resolved by initalParams, you can just redirect to HOME, or unmount the ValidateLogin screen 

Now the usage in `Report.js` is a bit harder to get around, because it probably is event driven - you can't just pass the reportId as a parameter at the start

https://github.com/Expensify/Expensify.cash/blob/a2d2f4ecd42aa9f2912db7dac92583498532c218/src/libs/actions/Report.js#L491

So to cover both the above cases you can maybe capture reportID in Navigation and provide it / export it from there to everyone else 

https://github.com/Expensify/Expensify.cash/blob/a2d2f4ecd42aa9f2912db7dac92583498532c218/src/libs/Navigation/Navigation.js#L62-L65

Maybe there's an easier way...

**Comment by isagoico** [comment]
@kidroca @marcaaron Any QA needed for this PR?

**Comment by isagoico** [comment]
Mmmm I think we could rerun the previous [PR](https://github.com/Expensify/Expensify.cash/pull/2575)? @marcaaron can you confirm this is ok?

**Comment by marcaaron** [comment]
Yep re-running the previous PR sounds OK. However, it's not likely you'll run into the issue as we aren't sure what causes it and it should be fixed now.

**Comment by roryabraham** [comment]
I am suspicious that this PR may have caused [a regression](https://github.com/Expensify/Expensify.cash/issues/2668)

**Comment by roryabraham** [comment]
Nevermind, doesn't seem like it did

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js [hunk 4]
```diff
@@ -85,3 +90,4 @@ export default compose(
         },
     }),
 )(MainDrawerNavigator);
+export {getInitialReportScreenParams};
```
Comment (roryabraham) [inline src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:93]: Old PR now, but any idea why this export was added? Doesn't seem to be used anywhere AFAICT

Comment (marcaaron) [reply src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:93]: Maybe we were using it somewhere at some point. I don't really know tbh.

Comment (kidroca) [reply src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:93]: Originally it was part of `reportUtils` and imported to `MainDrawerNavigator`: https://github.com/Expensify/App/commit/bc63c492e068d8b2a1c3361579e13d5894f3ca8b#diff-82f2652821babb48b600a87486fa1191db7b3cc300845573a5757676e13cfc26L44

I decided it's tied to the MainDrawerNavigator (see `_.once` decorator and description) and moved it for better context
I guess I used automatic refactoring, which preserves exporting the file after it's moved
