### PR TITLE
fix: paste and Ctrl+z

### LINKED ISSUE #4120: Pasted content is placed at the beginning of the message and not where the cursor is positioned and undo (CTR+Z) is not working
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to e.cash and navigate to a conversation
2. Send a message
3. After the message has sent, copy it
4. In the compose box, enter some text
5. With the cursor at the end of the input, paste the message
6. Press the shortcut for undo (CTRL+Z)

## Expected Result:
Pasted content should be displayed were the cursor was positioned, in this case at the end of the message. CTRL+Z should undo the last action that was the pasted content. 

## Actual Result:
Pasted content is displayed at the start of the message and CRTL+Z does not remove the pasted content. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
Where is this issue occurring?

 Web ✔️ 
 iOS
 Android
 Desktop App ✔️ 
 Mobile Web

**Version Number:** 1.0.79-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

KkUUmcOWPQ

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
From @alex-mechler https://expensify.slack.com/archives/C01GTK53T8Q/p1626366219328100
> When pasting content from another message on Desktop, the pasted content is always placed at the beginning of the compose, regardless of where the cursor is. Reproduction steps in the thread

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ Fixes #4120

### Tests | QA Steps
1. Log in to e.cash and navigate to a conversation.
2. Send a message.
3. After the message has been sent, copy it.
4. In the compose box, enter some text.
5. With the cursor at the end of the input, paste the message.
6. Press the shortcut for undo (CTRL+Z).

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Web

https://user-images.githubusercontent.com/24370807/126042511-42d79c72-9d41-4374-aaca-8d082b230c0c.mp4

### CODE REVIEW

**Review by mountiny — APPROVED** [review]
@parasharrajat Tested based on instruction in here https://github.com/Expensify/Expensify.cash/issues/3790. 

I assume that copy pasting bold text from a message in E.cash is different problem, right?

**Comment by parasharrajat** [comment]
Yes @mountiny  That is a different issue.

File: src/components/TextInputFocusable/index.js [hunk 1]
```diff
@@ -252,13 +236,11 @@ class TextInputFocusable extends React.Component {
...
-        this.textInput.value = beforeCursorText + markdownText + afterCursorText;
-        const newCursorPosition = beforeCursorText.length + markdownText.length;
-        this.setState({selection: {start: newCursorPosition, end: newCursorPosition}});
-        this.updateNumberOfLines();
-        this.props.onChangeText(this.textInput.value);
+        try {
+            document.execCommand('insertText', false, markdownText);
+            this.updateNumberOfLines();
+        // eslint-disable-next-line no-empty
+        } catch (e) {}
```
Comment (HorusGoul) [inline src/components/TextInputFocusable/index.js:243]: The `execCommand` API is deprecated. Is there an alternative to this?

Also, could you add a comment to explain why do we need an empty `catch {}` block here?

**Review by HorusGoul — CHANGES_REQUESTED** [review]

File: src/components/TextInputFocusable/index.js (hunk 1 above)
Comment (parasharrajat) [reply src/components/TextInputFocusable/index.js:243]: @HorusGoul Its deprecated but I didn't find any direct alternative. If we don't use it then we have to implement our own framework to manage undo redo and other operations. There are few WYSIWYG editors out there which does this but we are not currently using it. 

After a careful inspection I come to the decision of using it, previously I was doing the manual paste but it lacked Undo functionality..

This is still supported for almost all browsers https://caniuse.com/?search=execCommand.
Also, I checked RN-WEB to see how they manage Copy to clipboard. They are also using it https://github.com/necolas/react-native-web/blob/98dcefd9041c10cc95a2385202498b274d926a6b/packages/react-native-web/src/exports/Clipboard/index.js#L50

I just borrowed the catch block from RN-web. 

We can think about of changing to different alternative when we redesign our composer  but I would say ATM its the best bet.

Comment (HorusGoul) [reply src/components/TextInputFocusable/index.js:243]: Great! Let's merge then :)

**Review by HorusGoul — APPROVED** [review]

**Comment by isagoico** [comment]
This is working as intended in **MacOS Desktop and Web only**. Windows is still facing this same issue https://github.com/Expensify/App/issues/4066

**Comment by parasharrajat** [comment]
@isagoico #4066 is different from thr problem this PR solves. It is meant to solve #4120.

I will look into that seperately.

File: src/components/TextInputFocusable/index.js [hunk 2]
```diff
@@ -353,7 +335,7 @@ class TextInputFocusable extends React.Component {
                 onChange={() => {
                     this.updateNumberOfLines();
                 }}
-                onSelectionChange={this.saveSelection}
+                onSelectionChange={this.onSelectionChange}
```
Comment (esh-g) [inline src/components/TextInputFocusable/index.js:338]: Shouldn't this be `this.props.onSelectionChange`? Because `onSelectionChange` does not exist as a method on `Composer`

Comment (esh-g) [reply src/components/TextInputFocusable/index.js:338]: @parasharrajat
