### PR TITLE
Fix profile menu position

### LINKED ISSUE #3895: [HOLD for payment July 19] Web: “Edit Photo” dropdown menu in `Settings > Profile` does not launch from the bottom of the button and ends up covering the profile photo
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Expensify.cash on web browser (or desktop app)
2. Click on profile photo
3. Click on Profile
4. Click `Edit Photo`.

## Expected Result:
 The dropdown should open top to bottom below the `Edit Photo` button.

## Actual Result:
The edit menu obscures the profile photo 

## Workaround:
N/A (display issue) 

## Platform:

 Web :heavy_check_mark: 
 iOS
 Android
 Desktop App :heavy_check_mark: 
 Mobile Web

**Version Number:** 1.0.75-5
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

From Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1625597860486800

> ISSUE: the “Edit Photo” dropdown menu in Settings > Profile does not launch from the bottom of the button and ends up covering the profile photo

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ Fixes #3895

### Tests |  QA Steps
1. Open ProfilePage on E.cash.
2. Click edit Image.
3. menu should open below the edit button and animating from top to bottom.

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Web | Desktop

image

### CODE REVIEW

File: src/components/AvatarWithImagePicker.js [hunk 1]
```diff
@@ -125,8 +125,8 @@ class AvatarWithImagePicker extends React.Component {
                                     onItemSelected={() => this.setState({isMenuVisible: false})}
                                     menuItems={this.createMenuItems(openPicker)}
                                     anchorPosition={this.props.anchorPosition}
-                                    animationIn="fadeInRight"
-                                    animationOut="fadeOutRight"
+                                    animationIn="fadeInDown"
+                                    animationOut="fadeOutUp"
```
Comment (chiragsalian) [inline src/components/AvatarWithImagePicker.js:129]: Okay, so I know this is part of your proposal but it's sort of unsettling for my OCD. Because as i test this whenever I click edit, for a brief second the menu is over my avatar which is really weird for me. Not sure if it's just me so I'll let @shawnborton chime in his preference since it's mostly a design thing.

Comment (parasharrajat) [reply src/components/AvatarWithImagePicker.js:129]: I just move the solution to a simpler one. Otherwise, we have to adjust all of our Popups.

Comment (parasharrajat) [reply src/components/AvatarWithImagePicker.js:129]: @shawnborton Could you please provide your feedback? Thanks. What Chirag is saying is that Menu is shown with fade In down effect which covers some part of the avatar while animating to the bottom. Do you feel that this is an UX issue?

Comment (shawnborton) [reply src/components/AvatarWithImagePicker.js:129]: I agree with this feedback and I've personally felt the same way about the way the popover launches when you tap on the little phone/call button on desktop. That being said, I think it makes sense to just implement the simple solution Rajat has in place for now, but it might be nice to revisit this as a more holistic thing and make sure we launch these popovers starting from the bottom of the element. Or even just a simple fade in would do the trick.

Comment (chiragsalian) [reply src/components/AvatarWithImagePicker.js:129]: Alright, thanks for the thoughts Shawn. I'll go ahead and merge and we can revisit improvements at a later point.

**Review by chiragsalian — APPROVED** [review]
