### PR TITLE
fixed scrolling when focusing on the edit box for old message

### LINKED ISSUE #3545: Tapping on Edit Message scrolls down to the bottom to the compose box
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Describe what you think should've happened

## Expected result:
User stays in the same position and is able to edit the message

## Actual result:
Tapping on Edit scrolls down the page to the compose box

## Actions Performed:
1. Launch the app and log in
2. Hover over a sent message and click on the edit comment option in the menu
3. Start editing the message

## Platform:

Android ✔️

**Notes/Images/Video:**

https://user-images.githubusercontent.com/43996225/121611132-92c64480-ca25-11eb-8aaa-8c5204107ff7.mp4

**Version Number:** 1.0.67-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

Fixes #3545 

### Tests | QA Steps

  1.  Open any conversation on Ecash Mobile.
  2. Hover over a sent message and click on the edit comment option in the menu
  3. Focus on the edit box, Start editing the message.
  4. When the keyboard opens, you should be able to type in the edit box and chat should not scroll. Like 
  https://user-images.githubusercontent.com/43996225/121611132-92c64480-ca25-11eb-8aaa-8c5204107ff7.mp4

### Tested On

- [ ] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

#### Android

https://user-images.githubusercontent.com/24370807/121732118-76063b80-cb0f-11eb-8688-a4605150afcc.mp4

### CODE REVIEW

File: src/libs/ReportActionComposeFocusManager.js [hunk 1]
```diff
@@ -30,8 +32,20 @@ function clear() {
     focusCallback = null;
 }
 
+/**
+ * Tells about the current focus state of the report action composer.
```
Comment (Julesssss) [inline src/libs/ReportActionComposeFocusManager.js:36]: `Tells about the current focus...` > `Exposes the current focus...`

Comment (parasharrajat) [reply src/libs/ReportActionComposeFocusManager.js:36]: Sorry, do you want to update the comment?

Comment (Julesssss) [reply src/libs/ReportActionComposeFocusManager.js:36]: Yep, sorry :)

**Comment by parasharrajat** [comment]
Updated. Thanks

**Review by Julesssss — APPROVED** [review]

**Review by nickmurray47 — APPROVED** [review]

File: src/libs/ReportActionComposeFocusManager.js [hunk 2]
```diff
@@ -30,8 +32,20 @@ function clear() {
...
 
+/**
+ * Exposes the current focus state of the report action composer.
+ *
+ */
+function isFocused() {
+    if (composerRef.current) {
+        composerRef.current.isFocused();
+    }
+}
```
Comment (kidroca) [inline src/libs/ReportActionComposeFocusManager.js:43]: I've noticed this function does not `return` a value

File: src/pages/home/report/ReportActionsView.js [hunk 3]
```diff
@@ -107,7 +108,11 @@ class ReportActionsView extends React.Component {
     componentDidMount() {
         AppState.addEventListener('change', this.onVisibilityChange);
         subscribeToReportTypingEvents(this.props.reportID);
-        this.keyboardEvent = Keyboard.addListener('keyboardDidShow', this.scrollToListBottom);
+        this.keyboardEvent = Keyboard.addListener('keyboardDidShow', () => {
+            if (ReportActionComposeFocusManager.isFocused()) {
+                this.scrollToListBottom();
+            }
```
Comment (kidroca) [inline src/pages/home/report/ReportActionsView.js:114]: This logic will never run since `ReportActionComposeFocusManager.isFocused` does not return a value 

```js
function isFocused() {
    if (composerRef.current) {
        composerRef.current.isFocused();
    }
}
```

**Review by kidroca — COMMENTED** [review]
I think you've forgotten to test the case where the view should still scroll to the bottom
with the current changes it never will

---

And now a commercial break for my IDE: **Webostorm**:  https://lp.jetbrains.com/webstorm-ide-2/

image
- it also helped me trace the code to this PR

File: src/libs/ReportActionComposeFocusManager.js (hunk 2 above)
Comment (parasharrajat) [reply src/libs/ReportActionComposeFocusManager.js:43]: Oh what a mess. . PR incoming.
