### PR TITLE
fix composer hidden while loading messages

### LINKED ISSUE #11840: [$250] Bug: Draft message is persisted across chats
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) Open any chat
2) Type a message but do not send it
3) Switch to another chat

## Expected Result:
4) No draft message is shown in other chats (or a different draft message should show)

## Actual Result:
4) The draft message from step 2 is shown in every chat

## Workaround:
Yes, but this is still bad. Other draft messages are being overwritten

## Platform:

Where is this issue occurring?

- Web ✅ 
- iOS ❓ 
- Android ✅ 
- Desktop App ❓ 
- Mobile Web ✅ 

**Version Number:** `v1.2.15-2`
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Notes/Photos/Videos:** Added below:
**Reporter:** Tushu
**Slack:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665739959841639

https://user-images.githubusercontent.com/10736861/195832292-7bdf90f8-d66a-4a4c-8a00-69cba3a4740f.mov

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### PR DESCRIPTION
**Pull request by 0xmiroslav**
### Details
- revert https://github.com/Expensify/App/pull/11853
- To fix https://github.com/Expensify/App/issues/11840, add `key={this.props.report.reportID}` to `ReportActionCompose` so it re-renders whenever report changes

### Fixed Issues
$ https://github.com/Expensify/App/issues/11856
PROPOSAL: https://github.com/Expensify/App/issues/11856#issuecomment-1297004819

### Tests
1. Login with any account on web app
2. Open any chat
3. Switch between chats
4. Verify that composer view doesn't disappear
5. Refresh the page
6. Verify that composer view appears immediately

NOTE: On small screen devices (mobile, mWeb), it's intended behavior to freeze screen (loading skeleton without showing composer) until drawer is fully open. But after that, composer should appear along with skeleton while loading messages.

- [x] Verify that no errors appear in the JS console

### QA Steps
1. Login with any account on web app
2. Open any chat
3. Switch between chats
4. Verify that composer view doesn't disappear
5. Refresh the page
6. Verify that composer view appears immediately

NOTE: On small screen devices (mobile, mWeb), it's intended behavior to freeze screen (loading skeleton without showing composer) until drawer is fully open. But after that, composer should appear along with skeleton while loading messages.

- [ ] Verify that no errors appear in the JS console

#### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

#### Web

https://user-images.githubusercontent.com/97473779/200295725-ddb1c3e4-ee3c-4d90-a6e7-285538422994.mov

#### Mobile Web - Chrome

https://user-images.githubusercontent.com/97473779/200295580-7de9d07a-ed0f-4d6d-bf54-76a2a9c2f3b5.mp4

#### Mobile Web - Safari

https://user-images.githubusercontent.com/97473779/200295626-b14b499c-41b1-4021-a71d-de3671b83bfb.mp4

#### Desktop

https://user-images.githubusercontent.com/97473779/200295451-f4fd940a-d78c-4c01-86ef-b577f506b957.mov

#### iOS

https://user-images.githubusercontent.com/97473779/200295514-cdf7f6c3-ac7c-44e5-a3df-b12a706f0a81.mp4

#### Android

https://user-images.githubusercontent.com/97473779/200295394-5e980cea-b1df-42c4-80fc-cdffaf4da88f.mp4

### CODE REVIEW

File: src/pages/home/ReportScreen.js [hunk 1]
```diff
@@ -301,17 +301,15 @@ class ReportScreen extends React.Component {
                                     containerHeight={this.state.skeletonViewContainerHeight}
                                 />
                             )}
-                            {this.isReportReadyForDisplay() && !isLoadingInitialReportActions && (
```
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:304]: Can you please summarize whatever question you have and what you have tried so far to solve the problem?

[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:304]: Sorry, @0xmiroslav - what is your question? Can you please summarize **what** you are trying to do? Or please ask a single specific question about some changes I've made and we can go from there? I am not able to fully review this PR at the moment and I don't understand at all what we are trying to achieve.

[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:304]: Which condition are you referring to? Do you have a good understanding of why it exists or not? Anything I can help clarify?

[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:304]: Without looking into whether it is "safe" or not - I'd assume no code is "safe" to remove unless we understand what it does and can explain why it's not needed.

[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:304]: Going off of what little has been provided I would say that forcing a re-render with a key could work, but we need to be sure that we are not showing a "composer" that is matched with the previous report. It's possible to transition from one report to another - which is why we hide/show the composer. 

I would probably suggest showing some kind of placeholder composer, but you are welcome to get more feedback in the Slack channel.

@rushatgabhane @Beamanator Was this detail considered during the design/proposal stage?

File: src/pages/home/ReportScreen.js [hunk 2]
```diff
@@ -301,17 +301,15 @@ class ReportScreen extends React.Component {
...
-                                    errors={addWorkspaceRoomOrChatErrors}
-                                    pendingAction={addWorkspaceRoomOrChatPendingAction}
-                                    isOffline={this.props.network.isOffline}
-                                    reportActions={this.props.reportActions}
-                                    report={this.props.report}
-                                    isComposerFullSize={this.props.isComposerFullSize}
-                                    onSubmitComment={this.onSubmitComment}
-                                />
-                            )}
+                            <ReportFooter
```
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:304]: I agree with @rushatgabhane. It doesn't need to be an _actual_ `ReportFooter` component? We just need to put something there to make the transition less jumpy.

[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:304]: >When open Report page first time, skeletonViewContainerHeight is not calculated yet. Therefore, composer floats to the top when swipe drawer first time.

Put it in the `ReportActionsSkeletonView` then

File: src/pages/home/ReportScreen.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:304]: There is some time before the `report.reportID` is correct. Review this and it will hopefully make more sense:

https://github.com/Expensify/App/blob/0422c5fb370762331530573dd32412d2006f80d6/src/pages/home/ReportScreen.js#L154-L162

**Comment by marcaaron** [comment]
bumping @rushatgabhane @Beamanator on this. I won't be reviewing this PR.

**Review by rushatgabhane — CHANGES_REQUESTED** [review]
> We keep current logic of conditionally rendering ReportFooter (don't add key)
At the condition of not rendering ReportFooter, instead show dummy ReportFooter along with skeleton (this is after freeze gone)
show dummy ReportFooter in freeze view


@0xmiroslav I don't quite agree with this approach. There are a few issues.

1. If a chat is loading and something is typed inside the composer, the draft will disappear after the chat has loaded because it was present in the dummy composer.

2. All loading reports have the same composer, so the draft text will also be the same across different loading reports.

https://user-images.githubusercontent.com/29673073/201422307-3a75171c-e46e-43a3-9dfa-1e802bb44c48.mov

**Comment by Beamanator** [comment]
Sorry y'all just coming back from vacay, I'll have time to review & respond tomorrow 👍

**Comment by Beamanator** [comment]
Fak 🙃 This is top priority for tomorrow, sorry for the delay y'all

**Comment by Beamanator** [comment]
So from the comments so far, it looks like the main "concern" with removing the `isLoadingInitialReportActions` check is that we need to make sure the ReportActionCompose we show _while a report is loading_ is not tied to any other report (mentioned [here](https://github.com/Expensify/App/pull/12505#discussion_r1018221426)). I've tested that the drafts created while reports are loading **ARE** sticking to the correct report, I think we also need to check message **SENT** while the report is loading (a.k.a. while the skeleton view is visible) are also sent to the correct report, is there anything else y'all are thinking could be an issue here?

**Comment by Beamanator** [comment]
There's two interesting things I see on this branch, I'm not sure if it's due to this PR or if it exists elsewhere, I'll test in staging soon: When I send a message in a report that has the skeleton view showing, I see:
1. The skeleton view disappears, even though the report actions are still loading. This makes it look like the message I sent is the only message in the chat, until the rest of the actions load
2. For some reason in this case, I see the newly sent message show bolded in the LHN, only when I send a message before the actions load

https://user-images.githubusercontent.com/3885503/203531081-98cdad68-2408-49ae-8e09-5fe50cf9618d.mov

**Comment by Beamanator** [comment]
Ok obviously ^ can't be tested the same way in staging b/c we can't send messages until the Report Action Compose shows up 😅 and in Staging / Prod it doesn't show up until the skeleton view hides. However, I did just reproduce the chat report becoming Bold by:
1. Changing the network to Slow 3G
2. Navigating to a report that I newly loaded (a.k.a. I saw the skeleton view)
3. Immediately after skeleton view hid, sent a message -> eventually saw that chat show bold in the LHN

So I think the only point we need to think about for this PR is: If we send a message while the skeleton view is showing, should we keep showing the skeleton view above until the rest of the actions are available? (I am thinking yes, but I'd like to see how it looks)

**Comment by marcaaron** [comment]
>When I send a message in a report that has the skeleton view showing the skeleton view disappears, even though the report actions are still loading. This makes it look like the message I sent is the only message in the chat, until the rest of the actions load

This is an interesting one. I think we're actually holding a few things wrong with the Report page at the moment and need to step back and sort them out. But doesn't feel like we should address them in this PR.

For now, we just need to show some variation of the composer while the report is loading so we can close out this issue.

File: src/components/ReportActionsSkeletonView/index.js [hunk 3]
```diff
@@ -32,10 +32,15 @@ const ReportActionsSkeletonView = (props) => {
...
+        <>
+            {skeletonViewLines}
+        </>
+    );
 };
 
 ReportActionsSkeletonView.displayName = 'ReportActionsSkeletonView';
 ReportActionsSkeletonView.propTypes = propTypes;
 ReportActionsSkeletonView.defaultProps = defaultProps;
+
```
Comment (marcaaron) [inline src/components/ReportActionsSkeletonView/index.js:45]: Can you please undo the changes in this file? They don't make any material difference and it's just extra noise.

File: src/pages/home/ReportScreen.js [hunk 4]
```diff
@@ -288,25 +297,14 @@ class ReportScreen extends React.Component {
...
-                                    <ReportFooter
-                                        errors={addWorkspaceRoomOrChatErrors}
-                                        pendingAction={addWorkspaceRoomOrChatPendingAction}
-                                        isOffline={this.props.network.isOffline}
-                                        reportActions={this.props.reportActions}
-                                        report={this.props.report}
-                                        isComposerFullSize={this.props.isComposerFullSize}
-                                        onSubmitComment={this.onSubmitComment}
-                                    />
-                                </>
```
Comment (marcaaron) [inline src/pages/home/ReportScreen.js:309]: I'm not following why this is being moved from here. Can we just leave it and make sure to show a default footer like we are doing in the `ReportActionsSkeletonView`. I had a previous suggestion to move the placeholder footer into that component. Did we try that or not?

File: src/pages/home/ReportScreen.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:318]: @0xmiroslav please address these comments.

**Review by marcaaron — CHANGES_REQUESTED** [review]

File: src/pages/home/ReportScreen.js (hunk 4 above)
Comment (marcaaron) [reply src/pages/home/ReportScreen.js:309]: That conversation makes no sense to me can you please summarize in one or two sentences why it does not work.

Comment (marcaaron) [reply src/pages/home/ReportScreen.js:309]: @0xmiroslav can you please provide a brief summary for us so we can move this along? One or two sentences would be perfect. I can better assist if you provide a clear explanation vs. links to videos or other conversations.

**Comment by Beamanator** [comment]
Posted summary of our latest test & possible options in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669728804509519?thread_ts=1669259814.248689&cid=C01GTK53T8Q)

File: src/pages/home/ReportScreen.js [hunk 5]
```diff
@@ -233,7 +233,16 @@ class ReportScreen extends React.Component {
                     placeholder={(
                         <>
                             <ReportHeaderSkeletonView animate={animatePlaceholder} />
-                            <ReportActionsSkeletonView animate={animatePlaceholder} containerHeight={this.state.skeletonViewContainerHeight} />
+                            <View style={[styles.flex1, styles.justifyContentEnd, styles.overflowHidden]}>
```
Comment (marcaaron) [inline src/pages/home/ReportScreen.js:236]: Why is it necessary to add a `View` here?

File: src/pages/home/report/ReportFooter.js [hunk 6]
```diff
@@ -94,6 +94,7 @@ class ReportFooter extends React.Component {
                                 contentContainerStyle={this.props.isComposerFullSize ? styles.flex1 : {}}
                             >
                                 <ReportActionCompose
+                                    key={this.props.report.reportID}
```
Comment (marcaaron) [inline src/pages/home/report/ReportFooter.js:97]: Do we need this anymore?

**Review by marcaaron — CHANGES_REQUESTED** [review]
I had some style improvements but I think I will just start adding commits here to push this along.

File: src/pages/home/report/ReportActionCompose.js [hunk 7]
```diff
@@ -518,6 +518,7 @@ class ReportActionCompose extends React.Component {
         const isBlockedFromConcierge = ReportUtils.chatIncludesConcierge(this.props.report) && User.isBlockedFromConcierge(this.props.blockedFromConcierge);
         const inputPlaceholder = this.getInputPlaceholder();
         const hasExceededMaxCommentLength = this.comment.length > CONST.MAX_COMMENT_LENGTH;
+        const isUserInteractionDisabled = this.props.reportID === '0';
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:521]: Can we do a `disabled` prop and pass it through `ReportFooter` as `shouldDisableCompose`. More explicit and less dependent on the `reportID` would be easier to understand.

File: src/pages/home/ReportScreen.js [hunk 8]
```diff
@@ -309,9 +318,18 @@ class ReportScreen extends React.Component {
...
+                                <>
+                                    <ReportActionsSkeletonView
+                                        containerHeight={this.state.skeletonViewContainerHeight}
+                                    />
+                                    <ReportFooter
+                                        isComposerFullSize={false}
+                                        isOffline={this.props.network.isOffline}
+                                        onSubmitComment={() => {}}
+                                        report={{reportID: '0'}}
+                                        reportActions={{}}
```
Comment (marcaaron) [inline src/pages/home/ReportScreen.js:330]: Similarly, these three (`onSubmitComment`, `report`, and `reportActions`) could just use a default when `shouldDisableCompose` is present - instead of having to add it in the two places.

File: src/pages/home/report/ReportActionCompose.js [hunk 9]
```diff
@@ -86,7 +86,7 @@ const propTypes = {
     isFocused: PropTypes.bool.isRequired,
 
     /** Is the composer full size */
-    isComposerFullSize: PropTypes.bool.isRequired,
+    isComposerFullSize: PropTypes.bool,
```
Comment (Beamanator) [inline src/pages/home/report/ReportActionCompose.js:89]: Does this requirement need to be removed? I don't see you removing the prop `isComposerFullSize` anywhere so I'd assume it should stay the same?

File: src/pages/home/report/ReportActionCompose.js [hunk 10]
```diff
@@ -567,7 +567,7 @@ class ReportActionCompose extends React.Component {
                                                             }}
                                                             style={styles.composerSizeButton}
                                                             underlayColor={themeColors.componentBG}
-                                                            disabled={isBlockedFromConcierge}
+                                                            disabled={isBlockedFromConcierge || this.props.disabled}
```
Comment (Beamanator) [inline src/pages/home/report/ReportActionCompose.js:570]: Please add `this.props.disabled` `propType`

**Review by Beamanator — CHANGES_REQUESTED** [review]
Few comments, overall code is looking nice!

**Comment by marcaaron** [comment]
@rushatgabhane what's the status of your review here? Can you please prioritize this?

File: src/pages/home/ReportScreen.js (hunk 8 above)
Comment (marcaaron) [reply src/pages/home/ReportScreen.js]: Looks great thanks.

File: src/pages/home/report/ReportActionCompose.js (hunk 7 above)
Comment (marcaaron) [reply src/pages/home/report/ReportActionCompose.js]: Amazing thank you!

**Review by marcaaron — DISMISSED** [review]
Code looks great, thanks for your patience her @0xmiroslav

**Review by Beamanator — DISMISSED** [review]
:shipit:

**Comment by Beamanator** [comment]
@rushatgabhane are you able to re-review on all platforms today? If not, please let me know and I will take care of it

**Review by rushatgabhane — DISMISSED** [review]
## Reviewer Checklist

@Beamanator LGTM!
Unrelated to PR - It kinda takes forever to load chats 😅
 
- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.


### Screenshots/Videos
<details>
<summary>Web</summary>


https://user-images.githubusercontent.com/29673073/205701227-6c401870-311e-4079-9417-ad271f74e02d.mov


</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/29673073/205715019-2c7e33ba-ce7d-450a-9240-42eaf885f2f3.mov


</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/29673073/205714769-bf90c66f-1b00-4cf4-b249-4b8beedf40a9.mov


</details>



<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/29673073/205714426-a3a9dc8a-fcd3-451a-939d-16b6cf467b07.mov



</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/29673073/205712859-580a257d-4065-47e6-985b-a6a32decbd23.mov



</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/29673073/205714186-8d649070-25b4-4d38-9f85-9d56a6de37e3.mp4



</details>

**Review by rushatgabhane — APPROVED** [review]
@Beamanator looks good.

Gave it a sanity check after merge conflicts were fixed


https://user-images.githubusercontent.com/29673073/206486726-6aaa7ff5-e024-4a6d-a719-7b4bb6a53045.mov

**Review by marcaaron — APPROVED** [review]

File: src/pages/home/ReportScreen.js [hunk 11]
```diff
@@ -312,9 +318,15 @@ class ReportScreen extends React.Component {
...
                             we'll unnecessarily unmount the ReportActionsView which will clear the new marker lines initial state. */}
                             {(!this.isReportReadyForDisplay() || isLoadingInitialReportActions) && (
-                                <ReportActionsSkeletonView
-                                    containerHeight={this.state.skeletonViewContainerHeight}
-                                />
+                                <>
+                                    <ReportActionsSkeletonView
+                                        containerHeight={this.state.skeletonViewContainerHeight}
+                                    />
+                                    <ReportFooter
```
Comment (sobitneupane) [inline src/pages/home/ReportScreen.js:325]: While the report is loading, user interaction in composer is disabled. (Implemented by this [commit](https://github.com/Expensify/App/commit/6fe2785f674a5a6933663a88dc47c02a6d336ea9)) We have [a feature request](https://github.com/Expensify/App/issues/14223) to enable composer even when the report is loading. So, @0xmiroslav @rushatgabhane  I am trying to understand why was it disabled? 

cc: @Beamanator @marcaaron

Comment (marcaaron) [reply src/pages/home/ReportScreen.js:325]: Yes, we chose to keep it disabled as it was not displayed at all before. So basically, we decided to focus on just one ticket at a time rather than open a big box of problems 😄
