### PR TITLE
Fix popovers after regression

### LINKED ISSUE #2420: Copy - Copy banner when using right click button on message too large
From Andrew in the #expensify-open-source channel https://expensify.slack.com/archives/C01GTK53T8Q/p1618510167289700
>Issue: Right click button is really big on web now
___

## Expected Result:
Copy message when using right click has a regular size (see image below) 

## Actual Result:
Copy message banner is taking more that 60% width of the page. 

## Action Performed:
1. Login in staging.expensify.cash
2. Go to a conversation with messages
3. Right click on a message

## Workaround:
Visual issue, no need for workaround. 

## Platform:
Where is this issue occurring?

 Web ✔️ 
 iOS
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.22-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Issue **not** reproducible in production. 

image

**Expensify/Expensify Issue URL:** N/A

### PR DESCRIPTION
**Pull request by roryabraham**
cc @npsedhain @tgolen 

### Details
Fixing a regression caused by [this PR](https://github.com/Expensify/Expensify.cash/pull/2222)

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2420

### Tests / QA Steps (Web/Desktop)
1. Hit the global create FAB, and verify that the `CreateMenu` appears in the correct position in the sidebar. It should fade in from the left and fade out to the left.
2. Hit the `+` icon in the `ReportActionCompose`. Verify that the `CreateMenu` appears in the correct position above the compose input. It should fade in from the bottom and fade out to the bottom.
3. Go to `Settings` -> `Profile` -> `Edit Photo`. Verify that the `CreateMenu` appears in the correct position above the "Edit Photo" button. It should fade in from the right and fade out to the right.
4. Right click on a message, and verify that the `ReportActionContextMenu` appears as it should in the location where the user clicks.
5. Open the emoji picker, make sure it looks normal (it shouldn't have any noticeable animation when it opens and closes).

### Tests / QA Steps (mWeb/iOS/Android)
1. Hit the following buttons, and verify that the `CreateMenu` appears as a bottom-docked modal:
    1. Global create FAB
    1. `+` in the `ReportActionCompose`
    1. `Settings` -> `Profile` -> `Edit Photo`
    1. Long-press a message.
    1. The emoji picker

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

|_Menu_|Web|Mobile Web|Desktop|iOS|Android|
|---|---|---|---|---|---|
|Global Create|image|image|image|image|image|
|ReportActionCompose|image|image|image|image|image|
|Edit Photo|image|image|image|image|image|
|ReportActionContextMenu|image|image|image|image|image|
|Emoji Picker|image|image|image|||

### CODE REVIEW

**Comment by roryabraham** [comment]
WIP while I gather screenshots

**Comment by roryabraham** [comment]
recheck

**Comment by roryabraham** [comment]
Hmmm CLA is being weird ... commenting "recheck" _did_ restart the CLA action which passed [here](https://github.com/Expensify/Expensify.cash/runs/2356912710?check_suite_focus=true), but for some reason it didn't update the PR. When I manually retried the check from the PR, it failed just like the first time due to the problem fixed [in this PR](https://github.com/Expensify/Expensify.cash/pull/2425)

**Comment by roryabraham** [comment]
Retested after merging main (and added the new `EmojiPickerMenu` popover), and verified that this still fixes the popover issues.

**Comment by npsedhain** [comment]
hey @roryabraham, thanks so much for this, also I am sorry I didn't see this yesterday, it was late in the night this part of the world. Let me know if there is anything I can do.

**Comment by Beamanator** [comment]
Looks like you _may_ be missing some screenshots for the emoji picker in android & desktop? I took these to help:

Desktop:
Screen Shot 2021-04-16 at 12 44 11 PM


Android: 
Screen Shot 2021-04-16 at 12 42 42 PM

File: src/components/CreateMenu.js [hunk 1]
```diff
@@ -95,5 +113,5 @@ class CreateMenu extends PureComponent {
 
 CreateMenu.propTypes = propTypes;
 CreateMenu.defaultProps = defaultProps;
-CreateMenu.displayName = 'CreateMenu';
```
Comment (Beamanator) [inline src/components/CreateMenu.js:98]: NAB; Just wondering, why did you remove this? I see most other components have this still 🤔

Comment (roryabraham) [reply src/components/CreateMenu.js:98]: `displayName` is only required for functional components, not class components 👍

Comment (roryabraham) [reply src/components/CreateMenu.js:98]: Although now that I'm saying that maybe it would be simpler to just always have it... 🤔
Anyways for now let's stick with the established pattern of having a `displayName` for functional components and no `displayName` for class components.

**Comment by roryabraham** [comment]
Thanks for testing and gathering those screenshots @Beamanator !

File: src/components/CreateMenu.js (hunk 1 above)
Comment (Beamanator) [reply src/components/CreateMenu.js:98]: Now I'm seeing that it is mentioned [here](https://github.com/Expensify/Expensify.cash/blob/431b60d09f4e41c7532707454625dbe2c3c22c21/STYLE.md#stateless-component-style) to only add for functional components, so good call :D

**Review by Beamanator — APPROVED** [review]
Love it - #LGTM 👍

**Comment by roryabraham** [comment]
@madmax330 I'm going to go ahead and merge this since it resolves a deploy blocker.

File: src/components/CreateMenu.js (hunk 1 above)
Comment (tgolen) [reply src/components/CreateMenu.js:98]: Yeah, in the original PR I had commented about this, and the part I was unclear on is if you need a display name for pure components.

The only purpose of the display name is so that the react dev tools is useful. So I would say, remove the display name property, and if it still has a proper name in the react dev tools (eg. `CreateMenu`) then it's fine to remove it. (again, I'm just not sure when it comes to `PureComponents`.

Comment (roryabraham) [reply src/components/CreateMenu.js:98]: We can check! IIRC it only makes a difference on mobile too

**Comment by isagoico** [comment]
## Attachment button in iOS is not working as expected, keyboard opens instead of modal

## Expected Result:
Popup " Add attachment" opens

## Actual Result:
Popup flashes for a moment and keypad opens to enter the text

## Action Performed:
1. Launch the app and login
2. Tap any chat from LHN
3. Tap + to attach a photo

## Workaround:
Unknown 

## Platform:
Where is this issue occurring?

 Web
 iOS ✔️ 
 Android
 Desktop App
 Mobile Web

**Version Number:**1.0.24-.

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/44479856/115096755-7958be80-9ef4-11eb-9123-e872cdac07a6.mp4

**Comment by Beamanator** [comment]
I reproduced on your branch - I often forget to test with keyboard enabled, so great catch @isagoico 👍

**Comment by Beamanator** [comment]
I believe this is the problem - https://github.com/Expensify/Expensify.cash/blob/main/src/pages/home/report/ReportActionCompose.js#L294, but supposedly that was added to fix some modal 2 modal transition in another PR

**Comment by roryabraham** [comment]
Thanks for looking into this @Beamanator. I will fiddle around and try to fix it. This is why it's always better to test with a physical device...

**Comment by roryabraham** [comment]
Fix is [here](https://github.com/Expensify/Expensify.cash/pull/2460) ... @isagoico are you sure this isn't present on production? I do not think this PR caused the bug/regression described.

**Comment by isagoico** [comment]
@roryabraham Sorry that I missed this before. I just verified with a tester that [this](https://github.com/Expensify/Expensify.cash/pull/2424#issuecomment-821737903) is not reproducible in prod.

**Comment by roryabraham** [comment]
Just confirmed on iOS v1.0.29-0 that this deploy blocker is solved.
