### PR TITLE
fixed count alignment on the LHN avatars

### LINKED ISSUE #2795: LHN - Group - Participant number is not centered in circle
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Number should be center in circle

## Actual Result:
Number is not centered in the circle. 

## Action Performed:
1. Log in to cash app
2. Create a group of 4+ participants 
3. Open the LHN 

## Workaround:
No need, visual issue. 

## Platform:
Where is this issue occurring?

 Web
 iOS ✔️ 
 Android ✔️ 
 Desktop App
 Mobile Web

**Version Number:** 1.0.41-11

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
On android it's not that noticeable as in iOS but it's still not centered

image

image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___
From @AndrewGable https://expensify.slack.com/archives/C01GTK53T8Q/p1620737290048200

> +5 on iOS does not look centered

### PR DESCRIPTION
**Pull request by parasharrajat**
Please review @roryabraham. 

### Fixed Issues

Fixes #2795

### Tests
 Performed some visual Tests
 1. edited the count manually to see if it is centered.

### QA Steps
1. Open E.cash
2. On LHN, observe the group chats that has 2 & more participants.
3. Count of participants should be centered.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web  

count-w

#### Mobile Web 
IMG_20210525_051438

IMG_20210525_051000

#### Desktop
Screenshot 2021-05-25 08:50:17

#### iOS
Simulator Screen Shot - iPhone 11 - 2021-05-25 at 15 27 31

#### Android

IMG_20210525_090017

### CODE REVIEW

**Comment by roryabraham** [comment]
@parasharrajat It doesn't look centered to me on iOS or mWeb

**Comment by parasharrajat** [comment]
@roryabraham vertically or horizontally?

**Comment by roryabraham** [comment]
Horizontally ... maybe both? Does it look centered to you?

image

**Comment by parasharrajat** [comment]
Lol. Vertically,  this is my life's hardest decision. Seems so.

Horizontally we used - margin to push the plus sign towards left. This is intentional. cc:  @shawnborton

**Comment by shawnborton** [comment]
Yup the slight horizontal push is intentional to give it a little more balance...

**Comment by sketchydroide** [comment]
Vertically I feel that it should be a pixel more to the bottom, but it's really hard to tell. @shawnborton what do your ~elf~ designer eyes see?

**Comment by parasharrajat** [comment]
I will try to measure it with some tool.

**Comment by shawnborton** [comment]
It might be helpful to show us full screenshots too... when it's zoomed in, it's a little harder to tell how it feels when it's perceived at a natural size.

**Comment by parasharrajat** [comment]
@shawnborton Interesting, I just found out that we are not using `GTAmericaExp-Regular` for the badge. Is this the correct behaviour?

**Comment by shawnborton** [comment]
That's not correct behavior, the badge should always use `GTAmericaExp-Regular` no matter the platform.

**Comment by parasharrajat** [comment]
Oh. Then in this case we have a problem. I just noticed that there are a couple of places where the font is not applied at all. But we should have `GTAmericaExp-Regular` as the base font for all text on the app. Correct?

**Comment by shawnborton** [comment]
That's correct.

**Comment by parasharrajat** [comment]
OK, then it better I create another issue to apply the font to all places so that I can send separate PR for that.

File: src/components/MultipleAvatars.js [hunk 1]
```diff
@@ -63,7 +64,7 @@ const MultipleAvatars = ({
                         />
                     ) : (
                         <View
-                            style={singleAvatarStyles}
+                            style={[singleAvatarStyles, styles.alignItemsCenter, styles.justifyContentCenter]}
                         >
                             <Text style={size === 'small'
                                 ? styles.avatarInnerTextSmall
```
Comment (roryabraham) [inline src/components/MultipleAvatars.js:70]: @parasharrajat I thought as part of the fix for this you were going to remove the custom line-height based styles?

Comment (parasharrajat) [reply src/components/MultipleAvatars.js:70]: Yes. I did planned this earlier but I realized that the font-family for the badge is not correct as we are using Text from RN instead of our customized version. But the new customized `Text` impose line-height of 20 which I think could be bigger for the LHN Focused mode thus keeping the line-height is a safe move. I am not sure how to reset the Line-height here as we don't actually need it.

**Comment by parasharrajat** [comment]
I am yet to update the IOS Screens. There is some build error. Hold on. Thanks.

File: src/components/MultipleAvatars.js (hunk 1 above)
Comment (roryabraham) [reply src/components/MultipleAvatars.js:70]: > thus keeping the line-height is a safe move

Hmmm ... I'm confused how you landed here. Since our custom `Text` component specifies a line-height, we should eliminate any unnecessary external styles which might conflict with the one specified internally.

As an aside (not to be handled in this PR, I think we should rename our custom `Text` component to `Expensitext`, to avoid the common mistake of importing `Text` from RN instead, which should never be done in Expensify.cash AFAIK.

Comment (parasharrajat) [reply src/components/MultipleAvatars.js:70]: > Since our custom Text component specifies a line-height, we should eliminate any unnecessary external styles which might conflict with the one specified internally
Normally, it have 20 LH which is fine. But when we are on #focused mode LH 20 is bigger for the avatar. it should be 18.

**Yeah let me check it again if LH is something we need to worry at all and then I will remove those from styles**.

There are many places where we are wrongly using the RN's `Text` I will send another PR for this. May be we can look at renaming it there.

Comment (parasharrajat) [reply src/components/MultipleAvatars.js:70]: @roryabraham It seems the extra Lineheight:20 is problematic in #focus mode. So either we keep these line heights or reset our Text's lH using `lineHeight:undefined` instead of these LHs.

**Comment by parasharrajat** [comment]
Updated all the screenshots and reset the custom Line_height from Text.

File: src/components/MultipleAvatars.js (hunk 1 above)
Comment (parasharrajat) [reply src/components/MultipleAvatars.js:70]: @roryabraham I updated the PR with `lineHeight:undefined` as I found it more promising.Thanks.

**Comment by parasharrajat** [comment]
Please let me know if something else is remained on this one.

**Review by roryabraham — APPROVED** [review]
