### PR TITLE
fixed offline messages are grayed out even if online

### LINKED ISSUE #2432: When offline, show which messages have been queued but not yet sent; when back online, show when they've been successfully delivered
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
When offline, know that a message hasn't been sent and, upon going back online, know that it has been sent.

## Actual Result:
You don't know if the message has been or when it does.

## Action Performed:

- Go offline on e.cash by switching off your internet connection to your device
- Send a message to someone
- Observe that you can't tell if the message hasn't been sent
- Once going back online, observe you can't tell when a message has successfully sent

### Deliverable: 

 Using the design mock up below, to implement a "You appear to be offline" prompt, with unsent messages in grey font - 

image

E/E issue - https://github.com/Expensify/Expensify/issues/155259
Upwork Posting - https://www.upwork.com/jobs/~01d9a1ee89310f7704

### PR DESCRIPTION
**Pull request by parasharrajat**
Please review @marcaaron 

### Details
Working on the change request here https://github.com/Expensify/Expensify.cash/issues/2432#issuecomment-824448698

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes #2432

### Tests / ### QA Steps
1. Try to send messages in any chat and observe the gray text until they are uploaded to the server.
2. Put on airplane mode, and send few messages, observe the text appearances.
3. You should also see a status  `You appear to be Offline` under the composer.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

https://user-images.githubusercontent.com/24370807/115645535-30fb2f80-a33e-11eb-8f59-c798931f9e41.mp4

### CODE REVIEW

**Comment by parasharrajat** [comment]
I also see that we are attaching a listener for `personaldetails` to `ReportActionItemSingle`. There would a lot of instances of this component on a single. Thus I suggest moving the listener up the `ReportActionsView` like I did here for `network`.

File: src/pages/home/report/ReportActionItem.js [hunk 1]
```diff
@@ -95,8 +98,18 @@ class ReportActionItem extends Component {
...
+                                            action={this.props.action}
+                                            isOffline={this.props.isOffline}
+                                        />
+                                    )
+                                    : (
+                                        <ReportActionItemGrouped
+                                            action={this.props.action}
+                                            isOffline={this.props.isOffline}
+                                        />
+                                    )}
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionItem.js:112]: Instead of drilling this prop down would it make sense to have `ReportActionItem` subscribe to the network key?

**Comment by marcaaron** [comment]
>I also see that we are attaching a listener for personaldetails to ReportActionItemSingle. There would a lot of instances of this component on a single screen. 

With stuff like this I think if you can time/benchmark and prove there is a perceptible difference then we should do it. But otherwise we could be making unnecessary optimizations.

File: src/pages/home/report/ReportActionItem.js (hunk 1 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionItem.js:112]: Ok Sure.

**Comment by parasharrajat** [comment]
Updated. Thanks.

File: src/pages/home/report/ReportActionItem.js (hunk 1 above)
Comment (marcaaron) [reply src/pages/home/report/ReportActionItem.js:121]: Sorry I misspoke here I meant to say, we should not need to pass `isOffline` prop to both `ReportActionItemSingle` and `ReportActionItemGrouped`. We can subscribe in `ReportActionItemMessage`.

**Review by marcaaron — CHANGES_REQUESTED** [review]
See additional comment thanks :)

File: src/pages/home/report/ReportActionItem.js (hunk 1 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionItem.js:121]: Oh.

**Comment by deetergp** [comment]
TIL: You can toggle online/offline in the browser debugger.

File: src/pages/home/report/ReportActionItem.js [hunk 2]
```diff
@@ -27,6 +29,16 @@ const propTypes = {
 
     // Should we display the new indicator on top of the comment?
     shouldDisplayNewIndicator: PropTypes.bool.isRequired,
+
+    // Information about the network
+    network: PropTypes.shape({
+        // Is the network currently offline or not
```
Comment (deetergp) [inline src/pages/home/report/ReportActionItem.js:35]: NAB: But the property name `isOffline` is pretty self-explanatory without the doc line.

Comment (parasharrajat) [reply src/pages/home/report/ReportActionItem.js:35]: I borrow the idea from Style guide. So I think we should keep it.

**Comment by parasharrajat** [comment]
Updated. Thanks.

File: src/pages/home/report/ReportActionItem.js (hunk 2 above)
Comment (marcaaron) [reply src/pages/home/report/ReportActionItem.js]: Yep, `propTypes` should always have doc lines

File: src/pages/home/report/ReportActionItemMessage.js [hunk 3]
```diff
@@ -2,18 +2,30 @@ import React from 'react';
...
+
+const defaultProps = {
+    network: {isOffline: false},
 };
 
-const ReportActionItemMessage = ({action}) => {
+const ReportActionItemMessage = ({action, network}) => {
     // reportActionID is only present when the action is saved onto server.
-    const isUnsent = action.loading && !action.reportActionID;
+    const isUnsent = network.isOffline && action.loading && !action.reportActionID;
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionItemMessage.js:28]: I'm not sure we need to check both `action.loading`  and `action.reportActionID`? What does having a `reportActionID` even mean?

**Review by marcaaron — CHANGES_REQUESTED** [review]
Looks better just one more comment about the original implementation here.

File: src/pages/home/report/ReportActionItemMessage.js (hunk 3 above)
Comment (marcaaron) [reply src/pages/home/report/ReportActionItemMessage.js:28]: Or asked another way are there comments that are "not loading" but "don't have a reportActionID"... it's unclear how we end up in that situation to me.

Comment (parasharrajat) [reply src/pages/home/report/ReportActionItemMessage.js:28]: I used this to make a difference from the attachment files. As they are also in loading status until they are uploaded. `action.reportActionID` is only present when comment is uploaded to backend.

Comment (parasharrajat) [reply src/pages/home/report/ReportActionItemMessage.js:28]: Yeah, it makes sense. we don't actually need it.

**Comment by parasharrajat** [comment]
@marcaaron Updated. Thanks. Sorry for the back and forth.

File: src/pages/home/report/ReportActionItemMessage.js (hunk 3 above)
Comment (marcaaron) [reply src/pages/home/report/ReportActionItemMessage.js]: >they are also in loading status until they are uploaded

Ok, yeah I believe there's no difference there. It should be the same whether attachment or not.

**Review by marcaaron — APPROVED** [review]

**Review by deetergp — APPROVED** [review]
LGTM!
