### PR TITLE
[Attendees Tracking] - More follow up issues

### LINKED ISSUE #61425: Expense - Attendees field is missing "x per person" in transaction thread
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.40-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/60067
**Email or phone of affected tester (no customers):** applausetester+300402kh@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Create expense > Manual.
4. Enter amount > Next.
5. On confirmation page, click Show more.
6. Click Attendees.
7. Select one more attendee.
8. Click Save.
9. Note that Attendees field has "x per person" on the confirmation page.
10. Click Create expense.
11. Go to transaction thread.

## Expected Result:
In transaction thread, Attendees field will also show "x per person".

## Actual Result:
In transaction thread, Attendees field is missing "x per person".

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e4cc3451-4e03-4274-9aa6-16256f02fd49

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #61426: Expense - Per diem - Attendees field shows "0.00 per person" when more than 1 user is selected
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.40-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/60067
**Email or phone of affected tester (no customers):** applausetester+300402kh@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Workspace has imported per diem rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Create expense > Per diem.
4. Select a destination.
5. Complete the rest of the flow and reach confirmation page.
6. On confirmation page, click Attendees.
7. Select one more attendee.
8. Click Save.

## Expected Result:
Attendees field will not show "0.00 per person" on confirmation page because it is not the correct amount.

## Actual Result:
Attendees field shows "0.00 per person" on confirmation page when more than 1 user is selected.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ac00cee9-e069-4143-9570-5ad77d075f52

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #61427: Expense - Same attendee name appears twice in the list and can be selected twice
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.40-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/60067
**Email or phone of affected tester (no customers):** applausetester+300402kh@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Create expense > Manual
4. Enter amount > Next.
5. On confirmation page, click Show more.
6. Click Attendees.
7. Enter a name (applee) and select the user.
8. Enter the same name again (applee).
9. Note that the same name appears twice. Do not select the same user.
10. Click Save.
11. Click Create expense.
12. Go to transaction thread.
13. Click Attendees.
14. Enter the same name from Step 7 (applee).
15. Select the duplicate name.
16. Click Save.
17. Note that the same name can be selected twice.

## Expected Result:
In Step 9, the same name will not appear twice in the list.
In Step 17, the same name can only be selected once.

## Actual Result:
In Step 9, the same name appears twice in the list.
In Step 17, the same name can be selected twice.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7853aa9e-1c3f-443e-b991-8e476b171e00

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #61429: Expense - Missing dot separator between Attendees and "x per person" in transaction thread
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.40-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/60067
**Email or phone of affected tester (no customers):** applausetester+300402kh@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Create expense > Scan
4. Upload a receipt.
5. On confirmation page, click Show more.
6. Click Attendees.
7. Select one more attendee.
8. Click Save.
9. Click Create expense.
10. Go to transaction thread.
11. Wait for the scan to complete.

## Expected Result:
There will be a dot separator between Attendees and "x per person" in transaction thread.

## Actual Result:
Dot separator is missing between Attendees and "x per person" in transaction thread.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1f6b8475-262c-42ff-9eb5-8b64a12c682b

Image

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

### LINKED ISSUE #61431: Review duplicates - Attendees field can be edited on confirmation page
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.40-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/58402
**Email or phone of affected tester (no customers):** sjdisndjssidu@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create two manual expenses with the same amount and merchant.
4. Go to transaction thread of any expense.
5. Click Review duplicates.
6. Select Keep this one on any expense preview.
7. On the confirmation page, click Attendees.
8. Edit the attendees.

## Expected Result:
Attendees field should be disabled on the confirmation page when reviewing duplicates (other fields are disabled on confirmation page).

## Actual Result:
Attendees field is not disabled on the confirmation page when reviewing duplicates and can be edited.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c3198415-d029-4b95-a95d-b9234a0583d2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #61433: Expense - Error after making changes to Attendees field as member after the expense is paid
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.40-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/60067
**Email or phone of affected tester (no customers):** applausetester+smidod11sj@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Admin and member are in the same workspace.

1. Go to staging.new.expensify.com
2. [Member] Go to workspace chat and submit an expense.
3. [Member] Click Submit on the expense preview.
4. [Admin] Go to workspace chat with member.
5. [Admin] Open the expense report.
6. [Admin] Click Approve and Pay elsewhere.
7. [Member] Go to the transaction thread of the paid expense.
8. [Member] Click Attendees field.
9. [Member] Add another attendee and save it.

## Expected Result:
Attendee field should be disabled for member after the expense is paid.

## Actual Result:
Attendee field is not disabled for member after the expense is paid. When editing the attendees field, app throws error.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c0f9387e-d8da-42c6-938e-b0223533b293

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #61491: [$250] Attendees field is missing on the confirmation page when creating per diem expense from FAB
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.40-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/60067
**Email or phone of affected tester (no customers):** applausetester+khcategory19@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Workspace has imported per diem rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Create expense > Per diem.
4. Select a destination.
5. Complete the rest of the flow and reach confirmation page.
6. Note that Attendees field is present on the confirmation page.
7. Close the RHP.
8. Open FAB > Create expense > Per diem.
9. Repeat Step 4 and 5 from FAB.

## Expected Result:
Attendees field will be present on the confirmation page when create per diem expense flow is initiated from FAB.

## Actual Result:
Attendees field is missing on the confirmation page when create per diem expense flow is initiated from FAB.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1a9facec-4924-4fdf-bf40-1ae568471468

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021919809646032177414</li>
        <li>Upwork Job ID: 1919809646032177414</li>
        <li>Last Price Increase: 2025-05-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dominictb</details>

### PR DESCRIPTION
**Pull request by allroundexperts**
### Explanation of Change

fixes https://github.com/Expensify/App/issues/61426
fixes https://github.com/Expensify/App/issues/61429
fixes https://github.com/Expensify/App/issues/61431
fixes https://github.com/Expensify/App/issues/61433
fixes https://github.com/Expensify/App/issues/61491
fixes https://github.com/Expensify/App/issues/61427
fixes https://github.com/Expensify/App/issues/61425

### Fixed Issues

$ https://github.com/Expensify/App/issues/44725
PROPOSAL: N/A

### Tests

**Test 1**
Precondition: Workspace has imported per diem rates.

1. Open the app, Go to workspace chat.
2. Click + > Create expense > Per diem.
3. Select a destination.
4. Complete the rest of the flow and reach confirmation page.
5. Note that Attendees field is present on the confirmation page.
6. Close the RHP.
7. Open FAB > Create expense > Per diem.
8. Repeat Step 4 and 5 from FAB.

Verify that Attendees field will be present on the confirmation page when create per diem expense flow is initiated from FAB.

**Test 2**

Precondition: Admin and member are in the same workspace.

1. [Member] Go to workspace chat and submit an expense.
2. [Member] Click Submit on the expense preview.
3. [Admin] Go to workspace chat with member.
4. [Admin] Open the expense report.
5. [Admin] Click Approve and Pay elsewhere.
6. [Member] Go to the transaction thread of the paid expense.
7. [Member] Click Attendees field.
8. [Member] Add another attendee and save it.

Verify that the attendee field should be disabled for member after the expense is paid.

**Test 3**
1. Go to workspace chat.
2. Create two manual expenses with the same amount and merchant.
3. Go to transaction thread of any expense.
4. Click Review duplicates.
5. Select Keep this one on any expense preview.
6. On the confirmation page, click Attendees.
7. Edit the attendees.

Verify that the attendees field should be disabled on the confirmation page when reviewing duplicates (other fields are disabled on confirmation page).

**Test 4**
1. Go to workspace chat.
2. Click + > Create expense > Scan
3. Upload a receipt.
4. On confirmation page, click Show more.
5. Click Attendees.
6. Select one more attendee.
7. Click Save.
8. Click Create expense.
9. Go to transaction thread.
10. Wait for the scan to complete.

Verify that there will be a dot separator between Attendees and "x per person" in transaction thread.

**Test 5**

Precondition: Workspace has imported per diem rates.

1. Go to workspace chat.
2. Click + > Create expense > Per diem.
3. Select a destination.
4. Complete the rest of the flow and reach confirmation page.
5. On confirmation page, click Attendees.
6. Select one more attendee.
7. Click Save.

Verify that attendees field will not show "0.00 per person" on confirmation page because it is not the correct amount.

**Test 6**
1. Go to workspace chat.
2. Click + > Create expense > Manual
3. Enter amount > Next.
4. On confirmation page, click Show more.
5. Click Attendees.
6. Enter a name (applee) and select the user.
7. Enter the same name again (applee).
9. Note that the same name appears twice.

Verify that the same name will not appear twice in the list.

**Test 7**
1. Go to workspace chat.
2. Click + > Create expense > Manual.
3. Enter amount > Next.
4. On confirmation page, click Show more.
5. Click Attendees.
6. Select one more attendee.
7. Click Save.
8. Note that Attendees field has "x per person" on the confirmation page.
9. Click Create expense.
10. Go to transaction thread.

Verify that in transaction thread, Attendees field will also show "x per person".

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

Same as above

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Unable to build android

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/e37d924f-f519-4d3d-8837-b90ebc06c35e

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/25e07434-6d08-4b1e-9824-a45fe33604e5

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/3b27231b-4ac0-4d90-a421-ea590a651fed

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/0df7d7b2-3872-4a81-b3ac-5d2b44944bb6

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/af1bdb49-86d8-4e98-99e9-cf748b86020d

</details>

### CODE REVIEW

**Comment by suneox** [comment]
I have another high-priority issue. If this PR isn't urgent, I can review it tomorrow.

**Comment by allroundexperts** [comment]
@mananjadhav Will be reviewing this @suneox.

**Comment by francoisl** [comment]
@mananjadhav how's it going with the review here? Do you think you'll be able to get to it today? TIA!

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: HybridApp
    - [x] Android: mWeb Chrome
    - [x] iOS: HybridApp
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: HybridApp</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: HybridApp</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by mananjadhav — APPROVED** [review]

**Comment by mananjadhav** [comment]
Having issues with my Android setup, so I skipped it. The changes are not native.

**Review by Julesssss — APPROVED** [review]

**Comment by Julesssss** [comment]
Let's request a pre-merge QA test, like last time.

**Review by Julesssss — COMMENTED** [review]
Could we re-enable the feature too please, so QA are able to test. Thanks

**Comment by francoisl** [comment]
It's already re-enabled, as far as I can tell? 
https://github.com/Expensify/App/pull/61484/files#diff-e0bbc1d7016fc365a636f5e1d9928913f99dc8a5e532727c6ebb9c2bbd1181bbR328-R330

I can see the attendee selector as expected locally, did you mean enable something else?

**Comment by Julesssss** [comment]
> I can see the attendee selector as expected locally, did you mean enable something else?

Nah thanks I missed that.

**Review by francoisl — APPROVED** [review]

**Comment by francoisl** [comment]
Still waiting for pre-merge QA tests - I bumped the team for an update.

**Comment by francoisl** [comment]
Pre-merge QA complete, no issues found 🚀

File: src/components/ReportActionItem/MoneyRequestView.tsx [hunk 1]
```diff
@@ -170,7 +170,7 @@ function MoneyRequestView({report, shouldShowAnimatedBackground, readonly = fals
     const shouldDisplayTransactionAmount = ((isDistanceRequest && hasRoute) || !!transactionAmount) && transactionAmount !== undefined;
     const formattedTransactionAmount = shouldDisplayTransactionAmount ? convertToDisplayString(transactionAmount, transactionCurrency) : '';
     const formattedPerAttendeeAmount =
-        shouldDisplayTransactionAmount && !isReceiptBeingScanned && didReceiptScanSucceed
+        shouldDisplayTransactionAmount && ((hasReceipt && !isReceiptBeingScanned && didReceiptScanSucceed) || !isPerDiemRequest)
```
Comment (c3024) [inline src/components/ReportActionItem/MoneyRequestView.tsx:173]: `shouldDisplayTransactionAmount` is sufficient here for displaying the per attendee amount. The other conditions prevented `per attendee` text from displaying in transaction thread. Fixed in #67086.
