### PR TITLE
[IS-3186] Fixed cursor position issue on Android

### LINKED ISSUE #3186: Android - Emoji - Cursor is not in front of the emoji
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result
Cursor position should display in front of the emoji 

## Actual Result
Cursor position is not in front of the emoji. Sometimes is behind the emoji and sometimes 2 characters ahead. 

## Action Performed
1. Launch the app
2. Log in with any account
3. Type some text
4. Add emoji in the middle of text

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
Where is this issue occurring?

 Web
 iOS
 Android ✔️ 
 Desktop App
 Mobile Web

**Version Number:** 1.0.55-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:**

image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
Originally posted here: https://github.com/Expensify/Expensify.cash/pull/3080#issuecomment-849069503

### PR DESCRIPTION
**Pull request by aliabbasmalik8**
@jboniface

### Details
This issue occurs only in the android platform so the solution is android specific. I  used Direct Manipulation
to fixed this issue because `selection` props on `textinput` have an issue on native platforms `https://github.com/facebook/react-native/issues/29063`

### Fixed Issues

Fixes https://github.com/Expensify/Expensify.cash/issues/3186

### Tests

1. Type some text
2. Add emoji in the middle of text
3. Cursor position will display in front of the emoji

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

**VIDEO:** https://recordit.co/0uUXWucubT
#### Mobile Web

**VIDEO:** https://recordit.co/1Y0RirncEZ
#### Desktop

**VIDEO:** https://recordit.co/w6lrt5jZqy
#### iOS

**VIDEO:** https://recordit.co/vkL2JOqSCL
#### Android

https://user-images.githubusercontent.com/31027036/120809040-8b230f00-c4fe-11eb-8a05-df19401e3c50.mp4

### CODE REVIEW

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -196,6 +201,12 @@ class ReportActionCompose extends React.Component {
         this.setState({isMenuVisible});
     }
 
+    updateSelectionOnAndroid(text, selection) {
+        if (getPlatform() === 'android') {
+            this.textInput.setNativeProps({text, selection});
+        }
+    }
+
```
Comment (thienlnam) [inline src/pages/home/report/ReportActionCompose.js:209]: We're avoiding using platform specific code such as this, please check out 

https://github.com/Expensify/Expensify.cash#philosophy
under `5. Cross Platform 99.9999%` and point `iii`

**Review by thienlnam — CHANGES_REQUESTED** [review]

File: src/pages/home/report/ReportActionCompose.js (hunk 1 above)
Comment (aliabbasmalik8) [reply src/pages/home/report/ReportActionCompose.js]: Got it and resolved it. Please have a look.

**Review by thienlnam — CHANGES_REQUESTED** [review]
Thanks for making those changes, this is looking much better!  Another thing you'll have to update is to change index.native.js of TextInputFocusable to index.ios.js since you have an android specific one now.  I also have a question, what changes here are you making that are specific to android, and would ios break if they had the same changes in them?  Because if not, since there is so much overlapping code in the ios.js and android.js files, it would be easier to maintain in the future if they were just both in native.js

**Comment by aliabbasmalik8** [comment]
> Thanks for making those changes, this is looking much better! Another thing you'll have to update is to change index.native.js of TextInputFocusable to index.ios.js since you have an android specific one now. I also have a question, what changes here are you making that are specific to android, and would ios break if they had the same changes in them? Because if not, since there is so much overlapping code in the ios.js and android.js files, it would be easier to maintain in the future if they were just both in native.js

TextInput `Selection` attribute break on `IOS` but I need it on `Android` so that's the reason I make a separate index.androd.js file

**Comment by thienlnam** [comment]
> TextInput Selection attribute break on IOS but I need it on Android so that's the reason I make a separate index.androd.js file

Do you mean the `Selection` prop isn't working on Android?  Also, how is it breaking?

**Comment by aliabbasmalik8** [comment]
> Do you mean the `Selection` prop isn't working on Android? Also, how is it breaking?
`Selection` prop not working on `ios` and it's already eliminated in `index.native.js` file.
https://github.com/Expensify/Expensify.cash/blob/de1a438527e7d72241a3745516c7e66fd9de8321/src/components/TextInputFocusable/index.native.js#L69

But I need that prop in android.

**Comment by thienlnam** [comment]
Ah I see what you mean now, although you'll still need to do this step:

> Another thing you'll have to update is to change index.native.js of TextInputFocusable to index.ios.js since you have an android specific one now

Additionally, at the top of the iOS / Android file can you explain why they need to be separated and link to the react native issue where this problem is being tracked?

**Comment by aliabbasmalik8** [comment]
> Ah I see what you mean now, although you'll still need to do this step:
> 
> > Another thing you'll have to update is to change index.native.js of TextInputFocusable to index.ios.js since you have an android specific one now
> 
> Additionally, at the top of the iOS / Android file can you explain why they need to be separated and link to the react native issue where this problem is being tracked?

DONE, Please have a look

File: src/components/TextInputFocusable/index.android.js [hunk 2]
```diff
@@ -0,0 +1,80 @@
+import React from 'react';
+import {TextInput} from 'react-native';
+import PropTypes from 'prop-types';
+import _ from 'underscore';
+import themeColors from '../../styles/themes/default';
+
+/**
+ * On native layers we like to have the Text Input not focused so the user can read new chats without they keyboard in
+ * the way of the view
+ * In Android I need selection prop for TextInput but for IOS selection prop have some issues
```
Comment (thienlnam) [inline src/components/TextInputFocusable/index.android.js]: Suggestion: 

On Android, the selection prop is required on the TextInput but this prop has issues on IOS <LINK_TO_REACTNATIVE_ISSUE>

Copy and paste that same thing to index.ios.js

**Review by thienlnam — CHANGES_REQUESTED** [review]

**Review by thienlnam — APPROVED** [review]

File: src/pages/home/report/ReportActionCompose.js [hunk 3]
```diff
@@ -233,6 +233,7 @@ class ReportActionCompose extends React.Component {
      * @param {String} newComment
      */
     updateComment(newComment) {
+        this.textInput.setNativeProps({text: newComment});
```
Comment (parasharrajat) [inline src/pages/home/report/ReportActionCompose.js:236]: @aliabbasmalik8 Sorry you ping you this way but I just want to know why did you add this? I am doing some changes to the component and I just want to know was there an issue, that required this. It's pretty urgent we have a couple of deploy blockers.

Comment (aliabbasmalik8) [reply src/pages/home/report/ReportActionCompose.js:236]: t's used to update comments ASAP because in android there is some issue with the selection position when we update without this.
What issue you are facing?

Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:236]: There are multiple things I am working on so I was trying to understand the old code. There is an issue when the cursor jumps. There is an issue when the app crashes......so on.

Comment (aliabbasmalik8) [reply src/pages/home/report/ReportActionCompose.js:236]: Got it, this code working perfectly and tested as well. you can mention PR here on which you are working so can help.

Comment (marcaaron) [reply src/pages/home/report/ReportActionCompose.js:236]: Hmm I could be wrong, but this does not seem like a correct usage of `setNativeProps()`... seems like there are various ways we clear the text input and I'm having a really hard time understanding why... please leave more context in the code in the future.

Comment (aliabbasmalik8) [reply src/pages/home/report/ReportActionCompose.js:236]: Yes, we can use some other ways as well but you can see in [some other issue conversation](https://github.com/Expensify/App/issues/2920#issuecomment-851836161) reviewer like the way of direct manipulation because uncontrolled input used in the app.
