### PR TITLE
fix: when deleting a workspace offline, the layout breaks

### LINKED ISSUE #17580: Workspace - When deleting a workspace offline. the layout breaks
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account that is ready for Error tests
3. Turn off internet connection
4. Delete a workspace while offline

## Expected Result:
User expects the layout to continue even when offline

## Actual Result:
Layout breaks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

https://expensify.testrail.io/index.php?/runs/view/14829&group_by=cases:section_id&group_order=asc&group_id=229065

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Screenshot 2023-04-18 at 10 56 35

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### PR DESCRIPTION
**Pull request by akinwale**
### Details
Updated PR for https://github.com/Expensify/App/pull/17310 rebased on the main branch.

This PR includes an additional commit to fix https://github.com/Expensify/App/issues/17580. Wrapping the `MenuItem` with a HOC or using `React.forwardRef` seems to be disregarding (or discarding?) some or all of the `defaultProps`, which includes the `defaultProps.style` change introduced by commit [a453d1e](https://github.com/Expensify/App/commit/a453d1e610a5dc14c62c21f5172dbbe444e3d0dd).

This can be observed when `applyStrikeThrough` is called on the children of an `OfflineWithFeedback` component, when the children are `MenuItem` components.

This PR applies the `defaultProps` to a reference of the wrapped component before the export call.

### Fixed Issues
$ https://github.com/Expensify/App/issues/16946
$ https://github.com/Expensify/App/issues/17656
PROPOSAL: https://github.com/Expensify/App/issues/16946#issuecomment-1498083798

### Tests
1. Log in to any account
2. Open the Settings page.
3. Long-press the Help link. This should present the Copy to Clipboard overlay with the action and link displayed at the bottom.
4. Use the Copy to Clipboard action and verify the copied URL.
5. Open the About page.
6. Long-press the View the code link. This should present the Copy to Clipboard overlay.
7. Repeat step 4.
8. Long-press the View open jobs link. This should present the Copy to Clipboard overlay.
9. Repeat step 4.
10. Click on App download links.
11. Long-press on each of the links. The Copy to Clipboard overlay should be displayed after long-pressing each link.
12. Verify that copied URL matches for each of the links.

- [x] Verify that no errors appear in the JS console

### Offline tests
1. Open the expensify URL.
2. Sign into a valid account that is ready for Error tests.
3. Turn off internet connection.
4. Delete a workspace while offline.
5. Ensure that the layout is not broken for a workspace that was deleted while offline. This means proper padding should be maintained for the left and right icons and the text.
6. Ensure that strikethrough is applied to the text of a workspace that was deleted while offline, especially on native iOS and Android.

### QA Steps
1. Run test steps above.
2. Run offline test steps above.
3. Verify old dot URL: On the Workspace Travel view, verify that that the URL to copy for the "Issue and manage cards" menu item matches the string: `https://<oldDotDomain>/domain_companycards` where `<oldDotDomain>` is the configured old dot domain for that particular environment.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

17580-web

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/4160319/231301584-7ce5ff6b-eba5-4574-a57f-e4896fea3372.webm

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/4160319/231301787-993f5ef0-5422-44d3-8601-614f02754317.mov

17580-ios-safari

</details>

<details>
<summary>Desktop</summary>

Desktop

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/4160319/231301833-7703b11b-d72e-4bab-be35-50e262ad22fd.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/4160319/231301587-f9bf1d8a-d517-4477-8d79-e1fe4a03da4e.webm

</details>

### CODE REVIEW

**Review by mountiny — COMMENTED** [review]
Thanks @akinwale Can you highlight the changes compared to the previous PR?

Also can you please leave the same tests and QA which were for the previous PR we still need to test for this here since it was not QAed in staging

File: src/components/MenuItem.js [hunk 1]
```diff
@@ -212,12 +221,18 @@ const MenuItem = (props) => {
...
+        </PressableWithSecondaryInteraction>
     );
 };
 
 MenuItem.propTypes = propTypes;
 MenuItem.defaultProps = defaultProps;
 MenuItem.displayName = 'MenuItem';
 
-export default MenuItem;
+const MenuItemWithWindowDimensions = withWindowDimensions(React.forwardRef((props, ref) => (
```
Comment (eVoloshchak) [inline src/components/MenuItem.js:232]: That is a weird bug. 
Thanks for coming up with a fix so fast, but I wonder why this is happening and how could we fix this without applying workarounds. 
I'll try to investigate this further a bit before we can merge this

Comment (akinwale) [reply src/components/MenuItem.js:232]: Sounds good. I have an additional fix incoming for this issue: https://github.com/Expensify/App/issues/17656. Just need to verify the details first.

**Comment by akinwale** [comment]
@eVoloshchak You can find more details about my approach with the latest commit here: https://github.com/Expensify/App/issues/17656#issuecomment-1515155074

**Comment by mountiny** [comment]
Thanks @akinwale I have also linked the other bug to this PR in the body, can you also update the QA/tests to cover that strikethrough styling?

**Comment by akinwale** [comment]
> Thanks @akinwale I have also linked the other bug to this PR in the body, can you also update the QA/tests to cover that strikethrough styling?

Done.

**Review by eVoloshchak — COMMENTED** [review]
This problem appears when we have a component created with `React.forwardRef` and we clone it using [React.cloneElement](https://github.com/Expensify/App/blob/1cd304c4d9871caa13362d76f1a8a11a940306b7/src/components/OfflineWithFeedback.js#L80).

This [comment](https://github.com/facebook/react/issues/16653#issuecomment-564423981) suggests we might change the way we apply defaultProps, started a discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1681997144480179)

**Comment by akinwale** [comment]
> This problem appears when we have a component created with `React.forwardRef` and we clone it using [React.cloneElement](https://github.com/Expensify/App/blob/1cd304c4d9871caa13362d76f1a8a11a940306b7/src/components/OfflineWithFeedback.js#L80).
> 
> This [comment](https://github.com/facebook/react/issues/16653#issuecomment-564423981) suggests we might change the way we apply defaultProps, started a discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1681997144480179)

Looks like I'd also have to move the `displayName` and `propTypes` below as well.

For `propTypes` I had a problem where if I removed it above, eslint complained, and there were console errors with the withWindowDimension props, so I guess I'll just set it again instead, depending on what is concluded in the discussion.

**Comment by akinwale** [comment]
@eVoloshchak @mountiny Just checking in to see if there will be any potential responses in the Slack discussion thread. I think that's the only thing left to close out this PR. Thanks.

**Comment by mountiny** [comment]
Bumped the thread, I see there are merge conflicts, we can resolve those after we get agreement on the thread

**Comment by akinwale** [comment]
The merge conflict appears to minor, just a new style added to `titleTextStyle`, `styles.ltr`, so I'll just do a merge with the main branch to keep things updated.

File: src/components/MenuItem.js [hunk 2]
```diff
@@ -212,12 +222,18 @@ const MenuItem = (props) => {
                     </View>
                 </>
             )}
-        </Pressable>
+        </PressableWithSecondaryInteraction>
     );
 };
 
 MenuItem.propTypes = propTypes;
 MenuItem.defaultProps = defaultProps;
```
Comment (eVoloshchak) [inline src/components/MenuItem.js:230]:
```suggestion
```

File: src/CONST.js [hunk 3]
```diff
@@ -2224,6 +2224,7 @@ const CONST = {
         'ILS', 'JPY', 'MYR', 'MXN', 'TWD', 'NZD', 'NOK', 'PHP',
         'PLN', 'GBP', 'RUB', 'SGD', 'SEK', 'CHF', 'THB', 'USD',
     ],
+
```
Comment (eVoloshchak) [inline src/CONST.js:2227]:
```suggestion
```

**Review by eVoloshchak — CHANGES_REQUESTED** [review]

**Comment by eVoloshchak** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>



</details>

<details>
<summary>Desktop</summary>



</details>

<details>
<summary>iOS</summary>



</details>

<details>
<summary>Android</summary>



</details>

**Review by eVoloshchak — DISMISSED** [review]
Tests well on all platforms
cc: @mountiny

File: src/libs/actions/Link.js [hunk 4]
```diff
@@ -34,33 +34,35 @@ function showGrowlIfOffline() {
...
-    /**
-     * @param {String} [shortLivedAuthToken]
-     * @returns {Promise<string>}
-     */
-    function buildOldDotURL(shortLivedAuthToken) {
-        const hasHashParams = url.indexOf('#') !== -1;
-        const hasURLParams = url.indexOf('?') !== -1;
+function buildOldDotURL(url, shortLivedAuthToken) {
+    const hasHashParams = url.indexOf('#') !== -1;
+    const hasURLParams = url.indexOf('?') !== -1;
```
Comment (mountiny) [inline src/libs/actions/Link.js:44]: @akinwale @eVoloshchak can you remind me please why is this change here?

**Review by mountiny — DISMISSED** [review]
One question

File: src/libs/actions/Link.js (hunk 4 above)
Comment (akinwale) [reply src/libs/actions/Link.js:44]: To summarise: Some of the menu items made use of the `openOldDotLink(url)` method, which built the URLs using the inner defined `buildOldDotURL` method. Since the original issue scope was to make the "Copy to clipboard" behaviour happen for all links, I had to refactor this method to the outer scope.

You can follow the discussion here for more details: https://github.com/Expensify/App/pull/17310#issuecomment-1505594964

Comment (akinwale) [reply src/libs/actions/Link.js:44]: @mountiny All done!

**Review by eVoloshchak — APPROVED** [review]

**Review by mountiny — APPROVED** [review]
