### PR TITLE
[IS-2151] Fixed Fab hidden by keyboard on IPAD

### LINKED ISSUE #2151: FAB hidden by Keyboard on iPad
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
The FAB should always be visible so users can easily trigger their desired action, on every platform

## Actual Result:
FAB hidden by keyboard on iPad

## Action Performed:
1. Log in to E.cash with iPad
2. Reveal software keyboard
3. Observe FAB menu is not visible

## Workaround:
None

## Platform:
 iOS (iPad)
Screen Shot 2021-03-29 at 12 56 06 PM

**Version Number:**
v1.0.7-0
**Logs:** None
**Notes/Photos/Videos:** See above
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/158758
**Upwork link:** https://www.upwork.com/jobs/~0158125c819a6e8fac

### PR DESCRIPTION
**Pull request by aliabbasmalik8**
### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2151

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Mobile Web

image

#### Desktop
image

#### iPad
Screen Shot 2021-03-31 at 6 13 16 PM

#### tablet Android
Screen Shot 2021-03-31 at 6 18 14 PM

### CODE REVIEW

**Review by Gonals — APPROVED** [review]

File: src/components/FAB.js [hunk 1]
```diff
@@ -64,15 +66,17 @@ class FAB extends PureComponent {
...
-            <AnimatedPressable
-                onPress={this.props.onPress}
-                style={[
-                    styles.floatingActionButton,
-                    {transform: [{rotate}], backgroundColor},
-                ]}
-            >
-                <AnimatedIcon src={Plus} fill={fill} />
-            </AnimatedPressable>
+            <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'position' : 'height'}>
```
Comment (marcaaron) [inline src/components/FAB.js:69]: Just a heads up this is not implemented correctly. Can you create a follow up PR to address this? @aliabbasmalik8 

https://github.com/Expensify/Expensify.cash#platform-specific-file-extensions

**Comment by marcaaron** [comment]
Please add QA steps in the future. This PR caused a regression [here](https://github.com/Expensify/Expensify.cash/issues/2207). The lack of test steps makes it hard connect the dots.

**Comment by aliabbasmalik8** [comment]
Looking into the issue. will care about test steps in the future
