### PR TITLE
[User Settings] Add new Change Password view

### LINKED ISSUE #1710: [User Settings] Add new Change Password view
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

Having added four new menu items to the Settings page, we now need to begin linking those menu items to actual pages.  This issue pertains to the `Change Password` page. 

The Change Password view will be displayed when the "Change Password" menu item is clicked. It will display a header with a left-facing arrow on the left-hand side, a title, and an `X` button to close the view on the right-hand side. The view will contain a prompt, three text boxes with a titles, and a button with the text `Save`.

### Deliverables 

- Clicking on the `Change Password` menu item on the Settings page will route the user to `settings/passwords` via the `SETTINGS_PASSWORD` route in ROUTES.js and display the new view
- The `Two Factor Code` field should only display if the `account.requiresTwoFactorAuth` is true
    - The two factor code text box should contain a placeholder saying `Required when 2FA is enabled` 
- If an incorrect current password or 2FA code is provided we should display the following error `Incorrect password. Please try again.`
    - This is similar to what we do on the login screen  
    - image
    - If `account.requiresTwoFactorAuth` is true, ensure the error message says `Incorrect password or two factor code. Please try again.`
   - Pressing `Save` should call `User.changePassword`
   - Pressing `X` will close the right-hand modal and route the user back to the last viewed report
   - Pressing `<` should display the main settings view.

| Mobile  | Web/Desktop |
| ------------- | ------------- |
|  |  |

### Upwork Link: https://www.upwork.com/jobs/~01fd29c39b73d1e4fa

### PR DESCRIPTION
**Pull request by Maftalion**
### Details
- Created new change password form

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes https://github.com/Expensify/Expensify.cash/issues/1710

### Tests
- Go to settings/changepassword page, attempt to change password using incorrect cred and confirm error message shows
- Use valid credentials and confirm pw was changed
- Enable 2FA in expensify.com and confirm new field required

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots
**Success**

https://user-images.githubusercontent.com/12075600/111101769-cc131500-8507-11eb-8a20-8d99182e3049.mov

**Error**
Screen Shot 2021-03-14 at 8 55 12 PM

#### Web

Screen Shot 2021-03-14 at 8 39 17 PM

#### Mobile Web

Screen Shot 2021-03-14 at 8 40 49 PM

#### Desktop

Screen Shot 2021-03-14 at 8 46 32 PM

#### iOS

Screen Shot 2021-03-14 at 8 39 33 PM

#### Android

Screen Shot 2021-03-14 at 8 52 43 PM

### CODE REVIEW

File: src/pages/settings/PasswordPage.js [hunk 1]
```diff
@@ -1,25 +1,158 @@
...
+import ONYXKEYS from '../../ONYXKEYS';
+import ButtonWithLoader from '../../components/ButtonWithLoader';
+import {changePassword} from '../../libs/actions/User';
+
+const propTypes = {
+    /* Onyx Props */
+    // Holds information about the users account that is logging in
+    account: PropTypes.shape({
+        // Whether 2FA is required for the users account that is logging in
+        requiresTwoFactorAuth: PropTypes.bool,
```
Comment (Maftalion) [inline src/pages/settings/PasswordPage.js:25]: I wasn't able to test this prop. I turned on 2FA in expensify.com but it would always return false for me.

Also the change password request came successful, but the followup call to Auth would fail with `402 Requires Two Factor Auth`

File: src/pages/settings/PasswordPage.js [hunk 2]
```diff
@@ -1,25 +1,158 @@
...
+                                        onChangeText={twoFactorCode => this.setState({twoFactorCode})}
+                                        placeholder="Required when 2FA is enabled"
+                                    />
+                                </View>
+                            ) : null}
+                            {!isEmpty(this.props.account.error) && (
+                                <Text style={styles.formError}>
+                                    {this.props.account.error}
+                                </Text>
+                            )}
```
Comment (Maftalion) [inline src/pages/settings/PasswordPage.js:130]: >There are a few errors you can get back from the API, each with user-friendly response messages that you could display. The main error codes to look out for are 401 if the old password is wrong and 402 if the password doesn't meet the validation conditions mentioned above.

@NikkiWines Just making sure this is correct but am I just displaying any error message that comes back or is the ask to override the 401's and display `Incorrect password. Please try again.`?

File: src/pages/settings/PasswordPage.js [hunk 3]
```diff
@@ -1,25 +1,158 @@
...
+                {() => (
+                    <>
+                        <HeaderWithCloseButton
+                            title="Change Password"
+                            shouldShowBackButton
+                            onBackButtonPress={() => Navigation.navigate(ROUTES.SETTINGS)}
+                            onCloseButtonPress={Navigation.dismissModal}
+                        />
+                        <View style={[styles.p5, styles.flex1]}>
+                            <Text fontSize={17} style={styles.mb6}>
```
Comment (shawnborton) [inline src/pages/settings/PasswordPage.js:78]: No need to increase the font size - let's just apply `styles.textP` and we should be set.

File: src/pages/settings/PasswordPage.js [hunk 4]
```diff
@@ -1,25 +1,158 @@
...
+                                Changing your password will update your password for both your Expensify.com
+                                and Expensify.cash accounts.
+                            </Text>
+                            <View style={styles.mb6}>
+                                <Text style={styles.mb1}>Current Password*</Text>
```
Comment (shawnborton) [inline src/pages/settings/PasswordPage.js:83]: Can we apply `styles.formLabel` for all of these labels above inputs?

File: src/pages/settings/PasswordPage.js (hunk 2 above)
Comment (NikkiWines) [reply src/pages/settings/PasswordPage.js:130]: Yeah, since `response.message` is pretty user-friendly I think it's fine to just display the error message returned from the API.

eg. With an incorrect old password.
image

However, maybe it's a good idea to do something like the following (in User.js in `changePassword()`) to make sure we always have an error message incase there's some weird case where we don't get one back from the API.
```Javascript 
errorMessage = lodashGet(response, 'message', 'Unable to change password');

File: src/pages/settings/PasswordPage.js (hunk 1 above)
Comment (NikkiWines) [reply src/pages/settings/PasswordPage.js:25]: I was able to get `requiresTwoFactorAuth` = `true`


View looks good, and confirmed that I can change my password successfully with the correct 2FA code.


However, I think we need a way to validate the 2FA code before actually changing the password (otherwise you just get booted out immediately if the 2FA code is wrong since we can't authenticate you). We have an API command `TwoFactorAuth_Validate` that takes in a `twoFactorAuthCode` that we haven't added to `API.js` yet. You could add that and call it `User.changePassword` if we pass along a 2fa code.

cc: @bondydaa since you're our resident 2FA expert

Comment (francoisl) [reply src/pages/settings/PasswordPage.js:25]: Weird - it seems to works for me. Did you try signing out of .cash after enabling 2FA on expensify.com?

File: src/pages/settings/PasswordPage.js [hunk 5]
```diff
@@ -1,25 +1,158 @@
...
+                                    autoCompleteType="password"
+                                    textContentType="password"
+                                    style={styles.textInput}
+                                    value={this.state.confirmNewPassword}
+                                    onChangeText={confirmNewPassword => this.setState({confirmNewPassword})}
+                                />
+                            </View>
+                            {this.props.account.requiresTwoFactorAuth ? (
+                                <View style={styles.mb6}>
+                                    <Text style={[styles.mb1, styles.formLabel]}>Two Factor Code</Text>
```
Comment (francoisl) [inline src/pages/settings/PasswordPage.js:117]: Since we only show that input when 2FA is required, should it also have a `*` at the end? Or alternatively, maybe we can skip the `*` everywhere since every field is required?

File: src/pages/settings/PasswordPage.js [hunk 6]
```diff
@@ -1,25 +1,158 @@
...
+                                    <TextInput
+                                        style={styles.textInput}
+                                        value={this.state.twoFactorCode}
+                                        onChangeText={twoFactorCode => this.setState({twoFactorCode})}
+                                        placeholder="Required when 2FA is enabled"
```
Comment (francoisl) [inline src/pages/settings/PasswordPage.js:122]: Can we make these inputs (at least the last 2 ones) work so that when you can also press enter instead of having to click the button? I think with `onSubmitEditing`?

File: src/pages/settings/PasswordPage.js [hunk 7]
```diff
@@ -1,25 +1,158 @@
...
+                                    {this.props.account.error}
+                                </Text>
+                            )}
+                        </View>
+                        <View style={styles.fixedBottomButton}>
+                            <ButtonWithLoader
+                                isDisabled={!this.state.currentPassword || !this.state.newPassword
+                                    || !this.state.confirmNewPassword
+                                    || (this.state.newPassword !== this.state.confirmNewPassword)
+                                    || (this.props.account.requiresTwoFactorAuth && !this.state.twoFactorCode)}
```
Comment (francoisl) [inline src/pages/settings/PasswordPage.js:137]: Idea (not a blocker): also disable if `newPassword === currrentPassword`, so that you can't try to change your password to the same one.

File: src/pages/settings/PasswordPage.js (hunk 1 above)
Comment (NikkiWines) [reply src/pages/settings/PasswordPage.js:25]: Also looking into an alternative method so that we could use `API.reauthenticate` and not have to require the 2FA code at all.

Comment (NikkiWines) [reply src/pages/settings/PasswordPage.js:25]: OK found something - it'll require an Auth PR (which will take a day or two to get deployed probably) but will fix the issue such that we can do what I mentioned above and call `API.reauthenticate('ChangePassword');` instead of `signIn` and also not require the user to enter a 2FA code at all.

Comment (Maftalion) [reply src/pages/settings/PasswordPage.js:25]: Yup, looks like I needed to logout/login to get the updated 2FA value

Comment (NikkiWines) [reply src/pages/settings/PasswordPage.js:25]: OK cool, after a long investigation it turns out we don't need to call `signIn` or `reauthenticate` when changing the password. Nor do we need an auth PR for this. Nor do we need to get the 2FA code for changing the password. 

@Maftalion could you remove the 2FA portion of the form from the Change Password view and also remove `signIn(password, twoFactorAuthCode);` from `User.changePassword`? Sorry for the confusion here.

File: src/pages/settings/PasswordPage.js (hunk 5 above)
Comment (NikkiWines) [reply src/pages/settings/PasswordPage.js]: Resolving this since we're no longer requiring 2FA for this view.

**Review by NikkiWines — DISMISSED** [review]
Tested with both a 2FA account and non-2FA account. Works great!

**Comment by NikkiWines** [comment]
@Maftalion just FYI you have some conflicts that are preventing this from getting merged

**Comment by Maftalion** [comment]
@NikkiWines updated!

**Review by NikkiWines — DISMISSED** [review]
:shipit:

**Review by francoisl — DISMISSED** [review]

**Review by NikkiWines — COMMENTED** [review]
This looks great. Looks like Michelle had some comments on the sub-text so not approving but will do so as soon as that's updated!

File: src/pages/settings/PasswordPage.js [hunk 8]
```diff
@@ -1,20 +1,152 @@
...
+                                autoCompleteType="password"
+                                textContentType="password"
+                                style={styles.textInput}
+                                value={this.state.newPassword}
+                                onChangeText={newPassword => this.setState({newPassword})}
+                                onFocus={() => this.setState({isPasswordRequirementsVisible: true})}
+                                onBlur={() => this.setState({isPasswordRequirementsVisible: false})}
+                            />
+                            {this.state.isPasswordRequirementsVisible && (
+                                <Text style={[styles.textMicro, styles.colorMuted, styles.mt1]}>
```
Comment (shawnborton) [inline src/pages/settings/PasswordPage.js:102]: @michelle-thompson @Maftalion @NikkiWines I think my suggestion here would be to create a new style like:

```
formHint: {
        color: themeColors.textSupporting,
        fontSize: variables.fontSizeLabel,
        lineHeight: 18,
    },
```

Also note that in my suggestion above, I am suggesting that we use `fontSizeLabel` which is 13px - I personally feel like the 11px size is too small.

**Comment by Maftalion** [comment]
With the new `formHint` style:

Screen Shot 2021-03-18 at 8 39 46 AM

**Comment by michelle-thompson** [comment]
Quick copy tweak -- it currently says `1 lowercase number` and should be `1 lowercase letter`

**Review by NikkiWines — DISMISSED** [review]
:shipit: looks great!

File: src/pages/settings/PasswordPage.js [hunk 9]
```diff
@@ -1,20 +1,152 @@
...
+        loading: PropTypes.bool,
+    }),
+};
+
+const defaultProps = {
+    account: {},
+};
+
+// at least 8 characters, 1 capital letter, 1 lowercase number, 1 number
+const passwordComplexityRegexString = '^(?=.*[A-Z])(?=.*[0-9])(?=.*[a-z]).{8,}$';
```
Comment (francoisl) [inline src/pages/settings/PasswordPage.js:34]: Let's move this CONST.js maybe? I imagine we'll need to reuse it soon-ish anyway.

**Review by francoisl — APPROVED** [review]
👍

**Review by NikkiWines — APPROVED** [review]
