### PR TITLE
Fix:: Account details stuck in RHN when switching chats

### LINKED ISSUE #6720: [HOLD for payment 2022-03-08] [$500] Account details stuck in RHN when switching chats
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click header in conversation with User B - their details open in Right Hand Nav (RHN) 
2. Type command+k to open Search to open chat with User C
3. Observe account details for User B still shows in RHN while new chat is open in the background for User C

## Expected Result:
Once new chat with User C is open, RHN is completely removed/disappears

## Actual Result:
Account details stuck in RHN

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.18-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
Screen Shot 2021-12-12 at 11 43 50 PM

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:*https://expensify.slack.com/archives/C01GTK53T8Q/p1639175807048600* 

**Job Post**: https://www.upwork.com/jobs/~01a4bf9b60eba80639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### PR DESCRIPTION
**Pull request by hiteshagja**
@chiragsalian @parasharrajat 

### Details
Re-written navigateBackToRootDrawer method to resolve #6720 and related issues if any. 

### Fixed Issues
$ https://github.com/Expensify/App/issues/6720

### Tests
By far I have checked following routes and they worked as expected.
bank-account - working
settings - working
settings/profile - working
settings/preferences - working
settings/security - working
settings/security/closeAccount - working
settings/security/password - working
settings/about - working
settings/about/app-download-links - working
settings/payments - working
settings/payments/add-paypal-me - working
settings/payments/add-debit-card - working
settings/payments/add-bank-account - working
settings/payments/transfer-balance - working
settings/payments/choose-transfer-account - working
new/group - working
new/chat - working
r/:reportID - working
iou/request - working
iou/request/:reportID - working
iou/split - working
iou/split/:reportID - working
iou/send - working
iou/split/currency - working
iou/split/currency/:reportID - working
iou/send/currency - working
iou/send/add-bank-account - working
iou/send/add-debit-card - working
iou/send/enable-payments - working
iou/details/add-bank-account - working
iou/details/add-debit-card - working
iou/details/enable-payments - working
iou/details/${chatReportID}/${iouReportID} - working
search - working
details?login=${encodeURIComponent(login)} - working
r/:reportID/participants - working
r/${reportID}/participants/details?login=${encodeURIComponent(login)} - working
r/:reportID/details - working
r/:reportID/settings - working
iou/send/currency/:reportID - working

### QA Steps
Here are many of the routes which I checked with following steps

1. Home -> go to any report -> click on header -> open detail -> ctrl+K -> search -> select any report

2. Home -> ctrl+k -> search -> select any report

3. Home -> click on search icon -> search -> select any report

4. Home -> click on groupReport -> click on header -> open group detail -> click on any member of group profile -> detail open -> ctl+k -> search -> select any report  

5. Home -> click on profile -> setting -> ctrl + k -> search -> select any report

6. Home -> click on plus icon -> start new chart -> ctrl + k -> search -> select any report

7. Home -> click on plus icon -> split bill -> enter amount -> select user -> split

8. Home -> setting -> change password -> update password

9. Home -> setting -> Profile -> update Profile

10. Home -> setting -> workspace -> general setting -> click on header (?) -> get assistance -> chat with concierge

11. Home -> setting -> workspace -> click on more(3 dot) on header -> delete workspace

### Tested On
- [x] Web
- [x] Android
- [x] iOS
- [x] Desktop

#### Web

https://user-images.githubusercontent.com/5493716/153891589-76c4c283-5599-4b12-9660-c28b1e643c6d.mp4

#### Android

https://user-images.githubusercontent.com/5493716/153885773-ce22cc50-aed3-4924-8462-c7a3b4ab99db.mp4

#### iOS

https://user-images.githubusercontent.com/5493716/154075299-50d2343f-e285-470c-9c59-9c3ab6113c6d.mov

#### Desktop

https://user-images.githubusercontent.com/5493716/154000446-59482ada-f3ac-491a-8965-739bc6617856.mp4

### CODE REVIEW

**Comment by hiteshagja** [comment]
I have read the CLA Document and I hereby sign the CLA

File: src/libs/Navigation/CustomActions.js [hunk 1]
```diff
@@ -6,40 +6,24 @@ import lodashGet from 'lodash/get';
...
-            return StackActions.popToTop();
-        }
-
-        // Otherwise, we are already on the last page of a modal so just do nothing here as goBack() will navigate us
-        // back to the screen we were on before we opened the modal.
-        return StackActions.pop(0);
+    const activeState = getActiveState();
+    navigationRef.current.dispatch({
+        ...StackActions.popToTop(),
+        target: activeState.key,
```
Comment (parasharrajat) [inline src/libs/Navigation/CustomActions.js:25]: Please add a descriptive comment about what is happening here. And also mention why does this works and when will it not work.

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Please add Screenshots/clips for all platforms. It is a must. Add QA and testing steps to test this change. 
As this change affects the whole app. Please be detailed in your QA steps and cover most of the different navigation cases. LHN, RHN, two Side-modals as per the issue, etc.

Don't forget to sign your commits.

File: src/libs/Navigation/CustomActions.js (hunk 1 above)
Comment (hiteshagja) [reply src/libs/Navigation/CustomActions.js]: Code comment added.

File: src/libs/Navigation/CustomActions.js [hunk 2]
```diff
@@ -6,40 +6,27 @@ import lodashGet from 'lodash/get';
...
-        if (state.routes.length > 1) {
-            return StackActions.popToTop();
-        }
+    const activeState = getActiveState();
 
-        // Otherwise, we are already on the last page of a modal so just do nothing here as goBack() will navigate us
-        // back to the screen we were on before we opened the modal.
-        return StackActions.pop(0);
+    //Dispatch "popToTop" action takes you back to the first screen in the stack at the same time 
+    //it will prevent bubbling of action and limit it to activeState by specifing target.
```
Comment (parasharrajat) [inline src/libs/Navigation/CustomActions.js:25]:
```suggestion
    // To navigate to the main drawer Route, pop to the first route on the Root Stack Navigator as the main drawer is always the first route that is activated.
    // It will pop all fullscreen and RHN modals that are over the main drawer. 
   // It won't work when the main drawer is not the first route of the Root Stack Navigator which is not the case ATM.
```

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Please sign your commits and add videos for all platforms and tick those checkboxes in the template.

File: src/libs/Navigation/CustomActions.js [hunk 3]
```diff
@@ -6,40 +6,27 @@ import lodashGet from 'lodash/get';
 import linkingConfig from './linkingConfig';
 import navigationRef from './navigationRef';
 
+/**
+ * @returns {Object}
+ */
+function getActiveState() {
```
[the remark this answers is not in the document]
Comment (chiragsalian) [reply src/libs/Navigation/CustomActions.js:12]: Thanks rajat. Just wanted to add to remember to always test your PR before putting it out for review. If you test the current code on ios you'll see,
image

which would quickly guide you to remove the extra method. Additionally, if you need more time you can always create a draft PR first without any assignees such that once its ready for review you can click on the ready for review button and it will then auto assign the reviewers.

**Comment by chiragsalian** [comment]
Also @parasharrajat, locally i removed the extra getActiveState and tested the flow mentioned [here](https://github.com/Expensify/App/issues/6720#issuecomment-1035543840).

Is this the correct expectation?
https://user-images.githubusercontent.com/14356145/153959263-d9ebc5eb-99b2-4529-abdb-c81b2a9e4886.mp4

**Comment by parasharrajat** [comment]
@hiteshagja You would have to sign all of you commits before we can merge this.

**Comment by parasharrajat** [comment]
@chiragsalian It does not seem like `Be taken to directly NewDot setup bank account page` is passing from your steps. But this Pr only affects going back to the main drawer which can be seen working in your video. So I think it is a pass. 

As a side note, we should look at why we are not landing on the bank page(if It should). I am actually sure what is that feature. Maybe Rory can help here. But this is surely out of scope of this PR.

**Comment by hiteshagja** [comment]
> @hiteshagja You would have to sign all of your commits before we can merge this. Also, a test on each platform is required. Please add the remaining platforms back to the description and tick them when tested.

@parasharrajat I am testing for iOS for now and will update you for the same. Also I tried to sign old commits but command didn't work in **6720 branch** with some strange reason. However, it's working fine if I create new branch.  

So, shall I close this repo and create new branch with single commit in it and raise new PR?

**Comment by hiteshagja** [comment]
> There is a small command to sign existing commits https://superuser.com/a/1123928/1035336. I don't think it is a good idea to close this PR and create new ones. We have discussed some important stuff here.
> 
> During the rebase please merge the duplicate commits as well. I see there are some on this PR.
> 
> let me know if you have some trouble with it.

Thanks!

signed all commits.

**Review by parasharrajat — DISMISSED** [review]
LGTM. 

cc: @chiragsalian. 

Leaving final testing to Chirag.

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by hiteshagja** [comment]
Shall I commit for that lint error?

**Comment by parasharrajat** [comment]
Yes. Thanks.

**Review by parasharrajat — APPROVED** [review]

**Review by chiragsalian — APPROVED** [review]
LGTM

**Comment by hiteshagja** [comment]
@parasharrajat , just wanted to check, in which upwork  job I have to submit my proposal?

**Comment by Stutikuls** [comment]
**Issue 1 -**

**Title**-[Medium] Chrome + Jaws: Screen reader : Focus does not lands on the new expanded content after activating the setting control.
**Actual** - Focus does not lands on the new expanded content of the setting control, focus moves to the next element (List elements) after activating the setting control.
**Expected** - After activating the setting control focus lands on the close(X) button of the new expanded window.
**WCAG failure** - 2.4.3
**Reproducible in staging?**: - Yes
**Version Number**: - v1.1.40-2
**Platforms** - Web(Chrome + Jaws), Desktop(MAC)

Note - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/157242198-38ff9278-da7b-4f8e-b6fc-fcf4a2d2eb2f.mp4
