### PR TITLE
Fixed Loading spinner on login form and crash after Login

### LINKED ISSUE #3838: [HOLD - for payment on July 14] Chat - Loading spinner appears after log in with different account
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Lunch the app
2. Log in with account A
3. Send some messages and attachments
4. Log out from Account A
5. Log in with Account B
## Expected Result:
Able to log in with Account B
## Actual Result:
Loading spinner displayed when trying to log in with another account
## Workaround:
Unknown

## Platform:
Where is this issue occurring?

 Web ✔️
 iOS
 Android ✔️
 Desktop App
 Mobile Web

**Version Number:**
1.0.75-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/124016929-21d6d480-d9b4-11eb-917a-80c1db90ab33.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details
https://github.com/Expensify/Expensify.cash/issues/3838#issuecomment-872929711
https://github.com/Expensify/Expensify.cash/issues/3838#issuecomment-873120845

### Fixed Issues

$ Fixes #3838

### Tests | QA Steps

    1. Lunch the app
    2. Log in with account A
    3. Send some messages and attachments
    4. Log out from Account A
    5. Log in with Account B

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

File: src/libs/OptionsListUtils.js [hunk 1]
```diff
@@ -215,7 +215,7 @@ function createOption(personalDetailList, report, draftComments, {
         login: !hasMultipleParticipants ? personalDetail.login : null,
         reportID: report ? report.reportID : null,
         isUnread: report ? report.unreadActionCount > 0 : null,
-        hasDraftComment,
+        hasDraftComment: !!reportDraftComment && reportDraftComment.length > 0,
```
Comment (chiragsalian) [inline src/libs/OptionsListUtils.js:218]: you don't need the `!!` here right. You could just do,
```
reportDraftComment && reportDraftComment.length > 0
```

File: src/libs/OptionsListUtils.js [hunk 2]
```diff
@@ -169,9 +169,9 @@ function createOption(personalDetailList, report, draftComments, {
 }) {
     const hasMultipleParticipants = personalDetailList.length > 1;
     const personalDetail = personalDetailList[0];
-    const hasDraftComment = report
+    const reportDraftComment = report
```
Comment (chiragsalian) [inline src/libs/OptionsListUtils.js:172]: I don't get why changing this variable from boolean to object has anything to do with your fixing loading spinner? It looks like it's just used as a boolean below anyway. Can you explain?

File: src/libs/OptionsListUtils.js [hunk 3]
```diff
@@ -297,13 +297,13 @@ function getOptions(reports, personalDetails, draftComments, activeReportID, {
             return;
         }
 
-        const hasDraftComment = report
+        const reportDraftComment = report
```
Comment (chiragsalian) [inline src/libs/OptionsListUtils.js:300]: Similar comment here. I don't get why this variable change is relevant to your PR.

**Review by chiragsalian — CHANGES_REQUESTED** [review]

File: src/libs/OptionsListUtils.js (hunk 3 above)
Comment (parasharrajat) [reply src/libs/OptionsListUtils.js:300]: Just to make more sense of it. As the end behaviour is changed. Previously, the variable was telling us that do we have a draft comment. Now it only store the draftComment object and we check for the Presence of draft message in later logic. So I thought change the variable name to reflect it.

File: src/libs/OptionsListUtils.js (hunk 2 above)
Comment (parasharrajat) [reply src/libs/OptionsListUtils.js:172]: So There are two issues, I am trying to fix here. Sometimes, the `lodashGet(draftComments, `${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${report.reportID}`, '')` returns null so. it will throw an error here that `.length` is not present.

**Comment by parasharrajat** [comment]
Updated. Thanks

File: src/libs/OptionsListUtils.js (hunk 2 above)
Comment (chiragsalian) [reply src/libs/OptionsListUtils.js:172]: Ah okay, i see. I didn't expect that value to be null (and hence not use the lodash get default value). Weird. Anyway, thanks for the fix 👍

**Review by chiragsalian — APPROVED** [review]
Changes LGTM

File: src/libs/OptionsListUtils.js (hunk 1 above)
Comment (kidroca) [reply src/libs/OptionsListUtils.js]: This is not true and completely broke the app for me 😃 

image

src/pages/home/sidebar/OptionRow.js
```jsx
                            {option.hasDraftComment && (
                                <View style={styles.ml2}>
                                    <Icon src={Pencil} height={16} width={16} />
                                </View>
                            )}
```

I have some empty `""` draft comment somewhere and it just crashes the app

The cast to boolean is necessary, though I would go with the explicit 

```jsx
Boolean(reportDraftComment) && reportDraftComment.length > 0
```

or

```jsx
Boolean(reportDraftComment && reportDraftComment.length > 0)
```

I don't know why I have an empty comment but it seems plausible and since `reportDraftComment` is a string it should be casted to prevent accidents like this

**Comment by kidroca** [comment]
@parasharrajat 
I've stumbled on an issue, added a comment here: https://github.com/Expensify/Expensify.cash/pull/3865/commits/6be5a3427d70d4878d093e0bca4b6b4ec3aecd3a#r665165970

**Comment by parasharrajat** [comment]
@kidroca Thanks for notifying me. That's why I added the boolean conversion but could think of it while review. I will patch this up in a small PR.

**Comment by chiragsalian** [comment]
Oh crap, nice catch @kidroca. I didn't consider the weirdness around empty string in JS wrt boolean operations.
Thanks for following up on the fixes @parasharrajat.

**Comment by roryabraham** [comment]
Unfortunately the deploy comments are not working right now. This was deployed to staging yesterday.
