### PR TITLE
Fix flashing messages on iOS

### LINKED ISSUE #2205: Fix flashing messages on iOS
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Platform - version:**  
iOS v1.0.9.4
Android - pixel 3. android 11 build rq2a.210305.006 - e.cash version v1.0.10-2

**Action Performed (reproducible steps):**
1. Navigate to chat 
2. Start sending messages
3. Observe the flashing messages

**Expected Result:**
Messages should not flash after being sent.

**Actual Result:**
Messages flash briefly after sending. 

**Notes/Photos/Videos:** 
 iOS

https://user-images.githubusercontent.com/16232057/113287838-04776900-92e6-11eb-82af-c1fd5f82f757.MOV

**Logs - JS/Android/iOS (if applicable)**:
None.

Upwork: https://www.upwork.com/jobs/~010e50957068c0dff4
E/E: https://github.com/Expensify/Expensify/issues/159056

### PR DESCRIPTION
**Pull request by Maftalion**
### Details
- Fixes weird behavior when messages flash upon sending a new message

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2205

### Tests
- Open any chat and send a message
- Test both chats with full page of messages and newer chats

### QA Steps
- same as above

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/12075600/113794468-79400e00-96ff-11eb-96e4-66f0c9929859.mov

#### Mobile Web

https://user-images.githubusercontent.com/12075600/113794476-8230df80-96ff-11eb-9b50-26fa982f4139.mov

#### Desktop

https://user-images.githubusercontent.com/12075600/113794526-9d035400-96ff-11eb-8705-3ee31abb2ae7.mov

#### iOS

https://user-images.githubusercontent.com/12075600/113794657-e3f14980-96ff-11eb-89b9-5deec7f8af6b.mov

#### Android

https://user-images.githubusercontent.com/12075600/113794554-aab8d980-96ff-11eb-9f11-31efeeaa2693.mov

### CODE REVIEW

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -56,7 +56,6 @@ class ReportActionCompose extends React.Component {
         this.updateComment = this.updateComment.bind(this);
         this.debouncedSaveReportComment = _.debounce(this.debouncedSaveReportComment.bind(this), 1000, false);
         this.debouncedBroadcastUserIsTyping = _.debounce(this.debouncedBroadcastUserIsTyping.bind(this), 100, true);
-        this.submitForm = this.submitForm.bind(this);
```
Comment (Maftalion) [inline src/pages/home/report/ReportActionCompose.js:59]: this was just a duplicate binding that I can across when looking into the issue

Comment (Beamanator) [reply src/pages/home/report/ReportActionCompose.js:59]: Nice catch! Funny that slipped by a previous review ;)

File: src/pages/home/report/ReportActionsView.js [hunk 2]
```diff
@@ -285,7 +285,7 @@ class ReportActionsView extends React.Component {
      */
     scrollToListBottom() {
         if (this.actionListElement) {
-            this.actionListElement.scrollToIndex({animated: false, index: 0});
+            this.actionListElement.scrollToOffset({animated: false, offset: 0});
```
Comment (Beamanator) [inline src/pages/home/report/ReportActionsView.js:288]: Yo, I definitely like the fix, but do you mind removing it from this issue and making a new one to report the problem, and propose this solution there? I know it's more effort on your part (sorry about that) but it's nice to keep each fix linked to the specific issue & investigation.

File: src/pages/home/report/ReportActionsView.js [hunk 3]
```diff
@@ -373,7 +373,7 @@ class ReportActionsView extends React.Component {
                 renderItem={this.renderItem}
                 CellRendererComponent={this.renderCell}
                 contentContainerStyle={[styles.chatContentScrollView]}
-                keyExtractor={item => `${item.action.sequenceNumber}`}
+                keyExtractor={item => `${item.action.timestamp}`}
```
Comment (Beamanator) [inline src/pages/home/report/ReportActionsView.js:376]: Sadly, this isn't actually going to work out. It turns out, it's quite easy to hit a problem if you send messages quickly (more than one per second), since `moment().unix()` (the code creating this timestamp, in `src/libs/actions/Report.js`) easily becomes non-unique.

Instead, I'm thinking we can change this to `item.action.clientID` since this comes from `optimisticReportActionID` in `Report.js`, which is created with `Date.now()` (more digits than `moment().unix()` plus a random number (see https://github.com/Expensify/Expensify.cash/pull/1394/files where this was added).

From my investigation, this does still a slight issue where `.clientID` doesn't exist when initially merging the new action into Onyx (in `Report.js -> addAction`) since we don't set `clientID` there -> `clientID` is added in the server code later, which is how it comes back to the front-end code. 

To fix this, I think we can just add `clientID: optimisticReportActionID,` when updating Onyx locally. Please let me know your thoughts on this 👍

**Review by Beamanator — CHANGES_REQUESTED** [review]
A few small comments with lots of explanation (sorry) - let me know if you agree / disagree / have questions!

File: src/pages/home/report/ReportActionsView.js (hunk 3 above)
Comment (Maftalion) [reply src/pages/home/report/ReportActionsView.js:376]: Ah, yeah it seems to work with `clientID` as well. updating the pr

**Comment by Maftalion** [comment]
Hmm not sure if I'm running into a weird caching issue, but I can't seem to reproduce the "flashing" on latest master.

**Review by deetergp — DISMISSED** [review]
Looks good!

**Comment by Beamanator** [comment]
> Hmm not sure if I'm running into a weird caching issue, but I can't seem to reproduce the "flashing" on latest master.

@Maftalion Me either - I also tested master on my physical android device (which i hadn't done while testing your changes before) and I don't experience the flashing either... I'm going to ask a few co-workers to check as well

**Comment by Beamanator** [comment]
Alright it looks like we're good to close this, no changes needed since the error isn't occurring on the latest version (dev, not production) - tested by you & me + a few of my colleagues

**Comment by Maftalion** [comment]
@Beamanator it looks like these changes still get rid of the "flashing" that reappeared. There is some new complexity with the IOU items, they don't come with a `action.clientID` so I can either fallback to `sequenceNumber` if `clientID` doesn't exist or I can check if `actionName === 'IOU'` and use `actionName === 'IOU'`. what are your thoughts?

Also would still need the change to `scrollToListBottom` to remove the bouncing that appears. Should I open a separate ticket for that as a followup?

**Comment by Beamanator** [comment]
Hey @Maftalion sorry for the delay!

I like the idea of falling back to `sequenceNumber` so we (hopefully) never get undefined / duplicate keys in the `keyExtractor`... I think we have to do a decent amount of testing to make sure the change does actually fix the problem - Currently I still can't even reproduce the issue on android or iOS 🤷‍♂️ were you ever able to consistently reproduce on the latest dev?

**Comment by deetergp** [comment]
Can confirm that the screen no longer flashes, but now we have a different behavior: newly-typed text appears in the chat history, then the entire chat history shifts down about half the font height:
https://user-images.githubusercontent.com/766197/116760418-b8dddb00-a9c9-11eb-81dd-213b1c1f59e4.mp4

**Comment by deetergp** [comment]
Neither behavior is happening in the `main` branch right now:
https://user-images.githubusercontent.com/766197/116760699-7a94eb80-a9ca-11eb-9ea2-2a9cee3187e4.mp4

**Comment by Beamanator** [comment]
I'm also not getting any flashing in the `main` branch... I guess we can close this again?

**Comment by trjExpensify** [comment]
The flashing is still happening on staging v1.0.37-0 (iOS). Here's another screen recording from today to confirm.

https://user-images.githubusercontent.com/16232057/117159414-2918a200-adb8-11eb-842d-12438861a739.MP4

Also, looks like another issue for this was created last night, so I've closed that dupe to focus our efforts here: https://github.com/Expensify/Expensify.cash/issues/2693

**Comment by deetergp** [comment]
Hookay! I spent WAY too much time getting myself setup to test this on a physical device and then building several branches to test if the bug IS definitely still there in 1.0.37-0 (and -1), as well as in the `main` branch:
https://user-images.githubusercontent.com/766197/117208966-9b828580-adaa-11eb-9d8e-047e027d29ad.mp4

And while @Maftalion's branch does get rid of the flashing, it introduces a regression that I'll call the Donky Kong Effect that makes the chat history shudder like there's a large gorilla stomping at the top:
https://user-images.githubusercontent.com/766197/117209170-da184000-adaa-11eb-955d-aba5e149fcde.mp4

As such, testing on a physical device is required, and no regressions should be included.

**Comment by Maftalion** [comment]
@deetergp does this mean it's only reproducible on a physical device? also I refer to the regression issue as "bouncing" above but totally like your terminology better 😆 . It can be fixed by updating `scrollToListBottom` to use `            this.actionListElement.scrollToOffset({animated: false, offset: 0});` but was told to followup with that change in a different issue/pr

**Comment by deetergp** [comment]
@Maftalion It may well only be reproducible on a physical device--all the times I tried testing any branch in the simulator, I haven't seen the flashing occur, and your branch definitely makes it go away.

> but was told to followup with that change in a different issue/pr

Ahh, that's what that was about. Has that fix already been merged into the `main` branch? If it has, can you pull `main` back into your branch and then we'll be good to go!

**Comment by Beamanator** [comment]
Hey guys, yeah that is probably my bad - I thought the ~bouncing~ Donkey Kong Effect was separate from the flashing issue, which is why I thought it best to separate the issues. If Matt's fix causes the Donkey Kong regression, which is easily fixed (with the fix he mentioned multiple times), let's combine them here and see if we can crush this issue once and for all :D

**Comment by Maftalion** [comment]
Awesome, sounds good! Just pushed up that change @Beamanator @deetergp

**Review by deetergp — DISMISSED** [review]
Tests pass and code looks good! Thanks for sticking with it 👍

https://user-images.githubusercontent.com/766197/117703021-1cac9480-b17e-11eb-99b8-fe69d7018756.mp4

**Review by Beamanator — COMMENTED** [review]
Sorry to do this to you, but can you merge master here & fix the merge conflict before I test? :D

**Comment by Maftalion** [comment]
@Beamanator fixed!

**Review by deetergp — APPROVED** [review]
Re-tested and it still works like a champ. Code looks good so let's get this merged ASAP, before more conflicts pop up!

**Review by Beamanator — APPROVED** [review]
Tests well for me too! LGTM :D

Thanks @deetergp & @Maftalion !
