### PR TITLE
Fix IOU request sent to new phone number account

### LINKED ISSUE #3614: Request money - Endless loading spinner when requesting money from phone number account
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Lunch the expensify cash app
2. Sign-up to Expensify.cash with a US phone number and validate that account (Account A)
3. Create another account with a different US phone number (Account B)
4. Log in with Account A
5. Click on green button
6. Click Request Money
7. Enter the phone number you like to request money
8. Click Next

## Expected Result:
Able to request money from phone number account
## Actual Result:
Endless loading spinner appears and could not complete the request
## Workaround:
Unknown

## Platform:
Where is this issue occurring?

 Web ✔️
 iOS ✔️
 Android ✔️
 Desktop App ✔️
 Mobile Web ✔️

**Version Number:** 1.0.69-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/122259442-31c4c380-cea0-11eb-89bf-d5ee1dbfdb11.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by Beamanator**
### Details

In Web-E, the `debtorEmail` param is using the `$_WAFDEF['_EMAIL'];` rule, which doesn't pass for phone numbers. Therefore, if we pass a basic phone number (ex: +17203334444) to a command using that param (ex: `CreateIOUTransaction`), `debtorEmail` will be wiped.

This is currently happening because when we merge personal details with the searchValue (in `getPersonalDetailsForLogins), `login` may not have an SMS domain (for new accounts, there's no `personalDetails` to merge, so we have to manually add the SMS domain there.

Video showing the issue:

https://user-images.githubusercontent.com/3885503/122456174-899d2080-cfad-11eb-8b12-4a6f5270ed34.mov

### Fixed Issues

Fixes https://github.com/Expensify/Expensify.cash/issues/3614

### Tests
1. Sign in to E.cash with existing account (or new one, doesn't matter)
2. Click main green `+` button
3. Click Request Money
4. Enter a phone number (Note: an account with this phone number shouldn't already exist)
    - Don't add `@expensify.sms` at the end
5. The IOU should be created successfully, without an infinite spinner

### QA Steps
1. Sign in to E.cash with existing account (or new one, doesn't matter)
2. Click main green `+` button
3. Click Request Money
4. Enter a phone number (Note: an account with this phone number shouldn't already exist)
    - Don't add `@expensify.sms` at the end
5. The IOU should be created successfully, without an infinite spinner

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/3885503/122454184-65d8db00-cfab-11eb-8a48-75452e28ffe1.mov

#### Mobile Web

https://user-images.githubusercontent.com/3885503/122454473-b9e3bf80-cfab-11eb-9037-2625dcdef288.mov

#### Desktop

https://user-images.githubusercontent.com/3885503/122456012-55296480-cfad-11eb-9cca-9d7fa39a7c43.mov

#### iOS

https://user-images.githubusercontent.com/3885503/122454876-15ae4880-cfac-11eb-86b8-207df4d93670.mov

#### Android

https://user-images.githubusercontent.com/3885503/122455763-0a0f5180-cfad-11eb-8713-6f71396703c2.mov

### CODE REVIEW

**Comment by Beamanator** [comment]
@HorusGoul looks like you got assigned by PullerBear when @francoisl was already assigned 🤷  feel free to unassign if you want, or add an extra review! 👍

File: src/libs/OptionsListUtils.js [hunk 1]
```diff
@@ -25,6 +25,19 @@ let preferredLocale;
...
+ *
+ * @param {String} login
+ * @return {String}
+ */
+function addSMSDomainIfPhoneNumber(login) {
+    if (Str.isValidPhone(login) && !Str.isValidEmail(login)) {
+        return login + CONST.SMS.DOMAIN;
+    }
+    return login;
+}
```
Comment (Beamanator) [inline src/libs/OptionsListUtils.js:39]: This _could_ go nicely in expensify-common, but I wanted to keep this in one PR since it's a deploy blocker

File: src/libs/OptionsListUtils.js [hunk 2]
```diff
@@ -25,6 +25,19 @@ let preferredLocale;
...
+ * Adds expensify SMS domain (@expensify.sms) if login is a phone number and if it's not included yet
+ *
+ * @param {String} login
+ * @return {String}
+ */
+function addSMSDomainIfPhoneNumber(login) {
+    if (Str.isValidPhone(login) && !Str.isValidEmail(login)) {
+        return login + CONST.SMS.DOMAIN;
+    }
+    return login;
```
Comment (Julesssss) [inline src/libs/OptionsListUtils.js:38]: We might prefer to return early, but NAB

**Review by Julesssss — APPROVED** [review]
LGTM

**Comment by Julesssss** [comment]
Tests well for me. I saw the infinite spinner when entering an incorrect mobile number, so I'll create a new issue to handle the Invalid number response.

**Comment by Beamanator** [comment]
> I saw the infinite spinner when entering an incorrect mobile number, so I'll create a new issue to handle the Invalid number response.

Aah good point, I didn't worry too much about that b/c we shouldn't be able to create new users w/ invalid phone numbers after https://github.com/Expensify/Expensify.cash/pull/3124

File: src/libs/OptionsListUtils.js (hunk 2 above)
Comment (francoisl) [reply src/libs/OptionsListUtils.js:38]: Or even make it a ternary, but I'm not sure either is more legible than this. I'd say let's keep it like it is now.

**Review by francoisl — APPROVED** [review]
