### PR TITLE
Fix navigating to reports via Search page on staging

### LINKED ISSUE #2538: Search feature is not working
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Jump to the chat

## Actual Result:
Blank screen and JS error

## Action Performed:
- CMD+k
- Select a person to chat
- See blank screen

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
Where is this issue occurring?

I only tested in web and in staging

**Version Number:**
**Notes/Photos/Videos:** 
image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
Fixes the broken Search page on staging.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2538

### QA Steps
1. Tap on a chat (mobile web)
2. Go back to the LHN
3. Tap on another chat
4. Test the browser back button behavior and verify that we do not get navigated to an empty screen
5. Open the `/search` screen and select a new chat
6. Verify you are able to navigate to that chat by tapping it
7. Find and locate a group DM chat in the LHN and tap it
8. Verify that you can also bring up a `/r/<reportID>/participants` route by tapping on a group chat header avatar

**Note:** The browser button works unexpectedly if we navigate to a new chat via the "Search" page. Considering that to be not a blocker for now, but will keep looking into it in the future.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

File: src/libs/Url.js [hunk 1]
```diff
@@ -10,23 +10,7 @@ function addTrailingForwardSlash(url) {
...
- * @returns {String}
- */
-function wrapWithForwardSlash(url) {
-    const newUrl = addTrailingForwardSlash(url);
-    if (newUrl.startsWith('/')) {
-        return newUrl;
-    }
-
-    return `/${newUrl}`;
-}
```
Comment (marcaaron) [inline src/libs/Url.js:25]: I don't know why I did this to begin with. All the routes start without a slash.

**Comment by marcaaron** [comment]
Leaving out the screenshots because there are no visual changes but I did test on all platforms to verify things work OK. @NikkiWines lmk if there's anything that should be explained better - planning to do a follow up after this since I'm not happy with where things are at but staging is borked. Thanks!!!!

**Review by NikkiWines — APPROVED** [review]

File: src/ROUTES.js [hunk 2]
```diff
@@ -43,13 +43,14 @@ export default {
...
     parseReportRouteParams: (route) => {
-        if (!route.startsWith(wrapWithForwardSlash(REPORT))) {
+        if (!route.startsWith(addTrailingForwardSlash(REPORT))) {
             return {};
         }
 
         const pathSegments = route.split('/');
         return {
             reportID: lodashGet(pathSegments, 1),
+            isParticipantsRoute: Boolean(lodashGet(pathSegments, 2)),
```
Comment (rushatgabhane) [inline src/ROUTES.js:53]: Coming from [issue - app crash when url is invalid](https://github.com/Expensify/App/issues/22507)

If the url has multiple double slash eg: `https://.....https//`, `pathSegments[2]` will be false. 
We should have simply checked the length of the array 

More details here - https://github.com/Expensify/App/issues/22507#issuecomment-1650301007
