### PR TITLE
Use Image instead of ImageBackground

### LINKED ISSUE #15237: Background illustration covers avatars and texts in chat room
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

Mobile: 
1. Open https://new.expensify.com on iOS Safari/Android Chrome Safari 
2. Plus button -> New chat -> choose a person you haven't chatted yet to create a new chat room
3. Zoom in and zoom out
4. Check the avatar is covered by an illustration when the chat room is zoomed out

https://user-images.githubusercontent.com/98560306/219568929-ff8a084c-37b4-4ae8-916c-ec5fc083992b.MOV

Desktop:
1. Open https://new.expensify.com on Safari MacOS 
2. Plus button -> New chat -> choose a person you haven't chatted yet to create a new chat room
7. Check the avatars and some texts are covered by background illustration

Screenshot 2023-02-16 at 6 36 50 PM

- Related issue: https://github.com/Expensify/App/issues/15238

## Expected Result:
Background illustration should be behind the avatars and tests

## Actual Result:
Avatars and some texts are covered by background illustration

## Workaround:
Users can still user Expensify, but the issue is quite noticeable

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [X] iOS / Safari
- [x] MacOS / Chrome / Safari _ONLY ON Safari_
- [ ] MacOS / Desktop

**Version Number:** v1.2.72-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hayata-suenaga and @dhanashree-sawant 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675330177865839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f02c6225cbf7e63</li>
        <li>Upwork Job ID: 1628072754773405696</li>
        <li>Last Price Increase: 2023-02-21</li>
    </ul>
</details>

### PR DESCRIPTION
**Pull request by hayata-suenaga**
### Details

I couldn't pinpoint the root cause of the original issue. The issue seems to stem from the `ImageBackground` RN component. This PR replaces `ImageBackground` with `Image`.

In the original code, `ImageBackground` was contained inside [this `View` component](https://github.com/Expensify/App/blob/571e051557a31af8b48289ad169f7665bf3ab3a9/src/pages/home/report/ReportActionItemCreated.js#L55), which also acted as a filler to push [this `View` component](https://github.com/Expensify/App/blob/571e051557a31af8b48289ad169f7665bf3ab3a9/src/pages/home/report/ReportActionItemCreated.js#L61) down.

In the original code, `ImageBackground` overflew its [parent `View` component](https://github.com/Expensify/App/blob/571e051557a31af8b48289ad169f7665bf3ab3a9/src/pages/home/report/ReportActionItemCreated.js#L55). This overflew part behaved differently depending on the platform. On laptop and mobile Safari and mobile Chrome, this overflew part covered [the `View` component](https://github.com/Expensify/App/blob/571e051557a31af8b48289ad169f7665bf3ab3a9/src/pages/home/report/ReportActionItemCreated.js#L61) which contains avatars and welcome texts.

Instead of using `ImageBackground`, this PR uses `Image` RN component with its `position` set to `absolute`. By putting this `Image` before other sibling components in the code, `Image` goes behind just like what `ImageBackground` does.

The [`View` component ](https://github.com/Expensify/App/blob/571e051557a31af8b48289ad169f7665bf3ab3a9/src/pages/home/report/ReportActionItemCreated.js#L55)which originally contained `ImageBackground` still needs to be there, as it also acts as a filler to position avatars and welcome texts correctly.

### Fixed Issues

$ https://github.com/Expensify/App/issues/15237

#### Mobile Safari and Mobile Chrome
1. Go to NewDot and sign in with any account
2. Create a new chat room
3. Zoom in and zoom out
4. Check if the avatars and welcome messages (`This is the beginning of your chat history...) are not covered by background illustration

- [ ] Verify that no errors appear in the JS console

_*You cannot zoom in or zoom out on NewDot on Chrome on Android device. You can use Chrome on iPhone to test zoom in and zoom out interactions._

#### Laptop Chrome and Safari, Desktop, Android and Safari Native
1. Go to NewDot and sign in with any account
2. Create a new chat room
3. Check if the avatars and welcome messages (`This is the beginning of your chat history...) are not covered by background illustration

### Offline tests

Same as above

### QA Steps

Same as above

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

Chrome
Screenshot 2023-02-22 at 3 20 19 PM

Safari
Screenshot 2023-02-22 at 3 19 37 PM

</details>

<details>
<summary>Mobile Web - Chrome</summary>

Screenshot_1677111062

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/98560306/220789644-b6ad41c0-1d7c-4999-a4eb-87a3ee0f024e.mp4

</details>

<details>
<summary>Desktop</summary>

Screenshot 2023-02-22 at 3 52 48 PM

</details>

<details>
<summary>iOS</summary>

Simulator Screen Shot - iPhone 14 - 2023-02-22 at 15 50 27

</details>

<details>
<summary>Android</summary>

Screenshot_1677109868

</details>

### CODE REVIEW

**Review by MariaHCD — DISMISSED** [review]
These changes make sense to me! Tagging @shawnborton to double check the style changes.

**Comment by shawnborton** [comment]
This looks good to me, also cc @dangrous who worked on this originally.

**Review by shawnborton — DISMISSED** [review]

**Comment by dangrous** [comment]
Ha! My original solution strikes again... So weird that ImageBackground doesn't behave like a background should, but if the Image component still looks the same, I'm totally fine with that. Seems like it does from the screenshots.

**Comment by hayata-suenaga** [comment]
@MariaHCD @aimane-chnaif could one of you complete the Reviewer Checklist, please?

**Review by aimane-chnaif — DISMISSED** [review]
Current solution looks good to me.

There are also alternative options to fix this issue:

- Option 1
Layout fix. Same as current solution, but no need to replace `ImageBackground` with `Image`

- Option 2
Use `zIndex` here:
```diff
function getReportWelcomeBackgroundImageViewStyle(isSmallScreenWidth) {
    if (isSmallScreenWidth) {
        return {
            height: CONST.EMPTY_STATE_BACKGROUND.SMALL_SCREEN.VIEW_HEIGHT,
+           zIndex: -1,
        };
    }

    return {
        height: CONST.EMPTY_STATE_BACKGROUND.WIDE_SCREEN.VIEW_HEIGHT,
+       zIndex: -1,
    };
}
```

File: src/pages/home/report/ReportActionItemCreated.js [hunk 1]
```diff
@@ -52,12 +52,11 @@ const ReportActionItemCreated = (props) => {
             onClose={() => Report.navigateToConciergeChatAndDeleteReport(props.report.reportID)}
         >
             <View style={StyleUtils.getReportWelcomeContainerStyle(props.isSmallScreenWidth)}>
-                <View pointerEvents="none" style={StyleUtils.getReportWelcomeBackgroundImageViewStyle(props.isSmallScreenWidth)}>
```
[the remark this answers is not in the document]
Comment (dangrous) [reply src/pages/home/report/ReportActionItemCreated.js:55]: I think that was from when I had initially used an 	`Image` instead of `ImageBackground` and we didn't want it to be selectable. https://github.com/Expensify/App/pull/13647#pullrequestreview-1232638704

File: src/pages/home/report/ReportActionItemCreated.js [hunk 2]
```diff
@@ -52,12 +52,11 @@ const ReportActionItemCreated = (props) => {
...
-                    <ImageBackground
-                        source={EmptyStateBackgroundImage}
-                        style={StyleUtils.getReportWelcomeBackgroundImageStyle(props.isSmallScreenWidth)}
-                    />
-                </View>
+                <Image
+                    source={EmptyStateBackgroundImage}
+                    style={StyleUtils.getReportWelcomeBackgroundImageStyle(props.isSmallScreenWidth)}
+                />
+                <View pointerEvents="none" style={StyleUtils.getReportWelcomeBackgroundImageViewStyle(props.isSmallScreenWidth)} />
```
Comment (dangrous) [inline src/pages/home/report/ReportActionItemCreated.js:59]: Do we need the `Image` to be inside of this `View`? If not, do we need this at all? If this is testing well it's probably fine but it feels a little weird on the code side so wanted to double check.

Comment (dangrous) [reply src/pages/home/report/ReportActionItemCreated.js:59]: Thanks!

**Comment by hayata-suenaga** [comment]
@aimane-chnaif thank you for your suggestion. I'll check your approaches when I got a minute. Please don't merge this PR until I test @aimane-chnaif's suggestions.

File: src/pages/home/report/ReportActionItemCreated.js [hunk 3]
```diff
@@ -52,12 +52,11 @@ const ReportActionItemCreated = (props) => {
...
         >
             <View style={StyleUtils.getReportWelcomeContainerStyle(props.isSmallScreenWidth)}>
-                <View pointerEvents="none" style={StyleUtils.getReportWelcomeBackgroundImageViewStyle(props.isSmallScreenWidth)}>
-                    <ImageBackground
-                        source={EmptyStateBackgroundImage}
-                        style={StyleUtils.getReportWelcomeBackgroundImageStyle(props.isSmallScreenWidth)}
-                    />
-                </View>
+                <Image
+                    source={EmptyStateBackgroundImage}
```
Comment (dangrous) [inline src/pages/home/report/ReportActionItemCreated.js:56]:
```suggestion
                <Image
                    pointerEvents="none"
                    source={EmptyStateBackgroundImage}
```
So that we can't select the background image (see [this comment](https://github.com/Expensify/App/pull/13647#pullrequestreview-1232638704))

File: src/pages/home/report/ReportActionItemCreated.js [hunk 4]
```diff
@@ -52,12 +52,11 @@ const ReportActionItemCreated = (props) => {
...
+                    style={StyleUtils.getReportWelcomeBackgroundImageStyle(props.isSmallScreenWidth)}
+                />
+                <View pointerEvents="none" style={StyleUtils.getReportWelcomeBackgroundImageViewStyle(props.isSmallScreenWidth)} />
                 <View
                     accessibilityLabel="Chat welcome message"
                     style={styles.p5}
```
Comment (dangrous) [inline src/pages/home/report/ReportActionItemCreated.js:62]:
```suggestion
                <View
                    accessibilityLabel="Chat welcome message"
                    style={[styles.p5,StyleUtils.getReportWelcomeBackgroundImageViewStyle(props.isSmallScreenWidth)]}
```

We can clean this up a bit with @aimane-chnaif's suggestion to make this have a marginTop rather than an extra View here with a fixed height.

However, for this to work you'll need to change `getReportWelcomeBackgroundImageViewStyle` to return `marginTop` instead of `height`. I also would suggest renaming the function since it's not quite right now. Maybe something like `getReportWelcomeTopMarginStyle` or something like that?

Other reviewers, let me know if this sounds good to you! I didn't test on every platform but checked Safari and Chrome on desktop, as well as iOS and it seems like it has the same behavior, with cleaner code.

**Review by dangrous — CHANGES_REQUESTED** [review]
Some updates to make things a bit nicer and fix a bug - let me know if everything makes sense!

File: src/pages/home/report/ReportActionItemCreated.js (hunk 3 above)
Comment (dangrous) [reply src/pages/home/report/ReportActionItemCreated.js:56]: Oh really? I was able to right click and download (Chrome on mac)

**Review by aimane-chnaif — DISMISSED** [review]

**Review by dangrous — DISMISSED** [review]
Looks good as long as it continues to test correctly! (@aimane-chnaif did you double check after these new changes?)

File: src/styles/StyleUtils.js [hunk 5]
```diff
@@ -699,15 +701,15 @@ function getReportWelcomeBackgroundImageStyle(isSmallScreenWidth) {
  * @param {Boolean} isSmallScreenWidth
  * @returns {Object}
  */
-function getReportWelcomeBackgroundImageViewStyle(isSmallScreenWidth) {
+function getReportWelcomeTopMarginStyle(isSmallScreenWidth) {
```
Comment (MariaHCD) [inline src/styles/StyleUtils.js:704]: You'll need to remove/update the description for this methods's docblock since it's not relevant anymore :)

**Review by MariaHCD — COMMENTED** [review]
Just a small comment from me but otherwise, looks great!

**Review by aimane-chnaif — APPROVED** [review]

**Review by dangrous — APPROVED** [review]

**Review by MariaHCD — APPROVED** [review]
