### PR TITLE
Exclude Concierge from IOU flows (2nd attempt)

### LINKED ISSUE #2698: [IOU] Users are able to send payment requests and split bills with Concierge
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Platform - version:**  

All platforms - v1.0.37-0

**How to enable the `Request Money` or `Spilt Bills` flow**
As the feature is currently behind a beta, you must perform the following change to reproduce the issue. Either navigate to Permissions.js,[ comment out this line ](https://github.com/Expensify/Expensify.cash/blob/e28b50e139c492442ea984c3d48e23be744ceb4e/src/libs/Permissions.js#L31)and return true -- or apply this [diff.txt](https://github.com/Expensify/Expensify/files/6427621/diff.txt) with ` git apply path/to/diff.txt`

**Action Performed (reproducible steps):**
0. Read the above section to ensure that the beta feature is available to you
1. Click the `+` icon on global create and select `Request Money` or `Spilt Bills`
2. Enter an amount and click `Next`
3. Search for concierge@expensify.com
4. Observe that Concierge is listed as a participant and available to send a payment request to
5. Now navigate to the Concierge DM and click the `+` icon within the DM
6. Observe that `Request Money` is an available option in the CreateMenu along with `Add Attachment`

**Expected Result:**
1. Concierge should not be an available participant to select on the IOUParticipants page via the `Request Money` or `Split Bills` flows.
2. `Request Money` should not be an available option in the CreateMenu when launched from within the Concierge DM

**Actual Result:**
1. Users can select Concierge as a participant 
2. Users can launch the `Request Money` flow from within the Concierge DM

**Notes/Photos/Videos:** 

image
image

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/162867
**Upwork Job URL:** https://www.upwork.com/jobs/~010daa7b8e343f79e4

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by tugbadogan**
cc @Luke9389 @roryabraham 

### Details
This is a duplicate of https://github.com/Expensify/Expensify.cash/pull/2740 and I'm using `_.contains()` to avoid crashing the app if `this.props.report.participant` is `undefined`.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2698

### Tests
* Tested manually and made sure that users cannot initiate IOU request with Concierge.
* Tested group creation and verified it's not crashing as described in https://github.com/Expensify/Expensify.cash/issues/2809

### QA Steps
```
- Open 1:1 and group chat with Concierge
- Press `+` icon next to chat composer
- Observe that there is no `Request Money` or `Split Bill` option on menu
```

```
- Open 1:1 and group chat without Concierge
- Press `+` icon next to chat composer
- Observe that there is a `Request Money` or `Split Bill` option on menu
```

```
- Press big green `+` icon on the sidebar
- Select `Request Money` or `Split Bill`
- Enter a random amount and press `Next`
- Search Concierge
- Observe that Concierge doesn't appear among results
```

Q&A steps for group creation issue https://github.com/Expensify/Expensify.cash/issues/2809
```
* Launch the app and login
* Create a group with 2 or more users
* Focus on the input field to type
```

### Tested On

- [X] Web
- [X] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

#### Web
Screenshot 2021-05-13 at 00 47 33
Screenshot 2021-05-13 at 00 47 18
Screenshot 2021-05-13 at 00 46 59
Screenshot 2021-05-13 at 00 46 48
Screenshot 2021-05-13 at 00 46 37
Screenshot 2021-05-13 at 00 46 24

### CODE REVIEW

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -308,10 +308,10 @@ class ReportActionCompose extends React.Component {
     render() {
         // eslint-disable-next-line no-unused-vars
         const hasMultipleParticipants = lodashGet(this.props.report, 'participants.length') > 1;
+        const hasConciergeParticipant = _.contains(this.props.report.participants, CONST.EMAIL.CONCIERGE);
```
Comment (tugbadogan) [inline src/pages/home/report/ReportActionCompose.js:311]: Only this line has been changed compared to the previous PR https://github.com/Expensify/Expensify.cash/pull/2740

Before:
```
const hasConciergeParticipant = this.props.report.participants.includes(CONST.EMAIL.CONCIERGE);
```

**Review by thienlnam — APPROVED** [review]
Changes look good, and I appreciate that you added tests! Passing on to @roryabraham or @Luke9389 for final merge.  Another note as I review this is that we should eventually update this from `excludeConcierge` to `excludeSupportEmails` or something similar and exclude Chronos as well

**Review by Luke9389 — APPROVED** [review]

**Comment by trjExpensify** [comment]
Merging this. Thanks for the fix here @tugbadogan, and @thienlnam & @Luke9389 for the reviews.
