### PR TITLE
Fix escape key for modal closing

### LINKED ISSUE #1039: Chat / The escape key should close open modals
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
Desktop, build 280

**Action Performed (reproducible steps):**

Test 1
1. Click the paperclip icon
2. Select a file to upload
3. Before confirming the upload, press Escape
4. Observe that the upload modal stays on the screen

Test 2
1. Click the paperclip icon
2. Select an image to upload
3. Upload the file
4. Click into the image 
5. Press escape
6. Observe that the attachment modal stays on the screen

**Expected Result:**
All modals should be cancelled when the user presses the Escape key. 

**Actual Result:**
The modal stays on the screen

**Notes/Photos/Videos:** 
102928813-6878ce80-4467-11eb-8aec-82c137cbf461

view the job on Upwork [here](https://www.upwork.com/jobs/~01122a92e0900bb65c).

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
There are two situations where `Escape` key was not working

1. The `Popover` component because `react-native-modal` is registering the `Escape` key press as a "back button press" and we are trying to close it twice (rather we toggle it so it just reopens again)
2. When we moved the right hand panel modals to `react-navigation` we lost the ability to close via `Escape`. This should add that behavior back in at the `ScreenWrapper` level so that any screen wrapped in that component should be able to trigger a `goBack()` if the `esc` key is pressed

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/1039

### QA Steps
1. Tap on the User avatar in the Sidebar
2. Press `Escape` after the right panel opens
3. Verify the right panel closes
4. Repeat test with all similar right panel modals - New Chat, New Group, Search, Chat User Details etc
5. Tap on the FAB
6. Press `Escape`
7. Verify the popover menus closes
8. Click on an attachment in a chat to open the large modal
9. Press `Escape`
10. Verify the image view modal closes

### Tested On

- [x] Web
- [x] Desktop

**These platforms have no hardware keyboard so I did not bother to test them beyond ensuring no broken behaviors were introduced**
- Mobile Web - N/A
- iOS - N/A
- Android - N/A

### CODE REVIEW

File: src/components/AttachmentModal.js [hunk 1]
```diff
@@ -79,7 +79,10 @@ class AttachmentModal extends PureComponent {
             return;
         }
 
-        this.props.onConfirm(this.state.file);
+        if (this.props.onConfirm) {
+            this.props.onConfirm(this.state.file);
```
Comment (marcaaron) [inline src/components/AttachmentModal.js:83]: This change is unrelated. I just noticed that if we press Enter on a regular attachment modal it throws a `TypeError` so I fixed that up.

File: src/libs/KeyboardShortcut/index.js [hunk 2]
```diff
@@ -90,13 +90,15 @@ const KeyboardShortcut = {
...
      * @param {Boolean} captureOnInputs Should we capture the event on inputs too?
+     * @returns {Function} clean up method
      */
     subscribe(key, callback, modifiers = 'shift', captureOnInputs = false) {
         const keyCode = this.getKeyCode(key);
         if (events[keyCode] === undefined) {
             events[keyCode] = [];
         }
         events[keyCode].push({callback, modifiers: _.isArray(modifiers) ? modifiers : [modifiers], captureOnInputs});
+        return () => this.unsubscribe(key);
```
Comment (marcaaron) [inline src/libs/KeyboardShortcut/index.js:101]: This is kind of extra. Probably didn't need to do it, but I like this pattern for cleaning up subscriptions.

**Review by thienlnam — APPROVED** [review]
