### PR TITLE
Fix issues with network queue during sign in

### LINKED ISSUE #1118: Signing in with `exitTo` doesn't work
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**
Desktop web (all?)

**Action Performed (reproducible steps):**
1. Sign in as normal
2. Navigate to a report
3. Click "Sign out"
4. Note that there is an `exitTo` in the URL
5. Enter an email address to sign in
6. Note that it hangs there forever

**Expected Result:**
Expected to see password/2FC page

**Actual Result:**
Hung with a spinner forever

**Notes/Photos/Videos:** 
image
 
**Logs - JS/Android/iOS (if applicable)**:

### PR DESCRIPTION
**Pull request by r8**
### Details

Fixes uncleared listener for the App Visibility, which causes unauthorized API request and breaks the Network Queue.
For the details of the issue see [1118#issuecomment-753555165](https://github.com/Expensify/Expensify.cash/issues/1118#issuecomment-753555165).

### Fixed Issues

Fixes #1118 

### Tests

1. Login to the web app
2. Navigate to any chat
3. Click "Sign Out"
4. Switch to other tab in the browser
5. Switch back to the Sign In page
6. Wait for 3 seconds
7. Enter the email, press "Continue"
8. Verify that sign in continues and user is able to enter the password

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots
<Add any necessary screenshots for all platforms if your change added or updated UI>

#### Web

https://user-images.githubusercontent.com/130532/104510226-89aa8600-55f3-11eb-98fa-ebfd7296c5d9.mp4

#### Mobile Web

https://user-images.githubusercontent.com/130532/104516491-1574e000-55fd-11eb-94bc-4dc9e6f416f0.mp4

#### Desktop

https://user-images.githubusercontent.com/130532/104510280-9dee8300-55f3-11eb-9eb0-728523a1ea7f.mp4

#### iOS

https://user-images.githubusercontent.com/130532/104516719-7997a400-55fd-11eb-958d-92a877b713ed.mp4

#### Android

https://user-images.githubusercontent.com/130532/104520356-a9e24100-5603-11eb-9f3d-b0cf1223d022.mp4

### CODE REVIEW

File: src/libs/API.js [hunk 1]
```diff
@@ -52,14 +52,15 @@ function addAuthTokenToParameters(command, parameters) {
 
     if (isAuthTokenRequired(command) && !parameters.authToken) {
         // If we end up here with no authToken it means we are trying to make an API request before we are signed in.
-        // In this case, we should cancel the current request by pausing the queue and clearing the remaining requests.
+        // In this case, we should cancel the current request and clear the queue.
         if (!authToken) {
             redirectToSignIn();
 
             console.debug('A request was made without an authToken', {command, parameters});
-            Network.pauseRequestQueue();
```
Comment (r8) [inline src/libs/API.js:60]: @marcaaron Could you please take a look here? 
It's your code and I'm a bit afraid to break something, because I don't see the whole picture yet.

This `pause` here still creates problems for sign in.
If user is already on Sign in page, then `redirectToSignIn()` does nothing (see [SignInRedirect](https://github.com/Expensify/Expensify.cash/blob/a6ba3f26ea8631b43dc34b559e86fd33c9cf69fa/src/libs/actions/SignInRedirect.js#L37))

So the user ends up on Sign In page with paused queue, and Continue button still spins forever.

File: src/libs/API.js [hunk 2]
```diff
@@ -190,6 +191,17 @@ function request(command, parameters, type = 'post') {
...
+                    if (!credentials || !credentials.autoGeneratedLogin || !credentials.autoGeneratedPassword) {
+                        // If we are here with invalid credentials it means we are trying to make an API request
+                        // before we are signed in. In this case, we should not continue.
+                        console.debug('A request tried to renew an authToken without credentials.', {
+                            command,
+                            parameters,
+                        });
+
+                        throw new Error('A request tried to renew an authToken without credentials.');
+                    }
```
Comment (marcaaron) [inline src/libs/API.js:203]: I'm confused about why we checking the credentials in the `.then()` at this point we have:

- An expired session
- The command we called is not `CreateLogin` or `Authenticate` since those would return early above (they are not retry-able see `parameters.doNotRetry`).

File: src/libs/API.js (hunk 1 above)
Comment (marcaaron) [reply src/libs/API.js:60]: To clarify, which command are we calling that causes `redirectToSignIn()` to be called?

**Review by marcaaron — COMMENTED** [review]
The event listener changes look good to me. Left some questions about the API/Network related changes.

File: src/libs/API.js (hunk 2 above)
Comment (r8) [reply src/libs/API.js:203]: At first I tried to insert it before `networkPromise`. 
But as first step of Sign in we send `GetAccountStatus` to check the email. And it's sending with expired session, so this check wouldn't allow it to go through.
So I decided to put it in `then` section instead.

Comment (marcaaron) [reply src/libs/API.js:203]: Hmm but `GetAccountStatus` does not require an `authToken` 🤔 

https://github.com/Expensify/Expensify.cash/blob/9f48370459159c7599be6f23661de737319739a0/src/libs/API.js#L21-L32

File: src/libs/API.js (hunk 1 above)
Comment (r8) [reply src/libs/API.js:60]: That's again a case of a request after the expired session, the one in the original issue.

It's fixed now, because I replaced the listener removal, but I'm able to reproduce when I revert b0f89ce

So if some forgotten request is being sent after the sign out, it no longer breaks in `handleExpiredAuthToken` because of my checks for credentials. Instead it ends up here (because there's no auth token).
And because we are still on Sign in page, the redirect isn't happening, page is not refreshed, queue is paused without unpause.

File: src/libs/API.js (hunk 2 above)
Comment (r8) [reply src/libs/API.js:203]: Yes, but it's still being sent with this `request` function. So if I add the check for credentials before creating the promise, it will not go through.

But I think I can use this `isAuthTokenRequired` function to check the command before the request.
How about this?

```javascript
function request(command, parameters, type = 'post') {
    return new Promise((resolve, reject) => {
        if (isAuthTokenRequired(command) && (!credentials || !credentials.autoGeneratedLogin || !credentials.autoGeneratedPassword)) {
            // If we are here with invalid credentials it means we are trying to make an API request
            // before we are signed in. In this case, we should not continue.
            console.debug('A request tried to renew an authToken without credentials.', {
                command,
                parameters,
            });

            throw new Error('A request tried to renew an authToken without credentials.');
        }

        const networkPromise = mockCommands[command]
            ? mockCommands[command]()
            : Network.post(command, parameters, type);
```

Comment (r8) [reply src/libs/API.js:203]: In this case probably `(!credentials || !credentials.autoGeneratedLogin || !credentials.autoGeneratedPassword)` should be extracted to function, because the condition becomes too big

File: src/libs/API.js (hunk 1 above)
Comment (marcaaron) [reply src/libs/API.js:60]: Ok I see now. I'm not sure we want to remove this, because there are cases where we do want to pause the queue so the queued command doesn't `fetch()` here:

https://github.com/Expensify/Expensify.cash/blob/b2c03fc5a8bd0d2c5a3f67847d132af1d41702e1/src/libs/Network.js#L59-L63

Throwing would stop the `fetch()` from happening, but might have other unintended effects as we are not catching this error in `processNetworkRequest()`.

Perhaps there's some other way to unpause the queue again?

I'm not too sure why we are preventing a redirect to sign in so maybe it would be reasonable to remove that check and just unpause the network request queue once storage has been cleared.

Comment (r8) [reply src/libs/API.js:60]: You mean to remove the check for sign in the url?

https://github.com/Expensify/Expensify.cash/blob/a6ba3f26ea8631b43dc34b559e86fd33c9cf69fa/src/libs/actions/SignInRedirect.js#L37-L40

In this case it might break the flow even more mysteriously for the user, because it might redirect and refresh the page.
User is entering email on the Sign in page, forgotten request suddenly fires (unseen by the user) and the page suddenly refreshes

File: src/libs/API.js (hunk 2 above)
Comment (r8) [reply src/libs/API.js:203]: You mean something like this?

```javascript
                if (response.jsonCode === 407) {
                    const unableToReauthenticate = (!credentials || !credentials.autoGeneratedLogin || !credentials.autoGeneratedPassword);

                    if (parameters.doNotRetry || unableToReauthenticate) {
                        resolve(response);
                        return;
                    }

                    handleExpiredAuthToken(command, parameters, type)
```

**Comment by marcaaron** [comment]
Talking to @tgolen about the best way to handle this. For now, it might be fine to just focus on solving the main bug with the event listeners. It would be nice to have some resiliency here, but a temporary alternative would just be to get more descriptive with our logs [here](https://github.com/Expensify/Expensify.cash/blob/b2c03fc5a8bd0d2c5a3f67847d132af1d41702e1/src/libs/API.js#L55) and be a little clearer about the situation and it's severity. e.g. indicate that API requests should not be made after sign out and likely an event listener must be cleaned up.

File: src/libs/API.js (hunk 2 above)
Comment (marcaaron) [reply src/libs/API.js:203]: yes, exactly

File: src/libs/API.js (hunk 1 above)
Comment (marcaaron) [reply src/libs/API.js:60]: Ah yep, that's a great point. We probably don't want to do that.

Comment (marcaaron) [reply src/libs/API.js:60]: Another idea discussed was to return a `Promise` from `signInRedirect()` and unpause once we resolve it. But this feels slightly hacky since what we really would like to do is let `processRequestQueue()` finish running and then unpause the request queue again.

Comment (r8) [reply src/libs/API.js]: FYI I've updated the credentials check, but still thinking how to resolve `signInRedirect` issue

**Comment by r8** [comment]
@marcaaron I went the Promise path, that you suggested. Maybe it's hacky, but it's the clearest and the simplest way to fix it.

Also, I checked what's happening when we remove the check for Sign in url. It doesn't break the flow, how I expected, but it still pauses the queue without unpausing. So it really doesn't fix anything.

File: src/libs/API.js [hunk 3]
```diff
@@ -54,11 +54,15 @@ function addAuthTokenToParameters(command, parameters) {
         // If we end up here with no authToken it means we are trying to make an API request before we are signed in.
         // In this case, we should cancel the current request by pausing the queue and clearing the remaining requests.
         if (!authToken) {
-            redirectToSignIn();
-
             console.debug('A request was made without an authToken', {command, parameters});
             Network.pauseRequestQueue();
             Network.clearRequestQueue();
+
+            redirectToSignIn().finally(() => {
```
Comment (marcaaron) [inline src/libs/API.js:61]: It might be good to add some context here about why we are unpausing the queue. Something like...

>We are unpausing the queue after we finish signing in so that new requests can be made again.

**Comment by marcaaron** [comment]
@r8 Ok, sorry for the back and forth here. I think if there is no good solution right now it would just be best to leave the code changes simple. Thinking about the `Promise` solution more and there is not much difference between it and a `setTimeout()` so we should probably not do it and it's a sign we should investigate a bit more how we have designed this. 

The main bug here has been fixed for now. And we can think some more on how to improve the code with the investigations here rather than add any hacks today. Sound ok?

**Comment by r8** [comment]
I personally prefer `Promise` over `setTimeout`, because in this case `Promise` gives us control, and with `setTimeout` we're launching our task into the future and crossing fingers hoping for the best :)

But I agree that both solutions are not good enough. So I've reverted the `Promise` commit.

**Review by marcaaron — APPROVED** [review]
