### PR TITLE
fixed slow emoji entry & Keyboard focus

### LINKED ISSUE #2920: [HOLD for payment June 27] Emoji Picker is slow to add emoji on Native Platforms and doesn't pull up the keyboard afterwards
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Upwork posting: https://www.upwork.com/jobs/~01572e274a1ada4be0

## Expected Result:
The emoji picker should add the emoji instantaneously and pull up the keyboard afterwards.

## Actual Result:
The emoji picker takes a half second to add an emoji once it's been tapped on, and the keyboard isn't pulled up afterwards.

## Action Performed:
1. Navigate to any conversation on mobile.
2. Open the emoji picker and tap on any emoji.

## Workaround:
Yep, just bad UX

## Platform:
Where is this issue occurring?

 iOS
 Android

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by parasharrajat**
Please review @jasperhuangg 

### Details
1. Updated the web only value update statement to cross-platform `setNativeProps`.
2. Workaround for the Keyboard with `setTimeout`. It seems there is not another way for now.
3. Remove unnecessary state updates on Composer.
4. Fix Promise rejection error on Picker for native devices.

### Fixed Issues

Fixes #2920

### Tests | QA Steps
1. Open e.cash.
2. Open any chat.
3. Click the emoji Picker icon.
4. Select any emoji.
5. Emoji should be added immediately and there should not be a delay after Picker is closed.
6. Keyboard should open after Picker is closed.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/24370807/120968774-ea935000-c786-11eb-886b-9298e4802610.mp4

#### Desktop

https://user-images.githubusercontent.com/24370807/120969031-4cec5080-c787-11eb-9ca6-9f920ff87721.mp4

#### Android

https://user-images.githubusercontent.com/24370807/120968938-2e865500-c787-11eb-8233-47139f85b171.mp4

### CODE REVIEW

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -204,7 +209,12 @@ class ReportActionCompose extends React.Component {
             // There could be other animations running while we trigger manual focus.
             // This prevents focus from making those animations janky.
             InteractionManager.runAfterInteractions(() => {
-                this.textInput.focus();
+                // Keyboard is not opened after Emoji Picker is closed
+                // SetTimeout is used as a workaround
+                // https://github.com/react-native-modal/react-native-modal/issues/114
+                setTimeout(() => {
+                    this.textInput.focus();
+                }, 100);
```
Comment (thienlnam) [inline src/pages/home/report/ReportActionCompose.js:217]: We're really trying to avoid using setTimeouts whenever possible, could we maybe try the 

```
this.props.navigation.addListener('transitionEnd', () => {
    if (this.textInput) {
        this.textInput.focus();
    }
});
```

**Review by thienlnam — CHANGES_REQUESTED** [review]
One comment, everything else looks good

**Review by thienlnam — DISMISSED** [review]

**Comment by parasharrajat** [comment]
@jasperhuangg Requesting review or merge.

**Comment by parasharrajat** [comment]
@jasperhuangg Waiting for your review. Thanks.

**Comment by parasharrajat** [comment]
Updated. Thanks

**Review by thienlnam — DISMISSED** [review]

**Comment by parasharrajat** [comment]
@jasperhuangg This PR is stalled till your review . Thanks

**Comment by parasharrajat** [comment]
@jasperhuangg Could you please review this as you were assigned to the issue and knows the context better. If you agree to the solution, I can resolve the conflict and we can move forward with the PR. Thanks

**Review by jasperhuangg — DISMISSED** [review]

**Comment by jasperhuangg** [comment]
Looks good! Do you mind resolving the conflicts?

**Comment by parasharrajat** [comment]
Just found out there are a couple of issues with cursor placement on the Mobile app. my changes here have not caused them but We have to fix those as well only then we can move ahead with this. I will debug those issues and then hopefully soon open the PR and again.

**Comment by parasharrajat** [comment]
@thienlnam @jasperhuangg I have carefully tested my solution it works fine now. 

But I have found other issues related to TextInput where sometimes Cursor is jumping around when the user place cursor at another location & I found that it's very laggy experience when to try to clear text. As said, they are not caused by the solution above as they are available on master. I suspect that they have to do with the Controlled selection prop. I am trying to find a solution to fix that.

**Review by jasperhuangg — APPROVED** [review]
Overall, looks good; feel free to open up a new issue for the other issues you've described.

**Comment by kavimuru** [comment]
## mWeb -Safari- Chat - Keypad  does not open after picking emoji
## Expected Result: 
Keypad should open after Picker is closed.
## Actual Result:
Keypad remains closed after picking emoji
## Actions Performed:
1. Open e.cash
2. Open any chat and type message
3. Click the emoji Picker icon
4. Select any emoji
5. Emoji should be added immediately and there should not be a delay after Picker is closed
6. Observe keypad
## Notes/Images/Video:

https://user-images.githubusercontent.com/43996225/122803599-cd857380-d294-11eb-80d1-1d6d39f58697.mp4

**Comment by parasharrajat** [comment]
Checking in

**Comment by parasharrajat** [comment]
@kavimuru. It seems to work fine for me on Emulator. Can anybody please test it on a real IOS device, I don't have one? What is your app version?

**Comment by kavimuru** [comment]
@parasharrajat  Issue occurs only in iPhone Safari. App works fine. Issue reproducible in iPhone 8 / iOS 13.3 / Safari 13 and iPhone XS/iOS 14.6 / Safari 14.  Build version is 1.0.73-0
