### PR TITLE
Tweaks to the expense flow

### LINKED ISSUE #54836: [Due for payment 2025-01-17] [Due for payment 2025-01-15]  Invoices - User can send invoice to themselves
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.81-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+2390223d@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Invoice feature is enabled.

1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount > Next.
4. Select the contact under "Personal", which is yourself.
5. Send the invoice.

## Expected Result:
User should not be able to send the invoice to themselves (production behavior).

## Actual Result:
User is able to send the invoice to themselves. The "invoice" is sent to self DM and becomes a track expense.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/23699403-ac07-4fa5-bd9f-54a0c37e53c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

### PR DESCRIPTION
**Pull request by JKobrynski**
This is followup to the reverted https://github.com/Expensify/App/pull/53760. 

On top on fixing https://github.com/Expensify/App/issues/52981 it also fixes https://github.com/Expensify/App/issues/54836, https://github.com/Expensify/App/issues/54844 and https://github.com/Expensify/App/issues/54861 which caused the revert

### Fixed Issues

$ https://github.com/Expensify/App/issues/52981
PROPOSAL: N/A

### Tests

1. Log into the app
2. Click on the **+** button
3. Select the **Create expense** option
4. Choose the **Manual** expense
5. Provide an expense value 
6. Navigate to the next step
7. Make sure the **Just track it (don't submit it)** option row is not visible
8. Verify if there is a **Workspace** and **Personal** section
9. Test if you can submit an expenses to workspaces, recents, contacts and to yourself
10. Verify the button on the **Confirm details** screen says "Create <currency>amount expense"

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

Same as **Tests** section above

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message: https://expensify.slack.com/archives/C01GTK53T8Q/p1734011675583879
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

[android-compressed.webm](https://github.com/user-attachments/assets/8d5ff40f-0f86-4ff2-b523-a22ffdfbcb0d)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

[chrome-compressed.webm](https://github.com/user-attachments/assets/d959a559-604d-45d4-ae42-049b5b9ac4b0)

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/6610cbba-294d-4d0e-9b22-a1a52d7c6822

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/a1e56b1c-921e-40a1-8836-57da834e9aee

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by JKobrynski** [comment]
Bug https://github.com/Expensify/App/issues/54836 fixed:


https://github.com/user-attachments/assets/58518dd4-6335-4c6c-9103-4b168b4fc782

**Comment by grgia** [comment]
@abdulrahuman5196 I'm going to assign @mananjadhav this one since it needs to be merged with https://github.com/Expensify/App/pull/54201

**Comment by mananjadhav** [comment]
Reviewing.

File: src/components/MoneyRequestConfirmationList.tsx [hunk 1]
```diff
@@ -429,16 +429,19 @@ function MoneyRequestConfirmationList({
                 text = translate('common.next');
             }
         } else if (isTypeTrackExpense) {
-            text = translate('iou.trackExpense');
+            text = translate('iou.createExpense');
```
Comment (mananjadhav) [inline src/components/MoneyRequestConfirmationList.tsx:432]: This code is being duplicated along with the other PR right? We'll have to take care of the conflicts.

File: src/libs/OptionsListUtils.ts [hunk 2]
```diff
@@ -1009,6 +1013,23 @@ function orderReportOptionsWithSearch(
     );
 }
 
+function orderWorkspaceOptions(options: ReportUtils.OptionData[]): ReportUtils.OptionData[] {
+    return lodashOrderBy(
```
Comment (mananjadhav) [inline src/libs/OptionsListUtils.ts:1017]: I can't remember the exact docs link, but isn't our preference to use built-in methods wherever possible? Can we use `options.sort` ?

**Comment by mananjadhav** [comment]
Reviewed partially, will review the rest today.

**Comment by grgia** [comment]
Can we get this wrapped today?

File: src/libs/OptionsListUtils.ts [hunk 3]
```diff
@@ -1700,6 +1744,23 @@ function filterReports(reports: ReportUtils.OptionData[], searchTerms: string[])
     return filteredReports;
 }
 
+function filterWorkspaceChats(reports: ReportUtils.OptionData[], searchTerms: string[]): ReportUtils.OptionData[] {
```
Comment (mananjadhav) [inline src/libs/OptionsListUtils.ts:1747]: I was wondering if any of these methods can have supporting unit tests?

**Review by mananjadhav — COMMENTED** [review]
Just finished with the reviewer, left minor comments. But I think it's best if we add a few unit tests to make it more reliable?

**Comment by mananjadhav** [comment]
@JKobrynski I was testing this but I had some issues.

1. On a new account, I didn't find the option for the self-DM. I am not sure if the issue related to the PR.

2. When the number of workspaces is high (I don't know if it's valid for the production users), the `Personal` and other users have to be scrolled down.

3. I can see `justTrackIt: 'Just track it (don’t submit it)',` keys are not removed from translation.

4. We also need to get rid of `4. Click "Just track it (don\'t submit it)".\n` in the [CONST](https://github.com/Expensify/App/blob/690bd3d2c20df16532ef011ff985515384cd4345/src/CONST.ts#L189) or we're fixing it in the other PR.

https://github.com/user-attachments/assets/9740b5cd-225a-4f18-ae3e-501614b288dc

**Comment by trjExpensify** [comment]
>1. On a new account, I didn't find the option for the self-DM. I am not sure if the issue related to the PR.

Nope, not related to this PR.  We stopped creating the selfDM on account creation unless you choose the track option in the onboarding modal. @MonilBhavsar I believe you were going to be looking into this, per [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1736467823279949?thread_ts=1736371131.733419&cid=C02NK2DQWUX).

**Comment by fabioh8010** [comment]
Just a heads up that @JKobrynski has been on OOO since Monday and will return tomorrow.

**Comment by trjExpensify** [comment]
Thanks for the heads up! What can we do to keep this moving to being merged today? 

>2. When the number of workspaces is high (I don't know if it's valid for the production users), the Personal and other users have to be scrolled down.

Is this just saying that the list of workspaces take up the scroll view when you have a ton of them? If so, I think that's fine and expected. That's clearly your primary use-case if you have that many and, after all, you can use the search bar if you want. 

>3. I can see justTrackIt: 'Just track it (don’t submit it)', keys are not removed from translation.
>4. We also need to get rid of `4. Click "Just track it (don\'t submit it)".\n` in the [CONST](https://github.com/Expensify/App/blob/690bd3d2c20df16532ef011ff985515384cd4345/src/CONST.ts#L189) or we're fixing it in the other PR.

Is there any harm or noticeable impact for the customer if we proceed to merge this, and take care of those in [this PR](https://github.com/Expensify/App/pull/54201#pullrequestreview-2549488006) which comes after it?

**Comment by fabioh8010** [comment]
@trjExpensify I can handle the remaining review comments if you want urgency here.

**Comment by trjExpensify** [comment]
Seems like we're okay to wait for tomorrow, because Georgia wants to merge this PR along with [this one](https://github.com/Expensify/App/pull/54201).

**Comment by JKobrynski** [comment]
> 2. When the number of workspaces is high (I don't know if it's valid for the production users), the Personal and other users have to be scrolled down.

Initially, that section was limited to 5 items (just like the other sections) but I was told to remove that limit, as users should be able to see all workspaces there (see [thread](https://github.com/Expensify/App/pull/53760#discussion_r1894023127))

CC: @mananjadhav

File: src/libs/OptionsListUtils.ts (hunk 2 above)
Comment (JKobrynski) [reply src/libs/OptionsListUtils.ts]: Done

**Comment by grgia** [comment]
Okay triggered a fresh one after the merge. I think we should handle the unit tests in a follow up given we merged the first

**Comment by grgia** [comment]
@mananjadhav could you prioritize this one so we can wrap this feature 🤘

**Comment by mananjadhav** [comment]
I'll get to this in 30 mins.

**Review by mananjadhav — COMMENTED** [review]
Just finished the review of the code. Will start testing it now.

**Comment by mananjadhav** [comment]
### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/27b9667a-fe3f-48c8-a188-28f0d40243c3

https://github.com/user-attachments/assets/0cc37662-4588-49fd-b6f8-63c8a0e39767

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/1ae5f702-0e4a-47fb-b461-a9cc28059c46

</details>

**Comment by trjExpensify** [comment]
>I can't search the Personal (self) by the first name. I can search by email but search by name doesn't work. The workspace list works fine but not Personal. May be this could be follow up too?

Did you sign-up for a new account and NOT select the track onboarding option?

**Comment by mananjadhav** [comment]
> > I can't search the Personal (self) by the first name. I can search by email but search by name doesn't work. The workspace list works fine but not Personal. May be this could be follow up too?
> 
> Did you sign-up for a new account and NOT select the track onboarding option here like you mention below?

It's a very old account, so I don't remember what I had chosen.

**Comment by trjExpensify** [comment]
>But as I said I can see the self option in the list and I can search by email but not First name or last name.

Oh, is that in the video you posted? 😕

**Comment by mananjadhav** [comment]
> > But as I said I can see the self option in the list and I can search by email but not First name or last name.
> 
> Oh, is that in the video you posted? 😕

Here you go

https://github.com/user-attachments/assets/0c4ba0f2-67a4-491f-8b17-e39312877c48

**Comment by trjExpensify** [comment]
Super helpful. If you use that same account on staging, can you search using the name?

**Comment by mananjadhav** [comment]
> Super helpful. If you use that same account on staging, can you search using the name?

No. But we didn't show the self-DM earlier in the search list.

https://github.com/user-attachments/assets/27ddc719-62c8-46b8-8321-f6ce5c351db5

**Comment by JKobrynski** [comment]
https://github.com/user-attachments/assets/f9ca9fae-f73a-47ff-9b40-6244eaac70be

Works for me for some reason 🤔 I noticed that the way our current logic searches through your chats to find the self DM chat (and display it if it's found) is by going through recent chats, so basically if self dm was not used for a long time, it won't be displayed in the list. Is that something that you'd like me to change?

CC: @mananjadhav @trjExpensify

**Comment by trjExpensify** [comment]
If it's not logic we've amended here, I think it's fine as a follow-up personally. After all, most people don't have 42 workspaces and it'll be there under the `Personal` row looking at Manan's vid.

**Comment by JKobrynski** [comment]
> If it's not logic we've amended here, I think it's fine as a follow-up personally. After all, most people don't have 42 workspaces and it'll be there under the Personal row looking at Manan's vid.

Understood! So, is there anything else you'd like me to change/fix about this PR?

**Comment by trjExpensify** [comment]
>So, is there anything else you'd like me to change/fix in this PR?

I'll defer to Manan on that!

**Comment by mananjadhav** [comment]
I think I am good here. But for some reason both my native builds are not running. 

image

image

@JKobrynski Can you try at your end if the build is working fine on the latest changes? I'll finish my testing on the adhoc build.

**Comment by JKobrynski** [comment]
@mananjadhav taking a look now 👀

**Comment by JKobrynski** [comment]
@mananjadhav I ran a dev build of both Android and iOS on my end and both worked fine, but I had some trouble getting them running, I think it was mainly because RN was upgraded to 0.76 recently. Maybe we could retrigger the builds and see what happens?

**Comment by grgia** [comment]
I'll re-trigger now

**Comment by mananjadhav** [comment]
Looks like the build is working fine. Seems like an issue on my end and I still couldn't get it working. I am completing the testing with adhoc builds.

**Review by mananjadhav — APPROVED** [review]

**Comment by trjExpensify** [comment]
@JKobrynski before we merge this, can you quickly make `trackScan` read "Scan receipt" instead of what it was changed to in [this PR](https://github.com/Expensify/App/pull/54201/files). Thanks!

**Comment by JKobrynski** [comment]
@trjExpensify done!

**Comment by mananjadhav** [comment]
@JKobrynski We've got some conflicts.

**Comment by JKobrynski** [comment]
@mananjadhav conflicts fixed!

CC: @grgia @trjExpensify

**Comment by trjExpensify** [comment]
Niceee!

**Review by grgia — APPROVED** [review]
🎸

**Comment by grgia** [comment]
Follow up issue here- https://github.com/Expensify/App/issues/55538

cc @JKobrynski @mananjadhav 

Gonna merge this!

**Comment by hannojg** [comment]
I have performance considerations with this. We shouldn't add new loops in getValidOptions, but instead move those checks to getValidReports and do it all on one loop.
I am working on it over here:

- https://github.com/Expensify/App/pull/55599

(currently a bit limited in bandwidth feel free to pick it up or explore other approaches. Otherwise I can also complete it)

**Comment by mananjadhav** [comment]
@JKobrynski How about we take care of [this](https://github.com/Expensify/App/pull/55016#issuecomment-2606818324) in the follow up PR?

**Comment by JKobrynski** [comment]
@mananjadhav should we create an issue for that?
