### PR TITLE
[Fix #16696] Rewrite `BaseTextInput` to function component

### LINKED ISSUE #16696: [HOLD for payment 2023-07-14] [$4000] Text selection options disappears abruptly
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to split bill
2. Enter some amount
3. Double click on amount to select -> Look for option above text.

## Expected Result:
Text formatting option should be visible properly

## Actual Result:
Text formatting option disappears abruptly

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.91-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/228638165-b77fbc3a-e80b-4e43-9da0-811918508c04.MP4

https://user-images.githubusercontent.com/43996225/228638187-fd727292-37f0-4b56-8cc9-04fee22e92dc.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dinaljivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1680084554334659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d391e71cd8a32e4c</li>
        <li>Upwork Job ID: 1644015735567663104</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

### PR DESCRIPTION
**Pull request by hannojg**
### Details

Previously the `BaseTextInput` component would control its own internal state for the input's value. Meaning when the `value` prop changed, it would re-render another time as in `componentDidUpdate` the internal `value` state got updated with a consecutive `setState` call.

It was discussed that the most future proof fix for this is to refactor to a function component and to use the `value` prop directly.

### Fixed Issues

$ https://github.com/Expensify/App/issues/16205
$ https://github.com/Expensify/App/issues/16696
PROPOSAL: https://github.com/Expensify/App/issues/16696#issuecomment-1576894931

### Tests

- [ ] Verify that no errors appear in the JS console
- [ ] Verify the bug is fixed (note: the bug happens on android as well. It's fixed for android as well, however, you will only be able to notice its fixed when used together [with this not yet merged PR](https://github.com/Expensify/react-native/pull/55). For now its enough to validate that its fixed on iOS)
  - Open the app authenticated
  - Press the Plus FAB button
  - Open "request money"
  - Enter a number
  - Select text, notice how the selection context menu stays
- [ ] Verify that every input throughout the app is still working as expected

### Offline tests

This change doesn't work with any network features, so no separate offline tests are needed.

### QA Steps

Same as tests. 

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/16821682/7c6a5a30-6315-4105-860c-c1b707ce41fc

https://github.com/Expensify/App/assets/16821682/5edf2399-3840-4eba-b2ea-7782d7695d40

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/16821682/1eae7b3a-cc65-40ee-99e1-6abebdbc6be8

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/16821682/f53d0a16-cad1-4905-b1d7-5cc2b6e70ae6

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/16821682/0b919cf6-8efd-436c-a27d-8fc3d2c9c34a

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/16821682/2705c4e4-6cfd-41d4-8917-8edc577152a6

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/16821682/e0f4aeb8-301c-42e1-b12e-ac8439d9cdde

</details>

### CODE REVIEW

File: src/components/TextInput/BaseTextInput.js [hunk 1]
```diff
@@ -21,381 +21,380 @@ import isInputAutoFilled from '../../libs/isInputAutoFilled';
...
+        return;
     }
 
-    componentDidMount() {
-        if (this.props.disableKeyboard) {
-            this.appStateSubscription = AppState.addEventListener('change', this.dismissKeyboardWhenBackgrounded);
+    Keyboard.dismiss();
+}
+
+function BaseTextInput(props) {
```
Comment (narefyev91) [inline src/components/TextInput/BaseTextInput.js:33]: based on this PR https://github.com/Expensify/eslint-config-expensify/pull/64 we can use destructuring props - which will clean code a little bit

Comment (narefyev91) [reply src/components/TextInput/BaseTextInput.js:33]: in current situation - i think it will be good idea to move away from defining every time a new variable like that:
    const propIsDisabled = props.disabled;
    const propOnPress = props.onPress;

Comment (mountiny) [reply src/components/TextInput/BaseTextInput.js:33]: I think we should still avoid destructuring props https://expensify.slack.com/archives/C01GTK53T8Q/p1686062674061049?thread_ts=1685727880.152119&cid=C01GTK53T8Q

https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#destructuring

File: src/components/TextInput/BaseTextInput.js [hunk 2]
```diff
@@ -21,381 +21,380 @@ import isInputAutoFilled from '../../libs/isInputAutoFilled';
...
+
+            if (propOnPress) {
+                propOnPress(event);
+            }
+
+            if (!event.isDefaultPrevented()) {
+                input.current.focus();
+            }
+        },
+        [propIsDisabled, propOnPress],
```
Comment (narefyev91) [inline src/components/TextInput/BaseTextInput.js:97]: if we will not use desctructive props you should remove this items and use direct props.disabled, and props.onPress. in current implementation you will re-create onPress callback on any re-render - which may cause performance and memory issues

File: src/components/TextInput/BaseTextInput.js [hunk 3]
```diff
@@ -21,381 +21,380 @@ import isInputAutoFilled from '../../libs/isInputAutoFilled';
...
+
+    const propOnFocus = props.onFocus;
+    const onFocus = useCallback(
+        (event) => {
+            if (propOnFocus) {
+                propOnFocus(event);
+            }
+            setIsFocused(true);
+        },
+        [propOnFocus],
```
Comment (narefyev91) [inline src/components/TextInput/BaseTextInput.js:144]: same here - let's use direct props.onFocus

File: src/components/TextInput/BaseTextInput.js [hunk 4]
```diff
@@ -21,381 +21,380 @@ import isInputAutoFilled from '../../libs/isInputAutoFilled';
...
+            }
+            setIsFocused(false);
+
+            // If the text has been supplied by Chrome autofill, the value state is not synced with the value
+            // as Chrome doesn't trigger a change event. When there is autofill text, don't deactivate label.
+            if (!isInputAutoFilled(input.current)) {
+                deactivateLabel();
+            }
+        },
+        [deactivateLabel, propOnBlur],
```
Comment (narefyev91) [inline src/components/TextInput/BaseTextInput.js:161]: and also here props.onBlur

File: src/components/TextInput/BaseTextInput.js [hunk 5]
```diff
@@ -21,381 +21,380 @@ import isInputAutoFilled from '../../libs/isInputAutoFilled';
...
+        (value) => {
+            if (propOnInputChange) {
+                propOnInputChange(value);
+            }
+
+            // TODO: what is the next line used for?
+            Str.result(props.onChangeText, value);
+            activateLabel();
+        },
+        [activateLabel, propOnInputChange, props.onChangeText],
```
Comment (narefyev91) [inline src/components/TextInput/BaseTextInput.js:210]: and this one too props.onInputChange

File: src/components/TextInput/BaseTextInput.js (hunk 1 above)
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js:33]: Okay, I double checked with the documentation and removed the `useCallbacks` where we don't need them according to the docs. This removed the weird prop usage anyway!

**Comment by mountiny** [comment]
@narefyev91 lets make sure to test the app thoroughly not only based on the tests steps due to the importance of this component. Mentions might be a good thing to look at

**Comment by narefyev91** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>



</details>

<details>
<summary>Desktop</summary>



</details>

<details>
<summary>iOS</summary>



</details>

<details>
<summary>Android</summary>



</details>

**Comment by narefyev91** [comment]
@hannojg something strange happened with native android, sometimes cursor jumped in not correct position - when typing fast, and i could not see highlight menu most of the times..... and when you get it, you can only move highlighter area on one position

https://github.com/Expensify/App/assets/28352309/07d0ffd3-e9de-4712-b995-a517d47bb4ba


https://github.com/Expensify/App/assets/28352309/380e6d69-35f2-4f87-b37e-b00f2c402624

**Comment by hannojg** [comment]
Hey @narefyev91 thanks for the testing!

I think the issues you are encountering on android are due to the fact, that your environment doesn't include the native fixes fromhttps://github.com/Expensify/react-native/pull/55 yet.
Right now these changes haven't landed in the expensify app repo yet, but i think they will next week.

I think those bugs have been also there before this changes, however, i am not entirely sure. Do you guys feel it makes sense to put the PR on hold until the native fix has landed?

**Comment by narefyev91** [comment]
> Hey @narefyev91 thanks for the testing!
> 
> I think the issues you are encountering on android are due to the fact, that your environment doesn't include the native fixes fromhttps://github.com/[Expensify/react-native/pull/55](https://github.com/Expensify/react-native/pull/55) yet (i double tested it, and with the native fix i can't reproduce the issues). Right now these changes haven't landed in the expensify app repo yet, but i think they will next week.
> 
> I think those bugs have been also there before this changes, however, i am not entirely sure. Do you guys feel it makes sense to put the PR on hold until the native fix has landed?

If we have already those bugs before - and current implementation is not introduce something new for other platforms (which is true) - i think we can not hold this - there are several tickets that may be unblocked/moving forward with new functional implementation - i will say that we can merge this one, but let's have @mountiny get last word here

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Few changes

File: src/components/TextInput/BaseTextInput.js [hunk 6]
```diff
@@ -21,381 +21,363 @@ import isInputAutoFilled from '../../libs/isInputAutoFilled';
...
+            styles.textInputContainer,
+            ...props.textInputContainerStyles,
+            props.autoGrow && StyleUtils.getWidthStyle(textInputWidth),
+            !props.hideFocusedState && isFocused && styles.borderColorFocus,
+            (props.hasError || props.errorText) && styles.borderColorDanger,
+            props.autoGrowHeight && {scrollPaddingTop: 2 * maxHeight},
+        ],
+        (finalStyles, s) => ({...finalStyles, ...s}),
+        {},
+    );
```
[the remark this answers is not in the document]
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js]: Indeed, good catch!

**Review by parasharrajat — CHANGES_REQUESTED** [review]

File: src/components/TextInput/BaseTextInput.js [hunk 7]
```diff
@@ -20,382 +20,362 @@ import FormHelpMessage from '../FormHelpMessage';
...
-
-    componentDidMount() {
-        if (this.props.disableKeyboard) {
-            this.appStateSubscription = AppState.addEventListener('change', this.dismissKeyboardWhenBackgrounded);
+function BaseTextInput(props) {
+    const inputValue = props.value || '';
+    const initialActiveLabel = props.forceActiveLabel || inputValue.length > 0 || Boolean(props.prefixCharacter);
+
+    const [isFocused, setIsFocused] = useState(false);
+    const [labelTranslateY] = useState(() => new Animated.Value(initialActiveLabel ? styleConst.ACTIVE_LABEL_TRANSLATE_Y : styleConst.INACTIVE_LABEL_TRANSLATE_Y));
```
[the remark this answers is not in the document]
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js:28]: alright, will refactor to use `useRef` here

File: src/components/TextInput/BaseTextInput.js [hunk 8]
```diff
@@ -20,382 +20,362 @@ import FormHelpMessage from '../FormHelpMessage';
...
+            {(props.autoGrow || props.autoGrowHeight) && (
+                // Add +2 to width so that the first digit of amount do not cut off on mWeb - https://github.com/Expensify/App/issues/8158.
+                <Text
+                    style={[...props.inputStyle, props.autoGrowHeight && styles.autoGrowHeightHiddenInput(width, maxHeight), styles.hiddenElementOutsideOfWindow, styles.visibilityHidden]}
+                    onLayout={(e) => {
+                        setTextInputWidth(e.nativeEvent.layout.width + 2);
+                        setTextInputHeight(e.nativeEvent.layout.height);
+                    }}
+                >
+                    {props.value || props.placeholder}
```
[the remark this answers is not in the document]
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js:372]: There are two scenarios:

- You can just have a `onChangeText` callback, but don't need any `value` prop for the textinput to show the text changes. This way you can't control the text input, but still get the text.
- You provide a `onChangeText` and `value` prop in the parent and thus control the input of the text input.

**Comment by mountiny** [comment]
@parasharrajat @narefyev91 thanks for the reviews here, can we confirm once again after these changes that there are no new regressions?

If the only issues found exist on main then we can merge this I agree

File: src/components/TextInput/BaseTextInput.js [hunk 9]
```diff
@@ -20,382 +20,362 @@ import FormHelpMessage from '../FormHelpMessage';
...
-        this.togglePasswordVisibility = this.togglePasswordVisibility.bind(this);
-        this.dismissKeyboardWhenBackgrounded = this.dismissKeyboardWhenBackgrounded.bind(this);
-        this.storePrefixLayoutDimensions = this.storePrefixLayoutDimensions.bind(this);
-    }
-
-    componentDidMount() {
-        if (this.props.disableKeyboard) {
-            this.appStateSubscription = AppState.addEventListener('change', this.dismissKeyboardWhenBackgrounded);
+function BaseTextInput(props) {
+    const inputValue = props.value || '';
```
[the remark this answers is not in the document]
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js]: Thank you, I missed handling that correctly.

File: src/components/TextInput/BaseTextInput.js [hunk 10]
```diff
@@ -20,382 +20,362 @@ import FormHelpMessage from '../FormHelpMessage';
...
+    const initialActiveLabel = props.forceActiveLabel || inputValue.length > 0 || Boolean(props.prefixCharacter);
+
+    const [isFocused, setIsFocused] = useState(false);
+    const [labelTranslateY] = useState(() => new Animated.Value(initialActiveLabel ? styleConst.ACTIVE_LABEL_TRANSLATE_Y : styleConst.INACTIVE_LABEL_TRANSLATE_Y));
+    const [labelScale] = useState(() => new Animated.Value(initialActiveLabel ? styleConst.ACTIVE_LABEL_SCALE : styleConst.INACTIVE_LABEL_SCALE));
+    const [passwordHidden, setPasswordHidden] = useState(props.secureTextEntry);
+    const [textInputWidth, setTextInputWidth] = useState(0);
+    const [textInputHeight, setTextInputHeight] = useState();
```
[the remark this answers is not in the document]
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js:32]: Looking at the previous code, I don't think its new?
In the original code it has been undefined as well:


https://github.com/Expensify/App/blob/559924e9417a0b3dc275f0cc1c46004fb9b4662e/src/components/TextInput/BaseTextInput.js#L31-L44

**Comment by hannojg** [comment]
@parasharrajat Added your latest feedback to the PR 😊

File: src/components/TextInput/BaseTextInput.js [hunk 11]
```diff
@@ -18,384 +18,369 @@ import getSecureEntryKeyboardType from '../../libs/getSecureEntryKeyboardType';
...
+
+    const [isFocused, setIsFocused] = useState(false);
+    const labelTranslateY = useRef(new Animated.Value(initialActiveLabel ? styleConst.ACTIVE_LABEL_TRANSLATE_Y : styleConst.INACTIVE_LABEL_TRANSLATE_Y)).current;
+    const labelScale = useRef(new Animated.Value(initialActiveLabel ? styleConst.ACTIVE_LABEL_SCALE : styleConst.INACTIVE_LABEL_SCALE)).current;
+    const [passwordHidden, setPasswordHidden] = useState(props.secureTextEntry);
+    const [textInputWidth, setTextInputWidth] = useState(0);
+    const [textInputHeight, setTextInputHeight] = useState();
+    const [prefixWidth, setPrefixWidth] = useState(0);
+    const [height, setHeight] = useState(variables.componentSizeLarge);
+    const [width, setWidth] = useState();
```
Comment (narefyev91) [inline src/components/TextInput/BaseTextInput.js:35]: can we clean up a little bit - move useState items under each other, and after place useRefs item? it will be easier to read

File: src/components/TextInput/BaseTextInput.js [hunk 12]
```diff
@@ -18,384 +18,369 @@ import getSecureEntryKeyboardType from '../../libs/getSecureEntryKeyboardType';
...
+                return;
+            }
+
+            Keyboard.dismiss();
+        });
+
+        return () => {
+            if (!props.disableKeyboard) {
+                return;
+            }
```
[the remark this answers is not in the document]
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js]: true, fixed

File: src/components/TextInput/BaseTextInput.js (hunk 11 above)
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js:33]: here we go 😊

**Comment by narefyev91** [comment]
> @parasharrajat @narefyev91 thanks for the reviews here, can we confirm once again after these changes that there are no new regressions?
> 
> If the only issues found exist on main then we can merge this I agree

Yes - i think i will re-test on all devices again - because there were some code changes - if nothing will happened we will be good to go

**Comment by narefyev91** [comment]
> I think @narefyev91 is C+ here. I just noticed a few things so pointed out. @mountiny Do you want to me run the tests as well?

I think it will be super helpful - in case this component is very important - and will be nice to have one more pair of eyes!
@parasharrajat

**Comment by mountiny** [comment]
@parasharrajat @narefyev91 yes because this is an important component, I think it makese sense that both of you could do proper testing here, thanks!

**Review by parasharrajat — CHANGES_REQUESTED** [review]
On StoryBook Server

BUG: autogrow height does not work. 
Bug: AUTOGROW WIDTH does not work. 
BUg: Default value story does not work. 

Compare these with https://staging.new.expensify.com/docs/index.html

**Comment by hannojg** [comment]
@parasharrajat Thank you for the review, I pushed fixes!

**Comment by hannojg** [comment]
@parasharrajat Good catch, its fixed, please text again!

**Comment by mountiny** [comment]
@hannojg lets try to address the feedback on this one again and make it ready for another look

File: src/components/TextInput/BaseTextInput.js [hunk 13]
```diff
@@ -167,17 +167,26 @@ function BaseTextInput(props) {
         [props.autoGrowHeight, props.multiline],
     );
 
+    const hasValueRef = useRef(inputValue.length > 0);
```
[the remark this answers is not in the document]
Comment (hannojg) [reply src/components/TextInput/BaseTextInput.js]: @parasharrajat I added a few comments to the code and moved it a bit to make it easier to understand. I hope it's better now?

In general we can't use inputValue directly, because it might doesn't represent the actual input value, due to the following reasons:

- `props.value` might be undefined, when its a uncontrolled text component
- `inputValue` is composed out of `props.defaultValue`. The input might get cleared of the `defaultValue`, but `inputValue` would still contain it as it doesn't get updated.

Thus we have to keep track of the actual fact whether there is a value inside the input field or not, which is what this ref accomplishes.
It's a ref because we want to avoid unnecessary re-renders.

**Comment by hannojg** [comment]
@mountiny @parasharrajat addressed the latest feedback 😊

**Comment by mountiny** [comment]
@parasharrajat @narefyev91 ready for another round of testing

**Review by parasharrajat — APPROVED** [review]
LGTM.

:ribbon: :eyes: :ribbon:  C+ reviewed

**Review by narefyev91 — APPROVED** [review]

**Comment by mountiny** [comment]
Thanks, due to SNH Conference and this being such important component, I will wait with merging this for next week! Thanks so much for thorough review and testing.

**Comment by s77rt** [comment]
@parasharrajat I'm assigned in https://github.com/Expensify/App/issues/16696 but I didn't review this PR since I was not aware of it (only after some time later) because this PR linked the other issue first and you got requested for review instead. So I think it would be fair that you take the C+ role here https://github.com/Expensify/App/issues/16696 as well.

**Comment by hannojg** [comment]
Merge conflicts resolved, made sure the latest changes made to the class component are reflected appropriately in the new function component

File: src/components/TextInput/BaseTextInput.js [hunk 14]
```diff
@@ -18,387 +18,387 @@ import getSecureEntryKeyboardType from '../../libs/getSecureEntryKeyboardType';
...
+        <>
+            <View>
+                <PressableWithoutFeedback
+                    onPress={onPress}
+                    focusable={false}
+                    accessibilityLabel={props.label}
+                    style={[props.autoGrowHeight && styles.autoGrowHeightInputContainer(textInputHeight, maxHeight), !isMultiline && styles.componentHeightLarge, ...props.containerStyles]}
+                >
+                    <View
+                        // When autoGrowHeight is true we calculate the width for the textInput, so It will break lines properly
```
Comment (mountiny) [inline src/components/TextInput/BaseTextInput.js:255]: NAB
```suggestion
                        // When autoGrowHeight is true we calculate the width for the textInput, so it will break lines properly
```

**Review by mountiny — DISMISSED** [review]
thanks for your patience while i was ooo and thorough testing and review. Going to ship it now. Thanks everyone!

**Review by mountiny — APPROVED** [review]

**Comment by Julesssss** [comment]
FYI this PR also seems to have introduced [this regression](https://github.com/Expensify/App/issues/22183). 

I'd revert it, but at this point, we've already cherry-picked fixes for other regressions related to navigation and I'm concerned about messy conflicts and dependency chains.

**Comment by sobitneupane** [comment]
[This regression](https://github.com/Expensify/App/issues/22169) was caused by the changes introduce in this PR.

**IssueTitle:** DEV: Console error on type email in close account page

**Comment by abdulrahuman5196** [comment]
This caused a regression of Text Description not toggling properly - more information here https://github.com/Expensify/App/issues/22204#issuecomment-1623242605
