### PR TITLE
Disable the focus trap for report page context menu

### LINKED ISSUE #14329: [HOLD for payment 2023-03-09] [$1000] Right-clicking a long message and closing the context menu causes scrolling in chat to the clicked message
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Send any long message (10000+ characters)
3. Send few message after long message
4. Right click on long message
5. Press copy to clipboard or touch outside to close the context menu

## Expected Result:
Chat should not auto scroll to the message clicked

# Actual Result:
Chat is being auto scroll to the clicked message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.54-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212752593-827b3e23-8411-4a15-913c-3fcc3f208c8b.mov

https://user-images.githubusercontent.com/43996225/212752748-332912b7-1870-4c38-a0fd-99a9567b266b.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673806343288019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01609e656afafc6317</li>
        <li>Upwork Job ID: 1623654809687388160</li>
        <li>Last Price Increase: 2023-02-09</li>
    </ul>
</details>

### PR DESCRIPTION
**Pull request by allroundexperts**
### Details

This PR fixes the issue where focus was being restored back to the message once the context menu closed. It disables this focus trap by blurring the element immediately after right click. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/14329
PROPOSAL: https://github.com/Expensify/App/issues/14329#issuecomment-1439041180

### Tests

Go to any chat
1. Send any long message (10000+ characters)
2. Send few message after long message
3. Right click on long message
4. Press copy to clipboard or touch outside to close the context menu

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Go to any chat
2. Send any long message (10000+ characters)
3. Send few message after long message
4. Right click on long message
5. Press copy to clipboard or touch outside to close the context menu

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/30054992/220768340-77de246b-6d80-4001-ad08-a7d9b2477487.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/30054992/220768509-09a133b8-a1a0-44e9-9f21-380b08dafd12.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/30054992/221042807-20c8d43d-bb9d-4494-a6fa-d79992c54a91.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/30054992/221042921-2970cbce-258f-4751-8351-31cd4b895518.mov

</details>

<details>
<summary>iOS Safari</summary>

https://user-images.githubusercontent.com/30054992/221042972-aa688085-a0b8-4954-a45c-360af8767a78.mov

</details>

<details>
<summary>Android Chrome</summary>

https://user-images.githubusercontent.com/30054992/221043012-4ec44737-9867-4356-aa77-9e3c05486aaa.mov

</details>

### CODE REVIEW

File: src/components/PressableWithSecondaryInteraction/index.js [hunk 1]
```diff
@@ -52,7 +55,12 @@ class PressableWithSecondaryInteraction extends Component {
                     this.props.onSecondaryInteraction(e);
                 }}
                 onPressOut={this.props.onPressOut}
-                onPress={this.props.onPress}
+                onPress={(e) => {
+                    if (this.props.withoutFocus && this.pressableRef) {
```
Comment (eVoloshchak) [inline src/components/PressableWithSecondaryInteraction/index.js:59]: Please add the comment explaining why this is needed
```
/**
 * This component prevents the tapped element from capturing focus.
 * We need to blur this element when clicked as it opens modal that implements focus-trapping.
 * When the modal is closed it focuses back to the last active element.
 * Therefore it shifts the element to bring it back to focus.
 * https://github.com/Expensify/App/issues/6806
 * https://github.com/Expensify/App/issues/14148
 */
 ```
 And I think `PressableWithoutFocus` can be deleted, since we're not using it anymore

**Review by eVoloshchak — CHANGES_REQUESTED** [review]

**Comment by allroundexperts** [comment]
@eVoloshchak I've gone through this again and I think that removing `PressableWithoutFocus` is not a good idea here. `PressableWithoutFocus` does not have any secondary interaction defined in it. If you do a right click on a `PressableWithoutFocus`, you'll see that a native context menu opens up. However, with `PressableWithSecondaryInteraction`, if you do a right click on it, the native context menu does not open. Instead, the handler provided for `longPress` gets triggered. We can add a property to disable this for `PressableWithSecondaryInteraction` but I think that will kill the whole purpose of this component. Please let me know what you think about this and I can edit the PR after that.

**Comment by eVoloshchak** [comment]
@allroundexperts, good catch!
I can observe this behavior too. In that case you can edit the PR, I'll start going through the checklist shortly

**Comment by allroundexperts** [comment]
> @allroundexperts, good catch! I can observe this behavior too. In that case you can edit the PR, I'll start going through the checklist shortly

Awesome. I've updated the PR.

File: src/components/PressableWithSecondaryInteraction/index.js (hunk 1 above)
Comment (allroundexperts) [reply src/components/PressableWithSecondaryInteraction/index.js]: Added the comment as well.

**Comment by eVoloshchak** [comment]
@allroundexperts, looks like you need to merge with `main`, there's something weird with the commits
image

**Comment by allroundexperts** [comment]
> @allroundexperts, looks like you need to merge with `main`, there's something weird with the commits image

@eVoloshchak Fixed.

File: src/components/PressableWithSecondaryInteraction/index.js [hunk 2]
```diff
@@ -34,6 +34,18 @@ class PressableWithSecondaryInteraction extends Component {
         if (this.props.preventDefaultContentMenu) {
             e.preventDefault();
         }
+
+        /**
+         * This component prevents the tapped element from capturing focus.
+         * We need to blur this element when clicked as it opens modal that implements focus-trapping.
+         * When the modal is closed it focuses back to the last active element.
+         * Therefore it shifts the element to bring it back to focus.
+         * https://github.com/Expensify/App/issues/6806
```
Comment (eVoloshchak) [inline src/components/PressableWithSecondaryInteraction/index.js:43]:
```suggestion
```

**Review by eVoloshchak — CHANGES_REQUESTED** [review]

File: src/components/PressableWithSecondaryInteraction/index.js (hunk 2 above)
Comment (allroundexperts) [reply src/components/PressableWithSecondaryInteraction/index.js]: Updated 😄

**Comment by eVoloshchak** [comment]
@allroundexperts, you need to check off every checkbox in the checklist. 
Also, there should be a video for each platform, even the ones that aren't affected by this change (just to verify everything works as expected)

**Comment by allroundexperts** [comment]
> @allroundexperts, you need to check off every checkbox in the checklist. Also, there should be a video for each platform, even the ones that aren't affected by this change (just to verify everything works as expected)
@eVoloshchak What screen should I show on mobile? Since there is no right click there, what should I show there?

**Comment by eVoloshchak** [comment]
> @eVoloshchak What screen should I show on mobile? Since there is no right click there, what should I show there?

You can long-press on a message to trigger the context menu. I've uploaded an iOS video [here](https://github.com/Expensify/App/pull/15375#issuecomment-1442100383)

**Comment by allroundexperts** [comment]
> > @eVoloshchak What screen should I show on mobile? Since there is no right click there, what should I show there?
> 
> You can long-press on a message to trigger the context menu. I've uploaded an iOS video [here](https://github.com/Expensify/App/pull/15375#issuecomment-1442100383)

Got it. Thank you. I'll upload these 👍

**Review by eVoloshchak — APPROVED** [review]
LGTM
cc: @chiragsalian

**Review by chiragsalian — APPROVED** [review]
Code LGTM too. 
The GH linked is incorrect. You linked https://github.com/Expensify/App/issues/14148
but i think you meant to link https://github.com/Expensify/App/issues/14329. @Luke9389 is supposed to review but i totally don't mind reviewing too 🙂 

Please correct it so that melvin can track the issue status properly 🙂

**Review by Luke9389 — APPROVED** [review]
