### PR TITLE
Fix - mWeb/Safari- Chat - After tapping on "Copy to clipboard", options menu does not close #28820

### LINKED ISSUE #28820: [HOLD for payment 2023-11-09] [$500] mWeb/Safari- Chat - After tapping on "Copy to clipboard", options menu does not close
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Long press on any message
3. Tap on "Copy to clipboard"

## Expected Result:
There should be a message indicating the message has been copied and then the options menu should close

## Actual Result:
There is no message indicating that the message has been copied and options menu does not close

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3c7d3265-135e-46ed-89f6-6da4ac595a8b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153aad7aa52da20d4</li>
        <li>Upwork Job ID: 1710335830550470656</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27277511</li>
<li>AmjedNazzal | Contributor | 27277514</li>
</ul></li>
    </ul>
</details>

### PR DESCRIPTION
**Pull request by AmjedNazzal**
### Details

We are adding a check for anchorNode and focusNode not being null before using setBaseAndExtent since it no longer accepts null as per changes in WebKit source code

### Fixed Issues

$ https://github.com/Expensify/App/issues/28820
PROPOSAL: https://github.com/Expensify/App/issues/28820#issuecomment-1769108431

### Tests

1. Open the app in either MacOS Safari v17 and above or Safari on iPhone 15 and above
2. Go to any chat and right click/Long press on a chat message to view the context menu
3. Click/Press on Copy to clipboard
4. Confirm that the context menu closes

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as Tests

### QA Steps

1. Open the app in either MacOS Safari v17 and above or Safari on iPhone 15 and above
2. Go to any chat and right click/Long press on a chat message to view the context menu
3. Click/Press on Copy to clipboard
4. Confirm that the context menu closes

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/74202751/aa25146b-b22c-4a77-aedf-4816718b91e9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/74202751/951d72e5-775d-449f-bea6-d6e163f7e65b

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/74202751/55ce8b00-af5c-4dde-836f-64ae5fc55c59

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/74202751/f1516bea-9abc-434a-b2e5-ea5256f81366

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/74202751/72765d73-c366-4751-be0a-27487725e4e0

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/74202751/57387553-6e40-4a40-9291-8b29236db82b

</details>

### CODE REVIEW

**Comment by cubuspl42** [comment]
@AmjedNazzal While Expensify doesn't have a strict policy on commit message content, and it's a known situation that many quickly typed commit messages land in the repo, I think this one is too much:

```
Issue28820
```

Please make it at something like "Fix issue #28820" and force-push

**Comment by cubuspl42** [comment]
On Android/Chrome, are you able to paste the copied message successfully?

**Comment by cubuspl42** [comment]
I also noticed that this is not likely related to this PR. Still, as we're changing essentially the same functionality, we should ensure that it's working after our changes (unless we're in an extreme hurry, etc.).

So I would say we should classify _why_ the functionality is not fully working on Android/Chrome and hold on the relevant issue/PR.

**Comment by AmjedNazzal** [comment]
@cubuspl42 I had a look around in all recent PRs and I couldn't find anything that has been merged but not deployed to staging yet that could be causing the android/chrome issue, I then checked why this is happening and what I managed to find out is that when running the app locally and browsing it from an android phone on chrome, it seem like whenever we try to call clipboard.write it throws an issue that it doesn't exist, I've done some logs and it seems like clipboard.write is not being exposed in navigation object at all, I'm suspecting this has to do with a permission issue as android phones connecting to.a locally run app will have a website not secure warning and maybe that's why it works on staging but not on local build, I don't have a way to absoloutely confirm that yet but I tried emulating a samsung phone on a cloud service and using a tunnel to access localhost and as you see in the video below it did work on that


https://github.com/Expensify/App/assets/74202751/a46437f5-1a22-436b-9b6e-d6033fc013ad

When it comes to not being able to reproduce on iPhone 15, on my end without my changes I can reproduce the issue on iphone 15 as the video below shows 


https://github.com/Expensify/App/assets/74202751/cdd46378-10ba-4202-9ecd-d74fd8211ebb

When it comes to the physical iPhone 13 mini, unfortunately I don't have access to a physical iPhone, I tested on imulated 13 mini with iOS 17 and I couldn't see blinking, all I could see is that without my changes, the original issue happened and with my changes it behaved fine as I will show in two recordings, one with the original main and one after the change


https://github.com/Expensify/App/assets/74202751/7ca728fd-71db-48af-9b92-2ca687457fdb

https://github.com/Expensify/App/assets/74202751/44f07285-7719-409f-8b14-d752de4adf1b

You said you get the blinking issue on your physical iPhone, do you get it in staging too or only on local builds?

**Comment by cubuspl42** [comment]
I had issues related to permissions & HTTP before, I'll try tunneling.

**Comment by AmjedNazzal** [comment]
I tried tunneling using ngrok with ngrok http --host-header=rewrite 8082 and it gave me a secure https connection to the local build so I tried it from my physical android phone and the paste now works fine, maybe that could resolve the iPhone mini issue as well

**Comment by cubuspl42** [comment]
I'm getting 429 during sign-in when I use `ngrok` or `stunel`. [I asked on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1698140153567259).

**Comment by AmjedNazzal** [comment]
@cubuspl42 what is your setup like? can you share some more information? 

What I do is configure authtoken with `ngrok config add-authtoken <token>` and just run `ngrok http --host-header=rewrite 8082` to bypass CORS kind of issues and it works

**Comment by AmjedNazzal** [comment]
@cubuspl42 any updates?

**Comment by cubuspl42** [comment]
I'll try testing with [the new HTTPS setup](https://github.com/Expensify/App/pull/28422/files) as recommended on Slack

**Comment by cubuspl42** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/2590174/d32015f6-1390-4ec2-8b44-637547be0b71

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/2590174/70ebbd19-cb79-4a1a-ad60-8a7664a1f199

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/2590174/8ace83c7-a53c-4428-b753-71a83cd1e024

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/2590174/cfff819e-9224-4305-a3e2-272db8fd0c6b

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/2590174/3b66f382-f2f2-4ee8-bb48-6552c7c45d69

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/2590174/854d3b33-31a0-45b2-8615-30d416508a9a

</details>

**Review by jakub-trzebiatowski — APPROVED** [review]

File: src/libs/Clipboard/index.js [hunk 1]
```diff
@@ -62,7 +62,7 @@ function setHTMLSync(html, text) {
 
     if (isComposer) {
         firstAnchorChild.setSelectionRange(originalSelection.start, originalSelection.end, originalSelection.direction);
-    } else {
+    } else if (originalSelection.anchorNode && originalSelection.focusNode) {
```
Comment (tgolen) [inline src/libs/Clipboard/index.js:65]: Can you please add a code comment to explain why this logic is here?

**Review by tgolen — CHANGES_REQUESTED** [review]

**Comment by AmjedNazzal** [comment]
@tgolen Done!

File: src/libs/Clipboard/index.js [hunk 2]
```diff
@@ -62,7 +62,8 @@ function setHTMLSync(html, text) {
...
+        // We are adding a check for anchorNode and focusNode to prevent null values from being passed to setBaseAndExtent as per recent changes in Safari
```
Comment (cubuspl42) [inline src/libs/Clipboard/index.js:66]: If we are to add a comment, I think we should focus on:

- why these values can become `null` in practice
- that `null` values are disallowed by this API per the standard

The fact that Safari actually started enforcing that is the least important matter and the comment might get outdated once other implementors start enforcing these `null`-checks

**Comment by AmjedNazzal** [comment]
I've added some further explanation

File: src/libs/Clipboard/index.js [hunk 3]
```diff
@@ -62,7 +62,9 @@ function setHTMLSync(html, text) {
 
     if (isComposer) {
         firstAnchorChild.setSelectionRange(originalSelection.start, originalSelection.end, originalSelection.direction);
-    } else {
+    } else if (originalSelection.anchorNode && originalSelection.focusNode) {
+        // When copying to clipboard here, since there will be no user selection the original values of anchorNode and focusNode will be null
```
Comment (cubuspl42) [inline src/libs/Clipboard/index.js:66]: @AmjedNazzal Thanks for the update! Unfortunately, we have a language issue here I think. I'm not sure what whs the intention here. This can be probably improved easily; I use ChatGPT for things like this

**Comment by AmjedNazzal** [comment]
@cubuspl42 is it better now?

**Comment by cubuspl42** [comment]
@AmjedNazzal Yes, thank you

**Review by tgolen — APPROVED** [review]
Looks really good, thanks for that comment 👍
