### PR TITLE
[No QA] Fix scroll issue

### LINKED ISSUE #1988: [Chat] [IOU] Create IOUConfirm step
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Upwork Posting**: https://www.upwork.com/jobs/~01744b3390e36e5f36

This issue builds on top of the existing IOU Modal, which was implemented [in this PR](https://github.com/Expensify/Expensify.cash/pull/1561). The `IOU Confirm` step page has already [been created](https://github.com/Expensify/Expensify.cash/blob/master/src/pages/iou/steps/IOUConfirmPage.js) and is a controlled component ([IOUModal](https://github.com/Expensify/Expensify.cash/blob/fa6185b2c51fdc0f28ab9cbc48b8a306f64a537d/src/pages/iou/IOUModal.js#L194-L198) manages its state).

The Confirm step allows users to confirm the 'request money' (1:1) or 'bill split'(multiple participants) amount and the participants they are requesting payment from. To open the Modal, you can navigate to `localhost:8080/iou/request` AND `localhost:8080/iou/split`.

You can also launch the IOUModal by temporarily modifying the routes in CreateMenu. Launch the request money flow with `Navigation.navigate(ROUTES.IOU_REQUEST)` and the bill split flow with `Navigation.navigate(ROUTES.IOU_BILL)`

**Mobile & mobile web**
Confirm Confirm Split

**Web & Desktop**
FAB Open

**Deliverables:**

1. The title should match the title from the Participants step (step 2). This will be 'Split' or 'Request', followed by the amount. (for example: 'Split $42.00' || Request $42.00)
2. If the IOU flow is for a bill split, then we should display the current user under the 'WHO PAID?' title (this is not shown for the request money flow)
3. We then need to display all participants other than the current user. With the amount that they will need to pay (total amount, split **equally** between amount of participants)
    1. If 'Bill split' flow, then we should reuse the list from the [IOUParticipantsSplit](https://github.com/Expensify/Expensify.cash/blob/fa6185b2c51fdc0f28ab9cbc48b8a306f64a537d/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js) page
    2. If 'Request money' flow, then we simply display a single user under the 'To' heading
4. An input field should allow the user to input an optional comment for the IOU request
5. The button label should read 'Request $[currency][amount]' or 'Split bill' if there are multiple participants
6. A new API function should be created within `API.js`: `createIOUTransaction`, which will be called from IOUModal to create the IOU (details for this request can be found below).
7. When the user hits this button, we should pass the comment input string up to IOUModal via the existing `onStepComplete` callback (or something similar), and we should then call the new `createIOUTransaction` API function from within a new [IOUAction](https://github.com/Expensify/Expensify.cash/blob/fa6185b2c51fdc0f28ab9cbc48b8a306f64a537d/src/libs/actions/IOU.js) function.
    1. We should show a loading indicator in the button (using [ButtonWithLoader](https://github.com/Expensify/Expensify.cash/blob/fa6185b2c51fdc0f28ab9cbc48b8a306f64a537d/src/components/ButtonWithLoader.js)), by setting the Onyx IOU key to `IOU: {loading:true}`. We should display a loading indicator in the Button while this is true.
    2. Within this new IOUAction function we should await a successful response to `createIOUTransaction`, and then pass the returned `reportID` value to `GetIOUReport`, to retrieve the full IOUReport details
    3. Then, we should persist the simplified version of these details to Onyx, just like we [are doing here](https://github.com/Expensify/Expensify.cash/blob/d8b9eb500332bf555a4b31f64c5ee26f054c789e/src/libs/actions/Report.js#L250-L251)
8. Finally, back in IOUModal we should subscribe to the `reportIOU_` Onyx key. Once we notice that the new IOU data has been persisted to Onyx (when we persist the data in step 7, we should receive this in our Onyx subscription). Once this value is not null, we know that the report has successfully been created and persisted to Onyx, so we can close the IOU Modal.

**CreateIOUTransaction API**
Example of the API which is used to create the IOU request / split.
```
curl --request POST \
  --url 'https://expensify-jules.ngrok.io/api?command=CreateIOUTransaction' \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --cookie 'email=jules%252B3%2540expensify.com; accountID=12; authToken=66ADF90...22AE918' \
  --form debtorEmail=admin2@verified.com \
  --form currency=USD \
  --form 'comment=Pizza 🍕' \
  --form amount=550
```

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/157782

### PR DESCRIPTION
**Pull request by barun1997**
<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

### Details
Initially, I solved the problem of the input boxes not lining up using flexGrow0 but that prompted the list to not grow. 

So, I worked on a solution to instead give the OptionsList a maxHeight, so that anything beyond that would be scrollable. 

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes #1988

### Tests
1. Make these changes locally: https://github.com/Expensify/Expensify.cash/compare/jules-showIOUMenuOptions?expand=1
2. Go to IOUSplit page and continue until you reach IOUConfirm
3. Verify if all the rows and comments are shown.
4. Add multiple participants (till the screen is filled)
5. Verify you can scroll through the list

### QA Steps
Please ping @Julesssss to run the QA steps, as this is not yet possible for external QA

### Tested On

- [x] Web
- [x] Mobile Web
- [x] iOS
- [x] Android

#### Web

Screenshot 2021-04-28 at 11 28 55

Screenshot 2021-04-28 at 11 29 12

#### Mobile Web

Screenshot 2021-04-28 at 11 30 18

#### iOS
viber_image_2021-04-28_11-02-13

viber_image_2021-04-28_11-02-11

Screenshot 2021-04-28 at 11 30 18

### CODE REVIEW

**Comment by barun1997** [comment]
cc @Julesssss

File: src/components/IOUConfirmationList.js [hunk 1]
```diff
@@ -80,6 +85,11 @@ const defaultProps = {
 };
 
 class IOUConfirmationList extends Component {
+    constructor(props) {
+        super(props);
+        this.minimumBottomOffset = 240;
```
Comment (Julesssss) [inline src/components/IOUConfirmationList.js:90]: Does 240 represent the size of the button area? I think this will change in the future, so would we need to make this dynamic in that case?

Also, I don't think it needs to be attached to IOUConfirmationList. Could you make this a constant please?

Comment (barun1997) [reply src/components/IOUConfirmationList.js:90]: It was based on hit and trial to accommodate the button as well as the comment box. Will include it in CONST.js then! :)

Comment (barun1997) [reply src/components/IOUConfirmationList.js:90]: But, isn't it more appropriate in IOUConfirmationList itself, considering it includes both the Button and Comment Box, which is only present in IOUConfirmationList right now? @Julesssss

Comment (Julesssss) [reply src/components/IOUConfirmationList.js:90]: I mean more that it doesn't need to be a class prop. A const within this file would be fine too I think.

Comment (barun1997) [reply src/components/IOUConfirmationList.js]: @Julesssss Ahh makes sense! Made the change :)

**Review by Jag96 — CHANGES_REQUESTED** [review]
@barun1997 can you please add manual tests so that the PR reviewers and QA can verify the fix? For example, it isn't clear how to get to the split screen

**Comment by barun1997** [comment]
@Jag96  It's there now :)

**Comment by Julesssss** [comment]
I've added a note for QA Steps, as it's not yet possible for QA to launch the IOU flow for non-web platforms. I'll do this testing myself.

File: src/components/IOUConfirmationList.js [hunk 2]
```diff
@@ -79,6 +84,8 @@ const defaultProps = {
     comment: '',
 };
 
+const MINIMUM_BOTTOM_OFFSET = 240;
```
Comment (Julesssss) [inline src/components/IOUConfirmationList.js:87]: One last request, could you add a comment above this const explaining why it needs to be 240. Thanks

Comment (barun1997) [reply src/components/IOUConfirmationList.js:90]: @Julesssss Done!

Comment (Julesssss) [reply src/components/IOUConfirmationList.js:90]: This is a really small thing, but could you make it two lines instead? 😀

Comment (barun1997) [reply src/components/IOUConfirmationList.js:89]: @Julesssss Haha done! I got a little overboard with the explanation. By any chance, did you find time to test the implementation itself as well?

Comment (Julesssss) [reply src/components/IOUConfirmationList.js:89]: Just tested, leaving another note elsewhere

**Review by Julesssss — CHANGES_REQUESTED** [review]
Just realized that the comment Component is covered by the button at some heights, any idea how to prevent this? 

Screenshot 2021-04-29 at 15 31 08

**Comment by barun1997** [comment]
@Julesssss I'll look for a solution. Not sure why it went below like that, is it on the Mobile web?

**Comment by barun1997** [comment]
@Julesssss I just found out it's only that when the user dynamically changes screen height. If you reload on the same height, the screen adapts. Will this be a blocker?

**Comment by barun1997** [comment]
Here's a video to explain it better: 

https://user-images.githubusercontent.com/19339044/116569959-95fbea00-a929-11eb-8c31-be38f7c8ee6c.mov

**Comment by Julesssss** [comment]
> @Julesssss I just found out it's only that when the user dynamically changes screen height. If you reload on the same height, the screen adapts. Will this be a blocker?

Oh, that's a good point. I guess it probably shouldn't be a blocker in that case, but ideally, it would adapt dynamically after changing the screen hieght.

**Comment by barun1997** [comment]
> > @Julesssss I just found out it's only that when the user dynamically changes screen height. If you reload on the same height, the screen adapts. Will this be a blocker?
> 
> Oh, that's a good point. I guess it probably shouldn't be a blocker in that case, but ideally, it would adapt dynamically after changing the screen height.

Sounds great! I did look into the solutions, haven’t found an elegant solution yet. Majority of the solutions use a listener of some sort to see if the dimensions changed. But since dimensions changing isn’t something that would normally happen with a user, I feel it’d be too over-engineered.

**Review by Jag96 — DISMISSED** [review]
This LGTM, I agree that the dimension resizing would be nice but isn't a blocker in this case. Will defer to @Julesssss for the final say on this.

File: src/components/IOUConfirmationList.js [hunk 3]
```diff
@@ -201,7 +210,12 @@ class IOUConfirmationList extends Component {
             <View style={[styles.flex1, styles.w100, styles.justifyContentBetween]}>
                 <View style={[styles.flex1]}>
                     <OptionsList
-                        listContainerStyles={[styles.flexGrow0]}
+                        listContainerStyles={[{
+                            // Give max height to the list container so that it does not extend
+                            // beyond the comment view as well as button
+                            maxHeight: Dimensions.get('window').height - MINIMUM_BOTTOM_OFFSET
```
Comment (Jag96) [inline src/components/IOUConfirmationList.js:216]: Any reason to use `Dimensions.get` here instead of updating this component to use `withWindowDimensions`?

Comment (barun1997) [reply src/components/IOUConfirmationList.js]: Didn't realise we had `withWindowDimensions`. Made the change now!

**Review by Julesssss — APPROVED** [review]
Looks good to me 👍

**Comment by Julesssss** [comment]
Ideally, we would make the whole page scroll. But that wasn't in the original requirements, so this can be done at a later date.

**Comment by cead22** [comment]
I wouldn't have known how to properly review this PR so thanks for not blocking on me. I went ahead and read the commits and the review comments to learn so I can be better prepared for the next PR
