### PR TITLE
Fix - LoginScreen use email keyboard type and disable auto complete

### LINKED ISSUE #1524: On Login screen use email keyboard type and disable auto complete
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

Platform - iOS version: v1.0.1-452

Action Performed (reproducible steps):

On Login screen when user enter the user name, 
email keyboard is not showing and auto complete is enable.

Auto correction

Expected Result:
On Login screen use email keyboard type and disable auto complete

Actual Result:
Email keyboard is not showing and auto complete is enable

Function found here.

Logs - JS/Android/iOS (if applicable): n/a
 
**Logs - JS/Android/iOS (if applicable)**:

### PR DESCRIPTION
**Pull request by dharammachra**
@marcaaron 

**I have read the CLA Document and I hereby sign the CLA**

### Details

We are using the default react native text input props autoCompleteType={"off"} and keyboardType={"email-address"}.

### Fixed Issues

Fixes #1524

### Tests

Go to the login screen and click on the enter your phone or email field, email type keyboard will open and when user type the email auto correct is disabled.

### QA Steps

1. Run the application
2. Login screen show
3. Click on the enter your phone or email field
4. Email type keyboard will show and auto correct is disabled

### Tested On

- [ ✅] Web
- [ ] Mobile Web
- [ ✅] Desktop
- [ ✅] iOS
- [ ] Android

#### Web

Web

#### Desktop

Desktop

#### iOS

iOS

### CODE REVIEW

**Review by HorusGoul — CHANGES_REQUESTED** [review]
We'll need to address some accessibility concerns that I see on the Web and Desktop platforms.

As you can see in the image, it marks it as invalid when you type a phone number (see the accessibility panel). That's because, under the hood, react-native-web uses an input with  type="email" when it receives the keyboardType="email-address" property, and in HTML5, that comes with a default validation that checks to see if the string contains the character `@`.

We could disable the html5 validation for this text field to solve this accessibility issue. Let me know what you think.

image

**Comment by marcaaron** [comment]
Nice catch @HorusGoul 

>We could disable the html5 validation for this text field to solve this accessibility issue. Let me know what you think.

Any thoughts on how we can do this?

**Comment by HorusGoul** [comment]
> Nice catch @HorusGoul
> 
> > We could disable the html5 validation for this text field to solve this accessibility issue. Let me know what you think.
> 
> Any thoughts on how we can do this?

I checked the react-native-web code to see if there's a way to set the input mode to email and use type=text but there's no way right now. https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TextInput/index.js#L140

The easiest way right now would be to not use `keyboardType` when targeting the web platform so it renders using `type="text"`. 

Like this:

```js
keyboardType={Platform.OS !== 'web' ? 'email-address' : 'default'}
```

**Comment by dharammachra** [comment]
@marcaaron  - Hi Marc, I am also think to put Platform check like @HorusGoul suggest. Please let me know I put the Platform check and commit my changes.

**Comment by marcaaron** [comment]
@HorusGoul nice, that seems reasonable to me. Just a small note that we are trying to avoid Platform usages in the code so that we are making few exceptions. There's some more guidance on how to handle this here -> https://github.com/Expensify/Expensify.cash/blob/main/README.md#platform-specific-file-extensions

@dharammachra The solution works for me, but the correct way to do it is something like a helper method

`getEmailKeyboardType()` with the following structures

```
.
└── libs/
    └── getEmailKeyboardType/
        ├── index.js        - return () => 'default'
        └── index.native.js - return () => 'email-address'
```

**Comment by dharammachra** [comment]
@marcaaron - I have committed the changes,  @HorusGoul so could you please review and merge the code.

File: src/libs/getEmailKeyboardType/index.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+
+/**
+ * * Return the defualt keyboard type when running on Web/Mobile-Web/Desktop
+ * @return {String | null}
```
Comment (HorusGoul) [inline src/libs/getEmailKeyboardType/index.js:4]: There is no need to add the `| null`; we are 100% sure about the return type. Also, Web covers Mobile-Web so that we can omit that part. And, there's a little typo in the `default` word.

```suggestion
 * Return the default keyboard type when running on Web/Desktop
 * @return {String}
```

File: src/libs/getEmailKeyboardType/index.native.js [hunk 2]
```diff
@@ -0,0 +1,8 @@
+
+/**
+ * Return the email-address keyboard type when running on native platforms.
+ * @return {String | null}
```
Comment (HorusGoul) [inline src/libs/getEmailKeyboardType/index.native.js:4]: There is no need to add the | null; we are 100% sure about the return type.

```suggestion
 * @return {String}
```

**Review by HorusGoul — CHANGES_REQUESTED** [review]
Please fix these minor issues with the code, and then we'll merge this. 

Thank you! 😄

File: src/libs/getEmailKeyboardType/index.js (hunk 1 above)
Comment (dharammachra) [reply src/libs/getEmailKeyboardType/index.js]: @HorusGoul  - I have committed the code review changes.

File: src/libs/getEmailKeyboardType/index.js [hunk 3]
```diff
@@ -0,0 +1,8 @@
+
+/**
+ * * Return the default keyboard type when running on Web/Desktop
```
Comment (HorusGoul) [inline src/libs/getEmailKeyboardType/index.js:3]: There's still a leading `*` that shouldn't be there:

```suggestion
 * Return the default keyboard type when running on Web/Desktop
```

**Review by HorusGoul — CHANGES_REQUESTED** [review]

File: src/libs/getEmailKeyboardType/index.js (hunk 3 above)
Comment (dharammachra) [reply src/libs/getEmailKeyboardType/index.js]: @HorusGoul  - Done

**Comment by dharammachra** [comment]
@HorusGoul  - I fixed the lint errors and committed the code.

**Review by HorusGoul — APPROVED** [review]

**Comment by marcaaron** [comment]
I believe this PR has caused a regression as I'm unable to run Android. I also see that we skipped testing for a couple of platforms (one of them Android). Please ensure all PRs are tested against all platforms. Thanks!

**Comment by marcaaron** [comment]
Gonna revert this so that Android is usable again.

**Comment by dharammachra** [comment]
@marcaaron @kadiealexander - Hi Marc, I have fixed the Android auto correct issue and committed the changes. Please find the attched screen shot. So could you please let me know the next step.
Android

**Comment by kadiealexander** [comment]
@HorusGoul  Hey mate! Since Marc's on leave, would you mind reviewing this PR?

**Comment by HorusGoul** [comment]
@kadiealexander Sure!

---

Hey @dharammachra, you'll need to open a new PR with all the changes so we can review it again.
