### PR TITLE
fixed modal animations

### LINKED ISSUE #2335: Modal animation is inconsistent
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
  The following things need to be fixed:
  1. Search page Animations.
  2. New Group page Animations.
  3. New Chat Page Animations.
  4. Settings Page Animations.
  5. IOU Modal Page Animations.
  
## Expected Result:
 Animations for all the models & EMOJI Picker should be smooth.

## Actual Result:
 When we close RightSiderbarModal (All the Pages mentioned above), it quickly closes but the opening animation is very smooth. Sometimes, Modals are open suddenly without animation.

## Action Performed:
1. Click search which opens the search modal and notices the Opening animation.
2. Now close the modal, Modal closes quickly.

## Workaround:
Does not affect functionality.

## Platform:

 Web - :heavy_check_mark: 
 iOS - :heavy_check_mark: 
 Android - :heavy_check_mark: 
 Desktop App - :heavy_check_mark: 
 Mobile Web - :heavy_check_mark: 

**Version Number:** Latest
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/24370807/114252237-d10d9c00-99c1-11eb-872f-adfe42a34751.mp4

#### Other Video

https://expensify.slack.com/files/U01J5Q81BRP/F01SZK4SMGT/5e8bd204-81ec-4646-8d02-948b7b8048e3.webm

**Expensify/Expensify Issue URL:**

### PR DESCRIPTION
**Pull request by parasharrajat**
Please review.

### Details
Details can be read https://github.com/Expensify/Expensify.cash/issues/2335#issuecomment-820618607

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes #2335 

### Tests / QA Steps
1. Click the search icon to open the Search Modal.
2. Open all the available models from the FAB button.
3. Open the User Details / Group participants modal.
4. Open the User Settings Modal.
5. **For all the modals enter and exit animation should be smooth and consistent.**

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
   

https://user-images.githubusercontent.com/24370807/117487785-29b46280-af89-11eb-9cd5-48aa160493e8.mp4

 

#### Mobile Web

https://user-images.githubusercontent.com/24370807/116024431-cf073680-a66b-11eb-93c0-a452dbd8fdff.mp4

#### Desktop

https://user-images.githubusercontent.com/24370807/116080015-2af6ad00-a6b6-11eb-9960-4e2fef0b2232.mp4

#### iOS

 Not able to record it as I have MAC VM but the animation on IOS works smoothly.
#### Android

https://user-images.githubusercontent.com/24370807/117493077-1c4ea680-af90-11eb-94eb-4000638bf4c6.mp4

### CODE REVIEW

**Comment by MariaHCD** [comment]
Requesting reviews from those who reviewed the original PR as they will have additional context!

**Comment by parasharrajat** [comment]
I have excluded the changes for the Emoji Picker as my changes caused a regression and i think its better to work on Emoji Picker separately as there couple of things that need to be fixed on it.


@marcaaron Initially I was suggesting to update the `react-native-modal` to latest minor as they have made few tweaks such as settings Interactions before animations but it won't be helpful on the web as `InteractionManager` does not work there.

So sticking to navigation event is fine. but the lib could be updated as there are no breaking changes.

**Comment by marcaaron** [comment]
@parasharrajat can we maybe figure out how to apply this solution to the IOU pages? The animations there are still inconsistent.

https://user-images.githubusercontent.com/32969087/117064498-fab89b00-acc1-11eb-998b-6f699827edba.mp4

Also, note there is still some lag when opening the search, new chat, new group pages. Which is probably something in addition to waiting for the text input. Could we maybe wait until the transition is done to do some extra work being done on those pages?

I'm also curious if we can incorporate this into the `ScreenWrapper` component so the logic is not repeated many times. Here's what I'm thinking...

1. Add the `this.props.navigation.addListener` logic to `ScreenWrapper` and inside set up the logic if we have passed an `onTransitionEnd` prop
2. Next figure out which expensive things interfere with the layout transition in each screen and perform that logic after the `onTransitionEnd` callback is done.

Lmk if that makes sense? I think it will give us a more sustainable way to handle similar issues in the future.

File: src/components/OptionsSelector.js [hunk 1]
```diff
@@ -87,7 +95,13 @@ class OptionsSelector extends Component {
...
 
     componentDidMount() {
-        this.textInput.focus();
+        this.unsubscribeTransitionEnd = this.props.navigation.addListener('transitionEnd', () => {
+            this.textInput.focus();
+        });
+    }
+
+    componentWillUnmount() {
+        this.unsubscribeTransitionEnd();
```
Comment (marcaaron) [inline src/components/OptionsSelector.js:104]: I could be wrong, but I thought this could be more useful in the `ScreenWrapper` and then we just pass a prop like `isScreenTransitioning`. Maybe it would be more complicated. Perhaps the same could be done with an HOC so we don't need to drill something like an `isScreenTransitioning` prop down.

Comment (marcaaron) [reply src/components/OptionsSelector.js:104]: Of course, it depends on if there are other places where we'll need to do this. I think there already are..

**Comment by parasharrajat** [comment]
@marcaaron I noticed  the same In our case rendering the optionList is very expensive. I would try to see what can be done to minimize the load.

And good Idea in moving the logic to ScreenWraper.

File: src/components/OptionsSelector.js (hunk 1 above)
Comment (jasperhuangg) [reply src/components/OptionsSelector.js:104]: +1, this looks like something that'll be needed down the road

**Review by jasperhuangg — COMMENTED** [review]
I wonder about creating a HOC for `isScreenTransitioning`, seems like a good idea and I'd like to get your thoughts

**Comment by parasharrajat** [comment]
As marc mentioned that we can just move this logic up to ScreenWrapper which is already used in all screens thus this hook would be unnecessary at times.

**Comment by parasharrajat** [comment]
So I profiled the pages and found that the fps is pretty low for the app. We have a lot of long tasks and some microtasks take a long time to finish. I was not really able to pinpoint that to the source in our app as performance tools are not pointing it correctly on chrome but efforts are still continued on it.

Few things I noticed.
1. OptionSelector component's first render is too expensive. if we delay its render until the SearchPage animation has complete, the animation is smooth.
2. React-navigation 's navigation to any screen is very expensive on the web. When we click on the Search Icon it takes an enormous(blocking the thread) 200ms to naviagte. On Native, it performs well due to `react-native-screens`.
3. I also noticed that React native's `Image` module uses [JS](https://github.com/necolas/react-native-web/blob/c9eb79479048db0a0b8eb664a4d0e1d7a2de09dd/packages/react-native-web/src/exports/Image/index.js#L174) to download images that were seen consuming the thread while the search page was opening.
4. This punch in a question, Are we allowing the browser to reuse the cache for the same images? I think we pass a new hash in the URL for each instance of an image.

**Any help in how can I correctly pinpoint the source code while profiling will be great. Browser points to the low lever lib code instead.**

**Comment by marcaaron** [comment]
>OptionSelector component's first render is too expensive. if we delay its render until the SearchPage animation has complete, the animation is smooth.

Nice! That might be a good place to start as it is easy to delay the rendering and replace with a loading spinner.

>React-navigation 's navigation to any screen is very expensive on the web. When we click on the Search Icon it takes an enormous(blocking the thread) 200ms to naviagte

Not sure how to get around this one. Maybe a [custom animation for the drawer content](https://reactnavigation.org/docs/drawer-navigator/#providing-a-custom-drawercontent). It seems like an issue that [has been reported before](https://github.com/react-navigation/react-navigation/issues/9033).

>Are we allowing the browser to reuse the cache for the same images? I think we pass a new hash in the URL for each instance of an image.

We _should_ be. At least for avatars, once they load they are not loaded again.

https://user-images.githubusercontent.com/32969087/117339347-58bcbe00-ae3b-11eb-8ffd-879074d755f6.mp4

**Comment by parasharrajat** [comment]
@marcaaron  Just found some evidence of Onyx blocking the thread. So I think the changes you suggested a while back about reusing the subscription and just emitting data from the memory if there are existing subscribers for the key, will work great here. https://expensify.slack.com/archives/C01GTK53T8Q/p1620065578311900.


https://user-images.githubusercontent.com/24370807/117448109-f3acb980-af5b-11eb-842f-1053770e2894.mp4

**Comment by marcaaron** [comment]
@parasharrajat Got it, I think we can wait for Kid Roca to work on that issue in the Slack thread.

>Using Multiget instead of one key at a time then dispatching all changes at once(calling setState once on the onyx instance 

This would require a refactor of Onyx, but agree it could be nice. I think it's not in scope for this issue.

The changes here are looking great! So I think we can roll with what we have and then propose additional improvements later?

File: src/components/ScreenWrapper.js [hunk 2]
```diff
@@ -46,14 +53,19 @@ class ScreenWrapper extends React.Component {
...
+            this.props.onTransitionEnd();
+        });
     }
 
     componentWillUnmount() {
-        if (!this.unsubscribe) {
-            return;
+        if (this.unsubscribe) {
+            this.unsubscribe();
+        }
```
Comment (marcaaron) [inline src/components/ScreenWrapper.js:65]: I know you didn't add this one (it was me!) but since we are adding a new listener can we maybe make the name for this more specific e.g. 

```js
this.unsubscribeEscapeKey();
```

File: src/libs/Navigation/AppNavigator/AuthScreens.js [hunk 3]
```diff
@@ -71,7 +71,7 @@ const RootStack = createCustomModalStackNavigator();
 // When modal screen gets focused, update modal visibility in Onyx
```
Comment (marcaaron) [inline src/libs/Navigation/AppNavigator/AuthScreens.js:71]: This comment is out of date now and we could add some more context about why we are waiting until the transition ends.

Separately, is there any reason to do this? `focus` and `transitionEnd` events should be reasonably the same when it comes to setting the "modal is visible" flag. Or did you see some reason why it doesn't work?

File: src/libs/Navigation/AppNavigator/AuthScreens.js [hunk 4]
```diff
@@ -159,7 +159,7 @@ class AuthScreens extends React.Component {
         const modalScreenOptions = {
             headerShown: false,
             cardStyle: getNavigationModalCardStyle(this.props.isSmallScreenWidth),
-            cardStyleInterpolator: modalCardStyleInterpolator,
+            cardStyleInterpolator: (...props) => modalCardStyleInterpolator(this.props.isSmallScreenWidth, ...props),
```
Comment (marcaaron) [inline src/libs/Navigation/AppNavigator/AuthScreens.js:162]: Why `(...props)`? it looks like there is only one object argument passed to `cardStyleInterpolator`?

Comment (marcaaron) [inline src/libs/Navigation/AppNavigator/AuthScreens.js:162]:
```suggestion
            cardStyleInterpolator: (props) => modalCardStyleInterpolator(this.props.isSmallScreenWidth, props),
```

File: src/pages/NewChatPage.js [hunk 5]
```diff
@@ -48,6 +49,7 @@ class NewChatPage extends Component {
         super(props);
 
         this.createNewChat = this.createNewChat.bind(this);
+        this.activateOptionsList = this.activateOptionsList.bind(this);
```
Comment (marcaaron) [inline src/pages/NewChatPage.js:52]:
```suggestion
        this.setShouldShowOptionsSelector = this.setShouldShowOptionsSelector.bind(this);
```

File: src/pages/NewChatPage.js [hunk 6]
```diff
@@ -112,12 +119,14 @@ class NewChatPage extends Component {
...
-            <ScreenWrapper>
+            <ScreenWrapper onTransitionEnd={this.activateOptionsList}>
                 <HeaderWithCloseButton
                     title="New Chat"
                     onCloseButtonPress={() => Navigation.dismissModal(true)}
                 />
-                <View style={[styles.flex1, styles.w100]}>
+                <View style={[styles.flex1, styles.w100, styles.pRelative]}>
+                    <FullScreenLoadingIndicator visible={!this.state.isReady} />
+                    {this.state.isReady && (
```
Comment (marcaaron) [inline src/pages/NewChatPage.js:129]:
```suggestion
                    {this.state.shouldShowOptionsSelector && (
```

**Review by marcaaron — CHANGES_REQUESTED** [review]
Looks good had a few suggestions.

File: src/libs/Navigation/AppNavigator/AuthScreens.js (hunk 3 above)
Comment (parasharrajat) [reply src/libs/Navigation/AppNavigator/AuthScreens.js:71]: Just to delay the Chain effect until the transition is over. `Focus` is fired earlier than the `transitionEnd` which trigger rerender for few components like `ReportActionCompose`.

File: src/libs/Navigation/AppNavigator/AuthScreens.js (hunk 4 above)
Comment (parasharrajat) [reply src/libs/Navigation/AppNavigator/AuthScreens.js:162]: ok. Will update.

File: src/pages/NewGroupPage.js [hunk 7]
```diff
@@ -51,6 +52,7 @@ class NewGroupPage extends Component {
 
         this.toggleOption = this.toggleOption.bind(this);
         this.createGroup = this.createGroup.bind(this);
+        this.activateOptionsList = this.activateOptionsList.bind(this);
```
[the remark this answers is not in the document]
Comment (parasharrajat) [reply src/pages/NewGroupPage.js:55]: Hmm. let me try that.

**Comment by parasharrajat** [comment]
@marcaaron Updated.

**Review by marcaaron — DISMISSED** [review]
Looks great and works great.

**Review by jasperhuangg — DISMISSED** [review]
tested locally and works, nice! Don't forget to resolve the merge conflicts.

**Comment by parasharrajat** [comment]
@jasperhuangg Updated.

**Review by marcaaron — APPROVED** [review]

**Comment by roryabraham** [comment]
This PR may have caused [a regression](https://github.com/Expensify/Expensify.cash/issues/2825). The weird thing is it's very inconsistent: sometimes the `transitionEnd` event handler is executed, and sometimes it's not. I have not been able to find a pattern.

**Comment by roryabraham** [comment]
On the [revert branch](https://github.com/Expensify/Expensify.cash/pull/2833) I am unable to reproduce the [regression](https://github.com/Expensify/Expensify.cash/issues/2825), so I think we should revert this PR and try again.

**Comment by parasharrajat** [comment]
Thanks. I was going to point that in the slack. It seems that `transitionEnd` is not reliable on IOS. We have to find another alternative to it. Damn.

**Comment by MitchExpensify** [comment]
Paying now! Apologies for the delay @parasharrajat, nice job!

**Comment by parasharrajat** [comment]
Wait we have revert the PR. New PR is in WIP. @MitchExpensify

**Comment by MitchExpensify** [comment]
My mistake. Can you point me to the new PR or does that exist yet?

**Comment by parasharrajat** [comment]
Here it is https://github.com/Expensify/Expensify.cash/pull/2956. We faced one regression on IOS for which there is no strong reason why it is happening on IOS but let me just ask Marc what does he think about it?

**Comment by MitchExpensify** [comment]
Awesome, thanks. I'll keep an eye on that and end the contract once its merged and no issues after 7 days.
