### PR TITLE
send button bug resolved

### LINKED ISSUE #983: 'Send' button incorrect color when no text is entered into the message field
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

View the job on Upwork [here](https://www.upwork.com/jobs/~01bed4c451e8bdd92e)

**Platform - version:**  

All platforms + versions

**Action Performed (reproducible steps):**

Open app, enter text and clear text, observing the 'send' button.

**Expected Result:**

Button should be grey when no text is entered.

**Actual Result:**

Button is green when no text has been entered.

**Notes/Photos/Videos:** 

Expected:

image

Actual:

image

 
**Logs - JS/Android/iOS (if applicable)**:

### PR DESCRIPTION
**Pull request by shanky97**
### Details
There was a bug in the cross-platform React Native application on all platforms (web, iOS, Android, desktop) where the send button is the same color with and without text input.

Without text input, we need this to be grey. When there is text in text input, this needs to turn to green.

Reproduction steps:
1. Open the app and login
2. Observe the 'Send' button without any text input and notice it is green
3. Add text and notice that it does not change color
4. Remove all of the text and observe that it remains green

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/983

### Tests
Test 1
1. Open the app and log in
2. Observe the 'Send' button without any text input and notice it is gray
3. Add text and notice that now it does change color (Previously it was not)
4. Remove all of the text and observe that it again becomes gray (previously it was green)

Test 2
1. Open the app and log in
2. Observe the 'Send' button without any text input and notice it is gray
3. Add text and notice that now it does change color (Previously it was not)
4. Before clicking on the Send button, open up another Chat Thread and type some text into that Thread.
5. Again comes back to the original Thread, Sees that We have Send Button in Green.

### Screenshots
Attaching a Video For Showing the Fix
https://user-images.githubusercontent.com/35005181/103121447-2be4e700-46a2-11eb-81fe-96731d1e6812.mov

### CODE REVIEW

**Comment by shanky97** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by timszot** [comment]
@shanky97 I see reference to images being attached, but I'm not seeing them. Also, can you please add `Fixes <insert_issue_url>` into the main comment to link this PR to the issue?

**Review by marcaaron — CHANGES_REQUESTED** [review]
Great start! I just have a few notes on style and one thing to point out. 
Thanks for the help with this!

If you investigate this section of the code you'll see that a comment can also be "saved" and set again when navigating away from the chat without sending that comment.

https://github.com/Expensify/Expensify.cash/blob/437d3894f7873e63e1fd81f1b321308c38844d89/src/pages/home/report/ReportActionCompose.js#L52-L58

So, in this case we will also want to "measure" the comment so that the button displays with the correct state when set from a stored value.

**Comment by marcaaron** [comment]
Example of incorrect behavior here:

https://user-images.githubusercontent.com/32969087/103040977-2019e900-4519-11eb-9f9d-2c137742ecbc.mp4

**Comment by shanky97** [comment]
> @shanky97 I see reference to images being attached, but I'm not seeing them. Also, can you please add `Fixes <insert_issue_url>` into the main comment to link this PR to the issue?
> 
> Edit: Can you please re-write the original post to use this template:
> 
> ```
> <If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>
> 
> ### Details
> <Explanation of the change or anything fishy that is going on>
> 
> ### Fixed Issues
> <Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
> Fixes GH_LINK
> 
> ### Tests
> 
> 
> ### Screenshots
> <Add any necessary screenshots for all platforms if your change added or updated UI>
> ```

@timszot please check the updated changes I have edited the original post as described by you please let me know if any other changes you want me to do.

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -207,9 +210,10 @@ class ReportActionCompose extends React.Component {
                         )}
                     </AttachmentModal>
                     <TouchableOpacity
-                        style={[styles.chatItemSubmitButton, styles.buttonSuccess]}
+                        style={[styles.chatItemSubmitButton, this.state.enableSend ? styles.buttonSuccess : styles.buttonDisable]}
```
[the remark this answers is not in the document]
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: Done please find it in the latest commit.

File: src/styles/styles.js [hunk 2]
```diff
@@ -266,6 +266,11 @@ const styles = {
         borderWidth: 0,
     },
 
+    buttonDisable: {
+        backgroundColor: themeColors.textMutedReversed,
+        borderWidth: 0,
+    },
```
[the remark this answers is not in the document]
Comment (shanky97) [reply src/styles/styles.js:272]: @marcaaron and @shawnborton, guys whatever the case here, if you guys require anything from me just let me know I'll do the required changes as per your suggestion.

File: src/pages/home/report/ReportActionCompose.js [hunk 3]
```diff
@@ -90,6 +91,8 @@ class ReportActionCompose extends React.Component {
      * @param {String} newComment
      */
     updateComment(newComment) {
+        // Change enableSend state according to the comment provided
+        this.setState({enableSend: !!newComment.length});
```
[the remark this answers is not in the document]
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: I have dropped the state approach and instead I'm using this.props.comment to handle the issue.

**Comment by shanky97** [comment]
> Example of incorrect behavior here:
> 
>  2020-12-23_12-18-49.mp4

@marcaaron Thanks for raising this, I have resolved this issue as well please find it in the latest commit I am also attaching the video link here for your reference.
https://user-images.githubusercontent.com/35005181/103121447-2be4e700-46a2-11eb-81fe-96731d1e6812.mov

**Comment by shanky97** [comment]
@marcaaron  I have made the changes as per your Comments, Please do let me know if any other changes you want from my side. Changes are in the latest commit.

File: src/pages/home/report/ReportActionCompose.js [hunk 4]
```diff
@@ -207,9 +207,11 @@ class ReportActionCompose extends React.Component {
                         )}
                     </AttachmentModal>
                     <TouchableOpacity
-                        style={[styles.chatItemSubmitButton, styles.buttonSuccess]}
+                        style={[styles.chatItemSubmitButton,
+                            this.props.comment ? styles.buttonSuccess : styles.buttonDisable]}
                         onPress={this.submitForm}
                         underlayColor={themeColors.componentBG}
+                        disabled={this.props.comment.length === 0}
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:214]: Using `this.props.comment` does create the intended behavior for both situations. But I think you were on a better path before as `this.props.comment` is updating after a delay. The initial color change of the button was **faster** before. By returning to the original solution and setting state in `componentDidUpdate()` you can solve this problem.

**Review by marcaaron — CHANGES_REQUESTED** [review]

File: src/pages/home/report/ReportActionCompose.js (hunk 4 above)
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: @marcaaron Thanks for this, and i have changed the code with  `this.State` Approach, to fix the delay issue. Please find it in the latest commit, And do let me know if there is anything else you want me to do, waiting for your feedbacks.

File: src/pages/home/report/ReportActionCompose.js [hunk 5]
```diff
@@ -207,9 +211,12 @@ class ReportActionCompose extends React.Component {
                         )}
                     </AttachmentModal>
                     <TouchableOpacity
-                        style={[styles.chatItemSubmitButton, styles.buttonSuccess]}
+                        style={[styles.chatItemSubmitButton,
+                            (this.state.isCommentEmpty || this.props.comment)
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:215]: We should be checking for `!this.state.isCommentEmpty` here. Also there is probably no need to check `this.props.comment` as well if we initialize the state value from `props`.

**Review by marcaaron — CHANGES_REQUESTED** [review]

File: src/pages/home/report/ReportActionCompose.js [hunk 6]
```diff
@@ -44,7 +44,8 @@ class ReportActionCompose extends React.Component {
         this.comment = props.comment;
         this.state = {
             isFocused: false,
-            textInputShouldClear: false
+            textInputShouldClear: false,
+            isCommentEmpty: false
```
[the remark this answers is not in the document]
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: yes @marcaaron initialised the state with this.props.comment

File: src/pages/home/report/ReportActionCompose.js (hunk 5 above)
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: Removed this.props.comment now only check is now with the state.

File: src/pages/home/report/ReportActionCompose.js [hunk 7]
```diff
@@ -90,6 +91,9 @@ class ReportActionCompose extends React.Component {
      * @param {String} newComment
      */
     updateComment(newComment) {
+        this.setState({
+            isCommentEmpty: !!newComment
```
[the remark this answers is not in the document]
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: assigned this.props.comment to the state. So assigned newComment in the state instead of true false

File: src/pages/home/report/ReportActionCompose.js [hunk 8]
```diff
@@ -44,7 +44,8 @@ class ReportActionCompose extends React.Component {
         this.comment = props.comment;
         this.state = {
             isFocused: false,
-            textInputShouldClear: false
+            textInputShouldClear: false,
+            isCommentEmpty: this.props.comment
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:48]: This should be a boolean and we can reference `props.comment` directly here.

e.g.

```js
isCommentEmpty: props.comment.length === 0
```

File: src/pages/home/report/ReportActionCompose.js [hunk 9]
```diff
@@ -90,6 +91,9 @@ class ReportActionCompose extends React.Component {
      * @param {String} newComment
      */
     updateComment(newComment) {
+        this.setState({
+            isCommentEmpty: newComment
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:95]: This works, but we should use a boolean instead of setting the comment itself to state. See above comment for suggestion on how to do this.

File: src/pages/home/report/ReportActionCompose.js [hunk 10]
```diff
@@ -207,9 +211,12 @@ class ReportActionCompose extends React.Component {
                         )}
                     </AttachmentModal>
                     <TouchableOpacity
-                        style={[styles.chatItemSubmitButton, styles.buttonSuccess]}
+                        style={[styles.chatItemSubmitButton,
+                            this.state.isCommentEmpty.length > 0
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:215]: This should just reference `this.state.isCommentEmpty`

File: src/pages/home/report/ReportActionCompose.js [hunk 11]
```diff
@@ -207,9 +211,12 @@ class ReportActionCompose extends React.Component {
...
+                                ? styles.buttonSuccess : styles.buttonDisable]}
                         onPress={this.submitForm}
                         underlayColor={themeColors.componentBG}
+                        disabled={this.state.isCommentEmpty.length === 0}
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:219]: Same here.

File: src/styles/styles.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/styles/styles.js:272]: This is fine for now I think.

**Review by marcaaron — CHANGES_REQUESTED** [review]

File: src/pages/home/report/ReportActionCompose.js (hunk 11 above)
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: done

File: src/pages/home/report/ReportActionCompose.js (hunk 10 above)
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: done

File: src/pages/home/report/ReportActionCompose.js (hunk 9 above)
Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: done

**Comment by shanky97** [comment]
@marcaaron Is there any more feedback? , If not then can we please merge this PR. And If there is any do let me know.

File: src/styles/styles.js [hunk 12]
```diff
@@ -266,6 +266,11 @@ const styles = {
         borderWidth: 0,
     },
 
+    buttonDisable: {
+        backgroundColor: themeColors.textMutedReversed,
```
Comment (shawnborton) [inline src/styles/styles.js:270]: Can you actually create a new `themeColor` for this that uses `colors.gray2` please Perhaps name it `themeColors.buttonDisabledBG`

File: src/pages/home/report/ReportActionCompose.js [hunk 13]
```diff
@@ -44,7 +44,8 @@ class ReportActionCompose extends React.Component {
         this.comment = props.comment;
         this.state = {
             isFocused: false,
-            textInputShouldClear: false
+            textInputShouldClear: false,
+            isCommentEmpty: this.props.comment.length > 0
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:48]: An "empty comment" would have a length of `0` so this logic is backwards.

**Review by marcaaron — CHANGES_REQUESTED** [review]

File: src/pages/home/report/ReportActionCompose.js (hunk 13 above)
Comment (marcaaron) [reply src/pages/home/report/ReportActionCompose.js:48]: Please change this to 

`isCommentEmpty: props.comment.length === 0`

and then update the usages so the behavior does not change

Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: Done @marcaaron  Please check and let me know if i need to update any other changes.

Comment (marcaaron) [reply src/pages/home/report/ReportActionCompose.js]: Thanks for the change. There is an unresolved comment from @shawnborton above.

File: src/pages/home/report/ReportActionCompose.js [hunk 14]
```diff
@@ -45,6 +45,7 @@ class ReportActionCompose extends React.Component {
         this.state = {
             isFocused: false,
             textInputShouldClear: false,
+            isCommentEmpty: this.props.comment.length === 0,
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:48]: This should also be changed to `props.comment.length === 0`.

Comment (marcaaron) [reply src/pages/home/report/ReportActionCompose.js:48]: No need to reference `this` inside the `constructor` thanks.

Comment (shanky97) [reply src/pages/home/report/ReportActionCompose.js]: Done @marcaaron

File: src/styles/styles.js (hunk 12 above)
Comment (marcaaron) [reply src/styles/styles.js:114]: @shanky97

Comment (shanky97) [reply src/styles/styles.js]: @marcaaron  @shawnborton  I have updated the changes, Please check.

**Review by marcaaron — APPROVED** [review]
