### PR TITLE
[IS-1500] Fixed compose field alignment issue

### LINKED ISSUE #1500: Padding and alignment on compose field for iOS looks misaligned
**Platform - version:**  
iOS 14
iPhone X

**Action Performed (reproducible steps):**
Open expensify.cash and login. Observe the **Compose** box. The text inside of the compose box is misaligned. It is not vertically centered. 

**Expected Result:**
I would expect the text to be vertically aligned within the compose area. See below, it is sitting too low in the box. 

**Actual Result:**
image

**Notes/Photos/Videos:** 
 
**Logs - JS/Android/iOS (if applicable)**:

### PR DESCRIPTION
**Pull request by aliabbasmalik8**
### Details
Added `textInputAlignSelf` utility for `textInputCompose` style object.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/1500

### Tests
Please look at `message compose box` now text inside of the compose box is aligned.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Mobile Web
image

#### Desktop
image

#### iOS
image

#### Android
image

### CODE REVIEW

File: src/styles/utilities/textInputAlignSelf/index.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export default {
+    alignSelf: 'center',
+};
```
Comment (thienlnam) [inline src/styles/utilities/textInputAlignSelf/index.js:3]: Could you update this so that it's similar to the other styles in utilities like `whiteSpace` or `wordBreak` by wrapping it in an object like

```
export default {
    center: {
        alignSelf: 'center',
    },
};
```

**Review by thienlnam — CHANGES_REQUESTED** [review]

**Review by thienlnam — APPROVED** [review]
Thanks! Tests well

**Comment by trjExpensify** [comment]
👋 Heads up! As per the new BugZero checklist. Commenting to surface that this introduced a regression outlined [here](https://github.com/Expensify/App/issues/10202#issuecomment-1307930393).
