### PR TITLE
#2821 add up arrow to edit feature

### LINKED ISSUE #2821: When in the compose box, allow clicking the up-arrow key to edit the previous message.
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
After sending a message in e.cash, while the text box is empty, when clicking the 'up arrow' on the keyboard, to be able to edit the previous comment (similar to Slack) 

## Actual Result:
Nothing happens, must use mouse to click the edit button/icon. 

## Action Performed:
- Send any text message in e.cash.
- While text box is empty, try to click the up-arrow key to edit the message you sent
- Observe it doesn't work. 

## Platform:
 I think it's only web and desktop.. right? 
 
**Notes/Photos/Videos:** Any additional supporting documentation
 https://expensify.slack.com/archives/C01GTK53T8Q/p1620835463106700

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by dklymenk**
### Details

In addition to solution described in my original [proposal](https://github.com/Expensify/Expensify.cash/issues/2821#issuecomment-846151330), code in this PR should be faster because it doesn't loop over all messages to filter the ones where user is the author, but instead it loops over the list in reverse order and stops on the first matching result.

Please note that this feature is not present on native apps, the same way the shortcut for sending message (Enter/Return key) is not working on native apps.

### Fixed Issues

Fixes #2821

### Tests / QA Steps

Web and Desktop:
1. Open a chat where you already have at least one message sent. (Or write a message if you don't have one)
2. While message box is focused, press ArrowUp.
3. The edit box for your last message should appear.

Android and iOS:
1. Since the feature is not present on native, make sure basic chatting functionality is not broken.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/64093836/119616094-e3745580-be08-11eb-89cc-b2b08bed075e.mp4

#### Mobile Web

https://user-images.githubusercontent.com/64093836/119619902-220c0f00-be0d-11eb-9c49-c2ae99628281.mp4

#### Desktop

https://user-images.githubusercontent.com/64093836/119620696-f3daff00-be0d-11eb-8576-9146fd401c29.mov

### CODE REVIEW

**Review by roryabraham — DISMISSED** [review]
Nice, this is looking great and testing well!

**Comment by roryabraham** [comment]
All yours @thienlnam

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -222,15 +239,34 @@ class ReportActionCompose extends React.Component {
...
-     * the form when we have enter
+     * Listens for keyboard shortcuts and applies the action
      *
      * @param {Object} e
      */
-    triggerSubmitShortcut(e) {
-        if (e && e.key === 'Enter' && !e.shiftKey) {
-            e.preventDefault();
-            this.submitForm();
+    triggerShortcut(e) {
```
[the remark this answers is not in the document]
Comment (dklymenk) [reply src/pages/home/report/ReportActionCompose.js:246]: `processHotkeyActions` does sound better especially considering I used the word "action" in one of the comments.

Might be better with `triggerHotkeyActions` since function itself doesn't process hotkey actions, it instead processes all key presses and triggers the actions.

File: src/pages/home/report/ReportActionCompose.js [hunk 2]
```diff
@@ -222,15 +239,34 @@ class ReportActionCompose extends React.Component {
...
+                this.submitForm();
+            }
+
+            // Trigger the edit box for last sent message if ArrowUp is pressed
+            if (e.key === 'ArrowUp' && this.state.isCommentEmpty) {
+                e.preventDefault();
+
+                const reportActionKey = _.find(
+                    Object.keys(this.props.reportActions).reverse(),
+                    key => this.props.reportActions[key].actorEmail === this.props.session.email,
```
Comment (parasharrajat) [inline src/pages/home/report/ReportActionCompose.js:260]: Not sure if this the correct way to do it. You should sort by the `sequenceNumber`.

File: src/pages/home/report/ReportActionCompose.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (roryabraham) [reply src/pages/home/report/ReportActionCompose.js:246]: `triggerHotkeyActions` sounds good 👍

**Review by parasharrajat — CHANGES_REQUESTED** [review]

**Comment by parasharrajat** [comment]
@roryabraham I noticed one thing may be not related to this issue. We can see the edit action on IOU actions but not edit box open for them and this PR will try to follow the same when user will press the `UP Arrow`.

File: src/pages/home/report/ReportActionCompose.js (hunk 2 above)
Comment (dklymenk) [reply src/pages/home/report/ReportActionCompose.js:260]: I can see that report actions are being sorted by `sequenceNumber` here:
https://github.com/Expensify/Expensify.cash/blob/9f305176681385f2aa80f43de06fc6dffa7f0b83/src/pages/home/report/ReportActionsView.js#L243-L255

Is this a requirement, however? In my local storage for any `ReportActions_<report_id>` `sequenceNumber` always matches the key of a report action.

Comment (roryabraham) [reply src/pages/home/report/ReportActionCompose.js:260]: What do you mean? This code just loops though the `reportActions` backwards and finds the first one where the actor email is the current user.

**Comment by roryabraham** [comment]
@parasharrajat Thanks for reviewing! Good point about not filtering out IOU actions!

Check out [these lines](https://github.com/Expensify/Expensify.cash/pull/2046/files#diff-ab84993378320f81d528552bc52c215aca2f62eb7aa0036c0329a1fcde8911f6R166-R169) from the `DeleteComment` pull request. It implements a function (reused for edit comment and delete comment) call `canEdit` that determines if the user should be able to edit that action.

So what we should do is:

1. Also return false in that function if the `reportAction` is an IOU action
1. Move that function to a separate library so it can be imported and used here.

File: src/pages/home/report/ReportActionCompose.js (hunk 2 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:260]: Objects keys are not sequential. so keys' order could be discrete.

**Comment by dklymenk** [comment]
Ok, I see.

I do the check for reportActionID, that's enough to avoid editing the newly created message, but I see the need to have a separate function for that since it's such a widely used check. 

So I create a new file `src/libs/canEdit.js` with default export? Or add a function to some existing one?

Also since that PR is not merged yet, I can't really "move" the function to separate library, so i'll just add a function and won't touch the original implementation.

**Comment by parasharrajat** [comment]
I think `reportUtils.js` will be a good place to use and you can suggest that function on the Delete comment PR.

File: src/pages/home/report/ReportActionCompose.js (hunk 2 above)
Comment (dklymenk) [reply src/pages/home/report/ReportActionCompose.js:260]: All the keys in my localstorage are ordered and identical to `sequenceNumber`. If one can't trust this order, I think running `sortBy` on entire object for every action trigger would not be very efficient. It would be better to have some storage for sorted list shared with `ReportActionsView.js` in that case.

**Comment by roryabraham** [comment]
Agreed, we can just add a function to `reportUtils.js` called `canEditReportAction`, then import it and use it both in the `ReportActionContextMenu` and here in the `ReportActionCompose`

**Comment by dklymenk** [comment]
Updated the PR with change regarding the new function.

I also took the liberty of adding the `isReportMessageAttachment` call to the new `canEditReportAction` function as well.

File: src/libs/reportUtils.js [hunk 3]
```diff
@@ -35,6 +36,20 @@ function sortReportsByLastVisited(reports) {
...
+ * Check whether user can edit report action
+ *
+ * @param {Object} reportAction
+ * @param {String} sessionEmail
+ * @returns {Boolean}
+ */
+function canEditReportAction(reportAction, sessionEmail) {
+    return reportAction.actorEmail === sessionEmail
+        && reportAction.reportActionID
+        && reportAction.actionName !== 'IOU'
```
Comment (roryabraham) [inline src/libs/reportUtils.js:49]:
```suggestion
        && reportAction.actionName === 'ADDCOMMENT'
```

Also, you could optionally add a const to CONST.js called `REPORT_ACTION.ACTION_TYPES` so that we're not using a string literal here.

**Review by roryabraham — CHANGES_REQUESTED** [review]
Two other suggestions:

1. I noticed that you didn't import & use your new function in `ReportActionContextMenu` [here](https://github.com/Expensify/Expensify.cash/blob/c11594b845351a638f4782e7e2d6dc0a6772294d/src/pages/home/report/ReportActionContextMenu.js#L115-L117). Let's do that to DRY this up.
1. Instead of using `withOnyx` and passing in the `sessionEmail` as a parameter to the `canEditReportAction` function, you could instead use `Onyx.connect` directly in `reportUtils` to keep a local reference to the current user's email. That way we have one Onyx subscription to the `SESSION` key instead of 2+

**Comment by roryabraham** [comment]
[Here's an example](https://github.com/Expensify/Expensify.cash/blob/0de1e6139c6f17371ebb5eb4e27b4e7a7c350ada/src/libs/API.js#L16-L20) of what I mean by using Onyx.connect directly in the lib.

**Comment by dklymenk** [comment]
Applied your suggestions.

**Review by thienlnam — DISMISSED** [review]
Nice, this looks really good - no complaints here

File: src/CONST.js [hunk 4]
```diff
@@ -156,6 +156,12 @@ const CONST = {
         NATIVE: 'Native',
     },
 
+    REPORT_ACTION: {
```
Comment (roryabraham) [inline src/CONST.js:159]: Hey @dklymenk, I apologize because this is completely my fault for not noticing during my last review, but I just noticed that we also have a `REPORT.ACTIONS.TYPE` constant in this file, so instead of creating this new one we should just put `ADDCOMMENT` there.

**Review by roryabraham — CHANGES_REQUESTED** [review]
Also, I believe that the `session` prop is unused in `ReportActionContextMenu` now so we can get rid of it and also remove the use of `withOnyx` from that component.

This should actually be a good performance increase too because we're replacing potentially hundreds of Onyx subscribers (because there are many instances of the `ReportActionContextMenu` component) with just one 🎉

**Comment by dklymenk** [comment]
I've applied requested changes. @roryabraham, please check. Thank you.

File: src/CONST.js [hunk 5]
```diff
@@ -47,6 +47,7 @@ const CONST = {
         TYPE: {
             CHAT: 'chat',
             IOU: 'iou',
+            ADDCOMMENT: 'ADDCOMMENT',
```
Comment (roryabraham) [inline src/CONST.js:50]: You've created `REPORT.TYPE.ADDCOMMENT` here, but we want `REPORT.ACTION.TYPE.ADDCOMMENT`

**Review by roryabraham — CHANGES_REQUESTED** [review]

File: src/CONST.js (hunk 5 above)
Comment (dklymenk) [reply src/CONST.js]: sorry, fixed

**Comment by dklymenk** [comment]
Fixed 2 merge conflicts. Please make sure this change is ok with you:

https://github.com/Expensify/Expensify.cash/pull/3157/files#diff-ab84993378320f81d528552bc52c215aca2f62eb7aa0036c0329a1fcde8911f6L124-R114

File: src/libs/reportUtils.js [hunk 6]
```diff
@@ -35,6 +45,20 @@ function sortReportsByLastVisited(reports) {
...
 
+/**
+ * Check whether user can edit report action
+ *
+ * @param {Object} reportAction
+ * @param {String} sessionEmail
+ * @returns {Boolean}
+ */
+function canEditReportAction(reportAction) {
+    return reportAction.actorEmail === sessionEmail
```
Comment (roryabraham) [inline src/libs/reportUtils.js:56]: Let's add a comment in here:

```
// Can only edit if it's a ADDCOMMENT, the author is this user and it's not a optimistic response.
        // If it's an optimistic response comment it will not have a reportActionID,
        // and we should wait until it does before we show the actions
```

File: src/pages/home/report/ReportActionContextMenu.js [hunk 7]
```diff
@@ -121,10 +111,7 @@ class ReportActionContextMenu extends React.Component {
             {
                 text: this.props.translate('reportActionContextMenu.editComment'),
                 icon: Pencil,
-                shouldShow: () => (
-                    this.canEdit()
-                    && !isReportMessageAttachment(this.getActionText())
-                ),
+                shouldShow: canEditReportAction(this.props.reportAction),
```
Comment (roryabraham) [inline src/pages/home/report/ReportActionContextMenu.js:114]:
```suggestion
                shouldShow: () => canEditReportAction(this.props.reportAction),
```

**Review by roryabraham — CHANGES_REQUESTED** [review]
This was broken after your last merge. To fix it, I think you'll need to:

1. Remove the `canEdit` member function from `ReportActionContextMenu` (including from the constructor)
1. Replace it's current usage in the `shouldShow` for `deleteComment` with `() => canEditReportAction(this.props.reportAction)`

Please be careful to retest locally before each new request for review, especially if you had to resolve merge conflicts.

**Comment by dklymenk** [comment]
My bad on this one. For some reason I did not think that conflict resolution would break stuff.

Applied your suggestions. Thanks.

**Comment by roryabraham** [comment]
@dklymenk Sorry, there are more merge conflicts now 😞

**Comment by dklymenk** [comment]
@roryabraham 

Resolved the conflict. Tested. Everything should be ok.

**Review by roryabraham — APPROVED** [review]

**Comment by roryabraham** [comment]
looks good and tests well 👍

**Comment by roryabraham** [comment]
@thienlnam All yours for the merge after E2E tests are done 👍

**Comment by roryabraham** [comment]
Since Jack approved a previous version of this pull request, and I think this _might_ resolve [this deploy blocker](https://github.com/Expensify/Expensify.cash/issues/3249), I'm going to go ahead and merge this.

**Comment by isagoico** [comment]
@dklymenk We found this issue in mWeb 

## mWeb - Up arrow not enabled for edit feature

## Expected Result
The edit box for your last message should appear.

## Actual Result
Arrow up is disabled and unable to select by tapping

## Action Performed 
1. Launch the url and login
2. Open a chat where you already have at least one message sent. (Or write a message if you don't have one)
3. While message box is focused, press ArrowUp.

## Platform 

mWeb ✔️ 

**Notes/images/video**

https://user-images.githubusercontent.com/44479856/120384944-cf42c380-c2f4-11eb-8e5d-685598140102.mp4

**Comment by roryabraham** [comment]
No need to block deploys on this @isagoico, but @dklymenk let's get this fixed with a follow-up PR. You showed a video of it working, so this hopefully should be pretty simple.

**Comment by dklymenk** [comment]
@isagoico Those "arrow keys" on your video are grayed out(inactive,disabled). Tapping them doesn't provide any feedback to user nor does it send any events to browser.

Moreover, those are not actually arrow keys. A quick online search told me, that they behave more like Tab and Shit+Tab to jump between inputs on a form.
Here is a demo (note that buttons become enabled when there is an action available):

https://user-images.githubusercontent.com/64093836/120431366-0f4f8800-c381-11eb-9e5f-774cbc9c23cf.mp4

I used https://www.w3schools.com/html/tryit.asp?filename=tryhtml_form_submit, but any form with proper html should do the trick.

Now I don't have a real iPhone, and to my understanding you cannot install apps from app store on a simulator, so if you can install some third-party full 5 row keyboard from store, try with that and it won't work, I'll try to get my hands on one to fix the issue.

@roryabraham The video I showed for mobile web is from Chromium dev tools responsive mode and I pressed an Up Arrow on my actual laptop keyboard there, but to demonstrate that it actually works on real phone, I have shot a few videos: one with third-party keyboard from [F-Droid](https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/) and one with actual physical keyboard connected via usb-c dongle:

https://user-images.githubusercontent.com/64093836/120432448-9a7d4d80-c382-11eb-904d-62c7fbc6dd62.mp4



https://user-images.githubusercontent.com/64093836/120432797-15deff00-c383-11eb-9a64-d7fcad032bcb.mp4


Hopefully, this clears up the confusion and the issue can be closed again. Thanks.

**Comment by iwiznia** [comment]
I agree with @dklymenk

**Comment by roryabraham** [comment]
Thanks @dklymenk!
