### PR TITLE
Fix react navigation issues with IOUModal

### LINKED ISSUE #1769: IOUModal View Issue
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

IOUModal view does not show chat view.

## Expected Result:
Chat view should be visible when user is redirected to `/iou/request` page.

Screenshot 2021-03-14 at 19 51 59

Page header should have some margin from top.

## Actual Result:
IOU Modal view is shown on the right sidebar, but the background is solid gray instead of chat view. In addition, close button doesn't work.

Screenshot 2021-03-14 at 19 43 02

Page header is overlapping with iOS status bar and close/back buttons don't work.

## Action Performed:
1. Login to expensify cash
2. Replace http://localhost:8080/ with http://localhost:8080/iou/request

## Platform:
Where is this issue occurring?

- [X] Web
- [X] iOS
- [?]  Android
- [?] Desktop App
- [X] Mobile Web

 
**Version Number:** v1.0.2-49

### PR DESCRIPTION
**Pull request by Julesssss**
### Details

Fixes a couple of issues related to the IOUModal pages and the recent React-native-navigation implementation:
- Reverted to the onPress prop to fix the close button
- Wrapped Modal pages in `<ScreenWrapper>`, fixing the status bar margin on mobile and aligning with other Modals
- DOES NOT FIX the issue where navigating directly to `localhost/iou/request` shows a grey background, as this doesn't occur when users use the navigation routing (should investigate this later)

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/1769

### Tests

_Save the following diff as `diff.txt` and apply with `git apply diff.txt` (make sure you include the empty new line!)_
```
diff --git a/src/components/CreateMenu.js b/src/components/CreateMenu.js
index 7c7afe3a..e37c842c 100644
--- a/src/components/CreateMenu.js
+++ b/src/components/CreateMenu.js
@@ -52,13 +52,13 @@ class CreateMenu extends PureComponent {
         const menuItemData = [
             {
                 icon: ChatBubble,
-                text: 'New Chat',
-                onPress: () => this.setOnModalHide(() => Navigation.navigate(ROUTES.NEW_CHAT)),
+                text: 'New Request',
+                onPress: () => this.setOnModalHide(() => Navigation.navigate(ROUTES.IOU_REQUEST)),
             },
             {
                 icon: Users,
-                text: 'New Group',
-                onPress: () => this.setOnModalHide(() => Navigation.navigate(ROUTES.NEW_GROUP)),
+                text: 'New Split',
+                onPress: () => this.setOnModalHide(() => Navigation.navigate(ROUTES.IOU_BILL)),
             },
         ].map(item => ({
             ...item,

```

**Confirm close button now works**
- Press the + (FAB) and select Request Money OR Split Bill
- Attempt to close the modal with the X button
- Modal should close
- Reopen, click next to navigate through the steps
- Attempt to close the modal with the X button
- Modal should close

**Confirm header does not overlap the status bar**
- Press the + (FAB) and select Request Money OR Split Bill
- Confirm that the status bar is not overlapped (margin should be similar to the Profile page header)

_Example of existing problem:_
Screenshot 2021-03-15 at 12 47 10

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
ioustatusweb

#### Mobile Web
ioustatusmweb

#### Desktop
ioustatusdesktop

#### iOS
ioustatusios

#### Android
ioustatusandroid

### CODE REVIEW

File: src/pages/iou/IOURequestPage.js [hunk 1]
```diff
@@ -1,7 +1,12 @@
 import React from 'react';
+import ScreenWrapper from '../../components/ScreenWrapper';
 import IOUModal from './IOUModal';
 
 export default props => (
     // eslint-disable-next-line react/jsx-props-no-spreading
```
Comment (flodnv) [inline src/pages/iou/IOURequestPage.js:6]: seems this should go on line 8-9 now?

File: src/pages/iou/IOURequestPage.js [hunk 2]
```diff
@@ -1,7 +1,12 @@
...
-    <IOUModal {...props} />
-);
+    <ScreenWrapper>
```
Comment (flodnv) [inline src/pages/iou/IOURequestPage.js:7]: What does this do?

**Review by flodnv — COMMENTED** [review]
Just 1 clarifying question for my knowledge 😁

File: src/pages/iou/IOURequestPage.js (hunk 2 above)
Comment (Julesssss) [reply src/pages/iou/IOURequestPage.js:7]: `ScreenWrapper` is used in the Modal views to provide consistent padding and other styles. The important fix for us is that the status bar for mobile will no longer overlap the Modal header.

File: src/pages/iou/IOURequestPage.js (hunk 1 above)
Comment (Julesssss) [reply src/pages/iou/IOURequestPage.js]: Yeah, nice spot

**Comment by Julesssss** [comment]
@flodnv  Fixed JSlint and move the disabled check to line 8 👍

**Review by flodnv — APPROVED** [review]
