### PR TITLE
Quit early when persistedRequests is empty

### LINKED ISSUE #3485: iOS - App crashes after turning off the internet connection
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
User status is shown offline and can explore the app
## Actual Result:
App crashes when turning off the internet connection

## Action Performed:
1. Lunch the app and login
2. Disable  internet connection on the device
## Workaround:
Unknown

## Platform:

 Web
 iOS ✔️
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.66-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/121399945-fb79c800-c924-11eb-926e-7eb20392f456.mp4

[ios crash.txt](https://github.com/Expensify/Expensify.cash/files/6625656/ios.crash.txt)

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by TomatoToaster**
@Dal-Papa, please review when you get the chance
CC: @marcaaron, in case I'm misunderstanding how this is supposed to work.

### Details
This callback was looping too quickly because of this line (which recursively calls the callback function it's in): https://github.com/Expensify/Expensify.cash/blob/afb44ff4667bb5686c81c074097af60c26913a5c/src/libs/Network.js#L42

The actual implementation of this function doesn't change. If `persistedRequests` is empty, `networkRequestQueue = [...networkRequestQueue, ...persistedRequests];` becomes `networkRequestQueue = [...networkRequestQueue, ...[]];` which essentially does nothing over and over again.

My theory for why this hasn't happened before is that Onyx wasn't fast enough to finish the `Onyx.set(..., [])` before the `didLoadPersistedRequests = true` line right after it. If it was slow, that would be set to true and this would exit early as expected. Alternatively we could swap line 42 and 43, but I think this change makes more sense.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/3485

### Tests
Did QA on each of the platforms (couldn't get android to work with the offline mode though I can't do that with production either, so I think that's due to my  VM)

### QA Steps
In each respective platform (specifically iOS is broken),
1. Verify you can go into offline mode and navigate around the app
2. Send a message in offline mode.
3. Verify that the message is sent when you go back online.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

### Screenshots

image

### CODE REVIEW

**Review by Dal-Papa — DISMISSED** [review]

File: src/libs/Network.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ let didLoadPersistedRequests;
 Onyx.connect({
     key: ONYXKEYS.NETWORK_REQUEST_QUEUE,
     callback: (persistedRequests) => {
-        if (didLoadPersistedRequests || !persistedRequests) {
+        if (didLoadPersistedRequests || !persistedRequests || persistedRequests.length === 0) {
```
Comment (marcaaron) [inline src/libs/Network.js:35]: Is this correct? Based on the issue I just read it seems like `didLoadPersistedRequests` _should_ be preventing this callback from executing - but does not because we are calling `Onyx.set()` before updating that variable. LMK if I've got it wrong. Probably we should...

1. Move the `didLoadPersistedRequests` above the `Onyx.set()` in this function to solve the issue for now
2. Fix Onyx so that `keysChanged()` is async (what we have before) to prevent other potential issues where we have assumed an asynchronous callback

**Review by marcaaron — CHANGES_REQUESTED** [review]

File: src/libs/Network.js (hunk 1 above)
Comment (TomatoToaster) [reply src/libs/Network.js:35]: Yes that solution also works, but is there a reason why we would want to continue running if have an empty array?

Comment (TomatoToaster) [reply src/libs/Network.js:35]: I'm still happy to switch to just do the other change though. That way we'll have close to original behavior as possible.

**Comment by TomatoToaster** [comment]
Updated and tested it works on iOS 👍🏾

File: src/libs/Network.js (hunk 1 above)
Comment (marcaaron) [reply src/libs/Network.js]: >is there a reason why we would want to continue running if have an empty array

No, I can't really think of one. But it's not the issue we are trying to fix here and doesn't seem to be causing any specific problem for us.

**Review by marcaaron — APPROVED** [review]
