### PR TITLE
fix Modal animations

### LINKED ISSUE #2335: Modal animation is inconsistent
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
  The following things need to be fixed:
  1. Search page Animations.
  2. New Group page Animations.
  3. New Chat Page Animations.
  4. Settings Page Animations.
  5. IOU Modal Page Animations.
  
## Expected Result:
 Animations for all the models & EMOJI Picker should be smooth.

## Actual Result:
 When we close RightSiderbarModal (All the Pages mentioned above), it quickly closes but the opening animation is very smooth. Sometimes, Modals are open suddenly without animation.

## Action Performed:
1. Click search which opens the search modal and notices the Opening animation.
2. Now close the modal, Modal closes quickly.

## Workaround:
Does not affect functionality.

## Platform:

 Web - :heavy_check_mark: 
 iOS - :heavy_check_mark: 
 Android - :heavy_check_mark: 
 Desktop App - :heavy_check_mark: 
 Mobile Web - :heavy_check_mark: 

**Version Number:** Latest
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/24370807/114252237-d10d9c00-99c1-11eb-872f-adfe42a34751.mp4

#### Other Video

https://expensify.slack.com/files/U01J5Q81BRP/F01SZK4SMGT/5e8bd204-81ec-4646-8d02-948b7b8048e3.webm

**Expensify/Expensify Issue URL:**

### PR DESCRIPTION
**Pull request by parasharrajat**
Please review.

### Details
Details can be read https://github.com/Expensify/Expensify.cash/issues/2335#issuecomment-820618607

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes #2335 

### Tests / QA Steps
1. Click the search icon to open the Search Modal.
2. Open all the available models from the FAB button.
3. Open the User Details / Group participants modal.
4. Open the User Settings Modal.
5. **For all the modals enter and exit animation should be smooth and consistent.**
6. Open Emoji Picker on Mobile devices and Web they should be animated.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
   

https://user-images.githubusercontent.com/24370807/116021093-205ff780-a665-11eb-9635-c64beceb9567.mp4

 

#### Mobile Web

https://user-images.githubusercontent.com/24370807/116024431-cf073680-a66b-11eb-93c0-a452dbd8fdff.mp4

#### Desktop

https://user-images.githubusercontent.com/24370807/116080015-2af6ad00-a6b6-11eb-9960-4e2fef0b2232.mp4

#### iOS

 Not able to record it as I have MAC VM but the animation on IOS works smoothly.
#### Android

https://user-images.githubusercontent.com/24370807/116021378-b7c54a80-a665-11eb-94d8-5ed0de1cf36d.mp4

### CODE REVIEW

**Comment by jasperhuangg** [comment]
@parasharrajat Is this still WIP, or are we good to merge?

**Review by jasperhuangg — DISMISSED** [review]

**Comment by parasharrajat** [comment]
@jasperhuangg Updated Screenshots. Ready for review.

File: src/pages/home/report/EmojiPickerMenu/index.js [hunk 1]
```diff
@@ -136,6 +136,9 @@ class EmojiPickerMenu extends Component {
                     renderItem={this.renderItem}
                     keyExtractor={item => `emoji_picker_${item.code}`}
                     numColumns={this.numColumns}
+                    removeClippedSubviews
+                    maxToRenderPerBatch={this.numColumns}
```
Comment (jasperhuangg) [inline src/pages/home/report/EmojiPickerMenu/index.js:140]: Can you clarify why you're using 3 for windowSize? Not good to have hard coded numbers so good to clarify with a comment.

File: src/pages/home/report/EmojiPickerMenu/index.js [hunk 2]
```diff
@@ -136,6 +136,9 @@ class EmojiPickerMenu extends Component {
...
+                    windowSize={3}
```
Comment (jasperhuangg) [inline src/pages/home/report/EmojiPickerMenu/index.js:141]: What does this have to do with your issue? This just seems like a FlatList optimization that doesn't have anything do with your changes. NAB but I think it's better to do this in a separate PR.

Also, can you clarify why you're using 3 for windowSize? Not good to have hard coded numbers so good to clarify with a comment.

File: src/pages/home/report/EmojiPickerMenu/index.native.js [hunk 3]
```diff
@@ -68,6 +68,9 @@ class EmojiPickerMenu extends Component {
                     renderItem={this.renderItem}
                     keyExtractor={item => (`emoji_picker_${item.code}`)}
                     numColumns={this.numColumns}
+                    removeClippedSubviews
+                    maxToRenderPerBatch={this.numColumns}
+                    windowSize={3}
```
Comment (jasperhuangg) [inline src/pages/home/report/EmojiPickerMenu/index.native.js:73]: same as above

File: src/pages/home/report/ReportActionCompose.js [hunk 4]
```diff
@@ -397,8 +408,6 @@ class ReportActionCompose extends React.Component {
                         onClose={this.hideEmojiPicker}
                         onModalShow={this.focusEmojiSearchInput}
                         hideModalContentWhileAnimating
-                        animationInTiming={1}
```
Comment (jasperhuangg) [inline src/pages/home/report/ReportActionCompose.js:400]: Why are we removing this? There's a comment above saying why they're there.

**Review by jasperhuangg — CHANGES_REQUESTED** [review]
A few questions.

File: src/pages/home/report/EmojiPickerMenu/index.js (hunk 2 above)
Comment (parasharrajat) [reply src/pages/home/report/EmojiPickerMenu/index.js:141]: This component is very laggy. Author of the component mentioned this so he disabled the animations. I put these changes to make the animation smooth so that I can enable animation on this component. 

Window size will not be reused so I put it directly over here. It just means to create three Windows where one window is equal to visible area of component.

File: src/pages/home/report/ReportActionCompose.js (hunk 4 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:400]: So It was added to disable the animation  as the author found it laggy but I was requested to enable animation on emoji picker thus I removed it. I will remove the comments as well.

File: src/pages/home/report/EmojiPickerMenu/index.js (hunk 2 above)
Comment (parasharrajat) [reply src/pages/home/report/EmojiPickerMenu/index.js:141]: I forgot to mention that there are other PRs on emoji picker which is optimizing it So I don't need to submit a PR for now. If in future issues persists with Emoji Picker I will handle them as a separate issue.

**Comment by parasharrajat** [comment]
@roryabraham waiting for your input. Thanks.

**Comment by parasharrajat** [comment]
@jasperhuangg Please let me know how should I proceed here based on my comments over review?

**Review by jasperhuangg — APPROVED** [review]
Looks good! Thanks for clarifying my concerns.

File: src/components/OptionsSelector.js [hunk 5]
```diff
@@ -59,6 +60,10 @@ const propTypes = {
 
     // Whether to show the title tooltip
     showTitleTooltip: PropTypes.bool,
+
+    // The ref to the search input
+    // eslint-disable-next-line react/forbid-prop-types
```
Comment (marcaaron) [inline src/components/OptionsSelector.js:65]: Surely we will use this enough times that a reusable prop is better than `PropTypes.object.isRequired` ?

File: src/components/OptionsSelector.js [hunk 6]
```diff
@@ -87,7 +92,13 @@ class OptionsSelector extends Component {
     }
 
     componentDidMount() {
-        this.textInput.focus();
+        this.unsubscribeTransitionEnd = this.props.navigation.addListener('transitionEnd', () => {
```
Comment (marcaaron) [inline src/components/OptionsSelector.js:95]: What transition are we listening for the end of here? 
Does this work for all screens that might use this component in the future?
Can we add some context about why this change was needed so that others have a better idea whether to follow this example or not?

File: src/pages/home/report/EmojiPickerMenu/index.js (hunk 2 above)
Comment (marcaaron) [reply src/pages/home/report/EmojiPickerMenu/index.js:141]: +1 for @jasperhuangg comments here. 

@parasharrajat appreciate you adding value here but please do limit changes to ones affecting the issue you are assigned so that we can manage which bugs and issues are being handled and where. random fixes make it much harder to track when a bug was fixed.

File: src/pages/home/report/ReportActionCompose.js [hunk 7]
```diff
@@ -249,9 +258,11 @@ class ReportActionCompose extends React.Component {
      * Focus the search input in the emoji picker.
      */
     focusEmojiSearchInput() {
-        if (this.emojiSearchInput) {
-            this.emojiSearchInput.focus();
-        }
+        this.emojiFocusInteractionHandle = InteractionManager.runAfterInteractions(() => {
+            if (this.emojiSearchInput && !this.props.isSmallScreenWidth) {
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:262]: Why only when we have a small screen width what about tablet ?

File: src/pages/home/report/ReportActionCompose.js [hunk 8]
```diff
@@ -161,7 +170,7 @@ class ReportActionCompose extends React.Component {
         if (this.textInput) {
             // There could be other animations running while we trigger manual focus.
             // This prevents focus from making those animations janky.
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:172]: Please elaborate on why this is helpful. Which "interaction" are we waiting to finish ?

File: src/components/OptionsSelector.js (hunk 6 above)
Comment (parasharrajat) [reply src/components/OptionsSelector.js:95]: Sure. We used this as Interaction Manager has issues on Web. This transition waits for the Navigation transition to finish. This component is being used for only Screen components so this works fine. But it's a good idea to mention it in a comment. Oh, PR is merged. I will open follow-up PR.

Let me know If we should handle this in a different way.

File: src/pages/home/report/ReportActionCompose.js (hunk 8 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:172]: So When the modal screen is being closed, we want to wait for those before focusing on it. And I noticed that manual focus is causing a lot of issues so I think it's better to put focus after Interactions, we have no side effects.

File: src/pages/home/report/ReportActionCompose.js (hunk 7 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:262]: Yeah, this is a bigger device (!isSmallScreenWidth) but we can remove this check as `emojiSearchInput` is already null for native devices.

File: src/pages/home/report/EmojiPickerMenu/index.js (hunk 2 above)
Comment (parasharrajat) [reply src/pages/home/report/EmojiPickerMenu/index.js:141]: I added these changes as per request https://github.com/Expensify/Expensify.cash/issues/2335#issuecomment-824089744

File: src/pages/home/report/ReportActionCompose.js (hunk 8 above)
Comment (marcaaron) [reply src/pages/home/report/ReportActionCompose.js:172]: Is there some way to see which "interactions" we are waiting for? Or am I misunderstanding what this method does? Which janky animation are we fixing specifically with this? Is there a before/after video we can share to verify the change does what it should and so QA can verify the change as well?

I'm not seeing anything at all about the emoji picker in the test steps so those will also need to be updated.

Comment (jasperhuangg) [reply src/pages/home/report/ReportActionCompose.js:172]: +1 @parasharrajat Can you updated the test steps to include something about the emoji picker? It's not super apparent that it's a modal and it might get missed in QA.

Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:172]: Sure @jasperhuangg

File: src/pages/home/report/EmojiPickerMenu/index.js (hunk 2 above)
Comment (marcaaron) [reply src/pages/home/report/EmojiPickerMenu/index.js:141]: Ah ok, thanks I missed this comment. No need to remove changes but if we are increasing the scope we need to add that context to the description of the original issue so we should:

1. Update the issue you are working on to show each problem we are solving (show that it is broken)
2. Ask QA to test the same flows and prove that it is fixed.

Otherwise, we're just adding random stuff and it's hard to have a good history.

Comment (parasharrajat) [reply src/pages/home/report/EmojiPickerMenu/index.js:141]: Sure, Thanks. Updating now.

**Comment by roryabraham** [comment]
I believe this PR caused [a regression](https://github.com/Expensify/Expensify.cash/issues/2660)

**Comment by parasharrajat** [comment]
I don't think so but I will debug it and see.

**Comment by roryabraham** [comment]
Yeah, I was just looking at the checklist [here](https://github.com/Expensify/Expensify.cash/issues/2639) and finding that this PR looked like the only potential culprit

**Comment by roryabraham** [comment]
Okay, actually I have figured out how to reproduce the regression, and I'm 90% sure it was indeed caused by this PR.

File: src/pages/home/report/EmojiPickerMenu/index.native.js (hunk 3 above)
Comment (roryabraham) [reply src/pages/home/report/EmojiPickerMenu/index.native.js:73]: I was able to confirm locally that removing these line fixes [a regression](https://github.com/Expensify/Expensify.cash/issues/2660)

**Comment by roryabraham** [comment]
Was able to confirm that [these lines](https://github.com/Expensify/Expensify.cash/blob/419c9d68dd583f6ee0c8c90ed42349bd3ef477ee/src/pages/home/report/EmojiPickerMenu/index.native.js#L71-L73) were the source of [the regression](https://github.com/Expensify/Expensify.cash/issues/2660).

**Comment by parasharrajat** [comment]
I am feeling like I need to test the app deeply before finalizing a PR. I am seeing that there have been couple of regressions.

**Comment by roryabraham** [comment]
@parasharrajat This PR has been [reverted](https://github.com/Expensify/Expensify.cash/pull/2663), so'll need to include these original changes in your follow-up too
