### PR TITLE
fix: reimbursable features

### LINKED ISSUE #58588: Add a non-reimbursable toggle on the expense form in New Expensify
WIP

### PR DESCRIPTION
**Pull request by daledah**
### Fixed Issues

$ https://github.com/Expensify/App/issues/58588
PROPOSAL: https://github.com/Expensify/App/issues/58588#issuecomment-2734334857

### Tests

Follow the test steps [here](https://github.com/Expensify/App/pull/63054#issuecomment-2996563292)

- [x] Verify that no errors appear in the JS console

### QA Steps

Follow the test steps [here](https://github.com/Expensify/App/pull/63054#issuecomment-2996563292)

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/d646ef82-e507-4504-acaf-93d85be6d594

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/a9b2ec8b-ceec-48b5-af4f-c010be273d47

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/f8af99ba-d0e5-4168-b2b5-55a0ed61f5f1

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/fa08dc0e-2b18-4fc8-b58d-c4920e0023f5

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/ac74b4cb-03fd-4d97-9939-2c895cedb788

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/a00e9319-d401-41ae-a487-28b8eb739863

</details>

### CODE REVIEW

**Comment by flaviadefaria** [comment]
@daledah are we good here for me to trigger a test build?

**Comment by daledah** [comment]
@flaviadefaria I just pushed an update for the update reimbursable messages. The PR is ready now 👍

**Comment by daledah** [comment]
The lint errors will be handled elsewhere. @flaviadefaria There's a last BE bug which I mentioned in https://github.com/Expensify/App/issues/58588#issuecomment-2959021632, other wise everything is good.

**Comment by flaviadefaria** [comment]
Thanks @daledah,  probably best to have that backend error fixed first so that we can test all in one go.

**Comment by daledah** [comment]
@Expensify/design coming from this [slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1749023592627069), let's discuss about unifying the text message content and the expense rule for reimbursable and billable.

For more context, here's the reimbursable rule and message:
Screenshot 2025-06-11 at 13 53 55
image

And here's billable rule and message:
Screenshot 2025-06-11 at 13 54 31
Screenshot 2025-06-11 at 13 54 58

Other fields seems to not have this issue, for example Max expense age field:
Screenshot 2025-06-11 at 13 56 49

Screenshot 2025-06-11 at 13 56 33

**Comment by flaviadefaria** [comment]
Good point @daledah! It looks like the comment is using as a reference what we have in Classic whereas in Rules we decided to go with something different. So perhaps for the Reimbursable option we should align rules with what we have in Classic:

Cash expenses are

**Reimbursable by default**
Expenses are most often paid back to employees
**Non-reimbursable by default**
Expenses are occasionally paid back to employees
**Always reimbursable**
Expenses are always paid back to employees
**Always non-reimbursable**
Expenses are never paid back to employees


image


Thoughts @Expensify/design and @trjExpensify?

**Comment by shawnborton** [comment]
Saying `Updated "Cash expenses are" to` feels weird to me. Can we use the label from NewDot, which would make it `Updated "Cash expense default" to`

**Comment by flaviadefaria** [comment]
>Saying Updated "Cash expenses are" to feels weird to me. Can we use the label from NewDot, which would make it Updated "Cash expense default" to

Ah, so you're actually suggesting we leave the copy we have in `Rules` and update the message copy. Works for me too.

@daledah so the plan as far as I understand it is to stick to:

> **Cash expense default**
> 
> **Reimbursable** 
> Expenses are most often paid back to employees
> **Non-reimbursable** 
> Expenses are occasionally paid back to employees
> **Always reimbursable**
> Expenses are always paid back to employees
> **Always non-reimbursable**
> Expenses are never paid back to employees
> 

And update the message to:

>Updated: "Cash expense default" to "non-reimbursable" (previously "always reimbursable")

**Comment by trjExpensify** [comment]
>And update the message to:
>
>Updated: "Cash expense default" to "non-reimbursable" (previously "always reimbursable")

This sounds good to me!

**Comment by flaviadefaria** [comment]
@daledah do you think you can get all the changes done by today so that I can test the PR tomorrow?

**Comment by daledah** [comment]
@flaviadefaria I updated the translations 👍

**Comment by flaviadefaria** [comment]
Awesome, I'll trigger a test app build right away!

**Comment by daledah** [comment]
Looking at the Typescript check errors, do we need to update translations for all the languages now? It's a new feature I'm not very familiar with.

**Comment by trjExpensify** [comment]
Yes, you do for the time being until we complete [this issue](https://github.com/Expensify/App/issues/62802) to automate incremental updates. Here was the [announcement in #open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1749840774298629) for ref.

**Comment by flaviadefaria** [comment]
Sorry I wasn't able to get to this last week. To make things easier for all of us, these are the tests I'll be running:

### Collect workspace ### 

1. Create an expense and verify that:
- The expense should display the reimbursable toggle above the report name in the expense form 
- The expense defaults to reimbursable

2. Update the reimbursable toggle in the Details Confirmation page and verify that:
- The expense switches to non-reimbursable
- The expense continues to display as non-reimbursable also in the expense preview page

3. Edit an open expense to switch the reimbursable status
- The expense preview page updates following the new change
- The report comments updates when the toggle is updated

4. Approve the report and verify that:
- The expense can no longer have the reimbursable option updated 

5. Import a company card expense and verify that:
- The expense defaults to non-reimbursable

6. Mark all the expenses on a report as non-reimbursable, verify that 
- The Pay button disappears
- The system message should actually update to: :checkmark no further action required as seen in the screenshot below:

### Workspace chat ###

1. [Admin] Click + > Create expense > Manual enter expense details and verify that
- [Admin] Reimbursable toggle is enabled for admin by default

2. [Member] Click + > Create expense > Manual enter expense details and verify that
- [Member] Reimbursable toggle will be enabled for member by default


### Control workspace ###

1. Go to the workspace settings and verify that:
- There are reimbursable settings under `Rules`

2. Update the default option to non-reimbursable and verify that:
- The expense form updated to non-reimbursable

3. Update the default option to always  reimbursable and verify that:
- The expense form updated to  always reimbursable

4. Update the default option to always non-reimbursable and verify that:
- The expense form has been updated to never reimbursable


### No workspace ###

1. Create an expense outside of a workspace and verify that:
- We don't display the reimbursable toggle

2. Create an expense outside of a workspace and select to submit to yourself, verify that:
- reimbursable toggle should not appear for p2p expense on the confirmation page.

3. In the Self-DM select `categorize it` or `share with my accountant`, which means the expense is being moved to a workspace, so verify that:
- At this point we display the reimbursable toggle and set it to the workspace's default settings for reimbursable expenses. If it's a Collect workspace, it will always default to reimbursable unless it's a card expense. If it's Control workspace, then it might have a different default within Rules that we'd need to check and apply to the expense.


### Invoices ###

Invoices should only contain reimbursable expenses, so when creating an expense from an invoice, the reimbursable toggle should simply not display. And if a non-reimbursable expense is ever moved to an invoice report, then we should automatically force the expense to be reimbursable.

### Offline ###

This is the intended behavior if the user tries to change a reimbursable toggle when offline:

1. User goes offline
2. Changes the reimbursable toggle, very that:
- The "changed the expense to non-reimb..." system message is added to the expense thread at 50% opacity as it's a pending action taken offline
- The pay button goes away (as there are no reimbursable expenses left on the report)

3. The user comes back online, verify that:
- If updating the reimbursability of the expense failed, an RBR dismissable message is added in line of the "changed the expense to non-reimb..." system message (i.e it's conceivable that somebody else paid this report while you were offline, in which case the action to mark it as non-reimbursable would fail). The message should say: This expense couldn’t be updated because a report change occurred while you were offline.
- If updating the reimbursability of the expense succeeded, the "changed the expense to non-reimb..." system message goes to 100% opacity.

**Comment by flaviadefaria** [comment]
@daledah I just did a massive round os testing and it looks like we still have some issues (flagged by the 🔴). Let me know in case you have any questions. Also as a FYI I'm going to double the payment amount for this issue cause this is turning out to be a lot more complex than we initially anticipated and is a high priority.


### Collect workspace ### 

1. Create an expense and verify that:
- The expense should display the reimbursable toggle above the report name in the expense form 🟢 
- The expense defaults to reimbursable 🔴 - expense defaults to non-reimbursable

2. Update the reimbursable toggle in the Details Confirmation page and verify that:
- The expense switches to non-reimbursable 🟢 - I had to switch to reimbursable since the default is currently incorrect
- The expense continues to display as non-reimbursable also in the expense preview page 🟢 - it continued as non-reimbursable

3. Edit an open expense to switch the reimbursable status
- The expense preview page updates following the new change 🟢 
- The report comments updates when the toggle is updated 🟢

4. Submit the report
- Confirm that the approver can see the reimbursable toggle on the expense form 🔴 - the expense doesn't display the reimbursable toggle for the approver.

4. Approve the report and verify that:
- The expense can no longer have the reimbursable option updated 🟢

5. Import a company card expense and verify that:
- The expense defaults to non-reimbursable (still need to test this but trying to get a card transaction to do so) 🟡 

6. Mark all the expenses on a report as non-reimbursable, verify that 
- The Pay button disappears 🟢
- The system message should actually update to: :checkmark no further action required 🟢

### Workspace chat ###

1. [Admin] Click + > Create expense > Manual enter expense details and verify that
- [Admin] Reimbursable toggle is enabled for admin by default 🔴 - toggle was disabled

2. [Member] Click + > Create expense > Manual enter expense details and verify that
- [Member] Reimbursable toggle will be enabled for member by default 🔴 - toggle was disabled


### Control workspace ###

1. Go to the workspace settings and verify that:
- There are reimbursable settings under `Rules` - 🟢 
- It is by default set to reimbursable-  🔴 (it is by default set to non-reimbursable)

2. Update the default option to non-reimbursable and verify that:
- The expense form updated to non-reimbursable - 🟢 (in this case I updated it to reimbursable)

3. Update the default option to always reimbursable and verify that - 🔴 I'm not able to update this, it automatically switches  to reimbursable.
- The expense form updated to  always reimbursable -  🟡 couldn't test
-  The reimbursable toggle should not be visible -  🟡 couldn't test

4. Update the default option to always non-reimbursable and verify that -  🔴 I'm not able to update this, it automatically switches to non-reimbursable.
- The expense form updated to  always nonreimbursable -  🟡 couldn't test
-  The reimbursable toggle should not be visible -  🟡 couldn't test

5. Create an expense and verify that:
- The expense should display the reimbursable toggle above the report name in the expense form 🔴 - it displays the reimbursable toggle below the report name


### No workspace ###

1. Create an expense outside of a workspace to another user (P2P) and verify that:
- We don't display the reimbursable toggle 🟢 

2. Create an expense outside of a workspace and select to submit to yourself, verify that:
- We don't display the reimbursable toggle 🟢 
- Reimbursable toggle should not appear for p2p expense on the confirmation page 🟢 

3. In the Self-DM select `categorize it` or `share with my accountant`, which means the expense is being moved to a workspace, so verify that:
- At this point we display the reimbursable toggle and set it to the workspace's default settings for reimbursable expenses. If it's a Collect workspace, it will always default to reimbursable unless it's a card expense. If it's Control workspace, then it might have a different default within Rules that we'd need to check and apply to the expense - 🟡 still need to test this though this is currently behind a beta so not super critical.


### Invoices ###

Invoices should only contain reimbursable expenses, so when creating an expense from an invoice, the reimbursable toggle should simply not display. And if a non-reimbursable expense is ever moved to an invoice report, then we should automatically force the expense to be reimbursable - 🟢 

### Offline ###
This is the intended behavior if the user tries to change a reimbursable toggle when offline:

1. User goes offline, verify that:
- They can change the reimbursable toggle - 🟢
- The "changed the expense to non-reimb..." system message is added to the expense thread at 50% opacity as it's a pending action taken offline - 🟢
- The pay button goes away (as there are no reimbursable expenses left on the report)

3. The user comes back online, verify that:
- If updating the reimbursability of the expense succeeded, the "changed the expense to non-reimb..." system message goes to 100% opacity - 🟢
- If updating the reimbursability of the expense failed, an RBR dismissable message is added in line of the "changed the expense to non-reimb..." system message (i.e it's conceivable that somebody else approved this report while you were offline, in which case the action to mark it as non-reimbursable would fail). The message should say: This expense couldn’t be updated because a report change occurred while you were offline - 🔴 This is super buggy if a submitter submits a report, goes offline and change the reimbursable toggle to non-reimbursable while the approver that is online approvers the report then when the user goes back online:
     - The toggle has been updated regardless of the report being approved when the user made the change offline
     -  The approver sees an incorrect report update that says "changed the expense to "non-reimbuirsable" previously "non-reimbursable" when it should say "previously reimbursable"
     - The approver still sees the `Pay with Expensify button` despite the expense having been updated to non-reimbursable.

**Comment by flaviadefaria** [comment]
@trjExpensify some questions for you on some other things I noticed while testing that I thought were confusing:
- In a report with more than 1 expense there is no way to quickly see if the expense is reimbursable or non-reimbursable which I found to be confusing. Should we maybe flag this somewhere in the table view?

image


- Then the report total differentiates between out-of-pocket (reimbursabe) vs. company spend (non-reimbursable) when there is a mix of both. But when there are only non-reimbursable expenses, you can't immediately see if it's a report with only reimbursable or non-reimbursable expenses, and I think it would be useful for an approver to know that right away:

image

image

What are your thoughts here?

**Comment by flaviadefaria** [comment]
@daledah did you have a chance to review the test results I posted above? Let me know if you have any questions!

**Comment by daledah** [comment]
@flaviadefaria I'm investigating and already have some results, I'll post a comment address all of the issues mentioned soon.

**Comment by trjExpensify** [comment]
>In a report with more than 1 expense there is no way to quickly see if the expense is reimbursable or non-reimbursable which I found to be confusing. Should we maybe flag this somewhere in the table view?

I think we can do nothing for now and wait for external feedback, and consider it after we have the accounting focused suggested searches and group-by's built. Similarly, if we more broadly look at "sorting" within a report to allow for grouped views for reimbursable/non-reimbursable, billable, category or tag. 

The mainline use-case for reimbursable/non-reimbursable is fairly obvious with card or cash symbols right now in the type column today, so I'm down to wait it out. 

>Then the report total differentiates between out-of-pocket (reimbursabe) vs. company spend (non-reimbursable) when there is a mix of both. But when there are only non-reimbursable expenses, you can't immediately see if it's a report with only reimbursable or non-reimbursable expenses, and I think it would be useful for an approver to know that right away:

Yeah, looks like OldDot's report view works like so:

- Mixture: Total & sub-totals for both reimbursable/non-reimbursable. 
- All reimbursable: Total only
- All non-reimbursable: Total & sub-total for non-reimbursable.

I guess I don't see the harm in making that change, we can do it adjacent to this PR though probably. Maybe while we're at it, rename these subtotals to `Reimbursable` and `Non-reimbursable`? CC: @JmillsExpensify

**Comment by daledah** [comment]
@flaviadefaria Sorry for the delays, here's the break down of all issues that you've listed:

1. Create an expense and verify that:
- The expense defaults to reimbursable 🔴 - expense defaults to non-reimbursable: This can only be reproduced with older workspaces, looks like BE doesn't send `defaultReimbursable` for these WS. We can fix in FE by default this value as `true` or fix BE (*)

4. Submit the report
- Confirm that the approver can see the reimbursable toggle on the expense form 🔴 - the expense doesn't display the reimbursable toggle for the approver: I can't reproduce this issue

## Workspace chat
1. [Admin] Click + > Create expense > Manual enter expense details and verify that
- [Admin] Reimbursable toggle is enabled for admin by default 🔴 - toggle was disabled
2. [Member] Click + > Create expense > Manual enter expense details and verify that
- [Member] Reimbursable toggle will be enabled for member by default 🔴 - toggle was disabled
-> Same as point (*) above

## Control workspace
1. Go to the workspace settings and verify that:
- It is by default set to reimbursable- 🔴 (it is by default set to non-reimbursable) (same as point (*) above)
3. Update the default option to always reimbursable and verify that - 🔴 I'm not able to update this, it automatically switches to reimbursable.-> I reported this issue [here](https://github.com/Expensify/App/issues/58588#issuecomment-2959021632).
4. Update the default option to always non-reimbursable and verify that - 🔴 I'm not able to update this, it automatically switches to non-reimbursable. -> Same as above
5. Create an expense and verify that:
- The expense should display the reimbursable toggle above the report name in the expense form 🔴 - it displays the reimbursable toggle below the report name -> Working on a fix, will update soon

## Offline - Investigating

**Comment by flaviadefaria** [comment]
@daledah it would be great if we could get this reviewed again by Monday end of day, do you think it's possible to have it updated by then?

**Comment by flaviadefaria** [comment]
I did! Fixed my original comment.

**Comment by flaviadefaria** [comment]
>the expense doesn't display the reimbursable toggle for the approver: I can't reproduce this issue

@daledah I tested this again with both a new and an old expense and I can no longer re-create it so I guess we're good.

**Comment by flaviadefaria** [comment]
I can still re-create it, but it might be because my testing steps are slightly different than yours:

1. Submit report
2. Go offline
3. Update reimbursable toggle (in this case I updated it from non-reimbursable to reimbursable)
4. Manager approved the report
5. Submitter went online, and the report was approved AND the expense toggle updated.


image

**Comment by trjExpensify** [comment]
The LHN is a complete whitewash on this adhoc build on Safari web: 

image

**Comment by trjExpensify** [comment]
Followed these steps, and couldn't repro: 

> 1. Create expense
> 2. Submit report to a different user
> 3. Go offline
> 4. Update reimbursable toggle (in this case I updated it from non-reimbursable to reimbursable)
> 5. Manager approves the report
> 6. Submitter went back online, and the report was approved AND the expense toggle updated.

https://github.com/user-attachments/assets/7bcd3b84-0516-4bd5-82f3-2b34c9c08672

**Comment by trjExpensify** [comment]
>@Expensify/design team, what is the expected behavior here? I so far suggested putting the billable and reimbursable toggles above the report name since that's how we have it in Classic (the report name goes last in the expense form) but before @daledah makes the final updates, I want to confirm that is correct.

Personally, I'd put the toggles at the bottom of the form so they're grouped together above push rows. I think Classic is a little different, insofar as they're checkboxes kinda' indented beneath the total amount field: 

image

**Comment by flaviadefaria** [comment]
Personally, from a hierarchy perspective, I prefer placing the report name last. I don’t think it makes a significant difference whether all the carat options are grouped together or one is separate.

From a user standpoint, they’re more likely to adjust the billable and reimbursable toggles than the report name. It also feels more intuitive to me to present all expense-level options first, followed by the report, which is simply the container the expense lives in.

Just my two cents!

**Comment by dannymcclain** [comment]
That's a fair point. I don't think I feel too strongly as long as the Reimbursable and Billable toggles stay grouped together (I think it makes sense to keep them together, right?) and the order of things doesn't switch around.

**Comment by inimaga** [comment]
Update, regarding the backend tasks: 
1. For the problems:
      a. Update the default option to always reimbursable and verify that it automatically switches to reimbursable.
      b. Update the default option to always non-reimbursable and verify that it automatically switches to non-reimbursable. 

      Outcome: After some investigation, it turns out the solution was fine, and the culprit was our firewall which was filtering out the parameter **disabledFields**, as it is new and had never been used before, resulting in it always being null and defaulting to false. I have now updated this [here](https://github.com/Expensify/Web-Expensify/pull/47558) and [here](https://github.com/Expensify/Web-Secure/pull/2872), so should be good to test tomorrow once deployed to staging.


2. Regarding the point: "_For Collect we want it to always default to reimbursable as the user has no workspace settings, for Control then we should default to reimbursable for new workspace and just keep whatever the user has in Classic for existing workspaces._", I don't think any action is needed here, as the default behaviour currently is 'reimbursable'.

**Comment by inimaga** [comment]
> @inimaga This seems pretty weird to me, because we use this field to update billable mode:
> https://github.com/Expensify/App/blob/46b07ddef35e90857c148cdf17fa5a0008eba654/src/libs/actions/Policy/Policy.ts#L4384-L4386

@daledah No, before the firewall changes, **disabledFields** basically evaluated to null on the backend. So whatever value was sent for that wasn't used. Only the value being sent for defaultBillable is being recognised by the Backend.
https://github.com/Expensify/App/blob/46b07ddef35e90857c148cdf17fa5a0008eba654/src/libs/actions/Policy/Policy.ts#L4383


.
Just checked and the firewall changes are now deployed to staging which means the below two from my comment above should be working without issues:
> a. Update the default option to always reimbursable and verify that it automatically switches to reimbursable.
> b. Update the default option to always non-reimbursable and verify that it automatically switches to non-reimbursable.

Do flag/confirm if otherwise.

**Comment by inimaga** [comment]
For a new account that hasn’t upgraded yet, and therefore only has access to a Collect workspace, when you create an expense, it should default to reimbursable.

https://github.com/user-attachments/assets/4cc4846b-38ca-48c6-80ed-b1b4d9d5fde6

**Comment by JmillsExpensify** [comment]
So I'm coming in late to this convo, though I kind of think the data says that report is going to be used more often than either of the reimbursable and billable toggles. Here's my logic (not sharing specific data points since this is a public repo):

 - The majority of customers have billable disabled entirely
 - Manually toggling reimbursable vs not is primarily an edge case, specifically for when we don't support a company's card program, though that's going to be even more uncommon now that we have international bank support
 - Then just in terms of NewDot, the request for the report row and changing reports has come up a lot more than either of these two options. 
 
 So as a result, I kind of feel strongly that `Report` should go above the toggles. Equally, I think the UX is better if all the toggles are at the bottom.

**Comment by dannymcclain** [comment]
I feel the same as Shawn 🤝

**Comment by dubielzyk-expensify** [comment]
Compelling arguments. Totally can get behind that as well 👍

**Comment by trjExpensify** [comment]
👋 @daledah can you fix the conflicts and failing tests here? Outside of that, are we ready for a re-review and can we get it merged tomorrow?

**Comment by trjExpensify** [comment]
@daledah we're trying to get this deployed to prod by the end of week at the latest, so it can be announced in the product email going out next week. Can you prioritise it please? 

>There's still this https://github.com/Expensify/App/pull/63054#issuecomment-3018941576 which I haven't gotten to the bottom of it yet, but I suspect it's a BE bug.

Recall we figured out this is only reproducible if the submitter and approver are both admins of the workspace: 

>Okay, I just tested the offline flow multiple times, and it seems like the issue is that when the submitter and approver are both set as admins in the workspace, I can reproduce https://github.com/Expensify/App/pull/63054#issuecomment-3018941576. However, like you and @trjExpensify, I'm not able to reproduce it when the submitter only has a user role. H/T to @trjExpensify for helping identify that!

Honestly, I wouldn't block on that to get this out if it comes to it. CC: @inimaga

**Comment by luacmartins** [comment]
@daledah I think the script broke somehow. We'll need to investigate what's wrong with it.

File: src/ROUTES.ts [hunk 1]
```diff
@@ -1885,6 +1885,10 @@ const ROUTES = {
         route: 'workspaces/:policyID/rules/billable',
         getRoute: (policyID: string) => `workspaces/${policyID}/rules/billable` as const,
     },
+    RULES_REIMBURSABLE_DEFAULT: {
+        route: 'settings/workspaces/:policyID/rules/reimbursable',
```
Comment (getusha) [inline src/ROUTES.ts:1889]:
```suggestion
        route: 'workspaces/:policyID/rules/reimbursable',
```

https://github.com/user-attachments/assets/ab0c35ab-6242-45e5-958d-ae6365d24e02

File: src/ROUTES.ts [hunk 2]
```diff
@@ -1885,6 +1885,10 @@ const ROUTES = {
...
+        getRoute: (policyID: string) => `settings/workspaces/${policyID}/rules/reimbursable` as const,
```
Comment (getusha) [inline src/ROUTES.ts]:
```suggestion
        route: 'workspaces/:policyID/rules/reimbursable',
        getRoute: (policyID: string) => `workspaces/${policyID}/rules/reimbursable` as const,
```

https://github.com/user-attachments/assets/ab0c35ab-6242-45e5-958d-ae6365d24e02

Comment (daledah) [reply src/ROUTES.ts]: @getusha Is this new standard for routes? I'm pretty sure it worked before.

Comment (getusha) [reply src/ROUTES.ts]: yeah, i think changed couple of weeks ago

**Comment by getusha** [comment]
@daledah why are expenses Non-Reimbursable by default in ND while it's otherwise in OD?

Screenshot 2025-07-10 at 5 45 40 in the afternoon

Screenshot 2025-07-10 at 5 45 51 in the afternoon

**Comment by getusha** [comment]
>This one is an odd bug. I had raised a PR to fix it, and the written internal tests were passing, but it seems I might need to mimic the actual curl with multipart/form-data for disabledFields : {"reimbursable":true} in the test, as for some reason this is behaving completely different.
Will raise the PR today.

Seems like @inimaga was working on a fix for https://github.com/Expensify/App/pull/63054#issuecomment-3057784274

**Comment by JmillsExpensify** [comment]
@getusha will you be able to retest today?

**Comment by trjExpensify** [comment]
>it would mean every existing workspace will have a non-reimbursable default. I'm not sure if this has already been discussed.

I don't understand this comment really. An existing workspace has the setting configured in some way, why aren't we retaining whatever that is?

**Comment by getusha** [comment]
>@getusha Looks like it has the same RCA as what I commented https://github.com/Expensify/App/pull/63054#issuecomment-3012203372:

Doesn't seem like it's fixed from the BE, since I was able to repro it on existing workspaces. Any side effects you're aware of, should we fix it in the FE until a BE fix is up?

**Comment by getusha** [comment]
@daledah I was looking into the DBs we had previously, we are not supposed to show the option for p2p expenses and invoice? https://github.com/Expensify/App/issues/62510 https://github.com/Expensify/App/issues/62511

**Comment by inimaga** [comment]
@daledah & @getusha I found the issue for this and have a change up. So let's proceed with the assumption that specific issue will get sorted when the change get merged. 

Is there anything else that is holding the merge of this PR apart from [this](https://github.com/Expensify/App/pull/63054#issuecomment-3053092548) issue mentioned by tjr?

**Comment by inimaga** [comment]
@daledah can you test now to confirm whether defaultReimbursable is now coming through in the OpenApp API call?

**Comment by getusha** [comment]
On it, @daledah could you fix the conflict?

**Comment by getusha** [comment]
Will finalize the review today

**Comment by flaviadefaria** [comment]
Thanks @daledah and @getusha, if we can get this one merged by tomorrow (considering everything looks good) it would be amazing!

**Comment by getusha** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: HybridApp
    - [ ] Android: mWeb Chrome
    - [ ] iOS: HybridApp
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: HybridApp</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: HybridApp</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by getusha** [comment]
A non-reimbursable expense can be paid with a reimbursable expense in a report.

Screenshot 2025-07-24 at 1 20 49 in the afternoon

**Comment by flaviadefaria** [comment]
>A non-reimbursable expense can be paid with a reimbursable expense in a report.

That's a good catch. Since the total amount paid should only reflect the report total reimbursable amount, we shouldn't add "cash paid" to the non-reimbursable expense.

**Comment by getusha** [comment]
The reimbursable option is still shown even after setting the workspace to Always reimbursable.

https://github.com/user-attachments/assets/2d37ab61-cbec-4fa2-ac37-51caf6512f33

Regarding the expected behavior:
I thought we would show a non-editable toggle when the option is set to either Always reimbursable or Always non-reimbursable.

**Comment by flaviadefaria** [comment]
What's the latest here? 😬

**Comment by trjExpensify** [comment]
>This is actually UI bug where we display the "Paid" text in the transaction, the paid amount is only the total amount of reimbursable expenses. So we should remove the text "Paid" here, is that correct @flaviadefaria?

Yes, a card transaction or a non-reimbursable expense shouldn't have `Paid` in the dot separator on the `Amount` field as it does not contribute to the reimbursable total of the expense report it is on. 

Can we fix the conflicts today and get this onto prod this week? Let's open a Slack thread if we need to resolve any outstanding questions/discussion. Thanks!

**Comment by getusha** [comment]
Not able to toggle the option on iOS native

https://github.com/user-attachments/assets/83166897-ecdd-4691-81e4-81b8042d663c

**Comment by getusha** [comment]
@daledah could you test on iOS again? Now the option doesn't appear in report view anymore. Could you also test on a workspace with default currency set to USD please, if that makes a difference.

https://github.com/user-attachments/assets/b99d9bfe-f7d0-4ac9-b73a-dfea0d36106f

**Comment by getusha** [comment]
@daledah please have a look at [this](https://github.com/Expensify/App/pull/63054#issuecomment-3140327630), lets show the toggle if it's set  Always reimbursable/non-reimbursable

**Review by getusha — APPROVED** [review]
LGTM, left one comment ^

**Review by getusha — APPROVED** [review]

**Review by getusha — APPROVED** [review]

**Comment by trjExpensify** [comment]
>@daledah please have a look at https://github.com/Expensify/App/pull/63054#issuecomment-3140327630, lets show the toggle even if it's set to Always reimbursable/non-reimbursable

Mhm, why? From the spec in the OP of the issue: 

> - If Always non-reimbursable is set via OldDot, don't show the toggle at all and create the cash expense as non-reimbursable.
> - If Always reimbursable is set via OldDot, don't show the toggle at all and create the cash expense as reimbursable.

**Review by inimaga — APPROVED** [review]

**Comment by JmillsExpensify** [comment]
I think we need to revert, and/or get a quick hotfix in. I'm seeing a locked reimbursable toggle for a workspace that is set to always reimbursable. In Expensify Classic, I don't see the reimbursable option in the creation flow, or when editing an expense, so the behavior should be the same. 
CleanShot 2025-08-06 at 22 27 32@2x

**Comment by JmillsExpensify** [comment]
Ah wait, I'm just seeing the convo above. I think we need to consider this a regression. Why did we knowingly ignore the product design spec and merge this PR before fixing it?

**Comment by trjExpensify** [comment]
Commented [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1754524924351089?thread_ts=1754399538.923349&cid=C01GTK53T8Q) in thread about those findings.

**Comment by lanitochka17** [comment]
Hello  
 Tester don't see the reimbursable status. It's WAD or issue?

**Comment by francoisl** [comment]
This PR was reverted, you no longer need to test it.

**Comment by lanitochka17** [comment]
@francoisl  thanks
