### PR TITLE
[IS-3218] Fixed cursor issue on edit comment box

### LINKED ISSUE #3218: If you edit a recently sent DM by pressing up on keyboard or hovering > edit comment, the focus is on the beginning of the message
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Focus should be on the end of the message

## Actual Result:
Focus is on the beginning of the message. 

## Action Performed:
1. Navigate to a conversation in e.cash
2. Hover over an owned message and click on the edit comment option in the menu 
**or**
3. Tap up arrow key to edit the previous comment. 
4. See the focus is set to the beginning of the message (it should be the end though)

## Workaround:
Users can manually set the focus where it's needed. 

## Platform:
Where is this issue occurring?

 Web ✔️ 
 iOS
 Android
 Desktop App ✔️
 Mobile Web

**Version Number:** 1.0.62-0 (1.0.62-0)

**Notes/Photos/Videos:** 
Important note: If you right click and use the edit comment option it does not have the same behaviour. To get this behaviour you have to use the hover action menu. Right-click has another issue [here](https://github.com/Expensify/Expensify.cash/issues/3017)

upwerk

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/166576

**Upwork Job URL** https://www.upwork.com/jobs/~0107b705b762cb168d

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
From @aliabbasmalik8 https://expensify.slack.com/archives/C01GTK53T8Q/p1622188890359100
> On Edit Comment, Cursor position at the start of comment

### PR DESCRIPTION
**Pull request by aliabbasmalik8**
### Fixed Issues

Fixes https://github.com/Expensify/Expensify.cash/issues/3218

### QA Steps

1. Navigate to a conversation in e.cash
2. Hover over an owned message and click on the edit comment option in the menu
3. or
4. Tap up arrow key to edit the previous comment.
5. See the cursor is set to the end of the message.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/31027036/121220923-ed02b200-c839-11eb-9e77-dd82217bee38.mov

#### Desktop

https://user-images.githubusercontent.com/31027036/121222217-30a9eb80-c83b-11eb-9f67-067fec4a0878.mov

#### iOS

https://user-images.githubusercontent.com/31027036/121220190-41596200-c839-11eb-86d5-88d98d6074c1.mov

#### Android

https://user-images.githubusercontent.com/31027036/121222923-d3fb0080-c83b-11eb-98f0-592d4bcedbe8.mp4

### CODE REVIEW

**Review by Gonals — APPROVED** [review]

File: src/pages/home/report/ReportActionItemMessageEdit.js [hunk 1]
```diff
@@ -36,12 +36,26 @@ class ReportActionItemMessageEdit extends React.Component {
...
+            },
         };
     }
 
+    /**
+     * Update Selection on change cursor position.
+     *
+     * @param {Event} e
+     */
+    onSelectionChange(e) {
```
Comment (parasharrajat) [inline src/pages/home/report/ReportActionItemMessageEdit.js:55]: Overall looks good but this state change is unnecessary, I have already seen a drawback of this and I am migrating tis unnecessary state change. So my suggestion here would be to remove this   as I mentioned over the issue.
cc: @Gonals

**Review by parasharrajat — CHANGES_REQUESTED** [review]

File: src/pages/home/report/ReportActionItemMessageEdit.js (hunk 1 above)
Comment (aliabbasmalik8) [reply src/pages/home/report/ReportActionItemMessageEdit.js:55]: @parasharrajat can you please let me know about the issue?
also, without state change, this issue will not be fixed.

**Comment by kavimuru** [comment]
## mWeb - No cursor appears in edit comment box 
## Expected Result: 
The cursor is set to the end of the message.
## Actual Result:
No cursor appears in edit comment box
## Actions Performed:
1. Go to https://staging.expensify.cash

2. Log in with applause account or gmail account
3. Navigate to a conversation in e.cash
4. Hover over an owned message and click on the edit comment option in the menu or tap up arrow key to edit the previous comment.
## Platform:
iOS 
mWeb ✔️
Android 
## Build:
1.0.66-0
## Notes/Images/Video:
https://user-images.githubusercontent.com/43996225/121380021-8bfadd00-c912-11eb-897b-b63aa299cf4f.mp4
Bug5104994_Screenshot_20210609-104016_Chrome

**Comment by parasharrajat** [comment]
@kavimuru It's being fixed https://github.com/Expensify/Expensify.cash/pull/3441.

**Comment by kavimuru** [comment]
## App crashes when editing a comment
## Expected Result: 
User is able to edit and save the message successfully
## Actual Result:
App keeps crashing when editing the message
## Actions Performed:
1. Launch the app and login
2. Hover over an owned message and click on the edit comment option in the menu
3. Start editing the message
## Platform:
iOS 
mWeb 
Android ✔️
## Build:
1.0.66-0
## Notes/Images/Video:
Bug5105065_Screenshot_20210609-114353_One_UI_Home_1_

https://user-images.githubusercontent.com/43996225/121389670-a89b1300-c91a-11eb-9ce0-b5d2cb79e3bd.mp4

[expensify.txt](https://github.com/Expensify/Expensify.cash/files/6625210/expensify.txt)

**Comment by Julesssss** [comment]
I believe this is no longer a deployBlocker, as this fix was merged and is on staging. Removing the label from here and the deploy issue.

File: src/pages/home/report/ReportActionItemMessageEdit.js (hunk 1 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionItemMessageEdit.js:55]: This change is going against our old pattern of not making the Component controlled.

**Comment by parasharrajat** [comment]
@Julesssss just a heads up, I feel that the change we have done here has unnecessary state updates. We just want to set the cursor at the end of the text when we initiate the edit. So why we are re-rendering it on every input and setting the cursor, making it a controlled input. I believe we are following uncontrolled Textinput throughout the app. Even here you can see at this line
https://github.com/Expensify/Expensify.cash/blob/19ad75ea6b6905ce31f37b5e8251d98e23add5a1/src/pages/home/report/ReportActionItemMessageEdit.js#L65
& 
https://github.com/Expensify/Expensify.cash/blob/19ad75ea6b6905ce31f37b5e8251d98e23add5a1/src/pages/home/report/ReportActionItemMessageEdit.js#L120. 
we don't use value prop intentionally. 

So I think I can submit a PR to replace the changes here with 
```
    componentDidMount() {
        this.textInput.setNativeProps({selection: {start: this.props.draftMessage.length, end: this.props.draftMessage.length}});
    }
```
What are your thoughts?

**Comment by Julesssss** [comment]
Thanks @parasharrajat, I need to review this on Monday but I think you make a good point. Have set a reminder to return to this.

**Comment by aliabbasmalik8** [comment]
@Julesssss 
We need a cursor position(`selection`) to add emojis in mid of the text. (there is an issue open to adding emojis functionality in the edit text compose box)

But for the 2nd point, we can use `Direct Manipulation` to avoid rerending also we can use this approach for the comment compose box. 

Thanks

**Comment by parasharrajat** [comment]
@Julesssss did you get chance to look at https://github.com/Expensify/Expensify.cash/pull/3434#issuecomment-859732106 ?

**Comment by Julesssss** [comment]
Ah, sorry I haven't yet. That makes sense to me though, good spot. 

Would you like to raise an issue for this, and we can get it exported?

**Comment by parasharrajat** [comment]
It's fine. Just a small change. Let me know PR will be up in no time.

**Comment by Julesssss** [comment]
I'll try to add a small bonus to an existing contract instead. Thanks @parasharrajat
