### PR TITLE
[CP Staging] Fix Custom Columns deploy blockers

### LINKED ISSUE #78021: [Due for payment 2025-12-30] Reports - "Maximum tax amount is 0.00" when editing amount after enabling Tax
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77836
**Email or phone of affected tester (no customers):** sdjoinsjoisjoisdnjo@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Expenses.
5. Click Columns.
6. Select Tax.
7. Click Save.
8. Click on the expense.
9. Click Amount.
10. Edit the amount and save it.

## Expected Result:
Amount can be edited.

## Actual Result:
Amount cannot be edited. "Maximum tax amount is MYR 0.00" error shows up.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/9323c790-ab64-4679-8111-8d8ab3849667

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

### LINKED ISSUE #78026: [Due for payment 2025-12-30] Reports - Original amount changes to $0.00 after changing the amount
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to validate in Prod - Provide reasoning.
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77814
**Email or phone of affected tester (no customers):** sdjoinsjoisjoisdnjo@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Expenses.
5. Click Columns.
6. Select Original amount.
7. Click Save.
8. Click on the expense.
9. Click Amount.
10. Edit the amount and save it.

## Expected Result:
Original amount will not change.

## Actual Result:
Original amount changes to $0.00 after changing the amount.
This issue also happens when editing other fields such as decription and merchant.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/cabe7961-9179-4451-9dc8-890cb0894dfa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

### LINKED ISSUE #78031: [Due for payment 2025-12-30] Reports - IOU report title is IOU instead of "x owes y"
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77777
**Email or phone of affected tester (no customers):** sdjoinsjoisjoisdnjo@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Open DM with any user.
3. Submit an expense to the user.
4. Go to Reports > Expenses.
5. Click Columns.
6. Select Title.
7. Click Save.
8. Scroll to Title column.

## Expected Result:
IOU report title will be "x owes y".

## Actual Result:
IOU report title is IOU.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/b1fb42a0-9ecc-4052-a866-d18bed04f31d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @brianlee-expensify</details>

### LINKED ISSUE #78038: [Due for payment 2025-12-30] Reports - Tax amount updates to the new amount, then reverts to initial amount
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77836
**Email or phone of affected tester (no customers):** smdosdinjosnjsoi@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
Precondition:
- Workspace has tax rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense with non-zero tax rate.
4. Go to Reports > Expenses.
5. Click Columns.
6. Select Tax.
7. Click Save.
8. Click on the expense.
9. Click Tax amount.
10. Edit the amount and save it.

## Expected Result:
Tax amount will update to the new amount.

## Actual Result:
Tax amount updates to the new amount, then reverts to initial amount.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/3929b904-89b2-4abc-920e-c0d636dafe0d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

### LINKED ISSUE #78042: [Due for payment 2025-12-30] Reports - Tax rate column does not show the applied rate when tax rate is deleted
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77836
**Email or phone of affected tester (no customers):** odjsodijsdoinjsdoi@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
Precondition:
- Workspace has tax rates.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense with tax rate.
4. Go to Reports > Expenses.
5. Click Columns.
6. Select Tax and Tax rate.
7. Click Save.
8. Go to workspace settings > Taxes.
9. Delete the tax rate used in Step 3.
10. Go to Reports > Expenses.

## Expected Result:
Tax rate column should still show the deleted rate (same as category).

## Actual Result:
Tax rate column does not show the applied tax rate when tax rate is deleted.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/e1f5724d-8555-41ff-866f-039c30220104

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

### LINKED ISSUE #78049: [Due for payment 2025-12-30] [HOLD on #78007] Reports - Original amount is 0.00 for scan expense
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77814
**Email or phone of affected tester (no customers):** odjsodijsdoinjsdoi@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a scan expense with a valid receipt..
4. Go to Reports > Expenses.
5. Click Columns.
6. Select Original amount.
7. Click Save.
8. Wait for scan expense to complete scanning.

## Expected Result:
Original amount will be the same as the receipt amount.

## Actual Result:
Original amount is 0.00 for scan expense.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/36bf1a72-7bcc-4317-93df-5c8f1254548c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

### LINKED ISSUE #78072: [Due for payment 2025-12-30] Reports - Columns overlap and table cannot be scrolled horizontally
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77895
**Email or phone of affected tester (no customers):** jsdoijdojnoinjisojsod@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Unapproved cash.
5. Expand the user row.
6. Click Columns.
7. Select all columns and click Save.
8. Expand the user row.
9. Try to scroll horizontally.

## Expected Result:
The table cannot be scrolled horizontally.

## Actual Result:
Columns overlap and table cannot be scrolled horizontally.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/3c68661d-41fe-4624-b335-8d7214bff2ef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @lydiabarclay</details>

### PR DESCRIPTION
**Pull request by luacmartins**
### Explanation of Change
Fixes several blockers related to custom columns

### Fixed Issues
$ https://github.com/Expensify/App/issues/78021
$ https://github.com/Expensify/App/issues/78026
$ https://github.com/Expensify/App/issues/78031
$ https://github.com/Expensify/App/issues/78038
$ https://github.com/Expensify/App/issues/78049
$ https://github.com/Expensify/App/issues/78072
$ https://github.com/Expensify/App/issues/78042 

### Tests
Same as fixed issues

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
Same as tests

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If new assets were added or existing ones were modified, I verified that:
    - [x] The assets are optimized and compressed (for SVG files, run `npm run compress-svg`)
    - [x] The assets load correctly across all supported platforms.
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
https://github.com/Expensify/App/issues/78021

https://github.com/user-attachments/assets/08613404-aea9-4673-903f-fb210656f085

https://github.com/Expensify/App/issues/78026

https://github.com/user-attachments/assets/14ed9e47-1704-499f-b5fa-ef38620cf4b7

https://github.com/Expensify/App/issues/78031

https://github.com/user-attachments/assets/e29d21d0-d27f-4f02-bec3-3414a01b4bc3

https://github.com/Expensify/App/issues/78072

https://github.com/user-attachments/assets/2e4217c4-6dd5-4c4a-b409-ec452927a0ee

<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

### CODE REVIEW

**Review by JS00001 — DISMISSED** [review]

**Review by JS00001 — APPROVED** [review]

**Review by brunovjk — APPROVED** [review]

File: src/components/TransactionItemRow/index.tsx [hunk 1]
```diff
@@ -550,7 +537,7 @@ function TransactionItemRow({
             [CONST.SEARCH.TABLE_COLUMNS.TITLE]: (
                 <View style={[StyleUtils.getReportTableColumnStyles(CONST.SEARCH.TABLE_COLUMNS.TITLE)]}>
                     <TextCell
-                        text={transactionItem.report?.reportName ?? ''}
+                        text={computeReportName(transactionItem.report) ?? transactionItem.report?.reportName ?? ''}
```
Comment (shubham1206agra) [inline src/components/TransactionItemRow/index.tsx:540]: @luacmartins I believe you should fetch report name from report attributes key. Can you please raise a fix to fix this?

Comment (luacmartins) [reply src/components/TransactionItemRow/index.tsx:540]: Is this causing an issue? AFAIK we use `computeReportName` to compute the report name since `report.reportName` doesn't have the correct name for IOUs for example

Comment (shubham1206agra) [reply src/components/TransactionItemRow/index.tsx:540]: @luacmartins `computeReportName` is a very expensive function for generating report names. We do the report name generation in the derived value system. Using derived values, we can get rid of redundant operations.

Comment (luacmartins) [reply src/components/TransactionItemRow/index.tsx:540]: I see. I think we should update [this comment](https://github.com/Expensify/App/blob/20823b8bd6b301c4447f895cc9b61cadd7d497c5/src/libs/ReportUtils.ts#L5550-L5555) then to suggest using the derived value
