### PR TITLE
Fix #80346: Navigate to Workspaces after self-revoking domain admin access

### LINKED ISSUE #80346: [$250] Domains - Not here page opens after removing yourself as admin
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.3.6-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/79765
**Email or phone of affected tester (no customers):** applausetester+210102abc@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Exploratory - Significant User Experience Deterioration
**Device used:** Mac 26.1 / Chrome
**App Component:** Workspace Settings

## Action Performed:
Precondition:
- Log in as domain admin which is not primary contact.

1. Go to staging.new.expensify.com
2. Go to Workspaces.
3. Scroll to the bottom.
4. Tap applause.expensifail.com domain.
5. Go to Domain admins.
6. Tap on your own profile.
7. Tap Revoke access.
8. Tap Remove.

## Expected Result:
User will be redirected to Workspaces page after removing themselves as admin.

## Actual Result:
Not here page opens after removing themselves as admin.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/a708e411-a0c0-46cb-b927-6c67e3e265b0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~022014735920364075423</li>
        <li>Upwork Job ID: 2014735920364075423</li>
        <li>Last Price Increase: 2026-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>MobileMage | Contributor | 110313073</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

### PR DESCRIPTION
**Pull request by MobileMage**
### Explanation of Change
When a domain admin removes their own admin access, `DomainInitialPage` renders `FullPageNotFoundView` because `!domain || !isAdmin` evaluates to true — but the user is never navigated away, so they see a "Not here" page.

This PR adds a `useEffect` with a loading guard (using `isLoadingOnyxValue`) that automatically navigates the user back to the Workspaces list when they lose admin access. This mirrors the existing pattern in `DomainNotFoundPageWrapper.tsx`.

### Fixed Issues
$ https://github.com/Expensify/App/issues/80346
PROPOSAL: https://github.com/Expensify/App/issues/80346#issuecomment-2855188498

### Tests
**Precondition:** Log in as a domain admin which is **not** the primary contact.

**Test 1 — Self-revoke redirects to Workspaces:**
1. Go to dev.new.expensify.com
2. Go to **Workspaces** (bottom tab bar)
3. Scroll to the bottom of the Workspaces list
4. Tap the domain (e.g. `applause.expensifail.com`)
5. Tap **Domain admins**
6. Tap on your own profile
7. Tap **Revoke access**
8. Tap **Remove** to confirm
9. Verify you are redirected to the **Workspaces** page (not a "Not here" page)
10. Verify that no errors appear in the JS console

**Test 2 — Normal admin access still works:**
1. Log in as a domain admin
2. Navigate to **Workspaces** > domain > **Domain admins**
3. Verify the page loads normally and you can see the list of admins
4. Navigate to **Workspaces** > domain > **SAML**
5. Verify the page loads normally
6. Verify that no errors appear in the JS console

- [x] Verify that no errors appear in the JS console

### Offline tests
**Precondition:** Log in as a domain admin which is **not** the primary contact.

1. Go to **Workspaces** and tap on a domain to open domain settings
2. Verify the domain page loads correctly
3. Turn off your network connection (airplane mode / disable Wi-Fi)
4. Verify the domain page still displays correctly and you are **not** falsely redirected to Workspaces
5. Turn your network connection back on
6. Verify normal behavior resumes and the domain page remains accessible

### QA Steps
**Precondition:** Log in as a domain admin which is **not** the primary contact.

1. Go to staging.new.expensify.com
2. Go to **Workspaces** (bottom tab bar)
3. Scroll to the bottom of the Workspaces list
4. Tap the domain (e.g. `applause.expensifail.com`)
5. Tap **Domain admins**
6. Tap on your own profile
7. Tap **Revoke access**
8. Tap **Remove** to confirm
9. Verify you are redirected to the **Workspaces** page instead of seeing a "Not here" page
10. Verify that no errors appear in the JS console

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If new assets were added or existing ones were modified, I verified that:
    - [x] The assets are optimized and compressed (for SVG files, run `npm run compress-svg`)
    - [x] The assets load correctly across all supported platforms.
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/45cec04b-fec4-45ca-b716-3b2679ef36c6

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/6db79406-afd3-4f8d-b739-e047a01fb316

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/2c9dc4bf-4283-4c04-bfa0-9c28703afea7

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/51fe2970-8e1d-46d5-86c5-4203ad43da1d

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/0f15924a-997a-4d6e-9e78-b0b159c3aa3a

</details>

### CODE REVIEW

**Review by joekaufmanexpensify — DISMISSED** [review]
Good from product 👍

**Comment by Krishna2323** [comment]
@MobileMage on native app, I get a console error after revoking access. Could you please check and see if that's related?


image


https://github.com/user-attachments/assets/fcdc56ad-df67-42b6-8a40-1657d3fd7769

**Comment by Krishna2323** [comment]
@MobileMage bump!

File: src/pages/domain/Admins/DomainAdminDetailsPage.tsx [hunk 1]
```diff
@@ -63,7 +63,7 @@ function DomainAdminDetailsPage({route}: DomainAdminDetailsPageProps) {
         }
 
         revokeDomainAdminAccess(route.params.domainAccountID, route.params.accountID);
-        Navigation.dismissModal();
+        Navigation.goBack(ROUTES.WORKSPACES_LIST.route);
```
Comment (Krishna2323) [inline src/pages/domain/Admins/DomainAdminDetailsPage.tsx]: This navigates to `WORKSPACES_LIST` for all revocations, including when admin A revokes admin B’s access. In that case, admin A should remain in the domain context (i.e., go back to the domain admins list) and should not be navigated to the workspaces page.

**Review by Krishna2323 — CHANGES_REQUESTED** [review]

File: src/pages/domain/Admins/DomainAdminDetailsPage.tsx (hunk 1 above)
Comment (MobileMage) [reply src/pages/domain/Admins/DomainAdminDetailsPage.tsx]: I can make this navigate conditionally based on whether it's a self-revoke or not go to `WORKSPACES_LIST` only when revoking yourself, otherwise go back to the domain admins list:

```diff
     const {translate, formatPhoneNumber} = useLocalize();
+    const {accountID: currentUserAccountID} = useCurrentUserPersonalDetails();
...
         revokeDomainAdminAccess(route.params.domainAccountID, route.params.accountID);
-        Navigation.goBack(ROUTES.WORKSPACES_LIST.route);
+        const isSelfRevoke = Number(route.params.accountID) === currentUserAccountID;
+        Navigation.goBack(isSelfRevoke ? ROUTES.WORKSPACES_LIST.route : ROUTES.DOMAIN_ADMINS.getRoute(Number(route.params.domainAccountID)));
```

Comment (Krishna2323) [reply src/pages/domain/Admins/DomainAdminDetailsPage.tsx]: @MobileMage Did [this issue](https://github.com/Expensify/App/pull/81209#issuecomment-3857500279) came from the original PR changes, or was it already there before? Could you please check? If it was already happening on main, we can probably leave it as is and handle it separately.

Comment (MobileMage) [reply src/pages/domain/Admins/DomainAdminDetailsPage.tsx]: @Krishna2323 Just checked on main and this console error is already happening there too, it's not introduced by this PR.

Happy to fix it separately\!

Comment (Krishna2323) [reply src/pages/domain/Admins/DomainAdminDetailsPage.tsx]: Please remove the changes related to that for now, as it requires proper investigation and implementation to avoid regressions. We can create a separate issue for it and handle it independently.

Comment (Krishna2323) [reply src/pages/domain/Admins/DomainAdminDetailsPage.tsx]: @MobileMage bump

File: src/pages/domain/DomainInitialPage.tsx [hunk 2]
```diff
@@ -100,6 +101,16 @@ function DomainInitialPage({route}: DomainInitialPageProps) {
 
     useConfirmReadyToOpenApp();
 
+    const shouldShowFullScreenLoadingIndicator = isLoadingOnyxValue(domainMetadata);
```
Comment (Krishna2323) [inline src/pages/domain/DomainInitialPage.tsx]: @MobileMage I think we should also pass `adminMetadata` to prevent premature navigation before Onyx data loads.

**Review by Krishna2323 — CHANGES_REQUESTED** [review]

File: src/pages/domain/DomainInitialPage.tsx (hunk 2 above)
Comment (MobileMage) [reply src/pages/domain/DomainInitialPage.tsx]: Done

**Review by Krishna2323 — APPROVED** [review]
LGTM! 🚀

**Review by mountiny — APPROVED** [review]
