### PR TITLE
[IS-2601] fixed cursor position after adding emoji

### LINKED ISSUE #2601: Web - After adding the emoji, cursor is not in the front of the message
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Emoji is added to the text input field and cursor moves forward

## Actual Result:
Cursor does not move after adding an emoji and user has to manually move the cursor in front of the emoji

## Action Performed:
1. Go to staging.expensify.cash and login with credentials
2. Tap any contact from the LHN
3. In the text input field type some text then select an emoji

## Workaround:
User has to manually move the cursor

## Platform:
Where is this issue occurring?

 Web ✔️ (MacOS Safari only) 
 iOS
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.32-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/44479856/116305984-81292600-a772-11eb-812e-897dfa7a645f.mp4

**Expensify/Expensify Issue URL:**

view this job on upwork [here](https://www.upwork.com/jobs/~019cc8e9b14b76f110) 

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by aliabbasmalik8**
### Details
Fixed these issues
1.  Update Cursor position after adding emoji in safari
2. Make input focus after adding emoji
3. when the cursor in the middle of the text the emoji added at the end of the text, Also fixed this issue and add emoji to the current cursor position.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2601

### Tests
1.  Add emoji in the safari browser.
2.  Add emoji in the middle of text

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
**VIDEO**: https://recordit.co/ziMaD0TipI
#### Mobile Web
**VIDEO**: https://recordit.co/WFYVuK3m9z
#### Desktop
**VIDEO** :https://recordit.co/WvLfDW0iEx
#### iOS
**VIDEO**: https://recordit.co/7ULinokWwp
#### Android
https://user-images.githubusercontent.com/31027036/119298365-bf9aef00-bc11-11eb-8a2e-5b9b5da12c2b.mp4

### CODE REVIEW

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -127,6 +128,10 @@ class ReportActionCompose extends React.Component {
                 horizontal: 0,
                 vertical: 0,
             },
+            selection: {
+                start: props.comment.length,
+                end: props.comment.length,
```
Comment (nickmurray47) [inline src/pages/home/report/ReportActionCompose.js:133]: why is the `start` and `end` the same here?

**Review by nickmurray47 — COMMENTED** [review]
looks good! just had a question about the selection object

File: src/pages/home/report/ReportActionCompose.js (hunk 1 above)
Comment (aliabbasmalik8) [reply src/pages/home/report/ReportActionCompose.js:133]: it's the initial cursor position.
if the `start` and `end` not equal that means some text selected from start to end

**Review by nickmurray47 — APPROVED** [review]

**Comment by isagoico** [comment]
## Android - Cursor is not in front of the emoji

## Expected Result
Cursor position should display in front of the emoji 

## Actual Result
Cursor position is not in front of the emoji. Sometimes is behind the emoji and sometimes 2 characters ahead. 

## Action Performed
1. Launch the app
2. Log in with any account
3. Type some text
4. Add emoji in the middle of text

## Platform 

Android ✔️ 

**Notes/images/videos**
image

https://user-images.githubusercontent.com/44479856/119721530-3bc34b80-be39-11eb-8284-ee38b87dbd46.mp4

**Comment by isagoico** [comment]
@aliabbasmalik8 / @nickmurray47 can this issue be considered a deploy blocker? Or should I open a different issue for this? Only affected platform is Android.

**Comment by aliabbasmalik8** [comment]
@isagoico according to mine, This issue is not a deploy blocker. It's related to the current task. Looking into this ISSUE.

**Comment by aliabbasmalik8** [comment]
@isagoico can you please open a different issue for this?
@nickmurray47 to fix this issue on `android` I need to use `selection` props in `TextInput` but `selection` props have a serious issue on `android and ios`.  and It's an open issue in React Native official repository `facebook/react-native/issues/29063`.
I'm also looking for some solution but till now not found.
Looking for your suggestion.
Thanks

**Comment by isagoico** [comment]
New issue created here https://github.com/Expensify/Expensify.cash/issues/3186

**Comment by nickmurray47** [comment]
@aliabbasmalik8 I tested on iOS and web but not on Android. Is there a reason why this issue did not come up when you tested on Android?

**Comment by nickmurray47** [comment]
@isagoico sorry for the late reply, but please do not clear a deploy blocker unless the commenter is an Expensify employee.
