### PR TITLE
Fix: urls for user details

### LINKED ISSUE #3924: [Hold for Payment 11 August] [Crash] App crashes on directly opening the user details
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any 1:1 conversation on E.cash.
2. Click the Chat title.
3. User details page should open.
4. Reload the page on the web.

## Expected Result:
App Should not crash.

## Actual Result:
 On local we see error `404 page not found` and on staging App crashes.
 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
go back to the Home page and then navigate to the user details.

## Platform:
Where is this issue occurring?

 Web :heavy_check_mark: 
 iOS
 Android
 Desktop App
 Mobile Web :heavy_check_mark: 

**Version Number:** latest
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/24370807/126659715-a0e460a7-18ad-4f0b-b2bd-569f712c5415.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details

This issue was caused due to the reason that Url Path had `.` which is not being parsed in React-navigation. I have also reported the issue to React-navigation but nobody is even bothering to reply so we have to fix it with a patch in our app. I will submit a new PR as soon as I got some leads on that issue which is very unlikely.

To fix, PR does the following:
1. Covert the route param `:login` to query param `?:login=xxx` which fixes the issue. and routes are parsed successfully.
e.g. `https://staging.expensify.cash/details/:login` to `https://staging.expensify.cash/details?login=:login`

### Fixed Issues

$ Fixes #3924

### Tests | QA Steps
1. Open Any chat in E.cash on web.
2. Click user avatar to see its details.
3. refresh the page, you should land on the same page and app should not crash.

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

https://user-images.githubusercontent.com/24370807/127411771-a160378f-4966-44ae-8566-75d60f440c0b.mp4

### CODE REVIEW

File: src/ROUTES.js [hunk 1]
```diff
@@ -96,4 +96,22 @@ export default {
             isParticipantsRoute: Boolean(lodashGet(pathSegments, 2)),
         };
     },
+
+    /**
+     * React Navigation is failing to parse urls with dot in the path segment.
+     * This method enable pasring of urls with dot in path Segment
```
Comment (chiragsalian) [inline src/ROUTES.js:102]: NAB: switch 'enable' with 'enables'.
switch 'pasring' with 'parsing'.

File: src/ROUTES.js [hunk 2]
```diff
@@ -96,4 +96,22 @@ export default {
...
+     * @param {String} path - Path for the config
+     * @returns {Object}
+     */
+    getEmailRouteLinkingConfig: path => ({
```
Comment (chiragsalian) [inline src/ROUTES.js:106]: In the PR details you explain why you moved away from the initial solution but i don't quite understand the current solution. Can you add it to your PR or explain it to me.

Comment (parasharrajat) [reply src/ROUTES.js:106]: @chiragsalian  We can customize the default param parsing by using the parse and stringify option for LinkingConfig.
1. In stringify, I replace all the dots with `@dot@` safely. we first encode the existing `@dot@` in the URL and then do the dot conversion. Which will allow `@dot@` to be part of the email.
2. In parse, we revert to the original email by first converting `@dot@` back to dot and then replace the escaped version of `@dot@` back to `@dot@`.

Comment (parasharrajat) [reply src/ROUTES.js:106]: Any thoughts @chiragsalian.

Comment (chiragsalian) [reply src/ROUTES.js:106]: Ah nice, i had no idea. I just read more about this [here](https://reactnavigation.org/docs/configuring-links/#passing-params) too. Well it makes sense to me and i think its fine, but i'll loop in @marcaaron too for additional thoughts.

Comment (parasharrajat) [reply src/ROUTES.js:106]: @marcaaron Do you have any thoughts on this issue?

Comment (parasharrajat) [reply src/ROUTES.js:106]: Hey @marcaaron What do you think about it? Sorry for the ping.

File: src/ROUTES.js [hunk 3]
```diff
@@ -96,4 +96,22 @@ export default {
...
+        path,
+        parse: {
+            login: l => (l
+                ? decodeURIComponent(l).replace('@dot@', '.').replace(encodeURIComponent('@dot@'), '@dot@')
```
Comment (marcaaron) [inline src/ROUTES.js:110]: What does the second `.replace()` achieve here? Didn't we replace with `.` already?

File: src/ROUTES.js [hunk 4]
```diff
@@ -96,4 +96,22 @@ export default {
...
+                : undefined),
+        },
+        stringify: {
+            login: l => (l ? l.replace('@dot@', encodeURIComponent('@dot@')).replace('.', '@dot@') : undefined),
```
Comment (marcaaron) [inline src/ROUTES.js:114]: The logic here is also confusing... 

```js
l
    .replace('@dot@', encodeURIComponent('@dot@'))
    .replace('.', '@dot@')
```

- We are replacing the `@dot@` with `%40dot%40`
- Then we replace all `.` with `@dot@`... 

Why?

**Review by marcaaron — CHANGES_REQUESTED** [review]

**Comment by marcaaron** [comment]
@parasharrajat Is there some more context on the `@dot@` addition? URLs are going to look pretty weird after we do this no? Just wondering if we checked with anyone whether the weird looking urls are what we want.

File: src/ROUTES.js (hunk 3 above)
Comment (parasharrajat) [reply src/ROUTES.js:110]: I added this for safe parsing. In case the email already contains `@dot@` e.g. `rajat"@dot@"parashar@gmail.com`. Please let me know if I have forgotten to encounter any special cases.

`@dot@` I just took it based on the meaning. dot for `.` and `@` is a special URL character that allows us to safely convert emails that can contain `@dot@` as part of the string. 
`@` will be escaped and thus we can use it.

File: src/ROUTES.js (hunk 4 above)
Comment (parasharrajat) [reply src/ROUTES.js:114]: Maybe, I have answered it above. First replace will escape the existing `@dot@` from email and then we can use `@dot@` to convert `.`.

**Comment by parasharrajat** [comment]
I checked out on google, Using emails as URL is not a recommended thing as emails are considered private data. So if we use them in URL then it is kind of public. But we are not using any userIds so It's kind of good that the URL does not look like containing emails and bots can't read emails from it.
Thoughts?

File: src/ROUTES.js (hunk 3 above)
Comment (marcaaron) [reply src/ROUTES.js:110]: >In case the email already contains @dot@ e.g. rajat"@dot@"parashar@gmail.com. Please let me know if I have forgotten to encounter any special cases.

Sorry, not following. Why would a valid email have more than one `@` let alone an `@dot@` in it?

**Comment by marcaaron** [comment]
>I checked out on google, Using emails as URL is not a recommended thing as emails are considered private data. So if we use them in URL then it is kind of public. But we are not using any userIds so It's kind of good that the URL does not look like containing emails and bots can't read emails from it.

- The emails are easily accessible. What do we achieve by obscuring them in the URL only?
- The app is used to converse with people you know and work with not random people. Maybe that will change in the future, but it's not a problem today.

>we are not using any userIds so It's kind of good that the URL does not look like containing emails and bots can't read emails from it

I'm not sure this is a problem we need to solve right now, but could also not be understanding which bots we should be worried about.

To clarify, my concern is that the url looks weird and I don't see any discussion about how we landed on `@dot@` or other alternatives. Is there another way to do this? e.g. query params vs. path?

File: src/ROUTES.js (hunk 3 above)
Comment (parasharrajat) [reply src/ROUTES.js:110]: Ok. I saw somewhere that @ can be used in quotes. I believe I overthink it. I 'll remove the extra escaping.

Comment (parasharrajat) [reply src/ROUTES.js]: @marcaaron Updated the PR. Removed the Extra escaping stuff.

**Comment by parasharrajat** [comment]
Yeah, we can do this we Query param. This was the original Idea. But Route will not be strictly matched with the Query param.
for example, /details is equal to /details?user=xxxx;

We can definitely use query params. Let me know? Thanks.

**Comment by marcaaron** [comment]
We could maybe bring this up in Slack? I feel others may have opinions to share.

**Comment by parasharrajat** [comment]
Ok @marc after discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1627942434082700. I have used query params.

**Comment by parasharrajat** [comment]
@marcaaron This is ready. Please let me know if there is something that needs to be changed.

**Comment by marcaaron** [comment]
Thanks for the bump! Can we fix up the description so it reflects the final decision that was made?

**Comment by parasharrajat** [comment]
Done. Thanks for mentioning that.

**Comment by chiragsalian** [comment]
Did you retest? The moment i click on an avatar i get an error,
image

Okay looks like normal emails work. I got the failure with the email chirag+15@expensify.com which is a pretty normal test email to have. Would you be able to address this?

**Comment by parasharrajat** [comment]
@chiragsalian Yes I retested it but I didn't test the URL with Plus. I have fixed this issue. 
I think escaping is not happening for query params so I have added it myself and tested it.

**Review by chiragsalian — APPROVED** [review]
Nice, LGTM and works great 👍 
@marcaaron all yours.

**Review by marcaaron — APPROVED** [review]
