### PR TITLE
Fix ExpensiInput autoFocus & tab Focus

### LINKED ISSUE #4514: Input does not handle Tab focus and autofocus correctly.
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issues: 
1. New text input requires extra keystroke when using tab to get focus
2. Autofocus is not set correctly.

## Action Performed:

1. Open the Login page.
2. Observe the email input.
3. Go to the password page, observe the password input. It is auto-filled, but input is not focused.
4. Now try to navigate use the Tab key. Users have to press tag two times to set the focus on Input.

## Expected Result:
When autofocus is used, Input should be focused and the border should be shown on the input. 
The label should float top when input is focused.
Single Tab keystroke should set the focus in the input.

## Actual Result:

Input is not focused and the label is overriding the Input text. The cursor is placed on the Input but the label is not placed correctly and there is no blue border that shows the focused state. Users have to press the tab two times to get focus on the input.

## Workaround:
Clear the input and refocus.

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
image

#### Video
https://expensify.slack.com/files/UDQLCFDRA/F02AZA1V0GL/2021-08-10_10-31-21.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

Slack => https://expensify.slack.com/archives/C01GTK53T8Q/p1628627644189200

[Upwork Job](https://www.upwork.com/jobs/~01673ebd31e3f4ca80)

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ Fixes #4514

### Tests | QA Steps
1. Open the Login page on the Web.
2. Observe the email input. It should be autofocused correctly.
3. Go to the password page, observe the password input. If it is auto-filled, input should be focused correctly.
4. Now try to navigate using the Tab key. Ony single tab pres, the focus should be set on the Input.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/24370807/128928131-a9ad7ac5-1e05-48eb-8241-71b4293baec6.mp4

#### Mobile Web

foucs-fix-m

#### Android

fcous-fix-a

### CODE REVIEW

**Comment by francoisl** [comment]
@roryabraham do we need to apply the `CP Staging` label before merging this?

**Comment by roryabraham** [comment]
@francoisl Yep!

**Comment by roryabraham** [comment]
Actually JK I am going to remove the CP label in this case to help me finish testing https://github.com/Expensify/App/pull/4274 for the case of manual CP's

**Review by roryabraham — DISMISSED** [review]
So I tested this on iOS Safari and also desktop and it seems to work as expected 👍 

However, I think we _maybe_ should leave a comment explaining why we are not using the `autoFocus` prop, to prevent someone coming along and undoing this in the future. NAB though.

File: src/components/ExpensiTextInput/BaseExpensiTextInput.js [hunk 1]
```diff
@@ -34,6 +34,12 @@ class BaseExpensiTextInput extends Component {
         this.onBlur = this.onBlur.bind(this);
     }
 
+    componentDidMount() {
+        if (this.props.autoFocus && this.input) {
```
Comment (roryabraham) [inline src/components/ExpensiTextInput/BaseExpensiTextInput.js:38]:
```suggestion
        // We are manually managing focus to prevent this issue: https://github.com/Expensify/App/issues/4514
        if (this.props.autoFocus && this.input) {
```

**Comment by parasharrajat** [comment]
@roryabraham Your suggestions are up. Thanks.

**Comment by roryabraham** [comment]
I am going to merge this w/o waiting for E2E because I want to test the CP audit trail and because the only change between the previous commit, which passed all checks, is a comment.

**Review by roryabraham — APPROVED** [review]

**Comment by roryabraham** [comment]
CPing this here: https://github.com/Expensify/App/actions/runs/1125331217

**Comment by roryabraham** [comment]
Staging deploy is running [here](https://github.com/Expensify/App/actions/runs/1125339885), so hopefully once that finishes we'll see a comment on this PR to the tune of: "CPed to staging by @roryabraham..."

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-08-24.  :confetti_ball:

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-06.  :confetti_ball:
