### PR TITLE
Only fetch report history we need on reconnect + fix sign out issue

### LINKED ISSUE #2615: Fetching report history on reconnect is inefficient and causes issues for sign out
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
If we already have local report actions for a report we don't need to fetch them again.
If we log out quickly after logging in the app does not end up in a bad state.

## Actual Result:
Even though we are up to date on a report's history we will still re-download the 50 most recent items on reconnect
If we log in and out quickly the app appears to get caught in some kind of infinite loop.

## Actions Performed:
1. Be me
1. Have chat history already downloaded
1. Go offline and back online
1. See that we are fetching the history for all reports and returning up to 50 comments we already have for each

Screen Shot 2021-04-28 at 12 26 22 PM

1. Sign in and sign out quickly
2. See that the app tries to make API requests that it should not and gets caught in some sort of infinite loop.

## Workaround:
This mostly leads to performance issues like slowdowns from having to re-download things we've already got.

## Platform:
Where is this issue occurring?

Everywhere

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by marcaaron**
### Details

This PR is a little all over the place since I cleaned a few things up as I went, but mostly addresses two major issues:

1. When reconnection callbacks fire we are re-downloading report history even if we have that history stored to disk. This is inefficient and also causes a network request to fire for each chat you have - which can be quite a lot of requests and really bog things down, trigger storage eviction, etc.
2. I also noticed we were delaying a few network requests with timers and not cleaning them up on sign out which means that we would call them needlessly. Rather than allow this to happen I created a way to prevent that from happening in the `Timers` namespace. We register a timer id and then just clear them all on sign out.

**Other minor issues also being cleaned up here:**
- `NetworkConnection.stopListeningForReconnect()` was being called twice for no clear reason on sign out
- We were also still checking to see if we are on the `signin` route when signing out but that route was recently removed

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2615

### Tests
1. Log in as USER A (easy to inspect storage and networking on web or desktop so use one of those)
2. Close the tab
3. Add several comments to a report shared with USER A as USER B (use separate session e.g. incognito tab)
4. In USER A browser session create a new empty tab and open Chrome Dev Tools to reveal the Network tab
5. Paste the sites's url and hit enter
6. Watch the Network tab and verify that you don't see tons of requests to `Report_GetHistory` and only see the one for the report with new content
7. Inspect the response and verify that the `history` array only has as many comments as were added on the previous report.
8. Refresh the page and wait watching the JS console for the log
```
[info] [Report] Local reportActions up to date. Not fetching additional actions. - {}
```
9. Log out and log back in several times and verify there are no issues doing so

### QA Steps
1. Log in and log out repeatedly on the various platforms and verify there are no issues doing so

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by marcaaron** [comment]
@tgolen I'd like to get your review, but want to give @jasperhuangg and @Beamanator a shot at reviewing first if that's OK.

I'm open to feedback on any alternative ways to tackle these problems if we can identify some together. Thanks!

**Review by jasperhuangg — DISMISSED** [review]
Tested and it works great, plus the URL issue was fixed! Thanks for the opportunity to review, it was very insightful. Feel free to add https://github.com/Expensify/Expensify.cash/issues/2620 to the OP as another issue that's fixed!

**Review by Beamanator — COMMENTED** [review]
Looks pretty slick! Nice work! Tests also worked out well 💪 

Added only a few NAB comments

File: src/libs/actions/Report.js [hunk 1]
```diff
@@ -54,6 +56,35 @@ Onyx.connect({
...
+        if (!key || !val) {
+            return;
+        }
+
+        const reportID = CollectionUtils.extractCollectionItemID(key);
+        const mostRecentAction = _.chain(val)
+            .filter(action => !action.loading)
+            .sortBy('sequenceNumber')
+            .last()
+            .value();
```
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/libs/actions/Report.js:78]: Oh that's nice. However, I think this is a [lodash](https://lodash.com/docs/4.17.15#maxBy) method and unsure if I can use it with underscore's `chain()`.

Maybe I can use `find()` instead here if we are worried about complexity. The object of report actions _should_ be sorted by default since it's not an array. 

So if we reverse it then take the first one that isn't loading we could achieve something similar. I guess I didn't see much performance impacts from this so I didn't worry about it too much. But that might be a cleaner way to do it.

File: src/CONST.js [hunk 2]
```diff
@@ -125,6 +125,10 @@ const CONST = {
         STAGING: 'STG',
         PRODUCTION: 'PROD',
     },
+    DELAY: {
+        STARTUP: 8000,
```
Comment (tgolen) [inline src/CONST.js:129]: Please add comments to explain what these constants are for and why the values are what they are.

File: src/libs/actions/Report.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/libs/actions/Report.js]: Tried something else here...

- Turned the actions into an array
- Used [`findLastIndex`](https://underscorejs.org/#findLastIndex) to iterate in reverse and get the first non loading

**Comment by marcaaron** [comment]
Updated

File: src/libs/actions/Report.js [hunk 3]
```diff
@@ -54,6 +56,35 @@ Onyx.connect({
     },
 });
 
+/**
+ * Map of the most recent non-loading report history items we have stored for a report. Not to be confused with the
+ * reportMaxSequenceNumbers. We can compare these values to those to determine whether there is "available history"
```
Comment (tgolen) [inline src/libs/actions/Report.js:61]: I'm not sure what "these" and "those" refer to. Can you update this to be explicit, please?

File: src/libs/actions/Report.js [hunk 4]
```diff
@@ -54,6 +56,35 @@ Onyx.connect({
...
+ * to fetch from the server. maxSequenceNumber is retrieved when getting the reportList whereas these keep track of
+ * the actual reportActions saved in Onyx.
+ */
+const maxReportActionsSequenceNumbers = {};
```
Comment (tgolen) [inline src/libs/actions/Report.js:65]: This is definitely confusing with `maxSequenceNumber` now and unfortunately, the comment doesn't clear it up enough. I think they are both listening to different keys, but I can't figure out why there would be a difference between the two, why that difference is OK, and what that difference has to do with history being available to download from the server. I think the comment can do a better job of explaining why each map is different, as well as explaining why they can get out of sync, why it's OK that they get out of sync, and what is useful about that information as it pertains to downloading new content from the server. If you want me to take a stab at it, let me know, but I think I need to make sure I get my head wrapped around this logic first before I can be of any more help.

File: src/libs/actions/Report.js [hunk 5]
```diff
@@ -773,28 +802,47 @@ function fetchAllReports(
...
+            // Optionally delay fetching report history as it significantly increases sign in to interactive time.
+            const timerID = setTimeout(() => {
+                // Filter reports to see which ones have actions we need to fetch so we can preload Onyx with new
+                // content and improve chat switching experience by only downloading content we don't have yet.
+                // This improves performance significantly when reconnecting by limiting API requests and unnecessary
+                // data processing by Onyx.
+                const reportIDsToFetchActions = _.filter(returnedReportIDs, id => (
+                    _.isUndefined(maxReportActionsSequenceNumbers[id])
+
+                    // The most recent reportAction we have stored is less than the maxSequenceNumber for a report.
```
Comment (tgolen) [inline src/libs/actions/Report.js:823]: This sentence reads like it's incomplete... I'm not really sure what it's trying to explain.

File: src/libs/actions/Report.js [hunk 6]
```diff
@@ -773,28 +802,47 @@ function fetchAllReports(
...
+                    // This works because the reportMaxSequenceNumber is based on the reportActionList whereas the
```
Comment (tgolen) [inline src/libs/actions/Report.js:824]: "This works..." what is "This" referring to?

File: src/libs/actions/Report.js [hunk 7]
```diff
@@ -773,28 +802,47 @@ function fetchAllReports(
...
+                    // maxReportActionsSequenceNumbers can only be populated by adding reportActions to Onyx.
```
Comment (tgolen) [inline src/libs/actions/Report.js:825]: Maybe this is a more helpful context to put up by the Onyx connections.

File: src/libs/actions/Report.js [hunk 8]
```diff
@@ -773,28 +802,47 @@ function fetchAllReports(
...
+                    || maxReportActionsSequenceNumbers[id] < reportMaxSequenceNumbers[id]
+                ));
+
+                if (!_.isEmpty(reportIDsToFetchActions)) {
+                    Log.info('[Report] Fetching report actions for reports', true, {reportIDsToFetchActions});
```
Comment (tgolen) [inline src/libs/actions/Report.js:830]: Why is this being logged?

File: src/libs/actions/Report.js [hunk 9]
```diff
@@ -773,28 +802,47 @@ function fetchAllReports(
...
+                    _.each(reportIDsToFetchActions, (reportID) => {
+                        const offset = maxReportActionsSequenceNumbers[reportID];
+                        fetchActions(reportID, offset);
+                    });
+                } else {
+                    Log.info('[Report] Local reportActions up to date. Not fetching additional actions.', true);
```
Comment (tgolen) [inline src/libs/actions/Report.js:836]: Also here, why log this to the server?

File: src/libs/actions/Report.js [hunk 10]
```diff
@@ -773,28 +802,47 @@ function fetchAllReports(
...
+
+                // We are waiting a set amount of time to allow the UI to finish loading before bogging it down with
+                // more requests and operations. Startup delay is longer since there is a lot more work done to build
+                // up the UI when the app first initializes.
+            }, shouldDelayActionsFetch ? CONST.DELAY.STARTUP : CONST.DELAY.RECONNECT);
 
-            // We are waiting 8 seconds since this provides a good time window to allow the UI to finish loading before
-            // bogging it down with more requests and operations.
-            }, shouldDelayActionsFetch ? 8000 : 0);
+            // Register the timer so we can clean it up on sign out if it has not yet fired.
```
Comment (tgolen) [inline src/libs/actions/Report.js:844]: How is it even possible that this timer would never fire?

**Review by tgolen — CHANGES_REQUESTED** [review]
I'm a bit confused how the two datasets play with each other, but I like the general idea!

File: src/libs/actions/Report.js (hunk 4 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:65]: Lemme try a bit harder here. It sounds like you're getting it, but the comment doesn't explain some things that make sense to _me_ because I wrote this code.

File: src/libs/actions/Report.js (hunk 8 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:830]: Can remove it at this point. It was helpful when debugging whether the reconnection callbacks are happening or not, but there are other logs that can tell us this.

File: src/libs/actions/Report.js (hunk 10 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:844]: Will add a comment but the case is just logging in then logging out before the timer goes.

File: src/libs/actions/Report.js (hunk 4 above)
Comment (marcaaron) [reply src/libs/actions/Report.js]: Just went for this! I think it works and resolves a concern I have about people getting confused about which map to refer to in the future.

**Comment by marcaaron** [comment]
Ok so after chatting with @tgolen for a while about this I eventually landed on...

Moving the `maxReportActionsSequenceNumber` map into a new `actions/ReportActions.js` file. 

The intent here is that eventually other "reportActions" related actions can be moved into that file, but it would take too long to unwind right now.

The biggest concern I have with adding this new map is that it's confusing and people should find very few reasons to use it. To encourage this, I made a helper method that is exported by `ReportActions.js` called `dangerouslyGetReportActionsMaxSequenceNumber()` and it will throw angry error logs in the console unless explicitly silenced. I think that name + the `console.error` should discourage people from mistaking this for a more useful function.

**Comment by marcaaron** [comment]
Updated

File: src/libs/actions/Report.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (jasperhuangg) [reply src/libs/actions/Report.js]: > However, I think this is a [lodash](https://lodash.com/docs/4.17.15#maxBy) method and unsure if I can use it with underscore's `chain()`.

Oh derp, didn't even realize there was a distinction 😅, good job with your new solution though!

**Review by jasperhuangg — DISMISSED** [review]

File: src/libs/actions/Report.js [hunk 11]
```diff
@@ -56,7 +58,19 @@ Onyx.connect({
...
+ *
+ * There are several sources that can set the most recent reportAction's sequenceNumber for a report:
+ *
+ *     - Fetching the report object
+ *     - Fetching the report history
+ *     - Optimistically creating a report action
+ *     - Handling a report action via Pusher
+ *
+ * Those values are stored in reportMaxSequenceNumbers and treated as the main source of truth about what a report's max
+ * sequenceNumber is.
```
Comment (Beamanator) [inline src/libs/actions/Report.js:72]: How about this phrasing? I stumbled a bit when reading "... the main source of truth about what a report's max sequenceNumber is", and I think the suggestion here is a bit more clear, what do you think?

```suggestion
 * Those values are stored in reportMaxSequenceNumbers and treated as the main source of truth for each report's max sequenceNumber.
```

File: src/libs/actions/Report.js [hunk 12]
```diff
@@ -773,28 +788,46 @@ function fetchAllReports(
...
 
-            // We are waiting 8 seconds since this provides a good time window to allow the UI to finish loading before
-            // bogging it down with more requests and operations.
-            }, shouldDelayActionsFetch ? 8000 : 0);
+                // We are waiting a set amount of time to allow the UI to finish loading before bogging it down with
+                // more requests and operations. Startup delay is longer since there is a lot more work done to build
+                // up the UI when the app first initializes.
+            }, shouldDelayActionsFetch ? CONST.FETCH_ACTIONS_DELAY.STARTUP : CONST.FETCH_ACTIONS_DELAY.RECONNECT);
+
+            // Register the timer so we can clean it up if the user logs out after logging in. If we don't cancel the
```
Comment (Beamanator) [inline src/libs/actions/Report.js:828]: I think this only applies to a user logging out _before_ the API requests are made, right? Hopefully this is a tad clearer:

```suggestion
            // Register the timer so we can clean it up if the user quickly logs out after logging in. If we don't cancel the
```

File: src/libs/actions/ReportActions.js [hunk 13]
```diff
@@ -0,0 +1,73 @@
...
+import ONYXKEYS from '../../ONYXKEYS';
+import * as CollectionUtils from '../CollectionUtils';
+
+/**
+ * Map of the most recent non-loading sequenceNumber for a reportActions_* key in Onyx by reportID.
+ *
+ * What's the difference between reportMaxSequenceNumbers and reportActionsMaxSequenceNumbers?
+ *
+ * Knowing the maxSequenceNumber for a report does not necessarily mean we have stored the report actions for that
+ * report. To optimize and understand which reportActions we need to fetch we also keep track of the max sequenceNumber
```
Comment (Beamanator) [inline src/libs/actions/ReportActions.js:12]: NAB; I think switching "understand" and "optimize" reads a bit clearer.

```suggestion
 * report. To understand and optimize which reportActions we need to fetch we also keep track of the max sequenceNumber
```

**Review by Beamanator — CHANGES_REQUESTED** [review]
I love the new structure and the recommendation not to use the new function you created (if possible)!

I have only a few suggestions to make some comments clearer, let me know if you disagree with any of them 👍

File: src/libs/actions/Report.js [hunk 14]
```diff
@@ -773,28 +788,46 @@ function fetchAllReports(
...
+            // timer we'll make unnecessary API requests from the sign in page.
+            Timers.register(timerID);
```
Comment (tgolen) [inline src/libs/actions/Report.js:830]: Just a small thing, but the other code that users `Timers.register()` is passing an anonymous function, and I actually like that pattern better because it forces me to know to use `Timers.register()`. With this down here below the definition of the `setTimeout` I think it is easy to miss, so I vote for the consistency of the other pattern.

**Review by tgolen — CHANGES_REQUESTED** [review]
I like the new changes. It makes the situation much more clear what's happening. Thank you!

**Comment by marcaaron** [comment]
Updated

**Review by tgolen — APPROVED** [review]

**Review by Beamanator — APPROVED** [review]
Noice 💪 #LGTM

File: src/libs/Timers.js [hunk 15]
```diff
@@ -0,0 +1,31 @@
...
+ * Clears all timers that we have registered. Use for long running tasks that may begin once logged out.
+ */
+function clearAll() {
+    _.each(timers, (timer) => {
+        // We don't know whether it's a setTimeout or a setInterval, but it doesn't really matter. If the id doesn't
+        // exist nothing bad happens.
+        clearTimeout(timer);
+        clearInterval(timer);
+    });
+}
```
Comment (kidroca) [inline src/libs/Timers.js:26]: `const timers = [];` is never emptied

`clearAll` will be foreach-ing already cleared timers

Maybe it can be refactored to something like 

```js
const timers = {};

function clearSingle(id) {
  clearTimeout(id);
  clearInterval(id);
  delete timers[id];
}

function clearAll() {
  _.each(timers, clearSingle);
}
```

File: src/libs/actions/Report.js [hunk 16]
```diff
@@ -773,28 +788,44 @@ function fetchAllReports(
                 return fetchChatReportsByIDs(reportIDs);
             }
 
-            return fetchOrCreateChatReport([currentUserEmail, 'concierge@expensify.com'], false)
-                .then((createdReportID) => {
-                    reportIDs = [createdReportID];
-                });
+            return fetchOrCreateChatReport([currentUserEmail, 'concierge@expensify.com'], false);
```
Comment (kidroca) [inline src/libs/actions/Report.js:791]: Instead of modifying `fetchOrCreateChatReport` you could just return the array like:

```js
return fetchOrCreateChatReport([currentUserEmail, 'concierge@expensify.com'], false)
  .then(reportId => [reportId]); 
```

IMO it's better than having to justify something fishy with a comment

```js
            // We are returning an array with the reportID here since fetchAllReports calls this method or
            // fetchChatReportsByIDs which returns an array of reportIDs.
            return [data.reportID];
```
- this just discloses a coupling to the `fetchAllReports` usage

File: src/libs/Timers.js (hunk 15 above)
Comment (marcaaron) [reply src/libs/Timers.js:26]: That's a good point. But there is no danger in clearing already cleared timers so this might never be a problem.

File: src/libs/actions/Report.js (hunk 16 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:791]: Thanks for your notes here. I see no major problem with doing it either way.
