### PR TITLE
Fix some regression issues of merge expenses

### LINKED ISSUE #68171: Expense - Amount in the merged expense in self DM shows negative value
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.91-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/65596
**Email or phone of affected tester (no customers):** jsdknjsoisd@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Account has self DM.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense to the workspace.
4. Go to self DM.
5. Track a manual expense in self DM.
6. Open the transaction thread in self DM.
7. Click More > Merge.
8. Select the workspace expense > Next.
9. Select the amount from the workspace expense in Step 3.
10. Select any option for other fields.
11. Click Continue.
12. Click Merge expenses.

## Expected Result:
The amount in the merged expense in self DM will not show negative value.

## Actual Result:
The amount in the merged expense in self DM shows negative value.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1287db8a-0159-4470-bf6f-fd473f771205

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #68180: Merge expense - Tag in X: Y format is displayed as X/: Y in tag selection section
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.91-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/65596
**Email or phone of affected tester (no customers):** jsdknjsoisd@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Workspace has at least two tags in X: Y format.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses with different tag in X: Y format.
4. Open expense report.
5. Open the transaction thread from any expense.
6. Click More > Merge.
7. Select the other expense.
8. Click Continue.
9. Scroll down to Tag.

## Expected Result:
Tag in X: Y format will be displayed as X: Y.

## Actual Result:
Tag in X: Y format is displayed as X/: Y.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6ae6d4f2-05dc-45ce-83c2-f0e827107cf8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #68189: Expense - Unable to merge cash expense and card transaction if amount is from cash expense
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.91-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/65596
**Email or phone of affected tester (no customers):** sdojisdnjosjd@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- User has imported transactions from bank account.

1. Go to staging.new.expensify.com
2. Go to workspace chat that has imported transactions.
3. Open the expense report.
4. Submit a manual expense in the same report.
5. Click on the expense from Step 4.
6. Click More > Merge.
7. Select any imported transaction > Next.
8. Select the original amount as the manual expense (not imported transaction).
9. Select Merchant and Category from the imported transaction.
10. Select Yes for Reimbursable.
11. Click Continue.
12. Click Merge expenses.
13. Open the merged expense.

## Expected Result:
App should throw error if we cannot merge cash expense with card expense using the amount from cash expense.

## Actual Result:
App does not throw error when we merge cash expense with card expense using the amount from cash expense. 
User can still proceed with the merge process. In the end, the expense is not merged. The original detail (Merchant and Category) of the manual expense is retained.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d620c6a6-e6e2-4dd3-b0d7-88cd62341425

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #68196: Merge - Unable to change receipt after opening receipt on confirm page
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.91-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/65596
**Email or phone of affected tester (no customers):** jsdoijnsodisjo@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two scan expenses with different receipts.
4. Wait for scanning to complete.
5. Open expense report.
6. Open any scan expense.
7. Click More > Merge.
8. Select the other scan expense > Continue.
9. Select Receipt 2 from the other expense > Continue.
10. Select any detail for other field > Continue.
11. On confirm page, open the receipt in full screen.
12. Close the receipt view.
13. Click RHP back button twice.
14. Select Receipt 1.

## Expected Result:
Receipt 1 can be selected.

## Actual Result:
Receipt 1 cannot be selected after opening receipt on confirm page and reselecting other receipt.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/980af6f3-293a-41d4-a370-25b55838a470

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

### LINKED ISSUE #68197: When merging per diem expense with manual expense, receipt cannot be viewed in full screen
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.91-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/65596
**Email or phone of affected tester (no customers):** jsdoijnsodisjo@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Workspace has imported per diem rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a per diem expense and a manual expense with receipt.
4. Open expense report.
5. Open the per diem expense.
6. Click More > Merge.
7. Select the manual expense with receipt > Continue.
8. Select Receipt 2 from the manual expense > Continue.
9. Select any detail for other field > Continue.
10. On confirm page, open the receipt in full screen.

## Expected Result:
The receipt will open in full screen.

## Actual Result:
The receipt opens in full screen and closes immediately before it is loaded.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/83f67d9c-5869-41a6-9523-4153e5b4bbfb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #68206: [Hold PR #68204] Merge - Amount section does not show negative sign for negative amount in Select details page
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.91-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/65596
**Email or phone of affected tester (no customers):** sdjniodsoijosd@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.expensify.com
2. Create a report with two expenses with negative amount.
3. Log in to the same account on staging.new.expensify.com
4. Open the expense report.
5. Open any transaction thread.
6. Click More > Merge.
7. Select the other expense > Next.

## Expected Result:
Amount section will show negative amount correctly.

## Actual Result:
Amount section does not show negative sign for negative amount.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b4e29cbc-3e32-4684-ace4-e381f4b5069c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #68233: Merge - IOU - Today's date is used instead of the original date of the selected expense
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/65596
**Email or phone of affected tester (no customers):** agexptest+pr0808e@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create 2 scan expenses in an IOU chat
3. Wait until scanning is completed
4. Go to any of the scan expenses
5. Tap on the More button > Merge
6. Select another scan expense that is in the same report
7. Select any receipt
8. Select any amount and merchant
9. Note the expense date in the Confirm details page
10. Confirm

## Expected Result:
The expense date shown on the Confirm Details page remains unchanged on the Expense Details page

## Actual Result:
Today's date is assigned to the merged expense instead of keeping the date of the selected expense

## Workaround:
Unknown

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details> 

https://github.com/user-attachments/assets/9433c1be-cd77-4a26-8726-75f0aa9db918

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #68243: Merge flow – Misaligned radio button with long category name
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9.1.92-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exploratory
**Email or phone of affected tester (no customers):** Slottwo1 7423@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Redminote 10s android 13 phone
**App Component:** Money Requests

## Action Performed:
1. Launch app in both mweb and Android 
2. Open workpace chat 
3. Tap category 
4. Add a long category - Advertisingradhe-krishna-dfgggggghhhhhhh-hhhhhhhhh-hhhhhhhhhghbbnnbbbb-radhe-radherradhe-krishncvbbnhhjjjjjjjh Hbb.com
5. Create 2 expenses with merchant and category. For any one expense select the long category 
6. Open the expense in which long category is not selected
7. Tap more - merge - select the expense with long category 
8. Note in mweb and Android

## Expected Result:
In merge flow, when long category name is entered radio button placement must not be misaligned.

## Actual Result:
In merge flow, when long category name is entered radio button placement is misaligned in android and not in mweb.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/613e1b5b-1150-4fe0-8e54-33c86963a06d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### PR DESCRIPTION
**Pull request by hoangzinh**
### Explanation of Change

The last time we deployed merge expense PR to staging, we got a few DBs, then we hid "Merge" button to buy time for us to fix those DBs. This PR aims to fix some of them.

### Fixed Issues

$ https://github.com/Expensify/App/issues/65574
$ https://github.com/Expensify/App/issues/68189
$ https://github.com/Expensify/App/issues/68197
$ https://github.com/Expensify/App/issues/68196
$ https://github.com/Expensify/App/issues/68206
$ https://github.com/Expensify/App/issues/68243
$ https://github.com/Expensify/App/issues/68225
$ https://github.com/Expensify/App/issues/68170
$ https://github.com/Expensify/App/issues/68180
$ https://github.com/Expensify/App/issues/68195
$ https://github.com/Expensify/App/issues/68171
$ https://github.com/Expensify/App/issues/68233
$ https://github.com/Expensify/App/issues/69598
$ https://github.com/Expensify/App/issues/68178

PROPOSAL:

### Tests

Same as QA

- [x] Verify that no errors appear in the JS console

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

**Case 1**: Fix https://github.com/Expensify/App/issues/68189 => Auto select card transaction's amount when merge with cash expense

Precondition:
- User has card transactions

1. Go to staging.new.expensify.com
2. Go to workspace chat that has card transactions.
3. Open the expense report.
4. Submit a manual expense in the same report.
5. Click on the expense from Step 4.
6. Click More > Merge.
7. Select any card transaction > Next.
8. Verify that amount is not displayed in the details step
9. Complete details step
10. Verify that amount of the card transaction is auto-selected and displayed in the Confirmation page

**Case 2**: Fix https://github.com/Expensify/App/issues/68197 => When merging per diem expense with manual expense, receipt cannot be viewed in full screen

Precondition:
- Workspace has imported per diem rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a per diem expense and a manual expense with receipt.
4. Open expense report.
5. Open the per diem expense.
6. Click More > Merge.
7. Select the manual expense with receipt > Continue.
8. Select Receipt 2 from the manual expense > Continue.
9. Select any detail for other field > Continue.
10. On confirm page, open the receipt in full screen.
11. Verify that the receipt will open in full screen.

**Case 3**: Fix https://github.com/Expensify/App/issues/68196 => Unable to change receipt after opening receipt on confirm page

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two scan expenses with different receipts.
4. Wait for scanning to complete.
5. Open expense report.
6. Open any scan expense.
7. Click More > Merge.
8. Select the other scan expense > Continue.
9. Select Receipt 2 from the other expense > Continue.
10. Select any detail for other field > Continue.
11. On confirm page, open the receipt in full screen.
12. Close the receipt view.
13. Click RHP back button twice.
14. Select Receipt 1.
15. Verify that Receipt 1 can be selected.

**Case 4**: Fix https://github.com/Expensify/App/issues/68206 => Amount section does not show negative sign for negative amount in Select details page

1. Go to OD
2. Create a report with two expenses with negative amount.
3. Log in to the same account on ND
4. Open the expense report.
5. Open any transaction thread.
6. Click More > Merge.
7. Select the other expense > Next.
8. Verify that Amount section will show negative amount correctly.

**Case 5**: Fix https://github.com/Expensify/App/issues/68243 => Misaligned radio button with long category name

1. Open workpace chat
2. Tap category
3. Add a long category - `Advertisingradhe-krishna-dfgggggghhhhhhh-hhhhhhhhh-hhhhhhhhhghbbnnbbbb-radhe-radherradhe-krishncvbbnhhjjjjjjjh Hbb.com`
4. Create 2 manual expenses with merchant and category. For any one expense select the long category
5. Open the expense in which long category is not selected
6. Tap more - merge - select the expense with long category
7. Verify that long category name must not be misaligned with the radio button

**Case 6**: Fix https://github.com/Expensify/App/issues/68225 => Merge expense header message is partially hidden when a long merchant name is entered

1. Go to https://staging.new.expensify.com/home
2. Open workpace chat
3. Create a expense with long merchant - `Dirty[🥲](https://staging.new.expensify.com/r/1829442022550952)`
4. Create another expense
5. Open the expense has long merchant
6. Tap more - merge
7. Verify that merge expense header message must be fully visible when a long merchant name is entered

**Case 7**: Fix https://github.com/Expensify/App/issues/68170 Description with mark down shows HTML tags in description selection 

1. Go to workspace chat.
2. Submit two expenses with description that has mark down to the workspace.
3. Open expense report.
4. Open one of the expenses.
5. Click More > Merge.
6. Select the expense > Next.
7. Scroll down to description.
8. Verify that the description will not show HTML tags.

**Case 8**: Fix https://github.com/Expensify/App/issues/68180 => Tag in X: Y format is displayed as X/: Y in tag selection section

Precondition:
- Workspace has at least two tags in X: Y format.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses with different tag in X: Y format.
4. Open expense report.
5. Open the transaction thread from any expense.
6. Click More > Merge.
7. Select the other expense.
8. Click Continue.
9. Scroll down to Tag.
10. Verify that Tag in X: Y format will be displayed as X: Y.

Case 9: Fix https://github.com/Expensify/App/issues/68171 => Amount in the merged expense in self DM shows negative value
Precondition:
- Account has self DM.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense to the workspace.
4. Go to self DM.
5. Track a manual expense in self DM.
6. Open the transaction thread in self DM.
7. Click More > Merge.
8. Select the workspace expense > Next.
9. Select the amount from the workspace expense in Step 3.
10. Select any option for other fields.
11. Click Continue.
12. Click Merge expenses.
13. Verify that the amount in the merged expense in self DM shows a positive value.

Case 10: Fix https://github.com/Expensify/App/issues/68233 => Today's date is used instead of the original date of the selected expense

1. Go to staging.new.expensify.com
2. Create 2 scan expenses in an IOU chat
3. Wait until scanning is completed
4. Go to any of the scan expenses
5. Tap on the More button > Merge
6. Select another scan expense that is in the same report
7. Select any receipt
8. Select any amount and merchant
9. Note the expense date in the Confirm details page
10. Tap on "Merge expense"
11. Verify that the expense's date shown on the Confirm Details page remains unchanged on the Expense Details page

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/2466d7be-845a-4ce0-8825-b91125bd1c9d

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/444e22b4-49fb-469b-acdd-47a60df71be6

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/6a6f6765-5fc3-418b-a990-b25e586d00c6

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/63d2abf1-fc90-4085-bfd6-a2b259381db4

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/6b69043e-2005-4f22-ad34-bcfae9ac0c52

https://github.com/user-attachments/assets/68b8a3fd-5a96-42cb-8ba2-20d30377870c

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/3cd64071-d962-4159-8456-af9754004974

</details>

### CODE REVIEW

File: src/libs/actions/MergeTransaction.ts [hunk 1]
```diff
@@ -128,8 +128,8 @@ function getTransactionsForMerging({
 function mergeTransactionRequest(mergeTransactionID: string, mergeTransaction: MergeTransaction, targetTransaction: Transaction, sourceTransaction: Transaction) {
     const isUnreportedExpense = !targetTransaction.reportID || targetTransaction.reportID === CONST.REPORT.UNREPORTED_REPORT_ID;
 
-    // If the target transaction we're keeping is unreported, the amount needs to be positive. Otherwise for expense reports it needs to be the opposite sign.
-    const finalAmount = isUnreportedExpense ? Math.abs(mergeTransaction.amount) : -mergeTransaction.amount;
+    // If the target transaction we're keeping is unreported, the amount needs to be always negative. Otherwise for expense reports it needs to be the opposite sign.
+    const finalAmount = isUnreportedExpense ? -Math.abs(mergeTransaction.amount) : -mergeTransaction.amount;
```
Comment (youssef-lr) [inline src/libs/actions/MergeTransaction.ts:132]: Actually let's remove this `-` because some reported expenses can have negative/positive amounts

`const finalAmount = isUnreportedExpense ? -Math.abs(mergeTransaction.amount) : mergeTransaction.amount;`

Comment (hoangzinh) [reply src/libs/actions/MergeTransaction.ts:132]: Without "-", when I merge 2 expenses, BE returns with positive values, then it show as negative value

https://github.com/Expensify/App/blob/d7214c5dd5b9d2ef6a9fff8068ffb3c581b642e7/src/libs/TransactionUtils/index.ts#L598-L604

https://github.com/user-attachments/assets/7cf4cf44-85b0-465e-9b20-888fa3008673

Do you think it's better if BE can handle in this case?

Comment (youssef-lr) [reply src/libs/actions/MergeTransaction.ts:132]: That's weird, I'll test this today

File: src/languages/es.ts [hunk 2]
```diff
@@ -1411,6 +1411,7 @@ const translations = {
             pageTitle: 'Confirma los detalles que conservarás. Los detalles que no conserves serán eliminados.',
             confirmButton: 'Fusionar gastos',
         },
+        unreportedReport: '(ninguno)',
```
Comment (hoangzinh) [inline src/languages/es.ts]: Reuse translation from `accounting.none` here 

https://github.com/Expensify/App/blob/384bcf1e8708d855c6ad60318615be4e324dc855/src/languages/es.ts#L2243

File: src/languages/es.ts [hunk 3]
```diff
@@ -636,6 +636,7 @@ const translations = {
         submitTo: 'Enviar a',
         forwardTo: 'Reenviar a',
         merge: 'Fusionar',
+        none: 'Ninguno',
```
Comment (hoangzinh) [inline src/languages/es.ts:640]: Copy from existing translation here https://github.com/Expensify/App/blob/f63ce2e292d1473e4c88614f1da265019277737a/src/languages/es.ts#L2245

**Review by trjExpensify — DISMISSED** [review]
Part of an on-going product-approved project, approving. 👍

File: src/components/ReportActionItem/MoneyRequestView.tsx [hunk 4]
```diff
@@ -179,7 +182,10 @@ function MoneyRequestView({
     const isTransactionScanning = isScanning(updatedTransaction ?? transaction);
     const hasRoute = hasRouteTransactionUtils(transactionBackup ?? transaction, isDistanceRequest);
 
-    const actualAmount = updatedTransaction ? getAmount(updatedTransaction) : transactionAmount;
+    // If it's from the merge transaction flow:
+    // - We can use amount from the updated transaction because it's already converted to the correct sign for user to select
+    // - This will support to display correct sign of amount for negative amount
```
Comment (dominictb) [inline src/components/ReportActionItem/MoneyRequestView.tsx]:
```suggestion
    // Use the updated transaction amount in merge flow to have correct positive/negative sign
```

File: src/libs/actions/MergeTransaction.ts [hunk 5]
```diff
@@ -37,74 +37,105 @@ function getTransactionsForMerging(transactionID: string) {
...
+    currentUserLogin: string | undefined;
+}) {
+    const transactionID = targetTransaction.transactionID;
+
+    // Collect/Control workspaces:
+    // - Admins and approvers: The list of eligible expenses will only contain the expenses from the report that the admin/approver triggered the merge from. This is intentionally limited since they’ll only be reviewing one report at a time.
+    // - Submitters will see all their editable expenses, including their IOUs/unreported expenses
+    // IOU:
+    // - There are no admins/approvers outside of the submitter in these cases, so there’s no consideration for different roles.
+    // - The submitter, who is also the admin, will see all their editable expenses, including their IOUs/unreported expenses
```
Comment (dominictb) [inline src/libs/actions/MergeTransaction.ts:98]: Why do we need to extract these logic separately?

**Review by dominictb — CHANGES_REQUESTED** [review]

File: src/libs/actions/MergeTransaction.ts (hunk 1 above)
Comment (dominictb) [reply src/libs/actions/MergeTransaction.ts:132]: How is this? @youssef-lr @hoangzinh

File: src/libs/actions/MergeTransaction.ts (hunk 5 above)
Comment (hoangzinh) [reply src/libs/actions/MergeTransaction.ts:98]: Context is [here](https://expensify.slack.com/archives/C099T76RFU7/p1754650510946329?thread_ts=1754647064.561019&cid=C099T76RFU7), for Admin/approvers (and not submitter), we don't need to call API to get eligible transactions, just get list of transactions in same money report

cc @youssef-lr

Comment (dominictb) [reply src/libs/actions/MergeTransaction.ts:98]: Cool

**Review by dominictb — APPROVED** [review]
🎀👀🎀

**Review by youssef-lr — APPROVED** [review]
LGTM!
