### PR TITLE
Fix custom column deploy blockers

### LINKED ISSUE #76868: [Due for payment 2025-12-26] [Custom Columns][Release 4] Add taxRate column to Search results
1. Add the `taxRate` column to [this array](https://github.com/Expensify/App/blob/b98b1ea3f8a1b6969881fcc370c5026a247d7e1b/src/components/SelectionListWithSections/SearchTableHeader.tsx#L19)  
2. Add the `taxRate` column to [this function](https://github.com/Expensify/App/blob/61994ad151d78adaa219a6b3a32dcdf7ef81945b/src/libs/SearchUIUtils.ts#L2385), with default to `false`  
3. Add a `Text` component for the `taxRate` column [here](https://github.com/Expensify/App/blob/61994ad151d78adaa219a6b3a32dcdf7ef81945b/src/components/TransactionItemRow/index.tsx#L244-L255) (follow the order [here](?tab=t.0#bookmark=id.6q074a6ebjnm)). This column displays `taxRateName (taxRate)`.  
4. Add automated tests [here](https://github.com/Expensify/App/blob/61994ad151d78adaa219a6b3a32dcdf7ef81945b/tests/unit/Search/SearchUIUtilsTest.ts#L2627)

Parent issue: https://github.com/Expensify/Expensify/issues/566674

### LINKED ISSUE #77829: [Due for payment 2025-12-26] Reports - After deleting saved search, column settings on Expenses tab are not reset
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** hjidjnfjsdiuhs@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Reports.
5. Click Columns.
6. Unselect all the options except Action > Save.
7. Click Filters.
8. Click Save search.
9. Click 3-dot menu on the saved search > Delete > Delete it.

## Expected Result:
After deleting saved search and redirecting to Expenses tab, column settings on Expenses tab should reset to default.

## Actual Result:
After deleting saved search and redirecting to Expenses tab, column settings from the saved search are applied to Expenses tab.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/c85ca29d-6e79-4271-8211-9639b4722d2a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

### LINKED ISSUE #77831: Reports - Column options change after clicking on Reports tab twice
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** hjidjnfjsdiuhs@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Reports > Reports.
3. Click Columns.
4. Remember the column options.
5. Close the RHP.
6. Click Reports under Explore again.
7. Click Columns.

## Expected Result:
The column options should remain unchanged.

## Actual Result:
The column options change after clicking on Reports tab twice.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/5313706d-b010-4ecc-ac1f-118052ef4bb4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #77832: Reports - All table columns disappear except Type and Amount after applying columns:froom
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** hjidjnfjsdiuhs@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Expenses.
5. Click on the search field.
6. Type columns:froom.
7. Hit Enter.

## Expected Result:
The expense table should remain unchanged because "froom" is not a valid query.

## Actual Result:
All table columns disappear except Type and Amount after applying columns:froom.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/50b696a1-c126-4964-8929-137b28946ad2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #77833: Reports-Description column disappears after changing column filter when it is not customisable
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** hjidjnfjsdiuhs@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense with description.
4. Go to Reports > Expenses.
5. Click Columns.
6. Without changing anything, click Save.
→ Description column is displayed because it is not customisable in Column settings.
7. Click Columns.
8. Deselect any option and save it.

## Expected Result:
Description column should remain displayed because it is not customisable in Column settings.

## Actual Result:
Description column disappears after applying column filter when it is not customisable in Column settings.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/3a5ccf7e-d52e-42b4-a2ab-f2ae7a5ed690

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #77834: Reports - Tag column is shown after deselecting and reselecting Tag
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** hjidjnfjsdiuhs@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
Precondition:
- Tag feature is not enabled.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Go to Reports > Expenses.
5. Click Columns.
6. Without changing anything, click Save.
→ Tag column is not shown when Tag is selected in Column settings because expenses do not have tag - Expected.
7. Click Columns.
8. Deselect and reselect Tag.
9. Click Save.

## Expected Result:
Tag column should be hidden because expenses do not have tag, similar to Step 6. It should only shows when at least one expense has tag.

## Actual Result:
Tag column is shown after deselecting and reselecting Tag.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/927b458f-df13-4d3c-91f3-29a607f52be1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #77835: Reports - Column settings in Reports are also reflected in expense report in Inbox & Reports
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.79-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/77673
**Email or phone of affected tester (no customers):** hjidjnfjsdiuhs@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Mac 26.1 / Chrome
**App Component:** Search

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create two expenses.
4. Go to Reports > Reports.
5. Click Columns.
6. Unselect all the options except Action > Save.
7. Open the expense report.
8. Go to Inbox and open the expense report.

## Expected Result:
Column settings in Reports should only be reflected in Reports > Reports.

## Actual Result:
Column settings in Reports are only reflected in expense report in Inbox & Reports.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari

## Screenshots/Videos

https://github.com/user-attachments/assets/aef0dceb-c244-4026-a00c-baa43f16ccbb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### PR DESCRIPTION
**Pull request by luacmartins**
### Explanation of Change
Fixes several deploy blockers related to custom columns

### Fixed Issues
$ https://github.com/Expensify/App/issues/77829
$ https://github.com/Expensify/App/issues/77831
$ https://github.com/Expensify/App/issues/77832
$ https://github.com/Expensify/App/issues/77833
$ https://github.com/Expensify/App/issues/77834
$ https://github.com/Expensify/App/issues/77835
$ https://github.com/Expensify/App/issues/77869
$ https://github.com/Expensify/App/issues/77850
$ https://github.com/Expensify/App/issues/77859
$ https://github.com/Expensify/App/issues/77843
$ https://github.com/Expensify/App/issues/77868
$ https://github.com/Expensify/App/issues/77867
$ https://github.com/Expensify/App/issues/77853
$ https://github.com/Expensify/App/issues/77841

### Tests
Same as fixed issues

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
Same as tests

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If new assets were added or existing ones were modified, I verified that:
    - [x] The assets are optimized and compressed (for SVG files, run `npm run compress-svg`)
    - [x] The assets load correctly across all supported platforms.
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

### CODE REVIEW

**Comment by brunovjk** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: HybridApp
    - [x] Android: mWeb Chrome
    - [x] iOS: HybridApp
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: HybridApp</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: HybridApp</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

--------------------
### MacOS: Chrome / Safari

<details>
<summary>#77829 ✅</summary>



https://github.com/user-attachments/assets/ece89432-de17-43cf-ace3-4aea49b85291


</details>

----------------------

<details>
<summary>#77831 ✅</summary>



https://github.com/user-attachments/assets/df49796a-e1f4-481f-bead-4814c6de851d


</details>

----------------------

<details>
<summary>#77832 ❓</summary>



https://github.com/user-attachments/assets/85f759fe-2d4c-49b4-bd15-be71f4b2ad6d


</details>

Awaiting confirmation regarding the expected behavior.

----------------------

<details>
<summary>#77833 ✅</summary>



https://github.com/user-attachments/assets/640f56b6-47db-44b2-8481-92d5b332c391


</details>

----------------------

<details>
<summary>#77834 ✅</summary>



https://github.com/user-attachments/assets/2227fc47-fff3-44a9-84e6-4579e8bcbe72


</details>

----------------------

<details>
<summary>#77835 ✅</summary>



https://github.com/user-attachments/assets/1c3f98ac-8860-4223-b07d-3e772e951bf0


</details>

**Comment by luacmartins** [comment]
https://github.com/Expensify/App/issues/77832 @brunovjk we just ignore invalid columns. So if the only specified column is invalid, we show the default columns

**Comment by brunovjk** [comment]
Great @luacmartins !!! The issues seem to be resolved, I just need a little more time to look for regressions. It's late now, I'll continue tomorrow morning, is that okay? If @QichenZhu  wants to resume, that's fine with me.

**Comment by luacmartins** [comment]
Yea, that's fine. Thank you for the hard work!!

File: src/libs/SearchUIUtils.ts [hunk 1]
```diff
@@ -2688,7 +2690,10 @@ function getColumnsToShow(
         };
 
         // If there are no visible columns, everything should be visible
-        if (!visibleColumns.length) {
+        const filteredVisibleColumns = visibleColumns.filter((column) =>
```
Comment (JS00001) [inline src/libs/SearchUIUtils.ts:2794]: Why do we need this? Visible columns should already be only columns in custom_columns

File: src/libs/SearchUIUtils.ts [hunk 2]
```diff
@@ -2814,7 +2819,10 @@ function getColumnsToShow(
 
     // If the user has set custom columns for the search, we need to respect their preference, and only show
     // them what they want to see
-    if (!arraysEqual(Object.values(CONST.SEARCH.DEFAULT_COLUMNS.EXPENSE), visibleColumns) && visibleColumns.length > 0) {
+    const filteredVisibleColumns = visibleColumns.filter((column) =>
```
Comment (JS00001) [inline src/libs/SearchUIUtils.ts:2929]: same, why do we need this?

File: src/pages/Search/SearchColumnsPage.tsx [hunk 3]
```diff
@@ -26,11 +27,11 @@ function SearchColumnsPage() {
     const styles = useThemeStyles();
     const {translate} = useLocalize();
 
+    const {currentSearchQueryJSON} = useSearchContext();
     const [searchAdvancedFiltersForm] = useOnyx(ONYXKEYS.FORMS.SEARCH_ADVANCED_FILTERS_FORM, {canBeMissing: true});
-
-    const queryType = searchAdvancedFiltersForm?.type ?? CONST.SEARCH.DATA_TYPES.EXPENSE;
```
Comment (JS00001) [inline src/pages/Search/SearchColumnsPage.tsx:31]: is this value not always up to date?

**Review by JS00001 — CHANGES_REQUESTED** [review]

File: src/libs/SearchUIUtils.ts (hunk 1 above)
Comment (luacmartins) [reply src/libs/SearchUIUtils.ts:2794]: When the user types in `columns:invalid` the value `invalid` ends up here which sets it to true in the columns and we end up overriding the default columns. This fixes https://github.com/Expensify/App/issues/77832

File: src/libs/SearchUIUtils.ts (hunk 2 above)
Comment (luacmartins) [reply src/libs/SearchUIUtils.ts:2929]: Same as above

File: src/pages/Search/SearchColumnsPage.tsx (hunk 3 above)
Comment (luacmartins) [reply src/pages/Search/SearchColumnsPage.tsx:31]: It didn't seem like it when I tested yesterday

Comment (JS00001) [reply src/pages/Search/SearchColumnsPage.tsx:31]: commented here: https://expensify.slack.com/archives/C0A2X1R1TEZ/p1765984761552589?thread_ts=1765977010.963319&cid=C0A2X1R1TEZ

File: src/pages/Search/SearchColumnsPage.tsx [hunk 4]
```diff
@@ -26,11 +27,11 @@ function SearchColumnsPage() {
     const styles = useThemeStyles();
     const {translate} = useLocalize();
 
+    const {currentSearchQueryJSON} = useSearchContext();
```
Comment (JS00001) [inline src/pages/Search/SearchColumnsPage.tsx]: I think we can just use the form type now, right?

**Review by JS00001 — DISMISSED** [review]

**Comment by luacmartins** [comment]
https://github.com/Expensify/App/issues/77841

https://github.com/user-attachments/assets/006ebffa-2342-4e7f-b07f-10f1e86e4440


https://github.com/Expensify/App/issues/77853

https://github.com/user-attachments/assets/05c7a39f-488a-41cc-83a1-8b6dc06b99a5

https://github.com/user-attachments/assets/686fdf09-2aae-43e8-9c34-7533b7308167

**Review by AndrewGable — APPROVED** [review]
