### PR TITLE
Fix: Modal closes immediately after launch

### LINKED ISSUE #1913: iOS issue: Modal closes immediately after launch
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Expected Result:
`Add attachment` modal should remain open until dismissed. 

## Actual Result:
`Add Attachment` modal closes immediately when we attempt to display it. This only seems to occur when we attempt to launch Modal B from a callback within Modal A 

## Action Performed:
At present, we've applied a temporary fix for this issue by using setTimeout to delay the launching of the second Modal However, that fix is sub-optimal and we are seeking a better permanent solution. See screen recording for a demo of the issue. 

1. Open Expensify.cash on iOS
2. Tap into a chat with 2 or more participants
3. Click the paperclip icon to launch Modal A 
4. Click `Add Attachment` to launch Modal B 
5. Notice the `Add Attachment` modal (Modal B) closes immediately

## Notes

This is [the location](https://github.com/Expensify/Expensify.cash/blob/f06d86545d610e398ce1903120c60d2226e01329/src/pages/home/report/ReportActionCompose.js#L200-L206) of the problem/workaround.

## Platform:

 iOS
 
**Version Number:** 1.0.2-89

**Videos:**

https://user-images.githubusercontent.com/31225194/111735258-d42cc680-881f-11eb-8735-e50778c17bb2.mov

### LINKED ISSUE #2198: Android - Denying permissions to use camera is not handled
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Trying to use the camera, but you have previously denied permissions the app should clearly indicate that
you need to update permissions in settings (since we're no longer allowed to ask)

## Actual Result:
You try to use the camera the attachment menu just closes without explanation

## Action Performed:
1. Have a freshly installed app, or set app camera permissions to "deny" in settings
2. Open a Chat
3. Select the plus (+) button
4. Select "Add attachment"
5. Select "Take Photo"
5. You are prompted for permissions
6. Select "Deny & don't ask again"
7. You can optionally restart the app at this point (it won't matter)
8. Select the plus (+) button
9. Select "Add attachment"
10. Select "Take Photo"
11. The menu closes. Nothing else happens. You see no message.

## Workaround:
The user needs to go in Android settings, search for "permissions" or go to e.cash settings and manually set permission to "allow"

## Platform:
Where is this issue occurring?

 Web
 iOS
 [x] Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.10-2 (First sawed on 1.0.6-3)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/12156624/113288348-82903b80-92f7-11eb-8c11-61e9ef9c4fbe.mp4

---

For comparison on `iOS` this works correctly and you'd see this when you have denied permissions:
image

### PR DESCRIPTION
**Pull request by kidroca**
### Details
Converts the existing Attachment Picker implementation to a bottom docked modal. There's a sample video in the iOS section

Notable changes:
- `AttachmentPicker`: Since this is a multi index component - to keep props interface uniform it was extracted to separate file 
- Converted native `AttachmentPicker` to a class based component, preserving existing render prop interface
- Removed logic that causes a side effect that closes the attachment options modal
   - Discussed here: https://github.com/Expensify/Expensify.cash/issues/1913#issuecomment-807851083
- Added error handling to let the user know when image picking fails for reasons other than permissions instead of leaving him guessing
- The wrapped calls to RNImage picker with promises to keep a uniform and easy to follow interface

### Fixed Issues
Fixes #1913 also fixes #2198

#### For web, mWeb and Desktop
Found a bug related to Safari, please use another browser to test (Chrome works): https://github.com/Expensify/Expensify.cash/issues/2109

1. Open a chat
2. Press the (+) plus button to open the input menu
3. Select "Add Attachment"
4. The browser's file picker should open and you can select a file
5. When you select a file you should see File Preview modal
6. Pressing upload should upload the file and you should see the attachment/thumb inside the chat
7. Upon the File Preview closes (previous step) focus should be returned to the compose input field

#### iOS/Android
1. Open a chat
2. Press the (+) plus button to open the input menu
3. Select "Add Attachment"
4. A second modal should open and show options for: camera, gallery, document
- Selecting "Take Photo"
  - default flow: You shoot a photo, select "Use Photo" and continue to the next step (File Preview)
  - other cases:
    - pressing "Cancel" (inside the camera) closes any modals and returns you to the "Chat".
    - not granting permission should display a helpful Alert message
    - other errors should display a general error message to let the user know something did go right. You can verify this by selecting "Take Photo" on a iOS simulator - you should see a message that taking photos on a simulator is not supported
- Selecting "Choose from Gallery"
  -  default flow: You select a photo from the gallery and continue to the next step (File Preview)
  - other cases: 
    - pressing "Cancel" (inside the gallery) closes any modals and returns you to the "Chat".
    - there's error handling that should alert the user in case of an error but I don't know a way to trigger it. I tested it by manually forcing code execution through that flow
- Selecting "Choose Document"
  -  default flow: You select a document and continue to the next step (File Preview)
  - other cases: Same as in "Choose from Gallery"
6. File Preview
- At this point you should see a preview of whatever was selected using the previous options
- Pressing "Upload" should upload the file and you should see the attachment/thumb inside the chat
- Pressing (x) close on the top right corner should close the preview and not upload anything
- Upon the File Preview closes focus should be returned to the compose input field

Regarding field input focusing
- the field is no longer focused when **any** modal closes
- the field would autofocus at the end of the full attachment flow

### QA Steps
Same as above

Note that the video sample is using the iOS simulator with the software keyboard toggled on:
https://github.com/Expensify/Expensify.cash/pull/2114#issuecomment-812449033

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Mobile Web
image

#### Desktop
image

#### iOS (Video)
https://user-images.githubusercontent.com/12156624/112827336-e0721880-9096-11eb-97d4-1daa1ea243d0.mp4

#### Android
image

### CODE REVIEW

**Comment by kidroca** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kidroca** [comment]
recheck

**Comment by NikkiWines** [comment]
going to also add @Julesssss here as a reviewer since he's got context to for issue and proposed solution

File: src/pages/home/report/ReportActionCompose.js [hunk 1]
```diff
@@ -78,12 +73,9 @@ class ReportActionCompose extends React.Component {
...
         }
 
-        // When any modal goes from visible to hidden or when the report ID changes, bring focus to the compose field
-        if (
-            (prevProps.modal.isVisible && !this.props.modal.isVisible)
-            || (prevProps.reportID !== this.props.reportID)
-        ) {
-            this.setIsFocused(true);
+        // When the report ID changes bring focus to the compose field
+        if (prevProps.reportID !== this.props.reportID) {
```
Comment (kidroca) [inline src/pages/home/report/ReportActionCompose.js:77]: Hey reviewers I think we might have a merge conflict here as @parasharrajat  work needs to change this line as well #2022 

I've changed it, to exclude modal checks as they break modal to modal transition - the attachment modal would close immediately if focus is requested on the field 

If I revert this change, I'll also need to bring  the timeout back 😭

Any suggestions?

Comment (kidroca) [reply src/pages/home/report/ReportActionCompose.js:77]: Hmm, I've actually can revert most of my changes. The UX would be a bit odd but I guess this will be improved once autofocussing is solved and the keyboard stays collapsed

Here are some samples:
#### reverting almost everything in `ReportActionCompose` to original 

##### On Simulator
https://user-images.githubusercontent.com/12156624/112962392-022ed680-914f-11eb-9158-f53e76a1a36a.mp4

##### On a Real Device

https://user-images.githubusercontent.com/12156624/112963857-7453eb00-9150-11eb-99e3-ecc842168137.mp4

There's also a video showing how the current changes work in the pull request description

Anyway I'm willing to revert my changes to  `ReportActionCompose` so that we can merge this easier if another ticket is already addressing focusing

File: src/components/AttachmentPicker/propTypes.js [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+     *                     // Display or upload File
+     *                 },
+     *             });
+     *         }}
+     *     />
+     * )}
+     * </AttachmentPicker>
+     * */
+    children: PropTypes.func.isRequired,
+};
```
Comment (Julesssss) [inline src/components/AttachmentPicker/propTypes.js:23]: This separate file seems unnecessary for a single PropType

File: src/pages/home/report/ReportActionCompose.js (hunk 1 above)
Comment (Julesssss) [reply src/pages/home/report/ReportActionCompose.js:77]: The other PR should actually be changing to solve the focus issue in a less general way, so the modal checks you mention won't be a conflict for much longer.

I think this is fine for now actually.

File: src/components/AttachmentPicker/propTypes.js (hunk 2 above)
Comment (kidroca) [reply src/components/AttachmentPicker/propTypes.js:23]: I've done this because:
1. the component has platform specific implementations that need to keep the same (public) props interface. 
2. this was copy pasted to both implementations - if more props are added they will have to be copy pasted as well 
3. the example usage was copy pasted too - this means that if it changes for some reason it's possible to forget to update it on both places: e.g. ["This is the web/mWeb/desktop version since..."]( https://github.com/Expensify/Expensify.cash/pull/2114/files#diff-c5016cd4c4354cbb41b3252743d1d0024af50be56ecf42566893ad7052492b2bL104) written on the native component

**Comment by Julesssss** [comment]
> the field is no longer focused when any modal closes

This is a regression for Web & Desktop. We need to regain focus when the attachment picker closes (not for mobile though)

Also, it looks like we're not closing the AttachmentPicker menu when on item is selected, can we do this? IMO it's odd mobile UX to see the prior modal when cancelling from the gallery (for example) -- I would expect the modal to close as the gallery/camera/picker is launched

File: src/pages/home/report/ReportActionCompose.js (hunk 1 above)
Comment (Julesssss) [reply src/pages/home/report/ReportActionCompose.js:77]: Hmm, maybe this is required after all for the regression I [mentioned here](https://github.com/Expensify/Expensify.cash/pull/2114#issuecomment-810095724)

**Comment by Julesssss** [comment]
It tested well on Web and mobile, but mobile web (iOS) didn't work for me. I see the AttachmentModal, but tapping Add Attachment does nothing. 

I also would expect the options here to match mobile?

**Comment by kidroca** [comment]
> This is a regression for Web & Desktop. We need to regain focus when the attachment picker closes (not for mobile though)

I've also brought this up here: https://github.com/Expensify/Expensify.cash/issues/2129#issuecomment-809554367 
Autofocus should be handled differently on mobile vs web/desktop but I don't think this can be address by the current PR
 
> Also, it looks like we're not closing the AttachmentPicker menu when on item is selected, can we do this? IMO it's odd mobile UX to see the prior modal when cancelling from the gallery (for example) -- I would expect the modal to close as the gallery/camera/picker is launched

I wasn't sure about this, I can update it to close. My logic was that if I selected gallery by mistake I can press "Cancel" and return to select something else like documents

**Comment by kidroca** [comment]
> I also would expect the options here to match mobile?

I don't think the options would match on mWeb, it would use the web component with the hidden input - that would bring whatever file picker the browser would display to you. 

Something like this:
image

It's not even possible to test it right now as this issue is also affecting mobile Chrome: #2109:
image

**Comment by kidroca** [comment]
Updated
- reverted changes regarding "This is a regression for Web & Desktop."
- this also closes the 2nd modal when "Cancel" is picked inside the gallery/camera

File: src/pages/home/report/ReportActionCompose.js (hunk 1 above)
Comment (kidroca) [reply src/pages/home/report/ReportActionCompose.js]: Changes reverted.

File: src/components/AttachmentPicker/propTypes.js (hunk 2 above)
Comment (kidroca) [reply src/components/AttachmentPicker/propTypes.js:23]: @Julesssss can we resolve this one?

 My goal was to save some repetition for the documentation

The props possible to pass to a component should always match the same interface no matter the underlying platform implementation. So for platform specific components you'd need to keep them in sync if they are defined in separate files

Anyway I can define two separate prop types if you say so

Comment (Julesssss) [reply src/components/AttachmentPicker/propTypes.js:23]: Ah okay, I missed that it was reused -- I suppose that makes sense.

**Comment by Julesssss** [comment]
> Autofocus should be handled differently on mobile vs web/desktop but I don't think this can be address by the current PR.

Yeah, no problem. I just mentioned it in case it simplified things, clearly not :D

File: src/components/AttachmentPicker/index.native.js [hunk 3]
```diff
@@ -28,54 +35,72 @@ const documentPickerOptions = {
 };
 
 /**
- * Launch the DocumentPicker. Results are in same format as ImagePicker, so we can pass the repsonse to the
- * callback as is.
+ * Inform the users when they need to grant camera access and guide them to settings
+ */
+function showPermissionsAlert() {
+    Alert.alert(
+        'ExpensifyCash does not have access to your camera. To enable access, tap Settings and turn on Camera.',
```
Comment (Julesssss) [inline src/components/AttachmentPicker/index.native.js:42]: We should use 'Expensify.cash' here. Also, I think we may be able to remove this entirely? I don't see this message on physical devices, but instead seeing this:

permissionCamera

Comment (Julesssss) [reply src/components/AttachmentPicker/index.native.js:42]: Okay, never-mind. This is built into the library, I'll raise a new issue for this problem.

File: src/components/AttachmentPicker/index.native.js [hunk 4]
```diff
@@ -28,54 +35,72 @@ const documentPickerOptions = {
...
+ * @param {function} imagePickerFunc - RNImagePicker.launchCamera or RNImagePicker.launchImageLibrary
+ * @returns {Promise<ImagePickerResponse>}
  */
-function show(callback) {
-    RNImagePicker.showImagePicker(imagePickerOptions, (response) => {
-        if (response.error) {
-            if (response.error === 'Camera permissions not granted') {
-                Alert.alert(
-                    // eslint-disable-next-line max-len
-                    'ExpensifyCash does not have access to your camera. To enable access, tap Settings and turn on Camera.',
```
Comment (Julesssss) [inline src/components/AttachmentPicker/index.native.js:58]: Should say: 'Expensify.cash does not have access to your camera. Please enable the permission and try again.'

File: src/components/AttachmentPicker/index.native.js [hunk 5]
```diff
@@ -28,54 +35,72 @@ const documentPickerOptions = {
...
-                    ],
-                    {cancelable: false},
-                );
+function showImagePicker(imagePickerFunc) {
+    return new Promise((resolve, reject) => {
+        imagePickerFunc(imagePickerOptions, (response) => {
+            if (response.error) {
+                switch (response.error) {
+                    case 'Camera permissions not granted': showPermissionsAlert(); break;
+                    default: showGeneralAlert(response.error); break;
```
Comment (Julesssss) [inline src/components/AttachmentPicker/index.native.js:96]: Would you mind switching this to the default style that we use elsewhere? (with line breaks)

File: src/components/AttachmentPicker/index.native.js [hunk 6]
```diff
@@ -94,43 +119,117 @@ function getDataForUpload(fileData) {
...
  */
-const AttachmentPicker = ({children}) => children({
-    openPicker: ({onPicked}) => {
-        show((response) => {
-            onPicked(getDataForUpload(response));
+class AttachmentPicker extends Component {
+    constructor(...args) {
+        super(...args);
+
+        this.state = {isVisible: false, onPicked: () => {}, result: null};
```
Comment (Julesssss) [inline src/components/AttachmentPicker/index.native.js:132]: New lines for each field.

File: src/components/AttachmentPicker/index.native.js [hunk 7]
```diff
@@ -94,43 +119,117 @@ function getDataForUpload(fileData) {
...
+
+        this.setResult = this.setResult.bind(this);
+        this.close = this.close.bind(this);
+        this.onModalHide = this.onModalHide.bind(this);
+    }
+
+    /**
+     * After the modal closes, if an attachment was selected delegate it to the `onPicked` callback
+     */
+    onModalHide() {
```
Comment (Julesssss) [inline src/components/AttachmentPicker/index.native.js:160]: Functions should be named for what it does, not what triggered it. Something like `setAttachment`?

Comment (Julesssss) [reply src/components/AttachmentPicker/index.native.js:160]: or `setResult`

File: src/components/AttachmentPicker/index.native.js [hunk 8]
```diff
@@ -94,43 +119,117 @@ function getDataForUpload(fileData) {
...
+                `Invalid onPicked parameter. Check the children passed to: ${AttachmentPicker.displayName}`,
+            );
+        }
+
+        this.setState({isVisible: true, onPicked, result: null});
+    }
+
+    close() {
+        this.setState({isVisible: false});
+    }
```
Comment (Julesssss) [inline src/components/AttachmentPicker/index.native.js:189]: Could you add function docs here please

File: src/components/AttachmentPicker/index.native.js (hunk 3 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:42]: @Julesssss 
On `iOS` I do see this error if I don't grant permission:
image

I'll update the text

Now that I've checked this is probably related: https://github.com/react-native-image-picker/react-native-image-picker#android - we have declared `android.permission.CAMERA` in the andorid manifest and so we'll need to ask for Permissions when the camera option is selected. Did this work on Android before? It might be something that was handled internally previously when `RNImagePicker.showImagePicker` was used

Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:42]: This is what I see for Android (no modifications to current code):

#### The app asks for permissions when the Camera option is selected
image

#### Selecting deny shows me this message on android:
image

---

Note: with this PR we can upgrade to v3 of this library. Maybe this is handled differently there

File: src/components/AttachmentPicker/index.native.js (hunk 7 above)
Comment (Julesssss) [reply src/components/AttachmentPicker/index.native.js]: > It's not something that you can call anytime, it needs to be called specifically when the modal is fully gone 

I think it's fine to note that in the function comment. I'm not sure that the CreateMenu usage is valid tbh. It's also the same name as a ReactNativeModal prop, which is a little confusing.

`completeAttachmentSelection` seems fine

File: src/components/AttachmentPicker/index.native.js (hunk 4 above)
Comment (Julesssss) [reply src/components/AttachmentPicker/index.native.js:58]: Wrong place, but you get the idea

**Comment by kidroca** [comment]
Updated

Included a fix for Android camera permissions - it appears on android the `response.error` is different...
image


Still needs a designer touch as the message is used as title. 
Maybe something like:

```
Alert.alert(
  'Expensify.cash does not have access to your camera', // Title
  'To enable access, tap Settings and turn on Camera.', // Message
  [...]
)
```

File: src/components/AttachmentPicker/index.native.js (hunk 4 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:58]: @Julesssss can you take a look here: as that message also won't fit: https://github.com/Expensify/Expensify.cash/pull/2114#issuecomment-810436951

The first parameter is Alert `title` and the second is alert `content`

File: src/components/AttachmentPicker/index.native.js (hunk 5 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js]: I pushed a fix, but am leaving the comment unresolved so you can verify this fix properly address your comment

File: src/components/AttachmentPicker/index.native.js (hunk 6 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js]: I pushed a fix, but am leaving the comment unresolved so you can verify this fix properly address your comment

File: src/components/AttachmentPicker/index.native.js (hunk 7 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js]: Renamed to `completeAttachmentSelection` leaving unresolved so you can verify this fix

File: src/components/AttachmentPicker/index.native.js (hunk 8 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js]: I pushed a fix, but am leaving the comment unresolved so you can verify this fix properly address your comment

File: src/components/AttachmentPicker/index.native.js [hunk 9]
```diff
@@ -28,54 +35,77 @@ const documentPickerOptions = {
...
+
+/**
+ * A generic handling when we don't know the exact reason for an error
+ *
+ * @param {String} message
+ */
+function showGeneralAlert(message) {
+    Alert.alert(
+        'An error is preventing us to use handle the attachment',
+        message, // Todo: maybe we don't want to show this as it's probably not human friendly
```
Comment (NikkiWines) [inline src/components/AttachmentPicker/index.native.js:66]: I wouldn't include the `message` here, since - as you mentioned - it might not be user-friendly. 

I would also update the error message to be `Oops. An error occurred while selecting this attachment. Please try again.`

File: src/components/AttachmentPicker/index.native.js [hunk 10]
```diff
@@ -94,43 +124,135 @@ function getDataForUpload(fileData) {
...
+    }
+
+    /**
+     * Opens the attachment modal
+     *
+     * @param {function} onPicked A callback that will be called with the selected attachment
+     * @throws {Error} when the `onPicked` parameter is invalid
+     */
+    open(onPicked) {
+        if (typeof onPicked !== 'function') {
```
Comment (NikkiWines) [inline src/components/AttachmentPicker/index.native.js:194]: Is there a known scenario where we could be passing a non-function parameter to `open`?

File: src/components/AttachmentPicker/propTypes.js [hunk 11]
```diff
@@ -0,0 +1,25 @@
+import PropTypes from 'prop-types';
```
Comment (NikkiWines) [inline src/components/AttachmentPicker/propTypes.js:1]: Can we rename this file to `AttachmentPickerPropTypes.js` to match the convention we have for other files of this type?

**Review by NikkiWines — CHANGES_REQUESTED** [review]
Some small comments

File: src/components/AttachmentPicker/index.native.js (hunk 9 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:66]: Thanks, the intended text actually was "An error prevented us from selecting an attachment" because this can potentially happen anywhere from initially pressing "Camera" (or the other options) so the user might not have had the chance to pick something at all 

Also the first parameter of the alert is the alert modal title, having something lengthy there might get truncated on Android like here:
image
- this is already mentioned and handled separately

I'll address this and let you decide if it's good

File: src/components/AttachmentPicker/index.native.js (hunk 10 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:194]: No. And there shouldn't be
 
This is an insurance that whoever is using the component is notified right away if they haven't set it up correctly similar to prop types warnings, but prop types can only declare `children` is a required function and they can't validate it'll be called correctly

If we don't have an error guard here, you'll this error will just happen later when you try to call `onPicked` after selecting an attachment it's better to shoot right away so this doesn't slip undetected

I'm leaving the comment unresolved so you can verify this addresses your concern

File: src/components/AttachmentPicker/index.native.js (hunk 4 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:58]: I've addressed this with separate title and message:

#### Android
image

#### iOS (system theme is dark)
image

I'll let you decide is it OK and resolve

File: src/components/AttachmentPicker/index.native.js (hunk 9 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js]: I've update the error to appear like so:

#### Android:
image

#### iOS (system dark theme):
image

**Comment by kidroca** [comment]
Updated
- improved error messages

File: src/components/AttachmentPicker/index.native.js (hunk 4 above)
Comment (Julesssss) [reply src/components/AttachmentPicker/index.native.js:58]: Will do

**Comment by Julesssss** [comment]
> ```js
> Alert.alert(
>   'Expensify.cash does not have access to your camera', // Title
>   'Please enable the permission and try again.', // Message
>   [...]
> )
> ```

I think that should be fine if we leave it as the message: 

Title: Camera Permission Required
Message: Expensify.cash does not have access to your camera', please enable the permission and try again.

File: src/components/AttachmentPicker/index.native.js [hunk 12]
```diff
@@ -28,54 +35,76 @@ const documentPickerOptions = {
...
 
 /**
- * Launch the DocumentPicker. Results are in same format as ImagePicker, so we can pass the repsonse to the
- * callback as is.
+ * Inform the users when they need to grant camera access and guide them to settings
+ */
+function showPermissionsAlert() {
+    Alert.alert(
+        'Expensify.cash does not have access to your camera.',
+        'Please enable the permission and try again.',
```
Comment (Julesssss) [inline src/components/AttachmentPicker/index.native.js:43]:
```
Title: Camera Permission Required
Message: Expensify.cash does not have access to your camera', please enable the permission and try again.
```

File: src/components/AttachmentPicker/index.native.js [hunk 13]
```diff
@@ -28,54 +35,76 @@ const documentPickerOptions = {
...
+}
+
+/**
+ * A generic handling when we don't know the exact reason for an error
+ *
+ */
+function showGeneralAlert() {
+    Alert.alert(
+        'Oops. An error occurred while selecting an attachment.',
+        'Please try again.',
```
Comment (Julesssss) [inline src/components/AttachmentPicker/index.native.js:65]: Title should be brief:

Title:  Attachment Error
Message: An error occurred while selecting an attachment, please try again

File: src/components/AttachmentPicker/index.native.js (hunk 9 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js]: Resolving this as a new thread provided the message

**Comment by kidroca** [comment]
Updated
image

File: src/components/AttachmentPicker/index.native.js (hunk 9 above)
Comment (NikkiWines) [reply src/components/AttachmentPicker/index.native.js]: That looks good!

File: src/components/AttachmentPicker/index.native.js (hunk 10 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:193]: I'm resolving this as it seems to be the only thing blocking the PR

**Comment by kidroca** [comment]
@Julesssss @NikkiWines 
I have nothing more to do for this PR. Can you please take a look when you get a chance

File: src/components/AttachmentPicker/index.native.js (hunk 10 above)
Comment (Julesssss) [reply src/components/AttachmentPicker/index.native.js:193]: I get that this might help someone, but if that is its only purpose then it doesn't seem necessary. If someone creates the component elsewhere and sees an `: TypeError: undefined is not a function`, it should be pretty obvious where the issue lies.

File: src/pages/home/report/ReportActionCompose.js [hunk 14]
```diff
@@ -109,14 +108,32 @@ class ReportActionCompose extends React.Component {
...
+    }
+
+    /**
+     * Un-focus from the composer text input
+     */
+    blur() {
+        if (this.textInput) {
+            this.textInput.blur();
+        }
+    }
```
Comment (Julesssss) [inline src/pages/home/report/ReportActionCompose.js:135]: This isn't being called. Is it supposed to be?

Comment (kidroca) [reply src/pages/home/report/ReportActionCompose.js:135]: Currently no. Initially I used to clear focus from the input before opening a modal, so that the keyboard doesn't get in the way. 
Since we decided to revert this logic is no longer used, but I left it there as a compliment to `focus`

File: src/components/AttachmentPicker/index.native.js (hunk 10 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:193]: > I get that this might help someone, but if that is its only purpose then it doesn't seem necessary. If someone creates the component elsewhere and sees an : TypeError: undefined is not a function, it should be pretty obvious where the issue lies.

If this check is removed `undefined is not a function` would only appear after you complete the flow and select a file. 

With or without this clause you will end up with an error if the component is not setup properly, the check would just bring it to your attention sooner

I see this as something that can only help. As an external contributor it was my first time seeing a modal setup in this particular render prop configuration and it was a bit confusing for me. 

Anyway if it doesn't seem necessary to you I'll remove it next week, just let me know 😉

File: src/pages/home/report/ReportActionCompose.js (hunk 14 above)
Comment (Julesssss) [reply src/pages/home/report/ReportActionCompose.js:135]: Thanks for explaining, would you mind removing it in that case. We'd prefer to exclude an unused function as we may never need it.

File: src/components/AttachmentPicker/index.native.js (hunk 10 above)
Comment (Julesssss) [reply src/components/AttachmentPicker/index.native.js:193]: I appreciate the reasoning. Including this might cause other to add similar pre-optimisations which we tend to try to avoid. It's not a huge problem, but better to remove it imo.

File: src/pages/home/report/ReportActionCompose.js (hunk 14 above)
Comment (kidroca) [reply src/pages/home/report/ReportActionCompose.js:135]: Oki @Julesssss will do
Can I ask something for the future. It'll be easier to resolve such items if you say something like 
> This isn't being called. Is it supposed to be? We'd prefer to exclude an unused function as we may never need it.

So I know how to resolve this and skip some back and forth as I won't be able to address this today

Not that I'm in a hurry, but next week I'll be starting to work on other items, and I thought I was done with this one yesterday.

File: src/components/AttachmentPicker/index.native.js (hunk 10 above)
Comment (kidroca) [reply src/components/AttachmentPicker/index.native.js:193]: No problem, I'll remove it

**Review by NikkiWines — COMMENTED** [review]
This is looking great. Will re-review once conflicts are resolved and the two outstanding comments have been addressed. 

Just a note that I'm experiencing different behavior than what is shown in the iOS video in the OP re: focusing 

https://user-images.githubusercontent.com/16747822/113356013-7f488000-92f6-11eb-81bc-5bb2ba60a511.mov

**Comment by kidroca** [comment]
> Just a note that I'm experiencing different behavior than what is shown in the iOS video in the OP re: focusing

Toggling the keyboard on the simulator will switch between these behaviors. Though for a real device the keyboard will always pop out (unless it has an external keyboard)

image

**Comment by kidroca** [comment]
I would like to use rebase to resolve the merge conflicts 
To preserve review history, I'll push a backup branch or a tag that will store the original commits
This way I think review history will be kept as the original commits would still exist

Relevant discussion on slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1617306783315300

**Comment by kidroca** [comment]
Updated

> To preserve review history, I'll push a backup branch or a tag that will store the original commits
This way I think review history will be kept as the original commits would still exist

Sorry this didn't work. 😞 

You can still see what changes were requested in the Conversation tab, but they won't appear in "File Changes"

I've addressed all merge conflicts and tested that this still works as expected

**Review by NikkiWines — APPROVED** [review]
This looks good! Gonna leave it to @Julesssss for the final review + merge.

> Toggling the keyboard on the simulator will switch between these behaviors. Though for a real device the keyboard will always pop out (unless the device is connected to an external keyboard)

I would put this in your testing steps so that QA knows to do this if they're using a simulator. Otherwise they might think there's an issue with the PR.

**Review by Julesssss — APPROVED** [review]

**Review by Julesssss — CHANGES_REQUESTED** [review]
Code is looking good, but I ran through the tests again and I'm seeing a regression in the menu options. The 'Upload Photo' option is displayed -- for every single platform.

androidAttachment
Simulator Screen Shot - iPhone 11 - 2021-04-06 at 11 16 00
Screenshot 2021-04-06 at 11 19 39

**Review by Julesssss — APPROVED** [review]
Whoops, forget that last review -- the option has just been renamed to 'Upload Photo'. Outside of the scope of this PR.

**Comment by isagoico** [comment]
PR was a pass, only thing is that we were able to reproduce [this](https://github.com/Expensify/Expensify.cash/pull/2114#pullrequestreview-628806738)

image

**Comment by isagoico** [comment]
This [issue](https://github.com/Expensify/Expensify.cash/issues/2109) was reproducible in mWeb iOS only. On mWeb Android it was working as expected. 

Title: 
iOS mWeb - Attachment - Upload photo button does not work

## Expected Result
The 3 attachment options appear. 

## Actual Result
Nothing happens after clicking the upload photo button

## Action Performed
1. In a iOS device, go to Safari or Chrome
2. Navigate to staging.expensify.cash
3. Log in and navigate to a conversation
4. Click on the attachment button
5. Click on upload photo button. 

## Platform 

mWeb iOS ✔️ 

Version Number: 1.0.11-0

Logs: https://stackoverflow.com/c/expensify/questions/4856

Notes/Photos/Videos: Any additional supporting documentation

https://user-images.githubusercontent.com/44479856/113798727-bddca100-9721-11eb-9386-be1c9c8f674d.mp4

**Comment by isagoico** [comment]
Step 7 of the Web steps is failing **only** on firefox browser. Chrome browser works as expected. 

Title: 
Web - Firefox browser - After File Preview closes focus does not return to the input field automatically

## Expected Result
After File Preview closes focus should be returned to the compose input field

## Actual Result
After File Preview closes focus does not return to the input field automatically

## Action Performed
1. Login in app https://staging.expensify.cash/signin
2. Open a chat
3. Press the (+) plus button to open the input menu
4. Select "Add Attachment"
5. The browser's file picker should open and you can select a file
6. When you select a file you should see File Preview modal
7. Pressing upload should upload the file and you should see the attachment/thumb inside the chat

## Platform 

Web (Firefox) ✔️ 

**Build:** 1.0.13-0

**Notes/Images/Videos**
Important: This is only happening on **Firefox**. Let me know if I should open a separate issue for this. On chrome, the PR was a pass. 

https://user-images.githubusercontent.com/44479856/113799871-ecf41200-9723-11eb-9e33-c8f5a2e92d53.mp4

**Comment by kidroca** [comment]
> This issue was reproducible in mWeb iOS only. On mWeb Android it was working as expected.

It wouldn't do anything on desktop Safari too 

> Web - Firefox browser - After File Preview closes focus does not return to the input field automatically

I've went to the point before the changes introduced here - [v1.0.10-2](https://github.com/Expensify/Expensify.cash/tree/1.0.10-2) and the issue is still recreatable - it predates these changes

**Comment by Julesssss** [comment]
Thanks @isagoico. We have these issues covered already: 

**iOS mWeb - Attachment - Upload photo button does not work** 
- We have a separate issue for Safari attachments, which currently doesn't work

**Web - Firefox browser - After File Preview closes focus does not return to the input field automatically**
- We're handling focus issues together, I'll add this not to the issue to ensure Firefox is tested with the eventual fix: https://github.com/Expensify/Expensify/issues/154180

**Comment by isagoico** [comment]
Thanks for the clarification! Will check the PR off then 🙇

File: src/pages/home/report/ReportActionCompose.js [hunk 15]
```diff
@@ -208,6 +215,10 @@ class ReportActionCompose extends React.Component {
                                                 onPress={(e) => {
                                                     e.preventDefault();
                                                     this.setMenuVisibility(true);
+
+                                                    /* Keep last focus inside the input so that focus is restored
+                                                     on modal close. Otherwise breaks modal 2 modal transition */
+                                                    this.focus();
```
Comment (roryabraham) [inline src/pages/home/report/ReportActionCompose.js:221]: @kidroca I know this was a while ago, but could you potentially help me out with some reproduction steps for the issue you described here? i.e: If I remove this code how can I reproduce the modal 2 modal transition issue?

Comment (kidroca) [reply src/pages/home/report/ReportActionCompose.js:221]: @roryabraham 
You won't be able to. This is a leftover that should be removed. It was brought up here: https://github.com/Expensify/Expensify.cash/pull/2022#issuecomment-820330081

---

After this line is removed only on iOS, and only when the input field is initially focused there would be a small quirk in the modal to modal transition, but it was always there (even with the setTimeout fix). It might not be an issue in prod. 
Check my comments and videos. There's a full explanation and a possible fix.

Comment (roryabraham) [reply src/pages/home/report/ReportActionCompose.js:221]: Okay, so in your opinion is this safe to remove for now? (maybe with a follow-up to resolve some minor issues)?
