### PR TITLE
[CP Staging] Fix DB issues of Merge Expenses

### LINKED ISSUE #70329: Expense - After merging expenses offline, the original amount is still retained
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.9-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/68204
**Email or phone of affected tester (no customers):** sdnsdjoijiojsio@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create two expenses with different amount in the workspace chat.
4. Open the expense report.
5. Go offline.
6. Select the second expense via checkbox.
7. Click dropdown button > Merge.
8. Select the other expense > Continue.
9. Select all details from the other expense (the expense selected in Step 6).
10. Click Continue.
11. Click Merge expenses.

## Expected Result:
After merging expenses offline, the amount will update to the selected amount.

## Actual Result:
After merging expenses offline, the original amount is still retained and not the selected amount.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4a195177-cd8e-4325-a6a8-c3e657dc8b32

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### PR DESCRIPTION
**Pull request by hoangzinh**
### Fixed Issues

$ https://github.com/Expensify/App/issues/70329
$ https://github.com/Expensify/App/issues/70331
$ https://github.com/Expensify/App/issues/70336
$ https://github.com/Expensify/App/issues/70338
$ https://github.com/Expensify/App/issues/70356
$ https://github.com/Expensify/App/issues/70352
$ https://github.com/Expensify/App/issues/70345
$ https://github.com/Expensify/App/issues/70412
$ https://github.com/Expensify/App/issues/70351

PROPOSAL:

### Tests

Same as QA

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

Case 1: Disable merge IOU expenses
1. Go to 1:1 DM
2. Submit any expense
3. Open the expense report
4. Tap on "More" button
5. Verify that there is no "Merge" option

Case 2: Fix [After merging expenses offline, the original amount is still retained](https://github.com/Expensify/App/issues/70329#top)
1. Go to workspace chat.
2. Create two expenses with different amount in the workspace chat.
3. Open the expense report.
4. Go offline.
5. Select the second expense via checkbox.
6. Click dropdown button > Merge.
7. Select the other expense > Continue.
8. Select all details from the other expense (the expense selected in Step 6).
9. Click Continue.
10. Click Merge expenses.
11. Verify that the amount will optimistically update to the selected amount.

Case 3: Fix ["It´s not here" page displayed when merging expenses from different WS on "Reports"](https://github.com/Expensify/App/issues/70336#top)

Prerequisite: Account has at least two workspaces available.

1. Open the staging.new.expensify.com
2. Open any workspace chat.
3. Create a manual expense.
4. Navigate to another workspace chat.
5. Create a different manual expense.
6. Navigate to "Reports"
7. Open the last created expense.
8. Tap on "More" and select "Merge"
9. Select the first created expense to merge with.
10. Tap on "Continue"
11. Select the amount and report of the first created expense.
12. Tap on "Continue" and confirm the expenses merge.
13. Verify App navigates to merged expense

Case 4: Fix ["Moved this expense to" without report number seen after merging track expense.](https://github.com/Expensify/App/issues/70338#top)

Prerequisite: Account has at least two workspaces.
Prerequisite 2: Account has a Self DM.

1. Open the staging.new.expensify.com website.
2. Open any workspace chat.
3. Create a manual expense.
4. Return to "Inbox"
5. Create a new manual expense and submit it to Self DM.
6. Tap on "Submit to someone" below the expense.
7. Submit the expense to a workspace different than the used on step 2.
8. Navigate to workspace where track expense was submitted.
9. Open the report.
10. Tap on "More" and select "Merge"
11. Select the expense created on step 3 and tap on "Continue"
12. Select all the details of expense created on step 3 and finish the merging process.
13. When redirected to chat, navigate to the report of the remaining expense.
14. Verify that "Moved this expense to" message is displayed correctly

Case 5: Fix [Select details page is blank when merging with card transaction](https://github.com/Expensify/App/issues/70356#top)

Precondition:
- Workspace has imported card transactions.
- Create an expense that shares the same amount, merchant, description, category and date as the card transaction on the same report.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Open the expense report that has card and cash transactions from above.
4. Open the CASH expense.
5. Click More > Merge.
6. Select the CARD transaction (same details as the cash expense).
7. Click Continue.
8. Verify App navigates to confirmation page

Case 6: Fix [Merge expense - Second line of sentence is cut off when device font size is minimum](https://github.com/Expensify/App/issues/70352#top)

Precondition:

1. Device font size is the smallest.
2. Go to staging.new.expensify.com
3. Go to workspace chat.
4. Create two expenses with workspace chat. At least one of them has a long merchant.
5. Open expense report.
6. Long tap on the expense with long merchant > Select.
7. Tap dropdown button > Merge.
8. Verify The second line of sentence under Merge expenses header will not be cut off.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/e7dc4a36-c1b5-458b-bfa0-a45011efc312

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/bc6a38f0-93e5-4cbf-9165-9309552ca6c1

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/d9c04f38-502d-4857-a591-3f6977a3206e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/72c2d0c6-e351-4fd8-8328-1a11615c2a72

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/0f1b6391-dca9-42d5-bcdc-81e0298964fd

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/e7d8dcf4-03c4-4ec7-848b-6b8cf2b2d874

</details>

### CODE REVIEW

File: src/pages/TransactionMerge/ConfirmationPage.tsx [hunk 1]
```diff
@@ -67,10 +67,11 @@ function ConfirmationPage({route}: ConfirmationPageProps) {
         if (!targetTransaction || !mergeTransaction || !sourceTransaction) {
             return;
         }
+        const reportID = mergeTransaction.reportID;
 
         setIsMergingExpenses(true);
         mergeTransactionRequest(transactionID, mergeTransaction, targetTransaction, sourceTransaction);
-        Navigation.dismissModal();
+        Navigation.dismissModalWithReport({reportID});
```
Comment (dominictb) [inline src/pages/TransactionMerge/ConfirmationPage.tsx]: Does this fix the navigation after merge that I mentioned [here](https://expensify.slack.com/archives/C099T76RFU7/p1757279452136369)?

File: src/libs/MergeTransactionUtils.ts [hunk 2]
```diff
@@ -314,10 +314,10 @@ function buildMergedTransactionData(targetTransaction: OnyxEntry<Transaction>, m
  */
 function selectTargetAndSourceTransactionIDsForMerge(originalTargetTransaction: OnyxEntry<Transaction>, originalSourceTransaction: OnyxEntry<Transaction>) {
```
Comment (dominictb) [inline src/libs/MergeTransactionUtils.ts]:
```suggestion
function selectTargetAndSourceTransactionsForMerge(originalTargetTransaction: OnyxEntry<Transaction>, originalSourceTransaction: OnyxEntry<Transaction>) {
```

Comment (dominictb) [reply src/libs/MergeTransactionUtils.ts]: Same for the function JSDoc, remove all "IDs"

**Review by dominictb — APPROVED** [review]
We can merge once the above updates are resolved 👍

File: src/pages/TransactionMerge/ConfirmationPage.tsx (hunk 1 above)
Comment (hoangzinh) [reply src/pages/TransactionMerge/ConfirmationPage.tsx]: I think yes, it does

File: src/libs/MergeTransactionUtils.ts (hunk 2 above)
Comment (hoangzinh) [reply src/libs/MergeTransactionUtils.ts]: I updated in https://github.com/Expensify/App/pull/70334/commits/c6a62aa4f71e13c39c1074789e863426292b6400

**Review by thienlnam — DISMISSED** [review]

**Review by francoisl — DISMISSED** [review]

**Review by srikarparsi — APPROVED** [review]

**Review by francoisl — APPROVED** [review]

File: src/libs/actions/MergeTransaction.ts [hunk 3]
```diff
@@ -209,6 +239,33 @@ function mergeTransactionRequest(mergeTransactionID: string, mergeTransaction: M
...
+        : [];
+    const failureSourceReportActionData: OnyxUpdate[] = iouActionOfSourceTransaction
+        ? [
+              {
+                  onyxMethod: Onyx.METHOD.MERGE,
+                  key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${sourceTransaction.reportID}`,
+                  value: {
+                      [iouActionOfSourceTransaction.reportActionID]: {
+                          pendingAction: null,
+                      },
```
Comment (ahmedGaber93) [inline src/libs/actions/MergeTransaction.ts:264]: We also need to clear the `pendingAction` in success data to fix this https://github.com/Expensify/App/issues/71045

File: src/pages/TransactionMerge/ConfirmationPage.tsx [hunk 4]
```diff
@@ -67,11 +68,18 @@ function ConfirmationPage({route}: ConfirmationPageProps) {
...
-        Navigation.dismissModal();
-    }, [targetTransaction, mergeTransaction, sourceTransaction, transactionID]);
+
+        const reportIDToDismiss = reportID !== CONST.REPORT.UNREPORTED_REPORT_ID ? reportID : targetTransactionThreadReportID;
+        if (reportID !== targetTransaction.reportID && reportIDToDismiss) {
+            Navigation.dismissModalWithReport({reportID: reportIDToDismiss});
+        } else {
+            Navigation.dismissModal();
+        }
+    }, [targetTransaction, mergeTransaction, sourceTransaction, transactionID, targetTransactionThreadReportID]);
```
Comment (parasharrajat) [inline src/pages/TransactionMerge/ConfirmationPage.tsx:83]: Here we didn't handle the navigation properly for reports pages. It caused https://github.com/Expensify/App/issues/73057
