### PR TITLE
[No QA] fixed keyboard appears on split bill page

### LINKED ISSUE #1855: [Chat] [IOU] Mobile keyboard should not be displayed at IOUConfirm step
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

# Problem

The mobile alphabetic keyboard is being displayed on physical devices when the IOUAmount page is displayed. It isn't always consistent but occurs most of the time with no obvious pattern. This occurs on both Android and iOS physical devices. 

To reproduce this issue, apply the following diff so that 'New chat' and 'New group' launches the IOUModal:
_Make sure you include the final new line!_
```
diff --git a/src/components/CreateMenu.js b/src/components/CreateMenu.js
index 7c7afe3a..f311b4a1 100644
--- a/src/components/CreateMenu.js
+++ b/src/components/CreateMenu.js
@@ -53,12 +53,12 @@ class CreateMenu extends PureComponent {
             {
                 icon: ChatBubble,
                 text: 'New Chat',
-                onPress: () => this.setOnModalHide(() => Navigation.navigate(ROUTES.NEW_CHAT)),
+                onPress: () => this.setOnModalHide(() => Navigation.navigate(ROUTES.IOU_REQUEST)),
             },
             {
                 icon: Users,
                 text: 'New Group',
-                onPress: () => this.setOnModalHide(() => Navigation.navigate(ROUTES.NEW_GROUP)),
+                onPress: () => this.setOnModalHide(() => Navigation.navigate(ROUTES.IOU_BILL)),
             },
         ].map(item => ({
             ...item,

```

https://user-images.githubusercontent.com/10736861/111474608-25f02680-8724-11eb-899a-f860edf5ef80.mp4

# Desired Solution

The alphabetic keyboard should not be displayed, as we are not rendering an Input field on mobile:

**Upwork Link:** https://www.upwork.com/ab/applicants/1372398296191315968/job-details

### LINKED ISSUE #2377: Conversation - Tapping on "Upload Photo" will quickly flash keyboard
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Attachment flow proceeds with no issues

## Actual Result:
After user tap, keyboard will quickly flash before proceeding to the next attachment menu

## Action Performed:
1. Open app and login
2. Tap on any conversation
3. Tap on + on the left of message field
4. Tap on Upload Photo

## Workaround:
Visual issue, no need for workaround. 

## Platform:
Where is this issue occurring?

 Web
 iOS ✔️ 
 Android ✔️ 
 Desktop App
 Mobile Web

**Version Number:** 1.0.20-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

This was found while QAing https://github.com/Expensify/Expensify.cash/pull/2229

https://user-images.githubusercontent.com/44479856/114624928-799c5400-9c7f-11eb-866e-93ff57941268.mp4

**Expensify/Expensify Issue URL:**

### PR DESCRIPTION
**Pull request by parasharrajat**
Please review.

### Details
`ReportActionCompose` component has Controlled focus functionality. So when we close the modal we trigger the focus over the Keyboard on `ReportActiveCompose`. This behaviour was causing an issue when we navigate to the Split Bill page or possibly any other screen which we open from this image button's modal.

- Added a generic HOC component.

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes #1855 & Fixes #2377

### Tests/ QA steps
1. we need to enable the Split bill page first. for that replace the `CreateMenu`'s `menuItems` with the following on line L252.
```
          menuItems={[
                                                    {
                                                        icon: Paperclip,
                                                        text: 'Upload Photo',
                                                        onSelected: () => {
                                                            openPicker({
                                                                onPicked: (file) => {
                                                                    displayFileInModal({file});
                                                                },
                                                            });
                                                        },
                                                    },
                                                    {
                                                        icon: Paperclip,
                                                        text: 'Split Bill',
                                                        onSelected: () => {
                                                            Navigation.navigate(ROUTES.IOU_BILL);
                                                        },
                                                    },
                                                ]}
  
   ```                                            

Open any chat and then open the Split Bill page from the image  icon's modal. The keyboard should not open as the Split bill page has an onscreen keyboard.

### Tested On

- [x] Android

#### Android

https://user-images.githubusercontent.com/24370807/112221145-1d7c7c00-8c4d-11eb-916f-3251712ef649.mp4

### CODE REVIEW

**Review by Julesssss — COMMENTED** [review]
Looking good., but is there a reason you didn't end up going [with this solution?](https://github.com/Expensify/Expensify.cash/issues/1855#issuecomment-803212396) 

My understanding was that it would replace the need for us to handle the focus/blur lifecycle. But please correct me if I'm wrong here.

**Comment by parasharrajat** [comment]
@Julesssss. It was not working. `Navigation.isDrawerOpen` is only helpful when we have only a direct modal. But it involved multiple modals. The first modal would open when you press + icon. then on clicking split bill closes this modal. So the `Navigation.isDrawerOpen` check will allow the keyboard to open and then the Split bill modal will open. On the other hand,  screen focus is working well.

File: src/components/withNavigationContext.js [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+            this.unsubscribeFocus = this.context.addListener('focus', () => this.setState({
+                isScreenFocused: true,
+            }));
+            this.unsubscribeBlur = this.context.addListener('blur', () => this.setState({
+                isScreenFocused: false,
+            }));
+        }
+
+        componentDidUpdate() {
+            const valueToReturn = this.context.isFocused();
```
Comment (nickmurray47) [inline src/components/withNavigationContext.js:30]: is there a more descriptive variable name we can use for this `const`? I'm unsure what "value" is being stored here. 

If not, can we add a small comment above it describing what value we expect to get.

**Review by nickmurray47 — CHANGES_REQUESTED** [review]
had one small comment, looks good otherwise

File: src/components/withNavigationContext.js (hunk 1 above)
Comment (parasharrajat) [reply src/components/withNavigationContext.js:30]: what about `isCurrentlyFocused`?

Comment (nickmurray47) [reply src/components/withNavigationContext.js]: yup, that's great (if what's being returned is a `bool` vs. a number of some kind)

**Comment by parasharrajat** [comment]
@nickmurray47 @Julesssss Updated.

**Review by nickmurray47 — DISMISSED** [review]
LGTM - will leave final review / merging up to @Julesssss

File: src/components/withNavigationContext.js [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+                isScreenFocused: false,
+            };
+        }
+
+        componentDidMount() {
+            this.unsubscribeFocus = this.context.addListener('focus', () => this.setState({
+                isScreenFocused: true,
+            }));
+            this.unsubscribeBlur = this.context.addListener('blur', () => this.setState({
+                isScreenFocused: false,
```
Comment (Julesssss) [inline src/components/withNavigationContext.js:25]: I was trying to locate the docs for focus and blur to make sure I understand how this listener is invoked. Is this coming from [appState](https://reactnative.dev/docs/appstate#blur)?

File: src/components/withNavigationContext.js [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+    }
+
+    withNavigationContext.contextType = NavigationContext;
+    withNavigationContext.displayName = `withNavigationContext(${getComponentDisplayName(WrappedComponent)})`;
+    return withNavigationContext;
+}
+
+export {
+    navigationContextPropTypes,
+};
```
Comment (Julesssss) [inline src/components/withNavigationContext.js:68]: Is there a reason for not using the default export here?

Comment (Julesssss) [reply src/components/withNavigationContext.js:68]: I can see a default export and a separate export and haven't seen this before, would love to know more.

Comment (parasharrajat) [reply src/components/withNavigationContext.js:68]: So this is a HOC component. we generally want this file(module) to exhibit only the HOC functionality directly available. So you can say `navigationContextPropTypes` is a kind of Optional Export. However, it's just a pattern we can do this in any way, it suits us.

File: src/components/withNavigationContext.js (hunk 2 above)
Comment (parasharrajat) [reply src/components/withNavigationContext.js:25]: No. This `blur` event is coming from react-navigation navigation context [here](https://reactnavigation.org/docs/navigation-events/)
https://github.com/Expensify/Expensify.cash/blob/c4f64e56e764c799c736b19bf87e571cda5bda71/src/components/withNavigationContext.js#L61

Comment (Julesssss) [reply src/components/withNavigationContext.js:25]: Got it, thanks for sharing 👍

File: src/components/withNavigationContext.js (hunk 3 above)
Comment (Julesssss) [reply src/components/withNavigationContext.js:68]: Thanks, makes sense.

**Review by Julesssss — DISMISSED** [review]
Looks good to me, but I'm going to ask for one more reviewer.

**Comment by Julesssss** [comment]
Requested a review from someone more experienced with React Native

**Review by marcaaron — COMMENTED** [review]
Not blocking this PR. But I'm concerned this pattern will add complexity we don't need and overall feels like there might be a better way to solve this issue.

There are really only a handful of cases where we will want to focus the report comment input. Rather than add another check to see if we are focused on the report page it would be good to try to come up with some solution to explicitly focus the input based on actions the user is taking e.g. navigating to a report, closing the attachment modal etc.

I think if we can figure out how to do this... then there'd be no need to track screen focus or whether modals have "just been hidden" etc.

**Comment by parasharrajat** [comment]
@marcaaron Exactly. I was thinking that keyboard focus has many issues and this solution is limited to a small scope. We should only focus on special cases. Let me see into this.

Few issues :
1. Navigating between chats keyboard remains open.
2. When we scroll up and see an older message and open its context menu and do some action which opens a modal after modal is closed the keyboards opens again which should not happen.

It would be helpful if I can get a list of actions when we have to explicitly set the focus.
Thanks.

**Comment by parasharrajat** [comment]
@Julesssss  @nickmurray47 Thanks for the review. But I think we can keep this on hold. 

> It would be helpful if I can get a list of actions when we have to explicitly set the focus.

I would like to mould the PR in this direction.

**Comment by marcaaron** [comment]
I think the cases are:

- When we are navigating to a report/chat from some other route 
- When the drawer has opened from the LHN to the report
- When we are closing an "attachment modal"

**Comment by trjExpensify** [comment]
Hey guys, can we get a quick update on where we're at with this please?

**Comment by parasharrajat** [comment]
@trjExpensify. I am looking at other options to manage the focus on the Composer. There is a lot of discussion going around this issue. There are some issues #2100, #2154 which could change the behavior of the composer so I was waiting to have some update on that. I also saw that It was suggested that we should not focus on the Composer at all when we open the report from LHN. 
Thus, I am taking some time before I put some logic in place. But I will soon share some Logical update.

**Comment by marcaaron** [comment]
x-posting this here but here's what I think we should do to proceed...

1. Disable the "modal visibility aware" autofocus logic for the chat comment input when: 
    - we are using a native platform 
    - we are using mobile web (defined as anything that has a touch screen or software keyboard)
2. Modify this logic here so that it will only focus the input on desktop/web + when the report `isFocused` (use the `react-navigation` hook if necessary)
https://github.com/Expensify/Expensify.cash/blob/e9e726aa2a2f24ae98e88d9aa166acf4e8036ecb/src/pages/home/report/ReportActionCompose.js#L75-L78

3. Undo this change here https://github.com/Expensify/Expensify.cash/blob/e9e726aa2a2f24ae98e88d9aa166acf4e8036ecb/src/pages/home/report/ReportActionCompose.js#L261-L262 

We should only want to "autoFocus" on web/desktop (following the same rules of step 1). So, we require a custom implementation for this anyway instead of just passing `autoFocus` directly to the `TextInput`

4. Finally we should make sure that the keyboard is always dismissed when navigating from a chat to the sidebar/drawer content. @kidroca I think you've mentioned that `4` will no longer be necessary once we do the changes [here](https://github.com/Expensify/Expensify.cash/pull/2221)

**Comment by marcaaron** [comment]
What's the current status here @parasharrajat ?

**Comment by parasharrajat** [comment]
@marcaaron. Sorry for the delay here. I will pick this up now and post an update.

**Comment by kidroca** [comment]
@marcaaron @parasharrajat This should also be covered by the changes here: #2221 as they would disable the compose input while you're away from a chat

**Comment by parasharrajat** [comment]
@marcaaron Updated. Let me know your thoughts. And keyboard dismiss issue is gone after adding loader for report screen.

**Comment by parasharrajat** [comment]
@marcaaron I have pushed the new changes and there are a few lint errors which I will resolve after your review.

File: src/pages/home/report/ReportActionCompose.js [hunk 4]
```diff
@@ -66,18 +72,24 @@ class ReportActionCompose extends React.Component {
         this.setIsFocused = this.setIsFocused.bind(this);
         this.focus = this.focus.bind(this);
         this.comment = props.comment;
+        this.autoFocusEnabled = getPlatform() === 'desktop' || (getPlatform() === 'web' && !canUseTouchScreen());
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:75]: I'm pretty sure you've noticed by now, but this will need to be split up so we can use file extensions to determine whether to focus the input. Also, I don't think we need the distinction of desktop or web?

This name is a little verbose but I think it explains what we are trying to figure out here...

`canFocusInputOnScreenFocus()`

Then 

```js
// canAutoFocusTextInput/index.js
return () => !canUseTouchScreen();
```
```js
/// canAutoFocusTextInput/index.native.js
return () => false;
```

File: src/pages/home/report/ReportActionCompose.js [hunk 5]
```diff
@@ -66,18 +72,24 @@ class ReportActionCompose extends React.Component {
...
     }
 
     componentDidUpdate(prevProps) {
-        // When any modal goes from visible to hidden, bring focus to the compose field
-        if (prevProps.modal.isVisible && !this.props.modal.isVisible) {
+        // We want to manually set the focus only when.
+        //  1) Auto focus is enabled(we are on desktop/Desktop Web).
+        //  1) Screen is focsued.
+        //  2) When any modal goes from visible to hidden &
+        if (this.autoFocusEnabled && this.props.isScreenFocused
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:90]: `autoFocusEnabled` is maybe better named something like `this.shouldFocusInputOnScreenFocus`. Since we may be focusing in other contexts in the future and the focus isn't "disabled" per se it's just not what should happen when the parent screen gets focus.

File: src/pages/home/report/ReportActionCompose.js [hunk 6]
```diff
@@ -66,18 +72,24 @@ class ReportActionCompose extends React.Component {
...
         };
     }
 
     componentDidUpdate(prevProps) {
-        // When any modal goes from visible to hidden, bring focus to the compose field
-        if (prevProps.modal.isVisible && !this.props.modal.isVisible) {
+        // We want to manually set the focus only when.
+        //  1) Auto focus is enabled(we are on desktop/Desktop Web).
+        //  1) Screen is focsued.
+        //  2) When any modal goes from visible to hidden &
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:89]: This comment needs to be cleaned up a bit and formatted. The numbers are 1, 1, and 2, focused is spelled wrong, and there is a trailing `&`

It also doesn't really help explain why we are doing all of this. So I think we can just change it to...

>We only want to focus or refocus the input when a modal has been closed and the underlying screen is focused. We avoid doing this on native platforms since the software keyboard popping open creates a jarring and broken UX.

I think this way, someone will think twice before modifying the logic here.

File: src/pages/home/report/ReportActionCompose.js [hunk 7]
```diff
@@ -114,7 +126,9 @@ class ReportActionCompose extends React.Component {
      */
     focus() {
         if (this.textInput) {
-            this.textInput.focus();
+            InteractionManager.runAfterInteractions(() => {
+                this.textInput.focus();
+            });
```
Comment (marcaaron) [inline src/pages/home/report/ReportActionCompose.js:131]: I'm confused about what issue this is addressing. Can we add some comments to explain what interactions we are waiting to finish?

**Review by marcaaron — CHANGES_REQUESTED** [review]
Working well but have a few clean up requests. Thanks!

File: src/pages/home/report/ReportActionCompose.js (hunk 7 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:131]: Animations do not run smoothly, as a side effect of the focus. So this case should suffice when the modal closes. It's a precautionary check that's all. Not particularly needed for these changes.

File: src/pages/home/report/ReportActionCompose.js (hunk 6 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:89]: Haha, Sure. Feels like I need to work on better explanations more than code. :rofl:

File: src/pages/home/report/ReportActionCompose.js (hunk 7 above)
Comment (marcaaron) [reply src/pages/home/report/ReportActionCompose.js:131]: Cool whatever it is, please add an explanation so we have some insights when looking at the code. Out of curiositym is there a particular modal closing that causes jank? Maybe we can add a test to verify it does not look janky?

cc @Julesssss We should also maybe update these test steps so that it is testable by QA?

**Comment by marcaaron** [comment]
>Open any chat and then open the Split Bill page from the image icon's modal. The keyboard should not open as the Split bill page has an onscreen keyboard.

Not seeing how this can be done.

File: src/pages/home/report/ReportActionCompose.js (hunk 7 above)
Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:131]: So, the Most effect of focus interfering with animation can be seen on a new chat or new group screen where we set the focus on Search input. Here, we may need this on the web when we close modals and then set focus back to Input but it's not apparent. Due to the similar effect happening on New Chat modals, I thought it's better to apply `Interactionmanager` on all the places where we are setting focus.

**Comment by parasharrajat** [comment]
@marcaaron Updated the QA steps.

**Comment by parasharrajat** [comment]
Code Updated. Thanks.

**Comment by parasharrajat** [comment]
fixes #2377

**Review by marcaaron — APPROVED** [review]
Looks great thanks!

File: src/pages/home/report/ReportActionCompose.js (hunk 7 above)
Comment (kidroca) [reply src/pages/home/report/ReportActionCompose.js:132]: > So, the Most effect of focus interfering with animation can be seen on a new chat or new group screen where we set the focus on Search input.

But these are due to the `autoFocus` the logic would be applied for manual/programmatic focuses only
If you want to make auto focus wait for interactions as well you'll need to remove the `autoFocus` prop and call `this.focus()` when the component mount

> I thought it's better to apply `Interactionmanager` on all the places where we are setting focus.

This applies it only here on compose though right? Opening a new chat or search use the `TextInputFocusable`
Instead of adding this logic to all the places that set focus couldn't it perhaps be added to `TextInputFocusable` instead.
`TextInputFocusable` can wrap `inputRef.focus` with this behavior (before exposing it to parents)

Since focusing is done inside a callback, is it guaranteed you will always be inside a chat when this callback is invoked. Could it be possible for the user to tap/swipe open a chat and go back to LHN or somewhere else and then this callback runs and focuses the field
- `if (this.textInput)` - `textInput` - could be defined before setting this interaction, but could have changed inside the actual callback
- you will want to abort this interaction in case the component is unmounted but the callback is still scheduled to run. Similar to how you would clean up timers when a component unmounts

```js
focus() {
  this.scheduledIntercation = Interactionmanager.runAfterInteractions(() => {...})
}

componentWillUnmount() {
  if(this.scheduledIntercation) this.scheduledIntercation.cancel()
}
```

I think this works great, just that it should have been reusable/configurable for the other input fields as well

File: src/pages/home/report/ReportActionCompose.js [hunk 8]
```diff
@@ -66,18 +72,23 @@ class ReportActionCompose extends React.Component {
...
 
     componentDidUpdate(prevProps) {
-        // When any modal goes from visible to hidden, bring focus to the compose field
-        if (prevProps.modal.isVisible && !this.props.modal.isVisible) {
+        // We want to focus or refocus the input when a modal has been closed and the underlying screen is focused.
+        // We avoid doing this on native platforms since the software keyboard popping
+        // open creates a jarring and broken UX.
+        if (this.shouldFocusInputOnScreenFocus && this.props.isFocused
+            && prevProps.modal.isVisible && !this.props.modal.isVisible) {
+            this.setIsFocused(true);
```
Comment (kidroca) [inline src/pages/home/report/ReportActionCompose.js:91]: `setIsFocused(true)` would be called when the field is focused anyway. 
Though if there is a legit reason to call it here, the call can just be moved inside the `focus` method

```js
this.setIsFocused(true);
this.focus();
```

vs

```js
this.focus();
```

Comment (parasharrajat) [reply src/pages/home/report/ReportActionCompose.js:91]: Nice thoughts. Yeah Cancellation of Interaction is good to have. 

But about autofocus, I think there are some PR on react native that are handling animation and focus issue. But I agree lets just move the interaction based focus to TextInputFocusable. I didn't do this here as that covers bigger scope then the current issue. So its better to first analyze the effect of these changes and consider them.

**Comment by isagoico** [comment]
@marcaaron @Julesssss @nickmurray47 I don't think we're able to QA this PR since it requires changing some code. Can you guys assign someone to QA and let me know once it's done so we can check it off the list? Thanks in advance.

**Comment by Julesssss** [comment]
Just tested this and noticed that while the Keyboard doesn't display when opening a Modal, adding an attachment seems to have broke (**iOS** only, Android works fine) (if this is a regression from another issue please correct me). 

- Open a chat report on mobile
- Tap the '+' icon to add an attachment
- The Keyboard displays on top of the CreateMenu

https://user-images.githubusercontent.com/10736861/114855009-5ab3d400-9ddd-11eb-88ed-7e133df9c072.MP4

**Comment by parasharrajat** [comment]
@Julesssss as per the changes here, we have removed automatic opening of keyboard on Native devices. So autofocus should  not happen at all. I think this is regression from another PR

**Comment by kidroca** [comment]
@Julesssss @parasharrajat 
This is a leftover from the modal to modal fix 

https://github.com/Expensify/Expensify.cash/blob/29fe119755ab887edf010d38565b162f3269de6f/src/pages/home/report/ReportActionCompose.js#L232-L243

Due to the modal handling at the time (autofocusing) it was necessary to add this. Otherwise the 2nd modal would disappear immediately 

The decision to drop autofocus happened a week or more later.
The `focus` there should be removed as well

**Comment by kidroca** [comment]
Previously with the autofocus behavior something similar would happen (again only on iOS) due to focus going to that field from the code in `componentDidUpdate` that would move focus to the field as the 2nd modal opens and this would dismiss it.

But having the field already focused prevented this at the time

**Comment by parasharrajat** [comment]
I see. I will patch in another PR for that but its not a regression of this one so no need to reopen this.

**Comment by kidroca** [comment]
@parasharrajat @Julesssss 
It turns out there's more to this actually

The fix above resolves the issue - see the first part of the video below
But on iOS it looks like focus is restored to the input anyway. So when the input was focused and you go through the attachment flow. the keyboard pops up briefly in between the modals - second part of the video 

#### Removing the focus line
https://user-images.githubusercontent.com/12156624/114863600-9740f900-9df8-11eb-90fa-b526394a84c2.mov

This is why I originally had a `this.blur` function - I had disabled the autofocus to see how stuff would work and stumbled on this behavior.
My fix was to blur the input when you tap on the (+) button, because otherwise focus would try to return the input, though this is iOS specific as it's not caused by our code.

#### Replacing with blur

https://user-images.githubusercontent.com/12156624/114864738-04a15980-9dfa-11eb-9c88-bec5e5e96467.mov

Replacing with blur seem to work better. As far as I tested back then it didn't cause any issues on the other mobile platforms

If you want to I can open another PR with these changes

**Comment by Julesssss** [comment]
Thanks @kidroca, that sounds good to me but I think it's best to await confirmation from @marcaaron in case this has wider repercussions (I'm unable to look any further into this myself currently).

**Comment by marcaaron** [comment]
Tbh I'm having some trouble following the discussion. Maybe we should create a new issue as a next step so we can evaluate what is happening and what to do about it and who will do it?

**Comment by roryabraham** [comment]
@parasharrajat, it seems like this PR cannot be tested without some code modifications, is that correct? If that's the case, this is not going to be testable on staging (at least not until the IOU beta is set up). Given that this page isn't visible on staging or production yet, I'm going to check it off in the deploy checklist. 

For future reference, when pull requests are not possible to QA on staging, the title of the issue should be prefixed with `[No QA]`, and the "QA Steps" section of the pull request template should say "None".

**Comment by parasharrajat** [comment]
@roryabraham There is twist for this PR. Initially we started fixing the issue for Split bill page but then moved to manage the focus on the report action composer. 


To test it we can just switch the chat screen and drawer or open the modals and then close them.

We have to check that the focus is not set automatically to the composer on mobile devices but it is set on the web and desktop.
