### PR TITLE
check if room name is editable on form submit

### LINKED ISSUE #14756: [HOLD for payment 2023-02-20] `Invalid room name` message appears on press enter on keyboard
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to NewDot, and click Settings, Workspaces, and New workspace (if you don’t have one). 
2. Click on #admins or #announce in LHN. 
3. Go to Details > Settings of that room. 
4. Click on notify me about new message. Change the selection for that setting. 
5. Press enter button of keyboard. 
6. Notice that you receive a `Invalid room name` error. 

## Expected Result:
should not show any error message

## Actual Result:
shows invalid room name error message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.64-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/216390371-86590e20-15c6-4ded-8496-8f14abc1d61d.mov

https://user-images.githubusercontent.com/43996225/216391142-b93ad084-3971-4182-9a36-7f0b338def69.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675315466757109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01404139784a132659</li>
        <li>Upwork Job ID: 1621653739872579584</li>
        <li>Last Price Increase: 2023-02-03</li>
    </ul>
</details>

### PR DESCRIPTION
**Pull request by hayata-suenaga**
### Details

Initialized the property `shouldDisableRename` inside a constructor and made it available inside the class (instead of `shouldDisableRename` being a local variable of the `render` method.

Using the above property, `updatePolicyRoomName` method determines whether to invoke `Report.updatePolicyRoomName` or not. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/14756

### Tests / QA Steps / Offline tests

- [x] Verify that no errors appear in the JS console
Unrelated error on an invalid prop type appearing in the console

1. Login to NewDot, and click Settings, Workspaces, and New workspace (if you don’t have one).
2. Click on #admins or #announce in LHN.
3. Go to Details > Settings of that room.
4. Click on notify me about new message. Change the selection for that setting.
5. Press enter button of keyboard.
6. `Invalid room name error` doesn't appear.

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/98560306/217111673-de12339e-c168-4ba3-9b9e-45e8fdfa6410.mov

</details>

### CODE REVIEW

**Comment by hayata-suenaga** [comment]
I have read the CLA Document and I hereby sign the CLA

File: src/pages/ReportSettingsPage.js [hunk 1]
```diff
@@ -55,6 +55,8 @@ class ReportSettingsPage extends Component {
 
         this.validate = this.validate.bind(this);
         this.updatePolicyRoomName = this.updatePolicyRoomName.bind(this);
+        this.shouldDisableRename = ReportUtils.isDefaultRoom(this.props.report)
+        || ReportUtils.isArchivedRoom(this.props.report);
```
Comment (yuwenmemon) [inline src/pages/ReportSettingsPage.js:59]: NAB: You can probably put this on one line
```suggestion
        this.shouldDisableRename = ReportUtils.isDefaultRoom(this.props.report) || ReportUtils.isArchivedRoom(this.props.report);
```

File: src/pages/ReportSettingsPage.js [hunk 2]
```diff
@@ -71,8 +73,8 @@ class ReportSettingsPage extends Component {
     updatePolicyRoomName(values) {
         Keyboard.dismiss();
 
-        // When the room name has not changed, skip the Form submission
-        if (values.newRoomName === this.props.report.reportName) {
+        // When the room name has not changed or should not be changed, skip the Form submission
+        if (this.shouldDisableRename || values.newRoomName === this.props.report.reportName) {
```
Comment (yuwenmemon) [inline src/pages/ReportSettingsPage.js:77]: Do we need this check here if we're already not showing the submit button?

**Review by yuwenmemon — CHANGES_REQUESTED** [review]

**Comment by yuwenmemon** [comment]
FYI @hayata-suenaga you have git conflicts! (FUN 😅)

File: src/pages/ReportSettingsPage.js (hunk 2 above)
Comment (hayata-suenaga) [reply src/pages/ReportSettingsPage.js:77]: Even when the submit button is not being displayed, hitting `Enter` will still trigger `onSubmit`.

**Review by puneetlath — DISMISSED** [review]

**Comment by hayata-suenaga** [comment]
> FYI @hayata-suenaga you have git conflicts! (FUN 😅)

I fixed the merge issue.

File: src/pages/ReportSettingsPage.js [hunk 3]
```diff
@@ -56,6 +56,7 @@ class ReportSettingsPage extends Component {
 
         this.validate = this.validate.bind(this);
         this.updatePolicyRoomName = this.updatePolicyRoomName.bind(this);
+        this.shouldDisableRename = ReportUtils.isDefaultRoom(this.props.report) || ReportUtils.isArchivedRoom(this.props.report);
```
Comment (yuwenmemon) [inline src/pages/ReportSettingsPage.js:59]: I think we should pass this in as a prop rather than making a class variable here in the constructor.

Comment (yuwenmemon) [reply src/pages/ReportSettingsPage.js:59]: (FYI, I say this considering the 'Data flows down' rule we have) - check out our [React Style Guide](https://github.com/Expensify/Style-Guides/blob/main/react.md#rule-1-dataflowsdown) for more info!

**Review by yuwenmemon — CHANGES_REQUESTED** [review]

File: src/pages/ReportSettingsPage.js (hunk 3 above)
Comment (hayata-suenaga) [reply src/pages/ReportSettingsPage.js:59]: There are several places that navigate to ReportSettingsPage:

[log_nav_to_report_settings_page.txt](https://github.com/Expensify/App/files/10689191/log_nav_to_report_settings_page.txt)

I don't know in which case the room name requires to be editable. I feel like the logic for determining whether the room name should be editable depending on `reportId` passed belongs to `ReportSettingsPags`.

@yuwenmemon Please let me know your thoughts

Comment (yuwenmemon) [reply src/pages/ReportSettingsPage.js:59]: Oh hm yes because this is a page that comes directly from a route I see. Okay so nevermind me then! :ohnothing:

**Review by yuwenmemon — DISMISSED** [review]

**Review by 0xmiroslav — DISMISSED** [review]
Looks good and tests well!

**Comment by yuwenmemon** [comment]
> Or as a permanent solution, we should define shouldDisableRename flag as state value (not class member) so that flag synced whenever report data is updated.

Ah fair point :+1: Yeah we should probably do that @hayata-suenaga 

Although I don't see how we would need to block on https://github.com/Expensify/App/issues/14513#issuecomment-1424113923

**Comment by hayata-suenaga** [comment]
> > Or as a permanent solution, we should define shouldDisableRename flag as state value (not class member) so that flag synced whenever report data is updated.
> 
> Ah fair point 👍 Yeah we should probably do that @hayata-suenaga
> 
> Although I don't see how we would need to block on [#14513 (comment)](https://github.com/Expensify/App/issues/14513#issuecomment-1424113923)

I'll implement 0xmiroslav's suggestion

**Comment by hayata-suenaga** [comment]
I couldn't reproduce redirection that @0xmiroslav mentioned, but I made change to check if the room name is editable on every re-render.

**Review by 0xmiroslav — APPROVED** [review]

**Review by yuwenmemon — APPROVED** [review]
Ah, nice very clean!
