### PR TITLE
[IS-1549] Fixed submission form issue on press enter key

### LINKED ISSUE #1549: Pressing Enter key does not always submit forms on sign in screen
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  desktop 

**Action Performed (reproducible steps):**

1. Sign out and refresh Expensify.cash
2. Enter email and press return
3. Enter password and press return
4. Verify you get signed in
5. Sign out but do not refresh
6. Enter email and press return
7. Observe that the form is not submitted

**Expected Result:**
Hitting return should consistently submit the sign in form (really any form)

**Actual Result:**
Not _consistently_ submitting

**Notes/Photos/Videos:** 
 
**Logs - JS/Android/iOS (if applicable)**:

Job:  https://www.upwork.com/jobs/~01394d3648bb7249b5

### PR DESCRIPTION
**Pull request by aliabbasmalik8**
### Details
Fixed issue according to [these instructions](https://github.com/Expensify/Expensify.cash/issues/1549#issuecomment-786280962)

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/1549

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/31027036/109315815-da440e80-7842-11eb-8964-8f9c3cf79697.mov

#### Mobile Web
https://user-images.githubusercontent.com/31027036/109316195-46267700-7843-11eb-879d-b28721773b49.mov

#### Desktop
https://user-images.githubusercontent.com/31027036/109317014-20e63880-7844-11eb-9f58-ae602efe29fa.mov

#### iOS
https://user-images.githubusercontent.com/31027036/109317188-5c810280-7844-11eb-8e2b-2fff4004804a.mov

#### Android
https://user-images.githubusercontent.com/31027036/109317449-a23dcb00-7844-11eb-888d-79cde09cfdb5.mov

### CODE REVIEW

**Review by bondydaa — DISMISSED** [review]
👍 from me but going to tap @roryabraham or @marcaaron to also give this a look over too.

File: src/components/Modal/BaseModal.js [hunk 1]
```diff
@@ -8,86 +8,101 @@ import themeColors from '../../styles/themes/default';
...
+
+        this.subscribeToKeyEvents = this.subscribeToKeyEvents.bind(this);
+        this.unsubscribeFromKeyEvents = this.unsubscribeFromKeyEvents.bind(this);
+    }
+
+    componentWillUnmount() {
+        this.unsubscribeFromKeyEvents();
+    }
+
+    subscribeToKeyEvents = () => {
```
Comment (marcaaron) [inline src/components/Modal/BaseModal.js:23]: Can we avoid using the class property syntax here? We have standardized on just using regular class methods in components like these and since you've bound these in the constructor there is even less of a reason to do this here.

File: src/components/Modal/BaseModal.js [hunk 2]
```diff
@@ -8,86 +8,101 @@ import themeColors from '../../styles/themes/default';
...
+        KeyboardShortcut.subscribe('Escape', this.props.onClose, [], true);
+        KeyboardShortcut.subscribe('Enter', this.props.onSubmit, [], true);
     };
-    const unsubscribeFromKeyEvents = () => {
+
+    unsubscribeFromKeyEvents = () => {
```
Comment (marcaaron) [inline src/components/Modal/BaseModal.js:28]: Same with this one please thanks :)

**Review by marcaaron — CHANGES_REQUESTED** [review]
A couple of small comments from me but otherwise LGTM.

**Comment by marcaaron** [comment]
Testing great on web. Nice!

**Comment by marcaaron** [comment]
There are some lint errors that will need to be fixed before we can merge. Other than that, LGTM 👍

**Comment by aliabbasmalik8** [comment]
> There are some lint errors that will need to be fixed before we can merge. Other than that, LGTM 👍

Fixed lint issues, Please have a look 
Thanks

**Review by marcaaron — APPROVED** [review]
