### PR TITLE
fix cursor issue

### LINKED ISSUE #987: The cursor looks too close to the left edge
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

View the job on Upwork [here](https://www.upwork.com/jobs/~012aa302a196a4cc88)

**Platform - version:**  
Build version : Android 8.0
Device and OS: SG S8

**Action Performed (reproducible steps):**
1.  Launch the app and login
2. On the search box, search any user you have access to.

Tester login credentials - Password	: Feya86Katya
Tester login credentials - Email/Phone	: abeccivutest+1028@gmail.com

**Expected Result:**
The cursor should be placed a bit off typing field.

**Actual Result:**
The cursor looks too close to the edge.

**Notes/Photos/Videos:** 

image

### PR DESCRIPTION
**Pull request by UpworkBartkoski**
### Details

On Android, TextInput padding not working when its parent has display: none/flex to show/hide. 
In this case, position: 'absolute' works fine when the TextInput will be mounted/unmounted.
So,  we are using `width` to toggle visibility because display: 'none' on the parent affects padding styles on the TextInput.

### Fixed Issues

Fixes #987

### Tests

1. Login into the application on Android emulator or devices.
2. Click hamburger menu on Home screen to open sidebar
3. On the left sidebar, You can just see that the cursor doesn't look too close to the left edge of the search box.

### Screenshots

103078436-7a598f00-4597-11eb-9bf9-4b7c3ef75ccd

### CODE REVIEW

**Comment by UpworkBartkoski** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by timszot** [comment]
Please re-write the original post to use this template:
```
<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

### Details
<Explanation of the change or anything fishy that is going on>

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes GH_LINK

### Tests
<!--- 
Add a numbered list of manual tests you performed that validates your changes work on all platforms, and that there are no regressions present.
Add any additional test steps if test steps are unique to a particular platform.
Manual test steps should be written so that your reviewer can repeat and verify one or more expected outcomes.

For example:
1. Click on the text input to bring it into focus
2. Upload an image via copy paste
3. Verify a modal appears displaying a preview of that image 
--->

### Screenshots
<Add any necessary screenshots for all platforms if your change added or updated UI>
```

**Review by marcaaron — CHANGES_REQUESTED** [review]
This solution _does_ fix the issue. But it's not clear exactly why it fixes the issue and there are some broken styles on the web and desktop side now that must be fixed.

My _guess_ is that there is some kind of issue related to toggling the `position: 'absolute'` value, but not really understanding why this fix works. In any case, it seems like when we are on mobile we don't need to toggle the `hamburgerStyle` based on `this.props.isSidebarShown` since the sidebar should _always_ be `position: 'absolute'`.

Maybe @roryabraham or @AndrewGable have thoughts about why we should ever change the sidebar from `position: absolute` if the "sidebar is not shown". I believe as long as it's enabled it should stay "position: absolute".

**Comment by UpworkBartkoski** [comment]
> This solution _does_ fix the issue. But it's not clear exactly why it fixes the issue and there are some broken styles on the web and desktop side now that must be fixed.
> 
> My _guess_ is that there is some kind of issue related to toggling the `position: 'absolute'` value, but not really understanding why this fix works. In any case, it seems like when we are on mobile we don't need to toggle the `hamburgerStyle` based on `this.props.isSidebarShown` since the sidebar should _always_ be `position: 'absolute'`.
> 
> Maybe @roryabraham or @AndrewGable have thoughts about why we should ever change the sidebar from `position: absolute` if the "sidebar is not shown". I believe as long as it's enabled it should stay "position: absolute".

TextInput padding not working when its parent has display: none/flex to show/hide the TextInput. It works fine when the TextInput will be mounted/unmounted.

File: src/pages/home/HomePage.js [hunk 1]
```diff
@@ -205,8 +205,7 @@ class App extends React.Component {
     }
 
     render() {
-        const hamburgerStyle = this.state.isHamburgerEnabled && this.props.isSidebarShown
-            ? styles.hamburgerOpenAbsolute : styles.hamburgerOpen;
```
[the remark this answers is not in the document]
Comment (UpworkBartkoski) [reply src/pages/home/HomePage.js:209]: When TextInput is mounted, the hamburgerOpenAbsolute should be set as the initial style for Android to make padding work.
This issue occurs on Android only.
The hamburgerOpen style works for other platforms.
Screen Shot 2020-12-24 at 2 36 32 AM
Screen Shot 2020-12-24 at 2 39 40 AM
Screen Shot 2020-12-24 at 2 52 35 AM

File: src/pages/home/HomePage.js [hunk 2]
```diff
@@ -6,13 +6,14 @@ import {
     Animated,
     Easing,
     Keyboard,
-    Pressable,
+    Pressable
```
Comment (roryabraham) [inline src/pages/home/HomePage.js:9]: small detail - we always include trailing commas where valid. This is part of our style guide, but if it is not reflected by our ESLint rules we should try to fix that.

Comment (marcaaron) [reply src/pages/home/HomePage.js:9]: Created issue for this here: https://github.com/Expensify/Expensify/issues/149302
Has bothered me for a while 😄

Comment (UpworkBartkoski) [reply src/pages/home/HomePage.js]: > small detail - we always include trailing commas where valid. This is part of our style guide, but if it is not reflected by our ESLint rules we should try to fix that.

Done.

Comment (UpworkBartkoski) [reply src/pages/home/HomePage.js]: > Created issue for this here: [Expensify/Expensify#149302](https://github.com/Expensify/Expensify/issues/149302)
> Has bothered me for a while 😄

Expensify/Expensify#149302 shows 404

Comment (roryabraham) [reply src/pages/home/HomePage.js]: > Expensify/Expensify#149302 shows 404

No need to worry about this! Thanks for adding the trailing comma 👍

File: src/pages/home/HomePage.js [hunk 3]
```diff
@@ -205,8 +206,11 @@ class App extends React.Component {
     }
 
     render() {
-        const hamburgerStyle = this.state.isHamburgerEnabled && this.props.isSidebarShown
-            ? styles.hamburgerOpenAbsolute : styles.hamburgerOpen;
+        let hamburgerStyle = hamburgerInputPadding();
+        if (!hamburgerStyle) {
```
Comment (marcaaron) [inline src/pages/home/HomePage.js:210]: Rather than do a conditional check here we should make the styles below return an empty object and just reference them normally. One way to do that would be to import them into the `styles` object. Then we do not need to perform these checks here and can leave everything as it was.

Please let me know if that makes sense.

File: src/styles/hamburgerInputPadding/index.android.js [hunk 4]
```diff
@@ -0,0 +1,12 @@
+/**
+ * Android platform supports the "hamburgerInputPadding" property, so this
+ * can be added to the object
+ */
+
+import styles from '../styles';
+
+function hamburgerInputPadding() {
+    return styles.hamburgerOpenAbsolute;
```
Comment (marcaaron) [inline src/styles/hamburgerInputPadding/index.android.js:9]: This value does not get used?

File: src/styles/hamburgerInputPadding/index.android.js [hunk 5]
```diff
@@ -0,0 +1,12 @@
+/**
+ * Android platform supports the "hamburgerInputPadding" property, so this
+ * can be added to the object
```
Comment (marcaaron) [inline src/styles/hamburgerInputPadding/index.android.js:3]: Please include a link to the react native issue you found in this code so we can understand why the decision was made to do this.

**Review by marcaaron — CHANGES_REQUESTED** [review]
Thanks for the link to that issue!

But if the issue is that we are hiding the parent view would this perhaps _best_ be solved by... not hiding the parent view?

I left some comments about how to improve the existing solution. But it might be better to stop using `display: 'none'` for the parent view of the text input if android has an issue with this.

**Comment by UpworkBartkoski** [comment]
> Thanks for the link to that issue!
> 
> But if the issue is that we are hiding the parent view would this perhaps _best_ be solved by... not hiding the parent view?
> 
> I left some comments about how to improve the existing solution. But it might be better to stop using `display: 'none'` for the parent view of the text input if android has an issue with this.

Yes, we can use `width: 300` or `width0` instead of `display: 'flex'` or `display: 'none'`

File: src/pages/home/HomePage.js [hunk 6]
```diff
@@ -220,7 +220,7 @@ class App extends React.Component {
     render() {
         const hamburgerStyle = this.state.isHamburgerEnabled && this.props.isSidebarShown
             ? styles.hamburgerOpenAbsolute : styles.hamburgerOpen;
-        const visibility = !this.state.isHamburgerEnabled || this.props.isSidebarShown ? styles.dFlex : styles.dNone;
+        const visibility = !this.state.isHamburgerEnabled || this.props.isSidebarShown ? styles.w300 : styles.w0;
```
Comment (marcaaron) [inline src/pages/home/HomePage.js:223]: It would be nice to prevent this bug from returning somehow. Can we please link to the issue you found in a doc here with a note that we are using `width` to toggle `visibility` because `display: 'none'` on the parent affects padding styles on the `TextInput`?

**Review by marcaaron — CHANGES_REQUESTED** [review]
Looks great! But there is one request and minor visual regression that would be nice to take care of if possible. 

cc @shawnborton let us know if it's a concern

`master`

https://user-images.githubusercontent.com/32969087/103328367-c2940980-49fc-11eb-8aef-0a1327eee128.mp4

`UpworkBartkoski:chris-cursor-issue`

https://user-images.githubusercontent.com/32969087/103328394-d5a6d980-49fc-11eb-8084-18a173a738e9.mp4

If you look carefully, you'll notice the content is shifting some distance when opening and closing.

**Comment by shawnborton** [comment]
Good catch @marcaaron - I agree, we should resolve this regression so that the behavior looks like the example of master you showed above.

**Comment by UpworkBartkoski** [comment]
> Looks great! But there is one request and minor visual regression that would be nice to take care of if possible.
> 
> cc @shawnborton let us know if it's a concern
> 
> `master`
> 
>  2020-12-29_17-35-22.mp4 
> `UpworkBartkoski:chris-cursor-issue`
> 
>  2020-12-29_17-37-03.mp4 
> If you look carefully, you'll notice the content is shifting some distance when opening and closing.

This bug was caused by `borderRightWidth: 1` in `hamburgerOpen` style.

**Comment by UpworkBartkoski** [comment]
Updated

File: src/styles/styles.js [hunk 7]
```diff
@@ -743,11 +741,20 @@ const styles = {
...
 
+    w300br1: {
+        width: 300,
+        borderRightWidth: 1,
+    },
+
+    w0br0: {
+        width: 0,
+        borderRightWidth: 0,
+    },
```
Comment (marcaaron) [inline src/styles/styles.js:756]: I think for now we can just update these style names to `sidebarHidden` and `sidebarVisible`. 
After this change is applied I will merge the solution.

**Review by marcaaron — CHANGES_REQUESTED** [review]

File: src/styles/styles.js [hunk 8]
```diff
@@ -743,11 +741,20 @@ const styles = {
     },
 
     hamburgerOpen: {
-        borderRightWidth: 1,
         borderColor: themeColors.border,
         width: 300,
     },
 
+    w300br1: {
```
Comment (roryabraham) [inline src/styles/styles.js:748]: Could you please refactor this a bit so that `w300` and `w0` are in `src/styles/utilities/sizing.js`, then use them in here? Something like this:

```
w300b1: {
    ...sizing.w300,
    borderRightWidth: 1,
}
```

Also, maybe rename these styles to match their usage a bit more closely? Something like:

`w300br1` -> `hamburgerShown`,
`w0br0` -> `hamburgerHidden`

**Review by roryabraham — CHANGES_REQUESTED** [review]

File: src/styles/styles.js (hunk 8 above)
Comment (UpworkBartkoski) [reply src/styles/styles.js:748]: Hey, which one exactly should I get?
@marcaaron or @roryabraham

Comment (marcaaron) [reply src/styles/styles.js:748]: Can we change to `sidebarVisible` and `sidebarHidden` please? We are going to remove the "hamburger" language soon. Thanks! 🍔

**Comment by UpworkBartkoski** [comment]
Updated

File: src/styles/styles.js (hunk 7 above)
Comment (UpworkBartkoski) [reply src/styles/styles.js:756]: @marcaaron 
Updated

File: src/styles/styles.js (hunk 8 above)
Comment (UpworkBartkoski) [reply src/styles/styles.js]: @marcaaron @roryabraham 
Updated

**Review by marcaaron — APPROVED** [review]
Thanks for the changes and solution.

**Comment by UpworkBartkoski** [comment]
> Thanks for the changes and solution.

**Review by roryabraham — APPROVED** [review]
