### PR TITLE
Track Expense - Polish

### LINKED ISSUE #59597: Attendees - Attendees field shows "Attendees per person" while receipt is scanning
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.23-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/58120
**Email or phone of affected tester (no customers):** sdjmosdjojsoid@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Create expense > Scan.
4. Upload a receipt.
5. On confirmation page, click Attendees.
6. Select another user and click Save.
7. Note that Attendees field shows "Attendees • MYR 0.00 per person".
8. Create the expense.
9. Go to transaction thread.

## Expected Result:
Attendees field will show "Attendees • MYR 0.00 per person" in the transaction thread while the receipt is scanning.

## Actual Result:
Attendees field shows "Attendees per person" in the transaction thread while the receipt is scanning.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ea5ca6a1-c1d8-4530-b06d-f06615dfa0d5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

### LINKED ISSUE #59599: [Due for payment 2025-04-16] Attendees - Unable to select attendee when categorizing expense
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.23-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check, new feature
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** sdjmosdjojsoid@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Account has self DM.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Create expense > Manual.
4. Enter amount > Next,
5. On confirmation page, click Attendees.
6. Note that Attendees field is auto-selected to yourself and has a Save button.
6. Go to self DM.
7. Track a manual expense.
8. Click Categorize it.
9. Select a category.
10. Click Show more.
11. Click Attendees field.

## Expected Result:
Attendees field will auto-select to yourself and have a Save button.

## Actual Result:
Attendees field does not auto-select to yourself and does not have a Save button.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dd4a8aea-3318-4fb7-9366-135088728f41

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

### LINKED ISSUE #59600: Attendees - User appears twice briefly after selection
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.23-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** sdjmosdjojsoid@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Create expense > Manual
3. Enter amount > Next.
4. Select a destination if needed.
5. Click Show more.
6. Click Attendees.
7. Enter any user name.
8. Click on the user.

## Expected Result:
The user will not appear twice after the user is selected.

## Actual Result:
The user appears twice briefly after the user is selected.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/adc410cf-cf62-48c1-a2b4-dbcc23626302

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

### LINKED ISSUE #59602: Attendees - Attendees field is absent on invoice confirmation page but present in invoice thread
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.23-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sdjmosdjojsoid@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Other

## Action Performed:
Precondition:
- Workspace has enabled invoicing.

1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount > Next.
4. Select a new user with no previous chat.
5. Click Show more.
6. Note that there is no Attendees field on the confirmation page.
7. Submit the invoice.
8. Go to invoice thread.
9. Note that Attendees field is present in invoice thread.

## Expected Result:
Attendees field should be present or absent on both invoice confirmation page and invoice thread.

## Actual Result:
Attendees field is absent on invoice confirmation page but present in invoice thread.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0b7351c2-d189-4771-be40-15123dcfe4a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

### LINKED ISSUE #59603: Attendee- Attendee list shows to add a member that already included as attendee
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.1.23-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/58120
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Windows 10 /Chrome, Samsung Galaxy s10/ Chrome
**App Component:** Other

## Action Performed:
1. Navigate in to staging.new.expensify.com
2. Open WS setting and add a 1 member
3. Open the FAB menu and click on create expense.
4. Select manual expense creation and enter an amount.
5. On the confirmation screen, click on Attendees section and add one attendee users ( the one you add in step 2).
6. Submit the expense and go to expense details page.
7. Click on the Attendees section and Notice that you can add the selected member already

## Expected Result:
The selected member shouldn't be available to add again in contact list

## Actual Result:
In Attendees list, you can add the selected member again

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cb8b98cd-b093-4d6c-90a0-dfbc53bcd20e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

### LINKED ISSUE #59617: [Due for payment 2025-04-16] [Due for payment 2025-04-14] Attendees - Test manager tooltip does not disappear after selecting the manager
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.23-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** jsdoimjdosjos22djosj@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account
3. Create a new workspace
4. Go to workspace chat
5. Click + > Create expense > Manual
6. Enter amount > Next
7. Click Show more
8. Click Attendees
9. Select Manager McTest

## Expected Result:
The test manager tooltip will disappear after selecting the manager

## Actual Result:
The test manager tooltip does not disappear after selecting the manager
It still appears after selecting and unselecting the manager many times

## Workaround:
Unknown

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details> 

https://github.com/user-attachments/assets/2da9f89d-047a-4f1c-8700-b8b0e4c5950b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### LINKED ISSUE #59621: [Due for payment 2025-04-16] Scan - In failed scan expense selecting an attendee after scanning is complete displays error
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9 1.23-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check, new feature
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** Slottwo1 hons1@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Redminote 10s android 13
**App Component:** Money Requests

## Action Performed:
1. Launch app
2. Open employee workspace chat
3. Create a scan expense and wait till scanning failed and preview shows ₹0.00
4. Open the scan expense 
5. Tap attendees - select a attendee

## Expected Result:
In failed scan expense, selecting an attendee after scanning musnt display error.

## Actual Result:
In failed scan expense, selecting an attendee after scanning is over displays error " unexpected error editing this expense.Please try again later.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/622f1e8c-90b1-4b81-947c-19170d8c5268

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

### LINKED ISSUE #59631: [$250] Attendees - Selected attendee is cleared after creating Scan/Distance/Per diem expense
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.23-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No, reproducible on hybrid only
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ail.sdjomisos@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Create expense > Distance.
4. Enter waypoints > Next.
5. On confirmation page, click Show more.
6. Note that Attendees field has yourself selected.
7. Create the expense.
8. Go to transaction thread.

## Expected Result:
Attendees field in the transaction thread will retain the selection on the confirmation page.

## Actual Result:
Attendees field in the transaction thread is cleared.

This issue happens with Scan, Distance and Per diem expense.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2cf29dd0-3baf-4380-8ac4-bd42b7629691

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021907932172983504516</li>
        <li>Upwork Job ID: 1907932172983504516</li>
        <li>Last Price Increase: 2025-04-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

### PR DESCRIPTION
**Pull request by allroundexperts**
### Explanation of Change

fixes https://github.com/Expensify/App/issues/59602
fixes https://github.com/Expensify/App/issues/59603
fixes https://github.com/Expensify/App/issues/59617
fixes https://github.com/Expensify/App/issues/59621
fixes https://github.com/Expensify/App/issues/59631
fixes https://github.com/Expensify/App/issues/59597
fixes https://github.com/Expensify/App/issues/59599
fixes https://github.com/Expensify/App/issues/59600

### Fixed Issues

$ https://github.com/Expensify/App/issues/44725
PROPOSAL: N/A

### Tests

**Test 1**

https://github.com/Expensify/App/issues/59602

1. Open app, and create a workspace that has enabled invoicing.
2. Go to FAB > Send invoice.
3. Enter amount > Next.
4. Select a new user with no previous chat.
5. Click Show more.
6. Note that there is no Attendees field on the confirmation page.
7. Submit the invoice.
8. Go to invoice thread.

Expected Result:
Verify that the attendees field is not present in the thread.

**Test 2**

https://github.com/Expensify/App/issues/59603

1. Open the app, go to WS setting and add a member
2. Open the FAB menu and click on create expense.
3. Select manual expense creation and enter an amount.
4. On the confirmation screen, click on Attendees section and add one attendee users ( the one you add in step 2).
5. Submit the expense and go to expense details page.
6. Click on the Attendees section

Verify that the selected member shouldn't be available to add again in contact list

**Test 3**

https://github.com/Expensify/App/issues/59617

1. Log in with a new Gmail account
2. Create a new workspace
3. Go to workspace chat
4. Click + > Create expense > Manual
5. Enter amount > Next
6. Click Show more
7. Click Attendees
8. Select Manager McTest

Verify that the test manager tooltip will disappear after selecting the manager

**Test 4**

https://github.com/Expensify/App/issues/59621

1. Launch app and Open employee workspace chat
2. Create a scan expense and wait till scanning failed
3. Open the scan expense
4. Tap attendees - select a attendee

Verify that in failed scan expense, selecting an attendee after scanning does not display error.

**Test 5**

https://github.com/Expensify/App/issues/59631

1. Open the app and go to any workspace chat.
2. Click + > Create expense > Distance.
3. Enter waypoints > Next.
4. On confirmation page, click Show more.
5. Note that Attendees field has yourself selected.
6. Create the expense.
7. Go to transaction thread.

Verify that the attendees field in the transaction thread will retain the selection on the confirmation page.

**Test 6**

https://github.com/Expensify/App/issues/59597

1. Open the app and go to workspace chat.
2. Click + > Create expense > Scan.
3. Upload a receipt.
4. On confirmation page, click Attendees.
5. Select another user and click Save.

Verify that Attendees field shows "Attendees" only.

Create the expense.
Go to transaction thread.

Verify that the attendees field will show "Attendees" in the transaction thread while the receipt is scanning. Once scanned successfully, it should show `<currency> <amount> per person`

**Test 7**

https://github.com/Expensify/App/issues/59599

1. Go to self DM.
2. Track a manual expense.
3. Click Categorize it.
4. Select a category.
5. Click Show more.
6. Click Attendees field.

Verify that the Attendees field has a Save button.

**Test 8**

fixes https://github.com/Expensify/App/issues/59600

1. Open App > Go to FAB > Create expense > Manual
2. Enter amount > Next.
3. Select a destination if needed.
4. Click Show more.
5. Click Attendees.
6. Enter any user name.
7. Click on the user.

Verify that the user will not appear twice after the user is selected.

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

Same as above

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Unable to build android

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/0423deeb-194d-425a-9b13-3207cb92adf5

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/7fc12e2a-e224-48fe-87c6-d1abc47576ff

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/e64e174c-0006-4adc-bee3-7ba13ef60b26

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/99d1cabe-88c2-4cb2-ab43-d6d0c1df1938

https://github.com/user-attachments/assets/67e231bf-622c-4954-b1d9-627fe375725c

https://github.com/user-attachments/assets/98aca68f-9b08-4495-b3ae-2aba56e9099f

https://github.com/user-attachments/assets/2468af7c-58e1-4dea-a072-0d5008419ffd

https://github.com/user-attachments/assets/cee24fb3-33c4-4852-94a4-aec5b91a80f7

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/36dabb4a-ea23-4530-8302-f6bfa223dde7

</details>

### CODE REVIEW

**Comment by mananjadhav** [comment]
Started reviewing.

File: src/libs/OptionsListUtils.ts [hunk 1]
```diff
@@ -217,7 +217,7 @@ type GetOptionsConfig = {
     excludeLogins?: Record<string, boolean>;
     includeRecentReports?: boolean;
     includeSelectedOptions?: boolean;
-    recentAttendees?: Attendee[];
+    recentAttendees?: Option[];
```
Comment (mananjadhav) [inline src/libs/OptionsListUtils.ts:220]: question, why do we need to change to `Option`?

File: src/libs/OptionsListUtils.ts [hunk 2]
```diff
@@ -859,7 +871,7 @@ function createOption(
     result.participantsList = personalDetailList;
     result.isOptimisticPersonalDetail = personalDetail?.isOptimisticPersonalDetail;
     if (report) {
-        const reportNameValuePairs = getReportNameValuePairs(report.reportID);
```
Comment (mananjadhav) [inline src/libs/OptionsListUtils.ts:862]: Can we add a comment on why we're using the onyx key instead of the method?

File: src/pages/iou/request/MoneyRequestAttendeeSelector.tsx [hunk 3]
```diff
@@ -63,21 +63,18 @@ function MoneyRequestAttendeeSelector({attendees = [], onFinish, onAttendeesAdde
...
+    const [activePolicyID] = useOnyx(ONYXKEYS.NVP_ACTIVE_POLICY_ID, {canBeMissing: true});
+    const [recentAttendees] = useOnyx(ONYXKEYS.NVP_RECENT_ATTENDEES, {canBeMissing: true});
     const policy = usePolicy(activePolicyID);
-    const [isSearchingForReports] = useOnyx(ONYXKEYS.IS_SEARCHING_FOR_REPORTS, {initWithStoredValues: false});
+    const [isSearchingForReports] = useOnyx(ONYXKEYS.IS_SEARCHING_FOR_REPORTS, {initWithStoredValues: false, canBeMissing: true});
     const {options, areOptionsInitialized} = useOptionsList({
         shouldInitialize: didScreenTransitionEnd,
     });
-    const cleanSearchTerm = useMemo(() => debouncedSearchTerm.trim().toLowerCase(), [debouncedSearchTerm]);
+    const cleanSearchTerm = useMemo(() => searchTerm.trim().toLowerCase(), [searchTerm]);
```
Comment (mananjadhav) [inline src/pages/iou/request/MoneyRequestAttendeeSelector.tsx:74]: Can you help elaborate why we want to replace `debouncedSearchTerm` with `searchTerm`?

**Review by mananjadhav — COMMENTED** [review]
Small comments. Will finish the checklist after QA.

File: src/pages/iou/request/MoneyRequestAttendeeSelector.tsx (hunk 3 above)
Comment (allroundexperts) [reply src/pages/iou/request/MoneyRequestAttendeeSelector.tsx:74]: It solves https://github.com/Expensify/App/issues/59600

In short, it was causing a race condition, where the search term was getting updated later than the attendee selection, thus showing duplicate options.

**Comment by mananjadhav** [comment]
All good with the code changes. Left with the QA.

**Comment by francoisl** [comment]
@mananjadhav any update on the review here?

**Comment by mananjadhav** [comment]
Left with my QA on mobile web and apps. Just working on those.

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/6dfef10c-dbc8-4c0a-a2d0-c4ccddc715b8

https://github.com/user-attachments/assets/b1b15520-a210-4804-982f-505377246439

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/50827b03-30fb-4f2f-9b81-5df6667587cc

https://github.com/user-attachments/assets/cf19e516-c66f-47f9-88ea-fbfd5666fcb7

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/a2cf92cd-30a1-4e19-87ce-009c203901df

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/5d46ff13-2061-4346-9e83-d7f9e95a4583

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/78d770b2-a87f-47a2-a972-7a3988155619

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/991f6309-ea00-4369-b72f-8294cb44c8c6

</details>

**Review by mananjadhav — APPROVED** [review]

**Comment by Julesssss** [comment]
Hey @allroundexperts could you please resolve conflicts

**Comment by allroundexperts** [comment]
@francoisl @Julesssss Before we merge, is it possible to have the whole flow of attendees QA'ed?

**Comment by Julesssss** [comment]
Sure, good idea. I asked QA to test the linked issues [here](https://expensify.slack.com/archives/C9YU7BX5M/p1746040965330209).

**Review by Julesssss — COMMENTED** [review]
Passed to QA for pre-merge AdHoc build testing

**Comment by mvtglobally** [comment]
QA Results 

https://github.com/Expensify/App/issues/59602 - Pass 
https://github.com/Expensify/App/issues/59603 - Pass
https://github.com/Expensify/App/issues/59617 - BLOCKED (Manager McTest is not displayed if we follow the same KI steps.) 
https://github.com/Expensify/App/issues/59631 - Pass
https://github.com/Expensify/App/issues/59621 - Pass
https://github.com/Expensify/App/issues/59597 - Pass
https://github.com/Expensify/App/issues/59599 - Pass
https://github.com/Expensify/App/issues/59600 - Pass

**Comment by Julesssss** [comment]
Hey @allroundexperts, with just the oneissue I think we are good to go here. 

With test 3, I think we can be happy this will be verified.

**Review by Julesssss — DISMISSED** [review]

**Comment by Julesssss** [comment]
@mananjadhav I don't see verification on test 3. Would you mind retesting please, or sharing how you verified? thanks

**Comment by mananjadhav** [comment]
> @mananjadhav I don't see verification on test 3. Would you mind retesting please, or sharing how you verified? thanks

Looks like I missed. I don't see `Manager McTest` at all in the display list.

**Comment by mananjadhav** [comment]
@allroundexperts There's a conflict in the PR. Also can you also verify the test step 3 at youe ned?

**Comment by allroundexperts** [comment]
> Also can you also verify the test step 3 at youe ned?

I am no longer able to reproduce it.

**Comment by Julesssss** [comment]
> I am no longer able to reproduce it.

Cool, I'll regen builds and ask for a retest.

**Comment by Julesssss** [comment]
Actually this is 1/9 issues. Lets get it merged and tested and we can always submit a follow up for the 1 remaining issue which might not even be occuring.

**Review by Julesssss — APPROVED** [review]

File: src/components/MoneyRequestConfirmationListFooter.tsx [hunk 4]
```diff
@@ -618,7 +618,7 @@ function MoneyRequestConfirmationListFooter({
                     shouldShowRightIcon
                     title={iouAttendees?.map((item) => item?.displayName ?? item?.login).join(', ')}
                     description={`${translate('iou.attendees')} ${
-                        iouAttendees?.length && iouAttendees.length > 1 ? `\u00B7 ${formattedAmountPerAttendee} ${translate('common.perPerson')}` : ''
+                        iouAttendees?.length && iouAttendees.length > 1 && formattedAmountPerAttendee ? `\u00B7 ${formattedAmountPerAttendee} ${translate('common.perPerson')}` : ''
```
Comment (MonilBhavsar) [inline src/components/MoneyRequestConfirmationListFooter.tsx:621]: Why we removed `\u00B7`? Was that by purpose? It caused https://github.com/Expensify/App/issues/61429

Comment (Julesssss) [reply src/components/MoneyRequestConfirmationListFooter.tsx:621]: Good question. I don't recall. @allroundexperts do you recall?
