### PR TITLE
Fix that 'pay at hotel trip' report still shows 'Approve' button

### LINKED ISSUE #54570: [HOLD for payment 2025-01-24] [Medium] Expense report - Approved report still shows the button to approve in ND
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.78-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** applausetester+l4@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** macOS Sequoia 15.1.1, Desktop-Web / iPhone SE 3rd generation, iOS 18.2, app-mWeb
**App Component:** Money Requests

## Action Performed:
1. Open the URL: https://staging.expensify.com
2. Log in with a expensifail account
2. Click on Travel > Book or manage travel
3. Book a hotel can be any (On payment filter select: 'Pay at property')
4. After your booking is successful, go to https://staging.expensify.com
5. Click on 'Reports'
6. Click the booked hotel report > Click on 'Submit' > Click on 'Send'
7. Go to https://staging.new.expensify.com (Log in with the same expensifail account)
8. Open the chat of the booked hotel
9. Click on the expense report of the booked hotel (In the preview of the expense it says 'This booking is pending')
10. Click on 'Approve' button at top right corner

## Expected Result:
The approve button should not appear, as it has been previously approved.

## Actual Result:
The approve button is shown.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1b97d8b4-49db-45a1-9fbf-be9fb1337187

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

### PR DESCRIPTION
**Pull request by blazejkustra**
### Explanation of Change

This PR fixes #54570 and adjusts the logic so Trip summary is displayed no matter if it has a parent report or not. [**Here is context**](https://swmansion.slack.com/archives/C05S5EV2JTX/p1736332982688129)

### Fixed Issues
$ https://github.com/Expensify/App/issues/54570
PROPOSAL: N/A

### Tests

Precondition - book a travel from olddot within a workspace that doesn't support chats (you can check it in the console)
```
Policy.getCurrent().policy.isPolicyExpenseChatEnabled
```

- Open the URL: https://staging.expensify.com/
- Log in with an account
- Click on Travel > Book or manage travel
- Book a hotel can be any **(On payment filter select: 'Pay at property')**
- After your booking is successful, go to https://staging.expensify.com/
- Click on 'Reports'
- Click the booked hotel report > Click on 'Submit' > Click on 'Send'
- Go to https://staging.new.expensify.com/ (Log in with the same account)
- Open the chat of the booked hotel
- Click on the expense report of the booked hotel (In the preview of the expense it says 'This booking is pending')
- Verify that there is no 'Approve' button
- Verify that there is a 'summary trip' displayed in the trip room

### Offline tests

N/A

### QA Steps

Same as tests

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

[android.webm](https://github.com/user-attachments/assets/7489dfd8-e9d6-416c-8c2b-c28b0628b6b5)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

[android-web.webm](https://github.com/user-attachments/assets/c33ba12b-168e-4ab9-9404-4ed4262838f0)

</details>

<details>

<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/6c4054fc-e811-4d18-a931-3963e9843e0e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/6c4054fc-e811-4d18-a931-3963e9843e0e

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/dc8cfd1f-149f-46d7-af94-d6db02c2b1c1

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/e1427afc-2a5d-4935-af3f-afe815d892ab

</details>

### CODE REVIEW

**Comment by blazejkustra** [comment]
Similar to [this one](https://github.com/Expensify/App/issues/54537#issuecomment-2575518135), I think @shubham1206agra will review this PR.

**Comment by blazejkustra** [comment]
@shubham1206agra I added you to my new workspace:
image

**Comment by blazejkustra** [comment]
Merged the newest main for you @shubham1206agra

**Review by shubham1206agra — APPROVED** [review]

**Review by shubham1206agra — APPROVED** [review]

File: src/components/ReportActionItem/TripDetailsView.tsx [hunk 1]
```diff
@@ -142,10 +134,22 @@ function ReservationView({reservation, transactionID, tripRoomReportID, reservat
...
+
 function TripDetailsView({tripRoomReportID, shouldShowHorizontalRule}: TripDetailsViewProps) {
     const styles = useThemeStyles();
     const {translate} = useLocalize();
 
+    if (!tripRoomReportID) {
+        return null;
+    }
+
     const tripTransactions = ReportUtils.getTripTransactions(tripRoomReportID);
```
Comment (tgolen) [inline src/components/ReportActionItem/TripDetailsView.tsx:153]: I think this is a bad function because it breaks the reactivity of this component. It should get the transactions with `useOnyx()`. I'm going to open a GH to remove it.

**Review by tgolen — CHANGES_REQUESTED** [review]

**Review by tgolen — CHANGES_REQUESTED** [review]

File: src/components/ReportActionItem/TripDetailsView.tsx (hunk 1 above)
Comment (tgolen) [reply src/components/ReportActionItem/TripDetailsView.tsx:153]: GH is here: https://github.com/Expensify/App/issues/55077

**Review by tgolen — DISMISSED** [review]
Thanks! That looks nicer. Just gotta clear up those eslint errors

**Comment by blazejkustra** [comment]
I agree, thanks for reviewing! 🙇

**Comment by blazejkustra** [comment]
I also fixed lint errors in the latest commit, should be good now 😄

**Review by tgolen — APPROVED** [review]

**Comment by kavimuru** [comment]
@tgolen @blazejkustra @shubham1206agra 
we are blocked with this known bug https://github.com/Expensify/Expensify/issues/459996. Tester tried with 3 different accounts and same result. Could you help us?

**Comment by tgolen** [comment]
It looks like that's being looked into by @rlinoz and is an issue with the Spotnana sandbox API
