### PR TITLE
fixed messages are repeated on page refresh & process queue only when client is leader

### LINKED ISSUE #2451: After sending a message in offline mode and going back to online, messages are repeated when refreshing the page
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Only 1 message should be displayed. 

## Actual Result:
Message is sent twice when refreshing the page after coming back online. 

## Action Performed:
1. Log in to staging.expensify.cash
2. Navigate to a conversation
3. Disable the internet connection
4. Send a message while offline
5. Enable the internet connection and immediately refresh the page

## Workaround:
If the user does not refresh the page only 1 message is displayed. 

## Platform:
Where is this issue occurring?

 Web ✔️ 
 iOS
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.24-1

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/44479856/115265297-18540500-a105-11eb-8019-d284211a6b0b.mp4

**Expensify/Expensify Issue URL:**

___

From @parasharrajat https://expensify.slack.com/archives/C01GTK53T8Q/p1618602399353800

>ISSUE: After sending a message in offline mode and going back to online, messages is repeated(sent twice).

Upwork job: https://www.upwork.com/jobs/~0151bfc06bb91fc01c

### LINKED ISSUE #4214: [Network] Messages are sent twice
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to New Expensify with an unstable internet connection
2. Send some messages to an account you have access too. (Preferably you're logged in on another device with) 

## Expected Result:
Messages sent with an unstable internet connection should be sent without any issues. 

## Actual Result:
Messages are sent twice when there's unstable internet connection

## Workaround:
Unknown. 

## Platform:
Where is this issue occurring?

- [x] Web
- [ ] iOS
- [ ] Android
- [x] Desktop App
- [ ] Mobile Web

**Version Number:** 1.0.80-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

image

image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
From @JmillsExpensify https://expensify.slack.com/archives/C01GTK53T8Q/p1626890348078000
> When chatting with someone on a slow wifi connection, you get two of every message they send.

### PR DESCRIPTION
**Pull request by parasharrajat**
Please review @marcaaron.

### Details

1. This PR tries to fix the duplicate request issue from the Web platform. 
2. On the web, a user can open multiple tabs for E.cash. And all of these clients are able to send requests. 
3. But the User can go offline any time. we have a mechanism to handle requests when the user is offline.
4. Currently there is an issue that these persisted requests are duplicated when the user comes back online. 
5. Each client(tab) has an in-memory network queue. and We have global NETWORK_REQUEST_QUEUE for persisted requests.
6. When a user is offline all the clients will push their requests to an in-memory network queue, from which we filter all the retriable requests and push those to our persisted queue. We filter the in-memory queue and remove these persisted requests that are stored in the persisted queue.
7. Due to Onyx, this persisted queue is synced across the clients.
8. When the user comes back online, we ask the leader client to process all the persisted requests from each client. Thus no request will be duplicated. After all the requests are sent to the server, messages will be sync across tabs via Onyx, keeping the same report actions for all clients.

### Fixed Issues

Fixes #2451
Fixes #4214

### Tests / QA Steps
1. Log in to staging.expensify.cash
2. Navigate to a conversation
3. Disable the internet connection
4. Send a message while offline
5. Enable the internet connection and immediately refresh the page.
6. Messages should not be repeated.

### Tested On

- [x] Web (Affected Platfrom)
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web
 

<details>
<summary><h5 style="display:inline">Before</h5></summary>

https://user-images.githubusercontent.com/44479856/115265297-18540500-a105-11eb-8019-d284211a6b0b.mp4

</details>
<details open>
<summary><h3 style="display:inline">After</h3></summary>

https://user-images.githubusercontent.com/24370807/117200247-e7fcae00-ae08-11eb-8284-6ef0404129d6.mp4

</details>

### CODE REVIEW

File: src/libs/ActiveClientManager/index.js [hunk 1]
```diff
@@ -7,6 +7,16 @@ const clientID = Str.guid();
 const maxClients = 20;
 
 let activeClients;
+let setReady = null;
+
+// Whether the client Manager has started
+let isInit = false;
+
+// Are we ready to determine active Client?
+const isReady = new Promise((res) => {
```
Comment (parasharrajat) [inline src/libs/ActiveClientManager/index.js:16]: These changes are needed as the Client manager incorrectly reports the leadership of the client

Comment (marcaaron) [reply src/libs/ActiveClientManager/index.js:16]: Can you maybe elaborate on this?

File: src/libs/ActiveClientManager/index.js [hunk 2]
```diff
@@ -15,6 +25,9 @@ Onyx.connect({
             activeClients.shift();
             Onyx.set(ONYXKEYS.ACTIVE_CLIENTS, activeClients);
         }
+        if (isInit) {
+            setReady();
+        }
```
Comment (marcaaron) [inline src/libs/ActiveClientManager/index.js:30]: What is this doing...?

File: src/libs/Network.js [hunk 3]
```diff
@@ -3,9 +3,13 @@ import lodashGet from 'lodash/get';
 import Onyx from 'react-native-onyx';
 import HttpUtils from './HttpUtils';
 import ONYXKEYS from '../ONYXKEYS';
+import * as ActiveClientManager from './ActiveClientManager';
 
 let isQueuePaused = false;
 
+// Are we retrying requests when user comes back online?
+let retryRequestsAdded = false;
```
Comment (marcaaron) [inline src/libs/Network.js:11]: The comment above doesn't really help explain what the code is doing or how it works.

File: src/libs/Network.js [hunk 4]
```diff
@@ -31,15 +35,21 @@ let didLoadPersistedRequests;
 Onyx.connect({
     key: ONYXKEYS.NETWORK_REQUEST_QUEUE,
     callback: (persistedRequests) => {
-        if (didLoadPersistedRequests || !persistedRequests) {
-            return;
-        }
+        ActiveClientManager.isReady.then(() => {
```
Comment (marcaaron) [inline src/libs/Network.js:38]: Why are we using a promise to tell that the active client is ready? If there is a requirement for it to have such a state could we just set a boolean flag?

File: src/libs/Network.js [hunk 5]
```diff
@@ -31,15 +35,21 @@ let didLoadPersistedRequests;
...
+            // Only process queue when client is Leader and we have not retried the requests already
```
Comment (marcaaron) [inline src/libs/Network.js:39]: Why should we only process the queue when the client is the leader? (Put it in the comment)

File: src/libs/Network.js [hunk 6]
```diff
@@ -112,6 +122,7 @@ function processNetworkRequestQueue() {
             !request.data.doNotRetry && request.data.persist
         ));
         Onyx.set(ONYXKEYS.NETWORK_REQUEST_QUEUE, retryableRequests);
+        retryRequestsAdded = true;
```
Comment (marcaaron) [inline src/libs/Network.js:125]: Why do we need to set this flag?

File: src/libs/Network.js [hunk 7]
```diff
@@ -160,6 +171,11 @@ function processNetworkRequestQueue() {
             .catch(error => onError(queuedRequest, error));
     });
 
+    // User came back online and the request queue will resume, thus we should clear the NETWORK_REQUEST_QUEUE
+    if (ActiveClientManager.isClientTheLeader() && retryRequestsAdded) {
```
Comment (marcaaron) [inline src/libs/Network.js:175]: I'm still a little lost on why we only want to clear the queue when the client is the leader and there is also no explanation about the significance of `retryRequestsAdded`. Can you try explaining this better in the comments?

>// User came back online

How exactly does this tell us the user came back online?

**Review by marcaaron — CHANGES_REQUESTED** [review]
Hey @parasharrajat, Can we try to document this code better and add some comments? Overall, I'm confused by the implementation and unsure why we're doing most of what we're doing.

File: src/libs/Network.js (hunk 4 above)
Comment (parasharrajat) [reply src/libs/Network.js:38]: I used to promise to overcome the race conditions. So when the user just landed on the page, this callback is fired before the client is set. And this won't repeat this to make sure that our queue is processed, I rely on promise.

File: src/libs/Network.js (hunk 7 above)
Comment (parasharrajat) [reply src/libs/Network.js:175]: So When a user goes offline we filter the network request queue and put the retrievable requests on persisted Queue. But it is possible that a user can come back online without refreshing the page. Now those retriable requests will process as a part of `networkRequestQueue`. Thus we don't want to process the persisted queue `ONYXKEYS.NETWORK_REQUEST_QUEUE`. It should only run when the user refresh the page.

Comment (parasharrajat) [reply src/libs/Network.js:175]: We only allow the leader to handle the `ONYXKEYS.NETWORK_REQUEST_QUEUE` and make sure that we are only clear the queue when are processing those requests via normal `networkRequestQueue`. As we processed the normal queue, we will not need them to be persisted.

File: src/libs/ActiveClientManager/index.js (hunk 1 above)
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:16]: Yeah sure. There are cases where we run important callbacks once but It is possible that the client is not set before that callback call. Thus a promise to make sure that we run the callback. We have to use a flag and combination of Promises to achieve this.
as 
```
function init() {
    Onyx.merge(ONYXKEYS.ACTIVE_CLIENTS, [clientID]);
    isInit = true;
}
```
The above method does not really initialize the client it just request Onyx to set the client id. `merge` Ops is async and I think it does not return thenable callback thus we have to go to `connect` call.

```
 if (isInit) {
            setReady();
        }
```
Now we mark is ready by resolving the promise as we have set the clientId on the client stack.        This connect could fire multiple times, we only resolve the promise when `isInit` is set.

Comment (marcaaron) [reply src/libs/ActiveClientManager/index.js:16]: Would it be possible to wait until the client _is_ set to do the rest of the logic here?

One idea would be to add an `onReady` function to `ActiveClientsManager` so that we can register a callback then wait to do the `Onyx.connect()` below?

I think it might make it more obvious that we are waiting for the active client to be set

```js
ActiveClientsManager.onReady(() => {
    Onyx.connect({
        key: ONYXKEYS.NETWORK_REQUEST_QUEUE,
        callback: ...
    })
});
```

File: src/libs/ActiveClientManager/index.js [hunk 8]
```diff
@@ -7,6 +7,16 @@ const clientID = Str.guid();
 const maxClients = 20;
 
 let activeClients;
+let setReady = null;
+
+// Whether the client Manager has started
+let isInit = false;
```
Comment (marcaaron) [inline src/libs/ActiveClientManager/index.js:13]: Instead could we have something like:

`shouldFireOnReadyCallback` and `didInitialize` and then do

```js
if (shouldFireOnReadyCallback) {
    onReadyCallback();
    didInitialize = true;
}
```

File: src/libs/ActiveClientManager/index.js (hunk 1 above)
Comment (marcaaron) [reply src/libs/ActiveClientManager/index.js:16]: Ok Thanks I am seeing the problem now. And yeah, Onyx being asynchronous is making this difficult once again 😓

File: src/libs/Network.js (hunk 4 above)
Comment (marcaaron) [reply src/libs/Network.js:38]: Ok thanks worries I have a different idea that I think will be more typical way to handle this like we do elsewhere.

File: src/libs/Network.js (hunk 7 above)
Comment (marcaaron) [reply src/libs/Network.js:175]: Ok, it's still a little unclear to me, but I might have to just look harder at this and try to offer some better suggestions.

File: src/libs/Network.js (hunk 6 above)
Comment (parasharrajat) [reply src/libs/Network.js:125]: @marcaaron. We have a queue of requests as `networkRequestQueue`. we take retry requests and save them in `ONYXKEYS.NETWORK_REQUEST_QUEUE` in case the user closes the tab or refreshes it. Now let's say the user's internet is back but he didn't refresh the tab so `networkRequestQueue` will continue processing all those requests. This flag records this behavior. so when this is `true` we know we have processed the requests and clear the requests.
```
 // User came back online and the request queue will resume, thus we should clear the NETWORK_REQUEST_QUEUE
    if (ActiveClientManager.isClientTheLeader() && retryRequestsAdded) {
        Onyx.set(ONYXKEYS.NETWORK_REQUEST_QUEUE, []);
    }
```    

Also `Onyx.set(ONYXKEYS.NETWORK_REQUEST_QUEUE, retryableRequests);`. We reset the queue here but what will happen if the user is sending requests from multiple tabs. We will overwrite the old requests. Do we want this to behave like this or we should merge those requests `Onyx.merge`?

**Comment by parasharrajat** [comment]
@marcaaron So I found one more side effect so I changed the logic completely.

Now the code completely rely on persisted queue. let me know what do you think of it. I would be happy to explain everything. 

Due to Onyx.connect is called when user comes back online, we can just use the persisted queue and new logic is build up on that.

File: src/libs/ActiveClientManager/index.js [hunk 9]
```diff
@@ -23,6 +34,21 @@ Onyx.connect({
...
     Onyx.merge(ONYXKEYS.ACTIVE_CLIENTS, [clientID]);
+    didInitialize = true;
+}
+
+/**
+ * Allow to run any task after ActiveClientManager has successfully initialized
+ *
+ * @returns {Promise<void>}
+ */
+function isReady() {
```
[the remark this answers is not in the document]
Comment (marcaaron) [reply src/libs/ActiveClientManager/index.js:45]: Ok, I want to do it the way I've suggested for consistency reasons. It's not that your idea won't work, it's that we don't have many patterns like this and it's pretty unusual to see.

>We can just use promise in multiple places for multiple tasks. The callback would require an array to be implemented for that purpose.

There is no need to do this as only one thing needs to know whether we have "initialized".

File: src/libs/Network.js [hunk 10]
```diff
@@ -32,15 +33,34 @@ let didLoadPersistedRequests;
 Onyx.connect({
     key: ONYXKEYS.NETWORK_REQUEST_QUEUE,
     callback: (persistedRequests) => {
-        if (didLoadPersistedRequests || !persistedRequests) {
-            return;
-        }
+        ActiveClientManager.isReady().then(() => {
```
Comment (marcaaron) [inline src/libs/Network.js:36]: Sorry, I will repeat that I would prefer that we **not** do the check this way.

File: src/libs/Network.js [hunk 11]
```diff
@@ -107,12 +127,17 @@ function processNetworkRequestQueue() {
...
-        // If we have a request then we need to check if it can be persisted in case we close the tab while offline
-        const retryableRequests = _.filter(networkRequestQueue, request => (
-            !request.data.doNotRetry && request.data.persist
-        ));
-        Onyx.set(ONYXKEYS.NETWORK_REQUEST_QUEUE, retryableRequests);
+        const retryableRequests = [];
+
+        // If we have a request then we need to check if it can be persisted in case we close the tab while offline.
+        // We filter persisted requests from the normal Queue to remove duplicates
+        networkRequestQueue = _.reject(networkRequestQueue, (request) => {
```
Comment (marcaaron) [inline src/libs/Network.js:134]: >We filter persisted requests from the normal Queue to remove duplicates

Which duplicates are we talking about here? Can you provide an example? It's hard to visualize what you mean or why we are removing these from the normal request queue in memory.

Wouldn't this mean that if I add a comment while offline that it will be "removed" from the queue and not sent again when I come back online?

File: src/libs/Network.js [hunk 12]
```diff
@@ -161,6 +186,16 @@ function processNetworkRequestQueue() {
             .catch(error => onError(queuedRequest, error));
     });
 
+    // We should clear the NETWORK_REQUEST_QUEUE when we have loaded the perssited requests & Client is leader
```
Comment (marcaaron) [inline src/libs/Network.js:189]: Sorry, I still don't get why we are doing this or **_why_** we care that the "client is the leader" from reading this comment

**Review by marcaaron — DISMISSED** [review]

File: src/libs/Network.js (hunk 11 above)
Comment (marcaaron) [reply src/libs/Network.js:134]: Can you link me to where this happens?

**Comment by marcaaron** [comment]
Hey @parasharrajat can you please summarize the status of this PR and linked issue? Thanks.

**Comment by parasharrajat** [comment]
I will look into again and try to cross check everything. Also I will update the Promise to what you have suggested.

Overall, my solution would be based on the explanation above.

**Comment by joelbettner** [comment]
gentle bump

**Comment by parasharrajat** [comment]
Thanks for the Bump. I will try to check it off from my list this weekend. I need to rework here as there have been numerous changes since the PR was created.

**Comment by parasharrajat** [comment]
@joelbettner I have updated the PR and tested it.
@marcaaron I have a concern about your request of using callback instead of Promise to check ActiveClientManager readiness.
There are two scenes. 
It is not deterministic when the client will become active. It is possible that the client could be ready already when we register a callback. or another case would be, that client is not yet ready when we register the callback.

For the first case, we need to fire the callback as soon as we register. thus it will require another flag. I believe that the promise-based approach is neater and it allows multiple handlers. Let me know if you want me to do it in a callback way. Thanks.

Also I commented the code. Let me know if some thing is not clear. There is small explanation in the issue description as well.

**Comment by marcaaron** [comment]
Just leaving a comment that I won't be able to help out with this review since there are higher priority items for me to get to at the moment. If you need help please ask in the Slack channel. Also curious if @TomatoToaster wants to check this PR out since he recently edited these files and might understand how this stuff works.

File: src/libs/Network.js [hunk 13]
```diff
@@ -161,6 +201,18 @@ function processNetworkRequestQueue() {
             .catch(error => onError(queuedRequest, error));
     });
 
+    // We should clear the NETWORK_REQUEST_QUEUE when we have loaded the persisted requests & they are processed.
+    // As multiple client will be sharing the same Queue and NETWORK_REQUEST_QUEUE is synchronized among clients,
+    // we only ask Leader client to clear the queue
+    if (ActiveClientManager.isClientTheLeader() && didLoadPersistedRequests) {
```
Comment (TomatoToaster) [inline src/libs/Network.js:207]: NAB:  Do we just need `didLoadPersistedRequests` just for this line?

**Review by TomatoToaster — COMMENTED** [review]
Hi I just had some questions for clarifying. Just making sure I understand how this works correctly.

**Comment by parasharrajat** [comment]
Hi @TomatoToaster, I will get back to you with answers on these But I am sure about that flag that it is needed.

File: src/libs/ActiveClientManager/index.js [hunk 14]
```diff
@@ -7,13 +7,28 @@ const clientID = Str.guid();
...
+
+// Whether the current clientID is set
+let didInitialize = false;
+
+let resolveReadyPromise = null;
+
+// Keeps track of the ActiveClientManager's readiness.
+const readyPromise = new Promise((res) => {
+    resolveReadyPromise = res;
+});
```
[the remark this answers is not in the document]
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:19]: This is a technique to resolve a promise from outside the scope of the Promise. We expose resolve callback outside and then we call that resolve callback, it resolves the promise. In `isReady` we are using the same promise but that would be only resolved when `resolveReadyPromise` is called.

File: src/libs/Network.js (hunk 13 above)
Comment (parasharrajat) [reply src/libs/Network.js:207]: So If you try to think the bigger scope about all the tabs that are open in the browser with E.cash then the `ActiveClientManager.isClientTheLeader()` check makes sense. Without it, every tab would be handling the Offline queue.

Imagine, you send a message `Hey` form One of the browser tab while you are offline.
You have 5 tabs opened on your browser with E.cash.
If you check all 5 you will see that your `hey ` message is visible but grayed out.
Now you come back online, What do you expect that all tab should send `Hey` to server. or it should be sent once.
If server receives 5 requests, you will see 5 `hey` messages on your chat thus we only ask Leader to send that message and other client will automatically be synced.

Hope it clears the doubt.

File: src/libs/Network.js [hunk 15]
```diff
@@ -25,25 +26,57 @@ let onError = () => {};
...
+            _.each(persistedRequests, (request) => {
+                request.resolve = () => {};
+                request.reject = () => {};
+            });
+
+            // Merge the persisted requests with the requests in memory then clear out the queue as we only need to load
+            // this once when the app initializes
+            networkRequestQueue = [...networkRequestQueue, ...persistedRequests];
+            Onyx.set(ONYXKEYS.NETWORK_REQUEST_QUEUE, []);
+            didLoadPersistedRequests = true;
```
[the remark this answers is not in the document]
Comment (parasharrajat) [reply src/libs/Network.js:75]: my original PR had this change before your PR got merged. we can't be too sure if all the requests have loaded until reset the queue. so it is fine but in real, it does not make a change.
```
            Onyx.set(ONYXKEYS.NETWORK_REQUEST_QUEUE, []);
            didLoadPersistedRequests = true;
 ````
 &
 ```
           didLoadPersistedRequests = true;
           Onyx.set(ONYXKEYS.NETWORK_REQUEST_QUEUE, []);
 ```                     
Both behave the same as Onyx.set is async.

File: src/libs/ActiveClientManager/index.js (hunk 14 above)
[the remark this answers is not in the document]
Comment (joelbettner) [reply src/libs/ActiveClientManager/index.js:19]: Correct me if I'm wrong, but `res` is just an empty function, correct?

[the remark this answers is not in the document]
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:19]: yes.

File: src/libs/Network.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (TomatoToaster) [reply src/libs/Network.js:75]: Yep that makes sense to me.

File: src/libs/ActiveClientManager/index.js [hunk 16]
```diff
@@ -7,13 +7,28 @@ const clientID = Str.guid();
...
 Onyx.connect({
     key: ONYXKEYS.ACTIVE_CLIENTS,
     callback: (val) => {
         activeClients = !val ? [] : val;
         if (activeClients.length >= maxClients) {
             activeClients.shift();
-            Onyx.set(ONYXKEYS.ACTIVE_CLIENTS, activeClients);
+            Onyx.set(ONYXKEYS.ACTIVE_CLIENTS, activeClients).then(() => {
+                if (didInitialize) {
+                    resolveReadyPromise();
```
Comment (joelbettner) [inline src/libs/ActiveClientManager/index.js:29]: This is just an empty function, correct?

I'm struggling to determine the order of things...

Will it be:
 - the browser loads `index.js` which sets `resolveReadyPromise` to `NULL` and `didInitialize` to `false`
 - `Onyx.connect` gets called
   - on successful completion `Onyx.set` gets called
   - after `Onyx.set` is called, since `didInitialize` is `false` then we do not call `resolveReadyPromise`, so `isReady` is a non-resolved promise whenever it is called.
 - `init` gets called
   - `didInitialize` gets set to `true`
 - `isReady` gets called (from `Network.js`)
   - `readyPromise` is returned as an un-resolved promise
 - Client gets disconnected, and then re-connected
 - `Onyx.connect` gets called again
   - on successful completion `Onyx.set` gets called
   - after `Onyx.set` is called, since `didInitialize` is now set to `true` then we call `resolveReadyPromise` (which is an empty function) that resolves `readyPromise`
 - In `Network.js`, the `ActiveClientManager.isReady().then` can run because the `readyPromise` was resolved in `index.js`

Please correct me if any of that^ is wrong.

File: src/libs/ActiveClientManager/index.js [hunk 17]
```diff
@@ -23,6 +38,16 @@ Onyx.connect({
...
+    didInitialize = true;
+}
+
+/**
+ * Allow to run any task after ActiveClientManager has successfully initialized
+ *
+ * @returns {Promise<void>}
+ */
+function isReady() {
+    return readyPromise;
```
Comment (joelbettner) [inline src/libs/ActiveClientManager/index.js:50]: Instead of defining a variable called `readyPromise`, could we just do:

```js
function isReady() {
    return new Promise((res) => {resolveReadyPromise = res;}
}
```

File: src/libs/Network.js (hunk 13 above)
Comment (TomatoToaster) [reply src/libs/Network.js:207]: Gotcha, but since that check happens in line 57 of `Network.js` isn't it redundant here?

File: src/libs/ActiveClientManager/index.js (hunk 17 above)
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:50]: Does not serve its original purpose. In case isReady is used at multiple places then all of those promises will not be resolved instead only one would be resolved.

File: src/libs/ActiveClientManager/index.js (hunk 16 above)
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:29]: > Client gets disconnected, and then re-connected. 
Apart from it, you are correct. It does not happen in the flow.

**Comment by parasharrajat** [comment]
Any changes which you guys recommend here. I am looking to finish this one as I believe there is nothing left from my side. Thanks.

File: src/libs/ActiveClientManager/index.js [hunk 18]
```diff
@@ -7,13 +7,28 @@ const clientID = Str.guid();
...
 
 let activeClients;
+
+// Whether the current clientID is set
+let didInitialize = false;
+
+let resolveReadyPromise = null;
+
+// Keeps track of the ActiveClientManager's readiness.
+const readyPromise = new Promise((res) => {
```
Comment (TomatoToaster) [inline src/libs/ActiveClientManager/index.js:17]: NAB: Could we call `res` `resolve` here? Maybe it's obvious to most and this isn't necessary, but I think it might help newcomers (me 😅 ) follow this logic a bit better.

**Review by TomatoToaster — CHANGES_REQUESTED** [review]
Hi! Sorry this took a bit, I've been trying to wrap my head around it and I'm a little unfamiliar with the logic. I think it's starting to make sense to me.

I think overall the implementation here is correct, but I had some suggestions about comments and variable names that might make this clearer to someone reading this completely fresh. If any of the suggestions don't make sense, let me know. @joelbettner, I'm curious if you think these changes would've helped you understand it better too and if you had similar suggestions.

File: src/libs/ActiveClientManager/index.js [hunk 19]
```diff
@@ -7,13 +7,28 @@ const clientID = Str.guid();
 const maxClients = 20;
 
 let activeClients;
+
+// Whether the current clientID is set
+let didInitialize = false;
```
[the remark this answers is not in the document]
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:12]: This name was taken from the Init function. I believe it makes more sense.

[the remark this answers is not in the document]
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:12]: Moreover, this was suggested by Marc.

File: src/libs/ActiveClientManager/index.js [hunk 20]
```diff
@@ -7,13 +7,28 @@ const clientID = Str.guid();
...
+
+let resolveReadyPromise = null;
+
+// Keeps track of the ActiveClientManager's readiness.
```
[the remark this answers is not in the document]
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:16]: But moving function definition around is not useful here as the Existing pattern is to keep `Onyx.connect` calls at the top.

File: src/libs/Network.js (hunk 13 above)
Comment (parasharrajat) [reply src/libs/Network.js:207]: We only want one tab to clear the queue, there could be other clients there and if they all clear the queue the it makes prone to errors. And yes Onyx calls will be multiplied by a number of tabs.

**Comment by parasharrajat** [comment]
Updated

File: src/libs/ActiveClientManager/index.js (hunk 16 above)
Comment (joelbettner) [reply src/libs/ActiveClientManager/index.js:30]: If it does not happen when the client reconnects, when does `Onyx.connect` get called again?

Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:30]: Don't bother by those they were related to old implementation. And things have changed since then. Now If you look at the top of the file, we have a subscription for NETWORK key which triggers Onyx.connect for NETWORK_REQUEST_QUEUE.

File: src/libs/Network.js (hunk 13 above)
Comment (joelbettner) [reply src/libs/Network.js:207]: But even step #8 in the PR description say "When the user comes back online"

I'm just wondering how/when `Onyx.connect` gets called again.

File: src/libs/ActiveClientManager/index.js (hunk 16 above)
Comment (joelbettner) [reply src/libs/ActiveClientManager/index.js:30]: But even step #8 in the PR description say "When the user comes back online"

I'm just wondering how/when `Onyx.connect` gets called again.

Comment (joelbettner) [reply src/libs/ActiveClientManager/index.js:30]: > Now If you look at the top of the file, we have a subscription for NETWORK key which triggers Onyx.connect for NETWORK_REQUEST_QUEUE.

I have no idea what you're referring to...

File: src/libs/Network.js [hunk 21]
```diff
@@ -25,25 +26,57 @@ let onError = () => {};
...
 
-        // Merge the persisted requests with the requests in memory then clear out the queue as we only need to load
-        // this once when the app initializes
-        networkRequestQueue = [...networkRequestQueue, ...persistedRequests];
-        didLoadPersistedRequests = true;
-        Onyx.set(ONYXKEYS.NETWORK_REQUEST_QUEUE, []);
+        // Client becomes online, process the queue.
+        if (isOffline && !val.isOffline) {
+            // Fake merge which trigger the NETWORK_REQUEST_QUEUE Onyx's subscription callback
+            Onyx.merge(ONYXKEYS.NETWORK_REQUEST_QUEUE, []);
```
Comment (parasharrajat) [inline src/libs/Network.js:37]: @joelbettner This part triggers the Onyx.connect.

Comment (joelbettner) [reply src/libs/Network.js:37]: So...somehow (I'm not clear on how) this triggers the `Onyx.connect` in `ActiveClientManager/index.js`?

Are you sure this isn't triggering the `Onyx.connect` that is within `ActiveClientManager.isReady().then` in `Network.js`?

Comment (parasharrajat) [reply src/libs/Network.js:37]: No. Onyx.connect in ActiveClientManager/index.js does not have any linking with being online. That tiggers Onyx.connect for NETWORK_REQUEST_QUEUE.

Comment (parasharrajat) [reply src/libs/Network.js:37]: Onyx.connect that is within ActiveClientManager.isReady(), will resolve when we add a new client id on the Active_clients key.

File: src/libs/ActiveClientManager/index.js (hunk 20 above)
[the remark this answers is not in the document]
Comment (TomatoToaster) [reply src/libs/ActiveClientManager/index.js]: That's a good point. Hmm I think we can keep the functino where it is then, the comment clarifies enough.

File: src/libs/Network.js (hunk 13 above)
Comment (TomatoToaster) [reply src/libs/Network.js:207]: Cool this makes sense to me now, thanks!

File: src/libs/ActiveClientManager/index.js [hunk 22]
```diff
@@ -23,6 +39,16 @@ Onyx.connect({
  */
 function init() {
     Onyx.merge(ONYXKEYS.ACTIVE_CLIENTS, [clientID]);
+    didInitialize = true;
```
Comment (joelbettner) [inline src/libs/ActiveClientManager/index.js:42]: Just to ensure there is no race condition between when `Onyx.connect` gets called and when `didInitialize` gets set to `true`, can you put this line above the `Onyx.merge`?

**Review by joelbettner — CHANGES_REQUESTED** [review]

File: src/libs/ActiveClientManager/index.js (hunk 16 above)
Comment (joelbettner) [reply src/libs/ActiveClientManager/index.js:30]: Ok...I believe the answer is that `Onyx.connect` gets called when `Onyx.merge` is called within the `init` function.

Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:30]: Yes for activeCLientManager.

**Comment by parasharrajat** [comment]
@TomatoToaster @joelbettner Updated.

File: src/libs/ActiveClientManager/index.js [hunk 23]
```diff
@@ -7,13 +7,29 @@ const clientID = Str.guid();
...
+
 Onyx.connect({
     key: ONYXKEYS.ACTIVE_CLIENTS,
     callback: (val) => {
         activeClients = !val ? [] : val;
         if (activeClients.length >= maxClients) {
             activeClients.shift();
-            Onyx.set(ONYXKEYS.ACTIVE_CLIENTS, activeClients);
+            Onyx.set(ONYXKEYS.ACTIVE_CLIENTS, activeClients).then(() => {
+                if (didInitialize) {
```
Comment (tgolen) [inline src/libs/ActiveClientManager/index.js:29]: I tried testing something out, and if I add `console.log(didInitialize)` right before this, it is never called with anything other than `true`. It feels to me like this variable isn't necessary. Is there some case where this is called and `didInitialize` would not be `true`?

File: src/libs/Network.js [hunk 24]
```diff
@@ -25,25 +26,57 @@ let onError = () => {};
...
+            // otherwise requests will be duplicated.
+            // We only process the persisted requests when
+            // a) Client is leader.
+            // b) User is online.
+            // c) requests are not already loaded,
+            // d) When there is at least one request
+            if (!ActiveClientManager.isClientTheLeader()
+                || isOffline
+                || didLoadPersistedRequests
+                || !persistedRequests.length) {
```
Comment (tgolen) [inline src/libs/Network.js:60]: This line is causing an error for me:

image

File: src/libs/ActiveClientManager/index.js (hunk 23 above)
Comment (tgolen) [reply src/libs/ActiveClientManager/index.js:29]: I also think this logic is in the wrong spot. Currently, this logic only runs once there are more than 20 clients. If you clear local storage, then you either have to refresh the page 20 times, or open 20 tabs, in order for this logic to be triggered.

File: src/libs/Network.js [hunk 25]
```diff
@@ -25,25 +26,57 @@ let onError = () => {};
...
+        callback: (persistedRequests) => {
+            // NETWORK_REQUEST_QUEUE is shared across clients, thus every client will have similiar copy of
+            // NETWORK_REQUEST_QUEUE. It is very important to only process the queue from leader client
+            // otherwise requests will be duplicated.
+            // We only process the persisted requests when
+            // a) Client is leader.
+            // b) User is online.
+            // c) requests are not already loaded,
+            // d) When there is at least one request
+            if (!ActiveClientManager.isClientTheLeader()
```
Comment (tgolen) [inline src/libs/Network.js:57]: It kind of feels like to me that `isClientTheLeader()` should be the method that has a promise. It would only resolve once the Active Client Manager has been initialized and is able to make the determination.

**Review by tgolen — CHANGES_REQUESTED** [review]
I wanted to add a couple of comments here because I don't think the patterns in this code are intuitive to follow. I went through a screen share with Joel where I tried re-coding it in a way that made more sense to us, and I'd like to share a diff of those changes with you: https://github.com/Expensify/Expensify.cash/pull/3747

These are **incomplete** changes, but should demonstrate what I'm trying to do. The purpose of these changes is to:

1. Remove `didInitialize` completely (it makes it less complex)
2. Remove `isReady()` completely (it is very complex to understand when this is resolved)
2. Make `isClientTheLeader()` async (this is what really needs to be async anyway in the end)

There are other usages of `isClientTheLeader()` which need to be refactored that I didn't touch yet.

File: src/libs/ActiveClientManager/index.js (hunk 23 above)
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:29]: The last comment makes sense. I didn't realize it. wow.

File: src/libs/Network.js (hunk 24 above)
Comment (parasharrajat) [reply src/libs/Network.js:60]: I thought the default value is `[]`, What do you suggest setting a default value on Onyx or check for nullability here.

File: src/libs/ActiveClientManager/index.js (hunk 23 above)
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:29]: Seems like a good plan to me. I feel this is going to be little hactic. I belive that 
```
Onyx.connect({
    key: ONYXKEYS.ACTIVE_CLIENTS,
    callback: (val) => {
        activeClients = !val ? [] : val;
        if (activeClients.length >= maxClients) {
            activeClients.shift();
            Onyx.set(ONYXKEYS.ACTIVE_CLIENTS, activeClients).then(() => {
                isInitialized();
            });
        } else {
            isInitialized();
        }
    },
});
```
This is more accurate then as If the Max client condition is reached, then we can't be sure until the shift has happened.
```
function init() {
    Onyx.merge(ONYXKEYS.ACTIVE_CLIENTS, [clientID]).then(isInitialized);
}

Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:29]: There is one more case when the client Leader change on tab-switch.

Comment (tgolen) [reply src/libs/ActiveClientManager/index.js:29]: It's probably technically more accurate, but I think it places the logic in a non-intuitive spot, and there isn't any issue with putting it in the `init()` method (the same thing is still achieved).

File: src/libs/Network.js (hunk 24 above)
Comment (tgolen) [reply src/libs/Network.js:60]: I think adding a `null` check here is OK.

File: src/libs/ActiveClientManager/index.js (hunk 23 above)
Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:29]: Ok

Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:29]: I tested it. First of it causes duplicate messages. Secondly, It hurt the code readability where we are using `ActiveClientManager.isClientLeader`. I agree with the point that your changes give the ActiveClientManger a clean look. But I think that this is going to be touched very less instead we will be using  `ActiveClientManager.isClientLeader` in a couple of places. and currently, we use it in a sync way. Making it a promise will break the sync flow.

Motive, why I added `isReady` callback to ActiveClientManager was that on page reload it was giving false results for client leadership and there was no client as a leader. We are not really concerned with the latter cases as we just want one client to process requests or send notifications for messages. it could be anyone. 

I have tried to change the current implementation thrice out of which I prefer Marc's suggestion of using `onReady` callback instead of an `isReady` promise.

Comment (tgolen) [reply src/libs/ActiveClientManager/index.js:29]: > and currently, we use it in a sync way. Making it a promise will break the sync flow.

Yeah, I get this. But that only means that we need to refactor the two spots that reference this method and they are both easily refactored. I don't think this should be a determination of what solution we should use.

I don't know if I've seen a full solution of Marc's suggestion. Is that what your branch is on now? I would like to make sure that I see it so I can be sure to have all the context.

Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:29]: No, my Branch is not on that solution but here is a glimpse of that.
```
/**
 * Allow to run any task after ActiveClientManager has successfully initialized
 *
 * @returns {Promise<void>}
 */
function isReady() {
    return readyPromise;
}
```
TO
```
function onReady(callback) {
    resolveReadyCallback = callback;
}
```
Then at https://github.com/parasharrajat/Expensify.cash/blob/16c147f00de85fec995537dd4b5c4016c121e1ec/src/libs/ActiveClientManager/index.js#L30
call this callback. As we need to only call the callback at one place so this works.
```
 if (didInitialize) {
    resolveReadyPromise();
 }
 ```
 TO
 ```
  if (didInitialize) {
    resolveReadyCallback();
 }
```

Comment (tgolen) [reply src/libs/ActiveClientManager/index.js:29]: OK, thanks. I'm still really against `didInitialize` and `isReady` (or `onReady`). I'm not sure what it would take to convince me otherwise. I think both of those things make the code non-intuitive and we need to have a codebase that maintains low barriers to entry. If Joel (who is not traditionally a front-end engineer) can't understand what's going on, then it prevents him from lending a hand, and we are failing at being inclusive.

Comment (parasharrajat) [reply src/libs/ActiveClientManager/index.js:29]: OK. I will try to give one more attempt to what you suggested earlier and try to fix the duplication. But the `onReady` pattern is literally everywhere in our codebase.

**Comment by parasharrajat** [comment]
Update: just found an about message being removed on page refresh. So looking into it.

**Comment by joelbettner** [comment]
Bump.

**Comment by parasharrajat** [comment]
Hi @joelbettner. Sorry for the delay here. I got confused with different implementation requests. I am still unsure what is final but I will update the PR once more with the latest working implementation.

**Comment by parasharrajat** [comment]
Ok. This is ready for review.

**Comment by parasharrajat** [comment]
Does anyone feel that my solution is worth merging by doing some changes and refactor, then please do let me know? otherwise, this PR can be closed. Thanks.

**Comment by tgolen** [comment]
I'll give this another look tomorrow and let you know if I have any
additional feedback!

**Comment by parasharrajat** [comment]
@tgolen any thoughts?

**Comment by tgolen** [comment]
Nope, I still have other things on my list to get to before I look at this today. Thanks for your patience!

File: src/libs/Network.js (hunk 21 above)
Comment (tgolen) [reply src/libs/Network.js:37]: I want to start a separate convo from the above discussion, and it's specifically about the use of a "fake merge" in order to trigger a callback. I'm concerned that this is a little bit of a "hack" and it's not clear what's really happening. Instead, I think it would be better like this:

1. Move the `ONYXKEYS.NETWORK_REQUEST_QUEUE` callback to be in its own method (not an anonymous function)
2. Reference the new function from `Onyx.connect()`
3. Call the new function at this spot.

File: src/libs/Network.js (hunk 25 above)
Comment (tgolen) [reply src/libs/Network.js:57]: I am still a big fan of this suggestion based on the following arguments:

- There is no hint anywhere that this method must be run after `ActiveClientManager.isReady()`
- If `isClientTheLeader()` is ever called without `.isReady()` then it's always going to give a false result

This is setting a trap for anyone else that decides to use `isClientTheLeader()` in the future.

File: src/libs/Network.js (hunk 11 above)
Comment (tgolen) [reply src/libs/Network.js:149]: bump

File: src/libs/Network.js [hunk 26]
```diff
@@ -107,12 +140,19 @@ function processNetworkRequestQueue() {
...
+        // If we have a request then we need to check if it can be persisted in case we close the tab while offline.
+        // We filter persisted requests from the normal Queue to remove duplicates
+        networkRequestQueue = _.reject(networkRequestQueue, (request) => {
+            if (!request.data.doNotRetry && request.data.persist) {
+                retryableRequests.push(request);
+                return true;
+            }
+        });
+        if (retryableRequests.length) {
+            Onyx.merge(ONYXKEYS.NETWORK_REQUEST_QUEUE, retryableRequests);
```
[the remark this answers is not in the document]
Comment (tgolen) [reply src/libs/Network.js:156]: bump

**Review by tgolen — CHANGES_REQUESTED** [review]

**Comment by parasharrajat** [comment]
> If isClientTheLeader() is ever called without .isReady() then it's always going to give a false result
It is not correct. Only on page reload this gives the wrong result.  for later cases it works just fine.
That's why notifications are not broken in the app on the web.

**Comment by tgolen** [comment]
> It is not correct. Only on page reload this gives the wrong result (Until Onyx sets the key). 

OK, thanks for explaining. I see I wasn't completely correct, but the trap is still there. For example: if I add code somewhere else that executes on page load, and only reference `isClientTheLeader()` without using `.isReady()` then I wouldn't get an accurate result.

> Sorry I didn't understand.

Oh, sorry! "bump" is a common term we use that indicates there is an unanswered question that needs to be addressed.

> Sure I will do that.

Thanks!

File: src/libs/Network.js (hunk 11 above)
Comment (parasharrajat) [reply src/libs/Network.js:149]: When use comes online on line 37 we process the queue by fake merge which I will optimize based on the suggestion.

File: src/libs/Network.js (hunk 26 above)
[the remark this answers is not in the document]
Comment (parasharrajat) [reply src/libs/Network.js:156]: The suggestion makes it more confusing. Also, we are not trying to filter or reinject requests to the queue. Instead, here we save the requests to offline queue which is clear via `Onyx.Merge`

File: src/libs/Network.js (hunk 25 above)
Comment (parasharrajat) [reply src/libs/Network.js:57]: I am ready to do it but how will I make sure that the value resolved from `isClientTheLeader` is always up-to-date. 

* Why didn't I make isClientLeader a promise?
When we update the ONYXKEYS.NETWORK_REQUEST_QUEUE on ONyx. Onyx.connect is called multiple times due every open browser tab will update the ONYXKEYS.NETWORK_REQUEST_QUEUE. I noticed that If we subscribe to isClientLeader inside this connect callback then an old copy of persistedRequests is passed to the callback which duplicates request.
* Why can't I wrap Onyx.connect call of ONYXKEYS.NETWORK_REQUEST_QUEUE inside isClientLeader a promise which should solve the above problem?
Inside the connect callback we have to check client leadership. If we wrap the connect call inside isClientLeader promise, isClientLeader value will never update after the first resolution. Due to the reason that client leadership change on tab focus. We want to get the updated value here.

Comment (tgolen) [reply src/libs/Network.js:57]: OK, interesting problem, and makes sense. I think that same problem exists in the current solution?

It almost seems like the promise for `isClientTheLeader()` should be re-resolved each time the ACTIVE_CLIENTS changes. I don't think that's possible though. So, my next theory is that any call to `isClientTheLeader()` should be placed in a callback for ACTIVE_CLIENTS? That seems messy. I'm not sure what to do.

**Comment by parasharrajat** [comment]
Updated

**Comment by parasharrajat** [comment]
This is ready for another review. I can move to the callback-based `onReady` method if pointed to do so.

**Review by joelbettner — APPROVED** [review]

File: src/libs/Network.js (hunk 25 above)
Comment (parasharrajat) [reply src/libs/Network.js]: IMO, the current implementation is minimally handling the complexities here. The presence of `isReady` does not impose that it is necessary to wrap isClientLeader in this promise which is the actual case. For other places, we don't really need to check the Readiness at all.

**Comment by parasharrajat** [comment]
:roll_eyes:

**Comment by parasharrajat** [comment]
Sorry, I am being impatient here but see no reason to hold unless you tell me the reason.

**Review by TomatoToaster — APPROVED** [review]

**Review by tgolen — APPROVED** [review]
Thanks for making that change to the callbacks.

We are not really seeing eye-to-eye on `isClientTheLeader()` being asynchronous.

If @TomatoToaster and @joelbettner are absolutely fine with the current implementation, and they feel they understand it and could fix any race conditions with it (as opposed to just approving this PR because of review-fatigue), then I am OK merging this as-is.

**Comment by tgolen** [comment]
All yours @marcaaron

**Comment by parasharrajat** [comment]
> We are not really seeing eye-to-eye on isClientTheLeader() being asynchronous.

I agree with the point. Just finding it difficult to handle in the ONYX.connect callback without too much boilerplate. I am ready to move forward with the current implementation as ClientManager usages do not have any such race condition. Maybe if we have any problems with this we can rethink the approach here.

**Comment by marcaaron** [comment]
I have to be honest... reviewing this is going to be a bit of a context switch for me at the moment. The changes still seem a bit hard to follow, but to be fair, the persisting of requests did not really fit cleanly into the design when I added it.

That said, I feel like it's very possible we will want to do something like a Phase 2 Refactor for the networking code. And that's probably a good time to think a bit more about how we want this to work and just do it right.

So yeah that's a long way of saying... it feels like persisting requests are in a somewhat broken state and if this fixes them then I'm 👍

**Comment by parasharrajat** [comment]
Thanks Marc. Not sure what is the next step.

**Comment by TomatoToaster** [comment]
Yeah I think we can merge this. I can't think of a more perfect way to fix right now this and I agree that we can revisit this on a stage 2 refactor. I'll also sign up to help out on fixing any bugs with these persisted requests going forward 👍🏾  and help out with the eventual refactor since I've got this context at least.

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-06.  :confetti_ball:
