### PR TITLE
Fix: Blank screen after creating an account

### LINKED ISSUE #2497: [Hold for payment 5/7] Blank screen after creating an account
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
User proceeds to expensify.cash chat list

## Actual Result:
User is redirected to a blank screen and a JS error can be seen in the console

## Action Performed:
1. Start from logged out state and proceed to create a new account
2. While logged out, type and login with brand new email address so it can trigger sign up flow
3. Get validation link from e-mail. On dev I'm copying the email link and appending it to localhost - e.g. http://localhost:8080/setpassword/10024706/EHOHMPGWM
4. Type new password and click "set password"
5. User is redirected to a blank screen and a JS error can be seen in the console

## Workaround:
Refreshing the page manually would fix the issue and the chat list would load

## Platform:
Where is this issue occurring?
The issue is confirmed in:

 Web ✔️ 
 Android ✔️
 iOS
 Desktop App 
 Mobile Web

The other environments are probably affected as well

**Version Number:** 1.0.21-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/12156624/115445533-a7a10b80-a21e-11eb-822a-e3e1d4101e9f.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by kidroca**
<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>
@marcaaron

### Details
Address the problem that no navigator is available during application initialization
We don't need to keep the entire AuthScreens navigator unmounted but just the Report screen
This way the URL still resolves to the correct report after the data is available

### Fixed Issues
Fixes #2497

### Tests

1. Start from logged out state and proceed to create a new account
2. While logged out, type and login with brand new email address so it can trigger sign up flow
3. Get validation link from e-mail. On dev I'm copying the email link and appending it to localhost - e.g. http://localhost:8080/setpassword/10024706/EHOHMPGWM
4. Type new password and click "set password"
5. After a brief loading time you should see an initial chat list in LHN containing only the Concierge chat
    - the URL in the address would be `/r` until the initial report number is resolved
    - Depending on internet speed this can be too quick to notice
    - In the video samples below it reads `/loading` but we decided to change it
6. The Concierge chat should be loaded as the active conversation

Please check the steps listed in the PR here #2346 work as well and there's no regressions

### QA Steps
Same as above

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

I'm intentionally setting a slow internet connection to test that the URL (chat) would resolve correctly even when the data comes after the App's initial render

##### Creating account over a slow internet connection
https://user-images.githubusercontent.com/12156624/116293730-db8cab80-a79f-11eb-9ace-9f8ff0d4047f.mp4

##### Login in over a slow internet connection

https://user-images.githubusercontent.com/12156624/116294035-2c9c9f80-a7a0-11eb-84d2-de53b20003f3.mp4

##### Logging in on mobile web
https://user-images.githubusercontent.com/12156624/116302433-d7658b80-a7a9-11eb-814d-947bdeec626b.mov

##### Logging in on the desktop app
https://user-images.githubusercontent.com/12156624/116306650-0251de80-a7ae-11eb-8b93-e269f128f7df.mov

#### iOS

A simulated login using the magic link after an account is created

##### Simulate a magic link to set a password for a new account

https://user-images.githubusercontent.com/12156624/116302029-61f9bb00-a7a9-11eb-9a06-58b4d59071d9.mp4

#### Android

Testing on Android to verify everything still works as before

https://user-images.githubusercontent.com/12156624/116294183-58b82080-a7a0-11eb-960c-7802634bbe6f.mp4

### CODE REVIEW

File: src/libs/Navigation/Navigation.js [hunk 1]
```diff
@@ -91,6 +92,27 @@ function dismissModal(shouldOpenDrawer = false) {
...
+ * Executes the last captured navigation command if attempts were made prior being ready
+ */
+function enableNavigation() {
+    if (lastAttemptedRoute) {
+        navigate(lastAttemptedRoute);
+    }
+    // eslint-disable-next-line no-use-before-define
+    exports.navigate = navigate;
+}
+
```
Comment (kidroca) [inline src/libs/Navigation/Navigation.js:115]: This didn't resolve the original issue, and perhaps would not be a useful addition

Here's what happens following the Test steps in the PR

1. Start logged out - The Navigation is immediately enabled because we have an active navigator - `PublicScreens`
2. While logged out, type and login with brand new email address so it can trigger sign up flow
3. Get validation link from e-mail. On dev I'm copying the email link and appending it to localhost - e.g. http://localhost:8080/setpassword/10024706/EHOHMPGWM
4. Type new password and click "set password" - at this point `PublicScreens` unmount, but `AuthScreens` are not yet mounted. An error happens as a call to `navigate` is made during this time

File: src/libs/actions/Report.js [hunk 2]
```diff
@@ -659,9 +659,15 @@ function fetchOrCreateChatReport(participants, shouldNavigate = true) {
...
-                // Redirect the logged in person to the new report
-                Navigation.navigate(ROUTES.getReportRoute(data.reportID));
+                try {
+                    // Redirect the logged in person to the new report
+                    Navigation.navigate(ROUTES.getReportRoute(data.reportID));
+                } catch (e) {
+                    // When switching between the Auth and Public routers there's a brief time of no navigator mounted
+                    console.error(e);
+                }
             }
```
Comment (kidroca) [inline src/libs/actions/Report.js:669]: This is executed after the Navigation was initialized (when `PublicScreens` mounted) but before the `AuthScreens` are mounted and throws an error. When the error is not handled the promise chain is broken and the original caller never resolves which in turn prevents rendering the initial state of the app

File: src/libs/actions/Report.js [hunk 3]
```diff
@@ -727,15 +733,16 @@ function fetchAllReports(
                 return;
             }
 
-            // The string cast here is necessary as Get rvl='chatList' may return an int
-            reportIDs = String(response.chatList).split(',');
```
Comment (kidroca) [inline src/libs/actions/Report.js:731]: This produced a bug when `response.chatList` is empty `[]`. It would assign `['']` to report IDs, and the check ` if (reportIDs.length)` would be positive even though there are no reports

You can try this to see the outcome is `['']`

```js
console.log(String([]).split(',')) // prints ['']
```

---

Casting to string is no longer necessary as following usages of `reportIDs` work with both strings and numbers.
But if you need to have string IDs you can instead use map

```js
reportIDs = response.chatList.map(n => String(n)) // or n.toString()
```

**Review by kidroca — COMMENTED** [review]
I think it might be better to remove the conditional rendering in `AuthScreens`:

https://github.com/kidroca/Expensify.cash/blob/c4d25f5ed8c92131d48adcfa9affeee9baf75c86/src/libs/Navigation/AppNavigator/AuthScreens.js#L170-L174

And let the `AuthScreens` mount instantly so that stack navigators can swap instantly and a navigator is always available

This would also remove the code inside `shouldComponentUpdate`:

https://github.com/kidroca/Expensify.cash/blob/c4d25f5ed8c92131d48adcfa9affeee9baf75c86/src/libs/Navigation/AppNavigator/AuthScreens.js#L151-L158

When the app initializes from a stored state it would still load the persisted report
If no report is available in route params by the time the `ReportScreen` is mounted it can request navigation to transition to the first available report in the chat list

This way most of the changes in this PR, but the bug fixes, will be removed

File: src/libs/actions/Report.js (hunk 3 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:731]: To clarify, the string cast is necessary because the API can return a `Number` (could be fixed eventually, but we are working around it for now).

File: src/libs/Navigation/AppNavigator/AuthScreens.js [hunk 4]
```diff
@@ -169,7 +169,7 @@ class AuthScreens extends React.Component {
 
     render() {
         // Wait to resolve initial Home route params.
-        if (!this.initialReportID) {
+        if (!_.isString(this.initialReportID)) {
             return null;
         }
```
Comment (kidroca) [inline src/libs/Navigation/AppNavigator/AuthScreens.js:174]: What I'm trying to say here: https://github.com/Expensify/Expensify.cash/pull/2575#pullrequestreview-644939666 is most of the issues would come when we return `null` here and there's no mounted navigator

The code would become simpler with `initialReportID` defaulting to empty string, and when no stored report is available during init we still mount the navigator, when the ReportScreen mounts it can make a call to `Navigation.navigate(/* any/first available report */)` if there's nothing available **and the screen is focused** - e.g. it would not mess navigation if we're deeplinked to some other screen

File: src/libs/actions/Report.js (hunk 2 above)
Comment (kidroca) [reply src/libs/actions/Report.js:669]: This would be reverted as well if we use a different approach

File: src/libs/actions/Report.js (hunk 3 above)
Comment (kidroca) [reply src/libs/actions/Report.js:731]: Yes but the only usages have no problems with numbers:

`fetchChatReportsByIDs(reportIDs);` would convert everything to string anyway since internally it makes this `chatList.join(',')`

`fetchActions(reportID);` seems to work OK with number or string

And merging to Onyx would again use `String`

```js
const currentReportID = firstReportID ? String(firstReportID) : '';
```

File: src/libs/Navigation/AppNavigator/AuthScreens.js (hunk 4 above)
Comment (marcaaron) [reply src/libs/Navigation/AppNavigator/AuthScreens.js:174]: That makes sense. But to back up for a second, wasn't the point of waiting so that we could pass the `initialReportID` to `initialParams` of the screen?

File: src/libs/Navigation/Navigation.js (hunk 1 above)
Comment (marcaaron) [reply src/libs/Navigation/Navigation.js:115]: Sounds like we'd need to hook into some other `onReady` situation like the sidebar mounting or something to determine "readiness". But if we can avoid this complexity then let's do that instead :)

File: src/libs/actions/Report.js (hunk 3 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:731]: I'm still a little confused sorry. When we get the `response.chatList` from `API.Get` it can be a number or a string and must be turning into an `Array`. `fetchChatReportsByIDs()` is looking for an `Array` and it calls `.join()` on it. So it's not clear how this code is working.

File: src/libs/Navigation/AppNavigator/AuthScreens.js (hunk 4 above)
Comment (kidroca) [reply src/libs/Navigation/AppNavigator/AuthScreens.js:174]: Yes, but this waiting is causing issue like the one we're trying to solve. 

By removing it we'll won't have to come up with solutions like `try/catch` on certain `navigate` calls or custom nav handling like `navigateLater` 

Initial Prams was a good solution to fix the url in the address bar, but it's not the only one
I'll make sure to link the previous PR as well so that there's no regression on that matter

File: src/libs/actions/Report.js (hunk 3 above)
Comment (kidroca) [reply src/libs/actions/Report.js:731]: For me `response.chatList` is always an Array containing Integers like so:
image

Or an empty array like `[]` for new users

Are you saying there can be cases:
- a single number like `71402263` is returned
- a comma separated string is returned like `"71402263,71403817,71403849,71734617,71955477,72156283,72207410"`

In that case, yeah a special handling would be needed

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js [hunk 5]
```diff
@@ -28,22 +41,37 @@ const MainDrawerNavigator = props => (
...
+                        name="Report"
+                        component={ReportScreen}
+                        initialParams={{reportID: props.initialReportID}}
+                    />
+                )
+                : (
+                    <Drawer.Screen name="loading">
+                        {() => <FullScreenLoadingIndicator visible />}
+                    </Drawer.Screen>
+                )
```
Comment (kidroca) [inline src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:62]: Moving the conditional mounting here allows to always have a navigator mounted.

The Report screen will mount once `initialReportID` is available - either instantly the usual case, or after a brief time - login / create account.

In the meantime a placeholder screen is mounted as you can't have a Navigator without screens. It doesn't need to render anything, but I've added the loader. As a name I've used "loading" this would appear as a URL until the Report Screen is mounted, this can be renamed or setup so that it doesn't appear in the URL. You can see this in the video below

I've used the `isString` check in the rare event that no `initialReportId` is not resolved - there's a case where `''` would be set. This is an error case because, as you know initialization logic would always set a `initialReportId` (or navigate to the Concierge conversation). In that case the view would just show the empty report page and you can recover by selecting a different conversation or refreshing the page.

This can perhaps be further improved a bit if state is used. E.g. save state the first time that `props.initialReportID` becomes available and keep the Report Screen mounted ever since that - in case you think that something could delete/remove the `props.initialReportID` e.g. Onyx eviction

##### Video simulating how initialReportId is resolved from a network call
https://user-images.githubusercontent.com/12156624/116292439-610f5c00-a79e-11eb-8283-5bf9ef3c4784.mp4
- You can also see the effect of deleting currently viewed report during runtime

1. Report saved in Onyx is deleted
2. App is reloaded from root `/`
3. The route (report ID) resolves from Network

File: src/libs/actions/Report.js [hunk 6]
```diff
@@ -950,7 +951,7 @@ function handleReportChanged(report) {
  * @param {Number} reportID
  */
 function updateCurrentlyViewedReportID(reportID) {
-    Onyx.merge(ONYXKEYS.CURRENTLY_VIEWED_REPORTID, String(reportID));
+    Onyx.merge(ONYXKEYS.CURRENTLY_VIEWED_REPORTID, String(reportID || ''));
```
Comment (kidroca) [inline src/libs/actions/Report.js:954]: I've updated this so it can be reused in `fetchAllReports` and to guard against `null` , `undefined` as `String(null)` would create a `"null"`  (similar situation for undefined and NaN)

File: src/libs/actions/Report.js [hunk 7]
```diff
@@ -762,8 +763,8 @@ function fetchAllReports(
             }
 
             const firstReportID = _.first(reportIDs);
-            const currentReportID = firstReportID ? String(firstReportID) : '';
-            Onyx.merge(ONYXKEYS.CURRENTLY_VIEWED_REPORTID, currentReportID);
+            // eslint-disable-next-line no-use-before-define
+            updateCurrentlyViewedReportID(firstReportID);
```
Comment (kidroca) [inline src/libs/actions/Report.js:767]: Maybe I should move `updateCurrentlyViewedReportID` to be declared before this usage so the eslint override can be removed. 

About that eslint rule it can be tweaked. There's nothing wrong using a `function` before it's defined and the rule allows for such configuration. The problem is when you try to use a `class` or a variable before they are defined.
This style rule is forcing specifics to be defined at the top, which usually degrades readability.

**Comment by kidroca** [comment]
Updated

**Comment by marcaaron** [comment]
Thanks, going to let @thienlnam take a first pass at reviewing + testing this then I will jump in.

File: src/libs/actions/Report.js (hunk 3 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:731]: I may have misspoke, but I am remembering that it is "weird". 😂 

I think specifically it can be either an `Array` (like you are seeing) or a single number. Hence, why we were casting the array into a string before splitting it back into an array.

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js (hunk 5 above)
Comment (thienlnam) [reply src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:62]: This logic makes sense 👍  
Though I think 

> can be renamed or setup so that it doesn't appear in the URL

we should do this as we don't want a url that has /loading

**Review by thienlnam — COMMENTED** [review]
Changes look good, just a small comment and then going to give it a test

**Comment by kidroca** [comment]
I've added sample videos for all platforms:

I don't know how you test deep links on iOS / Android. This is what I do for iOS for example:

https://user-images.githubusercontent.com/12156624/116302029-61f9bb00-a7a9-11eb-9a06-58b4d59071d9.mp4
- create a new account
- copy the link from the email
- use the link in a terminal to trigger a simulator run: 
    ```shell
    xcrun simctl openurl booted expensify-cash://setpassword/10075909/XGFOJRHBO
    ```
    - note: you have to be logged out first in order for this particular link to resolve

Maybe something about it can be included in the README

File: src/libs/actions/Report.js (hunk 3 above)
Comment (kidroca) [reply src/libs/actions/Report.js:731]: Ok, in that case I'll revert the old logic, but add filtering on the resulting array so that the bug with the false positive is addressed. 

This is recent though as before, creating account would just fail due to the navigation issue, and then if you refresh everything is fine, while now if this is not addressed you will never enter the case where a Concierge conversation is created and you're stuck with no chats

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js [hunk 8]
```diff
@@ -1,22 +1,62 @@
...
+ */
+const shouldMountReportScreen = ({initialReportID, route}) => {
+    if (_.isString(initialReportID)) {
+        return true;
+    }
+
+    // After the ReportScreen is mounted it should stay mounted no matter initial report ID
+    return Boolean(route.state) && route.state.routeNames.includes(SCREENS.REPORT);
+};
+
```
Comment (kidroca) [inline src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:59]: This could be put in the component body like

```jsx
const MainDrawerNavigator = (props) => {
    const hasInitialParams = _.isString(props.initialReportID);
    const const isReportMounted = Boolean(route.state) && route.state.routeNames.includes(SCREENS.REPORT);

   return (
        <Drawer.Navigator>
           {
               hasInitialParams || isReportMounted 
                  ? <Drawer.Screen name={SCREENS.REPORT} />
                  : <Drawer.Screen name={SCREENS.LOADING} />
            }
    );
```

---

Underscore `get` function would have been useful here

```js
return _.get(route, ['state', 'routeNames'], []).includes(SCREENS.REPORT);
```

But it's not available in the current version

File: src/libs/actions/Report.js [hunk 9]
```diff
@@ -754,16 +759,15 @@ function fetchAllReports(
...
-                return;
+            if (shouldRedirectToReport || !lastViewedReportID) {
+                const firstReportID = _.first(reportIDs);
+                // eslint-disable-next-line no-use-before-define
+                updateCurrentlyViewedReportID(firstReportID);
             }
-
-            const firstReportID = _.first(reportIDs);
-            const currentReportID = firstReportID ? String(firstReportID) : '';
-            Onyx.merge(ONYXKEYS.CURRENTLY_VIEWED_REPORTID, currentReportID);
```
Comment (kidroca) [inline src/libs/actions/Report.js:766]: Moved this logic to `finally` as it's important to set the `CURRENTLY_VIEWED_REPORTID` during initialization, even in the event of an error

**Comment by kidroca** [comment]
Updated

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js (hunk 8 above)
Comment (kidroca) [reply src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:59]: I've just noticed there's a warning regarding accessing state
> Accessing the 'state' property of the 'route' object is not supported. If you want to get the focused route name, use the 'getFocusedRouteNameFromRoute' helper instead: https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state

I'll see if it's possible to change this so this is not using `route.state`

**Comment by kidroca** [comment]
Updated

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js [hunk 10]
```diff
@@ -1,49 +1,104 @@
...
+    initialReportID: null,
+};
+
 const Drawer = createDrawerNavigator();
+const LoadingScreen = React.memo(() => <FullScreenLoadingIndicator visible />, () => true);
+
+class MainDrawerNavigator extends React.Component {
+    constructor(props) {
+        super(props);
+        this.shouldMountReportScreen = _.isString(props.initialReportID);
```
Comment (marcaaron) [inline src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:38]: It might not be clear that an `initialReportID` should always either exist or be on its way soon. Could we document this somehow?

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js [hunk 11]
```diff
@@ -1,49 +1,104 @@
...
+        // Once the report screen is mounted we don't unmount it
+        if (!this.shouldMountReportScreen) {
+            this.shouldMountReportScreen = _.isString(nextProps.initialReportID);
+
+            if (this.shouldMountReportScreen) {
+                return true;
+            }
+        }
+
+        // Re-render the component only for these changes
```
Comment (marcaaron) [inline src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:51]: Out of curiosity was the re-rendering causing some issues? Probably the `ReportScreen` is expensive to re-render so we typically want to avoid doing it?

File: src/libs/actions/Report.js [hunk 12]
```diff
@@ -727,15 +727,20 @@ function fetchAllReports(
                 return;
             }
 
-            // The string cast here is necessary as Get rvl='chatList' may return an int
-            reportIDs = String(response.chatList).split(',');
+            // The cast here is necessary as Get rvl='chatList' may return an int or Array
+            reportIDs = String(response.chatList)
+                .split(',')
+                .filter(_.identity);
```
Comment (marcaaron) [inline src/libs/actions/Report.js:733]: I'm not too sure what this `filter(_.identity)` does here? Do we need it?

File: src/libs/actions/Report.js [hunk 13]
```diff
@@ -727,15 +727,20 @@ function fetchAllReports(
...
-            if (reportIDs.length) {
+            if (reportIDs.length > 0) {
                 return fetchChatReportsByIDs(reportIDs);
             }
 
-            return fetchOrCreateChatReport([currentUserEmail, 'concierge@expensify.com']);
+            return fetchOrCreateChatReport([currentUserEmail, 'concierge@expensify.com'])
+                .then((createdReportID) => {
+                    reportIDs = [createdReportID];
+                });
```
Comment (marcaaron) [inline src/libs/actions/Report.js:743]: another option could be to have `fetchOrCreateChatReport()` return a reportID in an array and just use the `reportIDs` passed to the next chain. But this works (I had this idea from another PR I'm working on).

File: src/libs/actions/Report.js (hunk 7 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:772]: >About that eslint rule it can be tweaked.

It has been brought up before. We generally agree with the reasoning laid out here 

https://eslint.org/docs/rules/no-use-before-define

File: src/libs/actions/Report.js (hunk 6 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:959]: Hmm, this is the _one thing_ that I'm not so sure about. If we are calling this with a `reportID` that is `null` or `undefined` why try to set it at all? Couldn't we just leave whatever existing value we have? Seems not ideal to fail silently and set the `currentlyViewedReportID` to an empty string. Maybe it would be appropriate to log an alert of some kind when this happens instead?

We have some ways to do that e.g. 

https://github.com/Expensify/Expensify.cash/blob/f213be0a1be5a04599d2f17d8848b0a7824eb8be/src/libs/actions/Report.js#L717-L720

**Review by marcaaron — DISMISSED** [review]
Nothing in this PR is a major blocker for me so I am leaning towards merging so we can unblock the deploy and do a follow up to address any comments. cc @roryabraham

File: src/libs/actions/Report.js (hunk 12 above)
Comment (kidroca) [reply src/libs/actions/Report.js:733]: `.filter(_.identity)` removes empty/null values from the resulting array. 
I thought it's clearer than `.filter(report => report)`

This is related to the bug I've commented about in the other thread: https://github.com/Expensify/Expensify.cash/pull/2575/files#r621584917

When `response.chatList` is an empty array `[]` (After creating an account for example) `String(response.chatList)` would return `['']` - an Array containing one empty string. Then the check below `reportIDs.length > 0` would redirect flow to `fetchChatReportsByIDs` and would not actually fetch anything. The LHN stays empty and Concierge chat is never created (Unless something else creates such a chat at a different time?)

File: src/libs/actions/Report.js (hunk 13 above)
Comment (kidroca) [reply src/libs/actions/Report.js:743]: This would be changing the other function for the convenience of the current usage.
I wouldn't expect to receive a list of one element from a function like `fetchOrCreateChatReport`

File: src/libs/actions/Report.js (hunk 6 above)
Comment (kidroca) [reply src/libs/actions/Report.js:959]: > Hmm, this is the one thing that I'm not so sure about. If we are calling this with a reportID that is null or undefined why try to set it at all? 

As you can see the original logic would save anything without any consideration, I've just updated it so that if called with null or undefined they are converted

I'll just revert this, this will also address the used-before-defined problem

File: src/libs/actions/Report.js [hunk 14]
```diff
@@ -754,16 +759,17 @@ function fetchAllReports(
...
             // bogging it down with more requests and operations.
             }, shouldDelayActionsFetch ? 8000 : 0);
-
+        })
+        .finally(() => {
             // Update currentlyViewedReportID to be our first reportID from our report collection if we don't have
             // one already.
             if (!shouldRedirectToReport || lastViewedReportID) {
                 return;
             }
```
Comment (kidroca) [inline src/libs/actions/Report.js:768]: Maybe consider changing the `shouldRedirectToReport` parameter. As you can see from this check - it will not be respected if `lastViewedRportID` is alredy set. 
Initially I thought that calling `fetchAllReports(shouldRedirectToReport: true)` will redirect to the report no matter what
But now it seems like it only serves to prevent a redirect

Instead of adding flags to the function you can do something like this in the only 2 usages:

##### Report.js
```js
NetworkConnection.onReconnect(() => {
    fetchAllReports();
});
```

##### AuthScreens
```jsx
class AuthScreens extends React.Component {
  componentDidMount() {
    this.initReports();
  }

  initReports() {
    fetchAllReports()
      .then(reportIds => {
         if (!this.props.lastViewedReportID) {
            const firstReportID = _.first(reportIDs);
            updateCurrentlyViewedReportID(firstReportID);
         }
      })
  }
}
```

I guess the concierge creating logic can be extracted as well.

What I'm saying is `fetchAllReports` is not only responsible for fetching reports but at least 2 other things.
If it's intended to always create the Concierge chat when there are no chats it can be renamed to something like `initUserReports` so the purpose is clear. From the current documentation the purpose of the function is just fetching

Even if the function is reused on the 10 places a specific usage like in the AuthScreens example can be extracted instead of flag parameters

Comment (kidroca) [reply src/libs/actions/Report.js:768]: I've actually found a different way and addressed this

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js [hunk 15]
```diff
@@ -1,49 +1,87 @@
...
-        <Drawer.Screen
-            name="Report"
-            component={ReportScreen}
-
-            // Providing an empty string here will ensure that the ReportScreen does not show as '/r/undefined'
-            // eslint-disable-next-line react/jsx-props-no-multi-spaces
-            initialParams={{reportID: ''}}
-            options={{
+// Decorated to always returning the result of the first call - keeps Screen initialParams from changing
+const getInitialReport = _.once(getLastAccessedReport);
```
Comment (kidroca) [inline src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:38]: `_.once` is ideal for initialization scenarios where the value need to be computed just once and always returned since

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js [hunk 16]
```diff
@@ -1,49 +1,87 @@
...
+
+const MainDrawerNavigator = (props) => {
+    // When there are no reports there's no point to render the empty navigator
+    if (_.size(props.reports) === 0) {
+        return <FullScreenLoadingIndicator visible />;
+    }
+
+    const initialReportID = getInitialReport(props.reports).reportID;
```
Comment (kidroca) [inline src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:46]: Once reports are loaded initial value is derived and no longer updates.
It doesn't need to update because the Screen would use `initialParams` when it mounts and no longer care if they change

The value returned by `getLastAccessedReport` would be the same as `ONYXKEYS.CURRENTLY_VIEWED_REPORTID`, but if there's no data in Onyx (like after signout -> login) the last seen report by the user will be resolved, this seems a bit better than just using the first report in the list.

This also simplifies other places:
- nothing no longer needs to make sure a `lastViewedReportID` is set so that Navigation can mount
- A chunk of code in `Report.fetchAllReports` was removed as it's no longer necessary

File: src/libs/actions/Report.js [hunk 17]
```diff
@@ -754,16 +757,6 @@ function fetchAllReports(
...
-
-            // Update currentlyViewedReportID to be our first reportID from our report collection if we don't have
-            // one already.
-            if (!shouldRedirectToReport || lastViewedReportID) {
-                return;
-            }
-
-            const firstReportID = _.first(reportIDs);
-            const currentReportID = firstReportID ? String(firstReportID) : '';
-            Onyx.merge(ONYXKEYS.CURRENTLY_VIEWED_REPORTID, currentReportID);
```
Comment (kidroca) [inline src/libs/actions/Report.js:766]: This is no longer needed because:
1. It was only called like that in `AuthScreens`
2. Initial report ID would be derived in `MainDrawerNavigator`
3. `MainDrawerNavigator` would mount the `ReportScreen`
4. `ReportScreen` would set `currentReportID` during mount and updates 
    https://github.com/Expensify/Expensify.cash/blob/42b73072b87ff9e22e2ce126c9b825c4096f6c50/src/pages/home/ReportScreen.js#L32-L35

**Review by kidroca — COMMENTED** [review]
With these changes `ONYXKEYS.CURRENTLY_VIEWED_REPORTID` is no longer needed for initialization purposes.

File: src/libs/actions/Report.js (hunk 6 above)
Comment (marcaaron) [reply src/libs/actions/Report.js]: Yes, I see. Only mentioning this since logging an alert would perhaps be useful. But no need to add it in this PR.

**Review by thienlnam — APPROVED** [review]
Nothing glaring is pointing out to me, let's get this deploy out - sending last review to you @marcaaron

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js (hunk 15 above)
Comment (marcaaron) [reply src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:38]: Ok, so we are now waiting for the `reports` to exist instead of a `currentlyViewedReportID`. Makes sense.

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js [hunk 18]
```diff
@@ -1,49 +1,87 @@
...
-    >
-        <Drawer.Screen
-            name="Report"
-            component={ReportScreen}
-
-            // Providing an empty string here will ensure that the ReportScreen does not show as '/r/undefined'
-            // eslint-disable-next-line react/jsx-props-no-multi-spaces
-            initialParams={{reportID: ''}}
-            options={{
+// Decorated to always returning the result of the first call - keeps Screen initialParams from changing
```
Comment (marcaaron) [inline src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:37]: This comment is a little hard to follow and I might change it to something like:

>We are decorating `getLastAccessedReport` so that it caches the first result once the reports load. This will ensure the `initialParams` are only set once for the `ReportScreen`.

Which also begs the question... what happens if the `initialParams` change? And why do we care? Maybe we can explain that as well here just so it is very obvious?

**Comment by roryabraham** [comment]
@kidroca, I noticed that you had one approval, and then made substantial changes to this PR. I don't have all the context for why those changes were made, but I did just want to point out that this PR fixes a [deploy-blocking issue](https://github.com/Expensify/Expensify.cash/issues/2497) that has been preventing us from running a production deploy for more than a week now. Generally with deploy blockers we want to get the quickest fix that solves the problem at hand so we're no longer holding up the deploy, even if you then create a follow-up PR to provide a better or more robust solution during the next deploy. Just something to keep in mind for the future 🙂

File: src/libs/actions/Report.js (hunk 12 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:731]: Ok, I think it's more common for us to use `filter(report => report)` or use `_.filter()` on it's own to remove bad values, but this isn't necessarily incorrect.

Screen Shot 2021-04-29 at 7 13 48 AM

File: src/libs/actions/Report.js (hunk 17 above)
Comment (marcaaron) [reply src/libs/actions/Report.js:766]: Ok so we will stop redirecting to the report and instead just show the most recently accessed report. Seems like a nice clean solution. Redirecting from here always felt a bit weird tbh.

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js (hunk 16 above)
Comment (marcaaron) [reply src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:46]: Yep that all sounds great to me!

**Review by marcaaron — APPROVED** [review]
LGTM, I only have some suggestions about how to improve the documentation around some of the logic in the drawer navigator but no need to block.

**Comment by kidroca** [comment]
@roryabraham 
I saw Marc comment regarding merging this.
It was a good point to explicitly say stop making further changes.

Since it wasn't merged and no one said nothing. I looked at the comments left by Marc and came up with an even more brilliant solution and had the time to implement it.
I always consider how easy would something be to review and wouldn't have done this if the solution wasn't way better
The changes might seem significant but 50% of them are blank lines comments and indentation change

Besides I've left a good description which should have helped reviewing them quickly

File: src/libs/Navigation/AppNavigator/MainDrawerNavigator.js (hunk 18 above)
Comment (kidroca) [reply src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:37]: Nothing will happen if we pass different `initialParams` after the screen is mounted. And that's why we want to stop calculating them each time `MainDrawerNavigator` re-renders

It might be better to just remove this `_.once` optimization and address it if it ever becomes a problem

Comment (marcaaron) [reply src/libs/Navigation/AppNavigator/MainDrawerNavigator.js:37]: Nice one, yep I think this is fine in any case but took me a second to get why so a small comment would have been helpful.

**Comment by marcaaron** [comment]
Just a heads up there is an issue with this implementation and it's _possible_ to get into a bad state if you have some partial report data e.g. a report that has only partial data. Here's what I've observed:

Screen Shot 2021-04-29 at 4 07 05 PM

Which, as you can imagine, leads to some pretty broken stuff 😄 

That said, I was only able to reproduce this a few times. Still we should be careful to avoid this case and not present any report that has no `reportID`.

**Comment by kidroca** [comment]
Nice catch @marcaaron 

I didn't know that there could be such a report in the collection

I see that this is handled with a `reportID` check here: 

https://github.com/Expensify/Expensify.cash/blob/2ae23e75b9c7b9166fb2a333bfcdd10646508448/src/libs/OptionsListUtils.js#L192-L195

I don't know why incomplete reports aren't stored in a different collection but perhaps we can extract this check to `reportUtils` for the time being 

```js
function isIncompleteReport(report) {
  if (!report || !report.reportID) return true;

  const participants = lodashGet(report, ['participants'], []);
  return _.isEmpty(logins);
}
```

Then update the code here:

https://github.com/Expensify/Expensify.cash/blob/2ae23e75b9c7b9166fb2a333bfcdd10646508448/src/libs/reportUtils.js#L30-L35

To account for that

```js
function getLastAccessedReport(reports) {
    return _.chain(reports)
        .filter(report => isIncompleteReport(report) == false)
        .toArray()
        .sortBy('lastVisitedTimestamp')
        .last()
        .value();
}
```

I can't find how a partial report is created to analyze this further, can you point me to when/where this happens?

**Comment by marcaaron** [comment]
Yep, perfect plan! I don't quite understand how they are created. It could be a race condition or a failed network request or something else entirely.

File: src/libs/actions/Report.js (hunk 12 above)
Comment (tgolen) [reply src/libs/actions/Report.js:731]: I came across this too, and I think it should be changed as it's not intuitive code (it's overly clever). Why would there be empty/null values? In what case would that ever happen?

Comment (kidroca) [reply src/libs/actions/Report.js:731]: > This produced a bug when `response.chatList` is empty `[]`. It would assign `['']` to report IDs, and the check ` if (reportIDs.length)` would be positive even though there are no reports
> 
> You can try this to see the outcome is `['']`
> 
> ```js
> console.log(String([]).split(',')) // prints ['']
> ```

`response.chatList` is `[]` when you create a new account 
when you convert that to a string `String(response.chatList)` and then split it `.split(',')`
you get `['']` and then the Concierge chat is not created

Comment (tgolen) [reply src/libs/actions/Report.js:731]: OK, thanks for explaining that! I think I have some ideas to clean this up.
