### PR TITLE
fix: enable paste html in compose box and fix regressions

### LINKED ISSUE #53637: [$250] App crashes when clicking add reaction
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation** (hyperlinked to channel name): [expensify_retain](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1733411293984459)

## Action Performed:
1. Go to any chat
2. Send a message
3. Click the "Add reaction" button to add a non-default emoji reaction
## Expected Result:
Emoji reaction menu appears
## Actual Result:
App crashes and shows "Uh-oh, something went wrong!" screen
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/b4ac8491-2d78-4398-b183-e5cca7a17007

```
hook.js:608 Error: Couldn't find a navigation object. Is your component inside NavigationContainer?
    at c (index.ts:32:24)
    at X (index.tsx:107:5)
overrideMethod	@	hook.js:608
uA	@	react-dom.production.min.js:188
a.componentDidCatch.n.callback	@	react-dom.production.min.js:189
Ha	@	react-dom.production.min.js:156
Es	@	react-dom.production.min.js:260
Is	@	react-dom.production.min.js:259
ms	@	react-dom.production.min.js:258
(anonymous)	@	react-dom.production.min.js:282
yl	@	react-dom.production.min.js:280
il	@	react-dom.production.min.js:269
v	@	scheduler.production.min.js:13
k	@	scheduler.production.min.js:14
e.exports	@	_invoke.js:5
f.<computed>	@	_task.js:35
I	@	_task.js:21
E	@	_task.js:25
```
At c is the useNavigation line:
```
const useHtmlPaste: UseHtmlPaste = (textInputRef, preHtmlPasteCallback, removeListenerOnScreenBlur = false, isMarkdownEnabled = true) => {
    const navigation = useNavigation();
```
At X is:
```
useHtmlPaste(input as MutableRefObject<TextInput | null>, undefined, false, isMarkdownEnabled);
```

https://github.com/user-attachments/assets/e019651b-eb49-4a6c-b35a-5efcb1e1ef4e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864710692177622796</li>
        <li>Upwork Job ID: 1864710692177622796</li>
        <li>Last Price Increase: 2024-12-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

### LINKED ISSUE #53654: [$250]  Profile - Email copied from profile is pasted twice in Private notes
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh16110001@applause.expensifail.com
**Issue reported by:** Applause- Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Click on the report header
4. Click copy icon next to the email
5. Click Private notes
6. CMD+V to paste the email

## Expected Result:
The email will be pasted one time

## Actual Result:
The email is pasted twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d9c36fbb-19e3-4c59-969b-edb7bef9ddcf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864831556453840652</li>
        <li>Upwork Job ID: 1864831556453840652</li>
        <li>Last Price Increase: 2024-12-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

### PR DESCRIPTION
**Pull request by daledah**
### Explanation of Change

This PR re-implements https://github.com/Expensify/App/pull/53367 with some changes to fix regressions:

- Remove `navigate` usage in `useHTMLPaste` to fix https://github.com/Expensify/App/issues/53637
- Remove `useHTMLPaste` in `PrivateNotesEditPage` to fix https://github.com/Expensify/App/issues/53654

### Fixed Issues

$ https://github.com/Expensify/App/issues/52681
$ https://github.com/Expensify/App/issues/53654
$ https://github.com/Expensify/App/issues/53637
PROPOSAL: https://github.com/Expensify/App/issues/52681#issuecomment-2482243469

### Tests

1. Open a chat
2. Type "> hi" and send message
3. Long press message and click "Copy to clipboard"
4. Open Emoji picker
5. Verify that: Emoji picker is opened, app is not crashed
6. Click on header
7. Click private notes
8. Press CMD+V or long press to paste
9. Verify that: Text with correct format is pasted and pasted only once

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open a chat
2. Type "> hi" and send message
3. Long press message and click "Copy to clipboard"
4. Open Emoji picker
5. Verify that: Emoji picker is opened, app is not crashed
6. Click on header
7. Click private notes
8. Press CMD+V or long press to paste
9. Verify that: Text with correct format is pasted and pasted only once

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/cdf851fd-61c8-492e-bcb1-b5ec02ccca28

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/ffb22d6e-3158-447b-92b9-39d5e668c80e

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/f6fd8345-87ec-4a64-a08a-471e582ed8ce

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/2e9b4904-f80d-4c16-9dfa-a9b16fc663f8

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/35712432-4132-4f38-91ea-af5512dde7d3

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/05f725cc-9b4b-4c60-8186-88dfd1b6b95d

</details>

### CODE REVIEW

**Review by thesahindia — APPROVED** [review]
LGTM!

**Review by flodnv — APPROVED** [review]

File: src/hooks/useHtmlPaste/index.ts [hunk 1]
```diff
@@ -145,27 +142,16 @@ const useHtmlPaste: UseHtmlPaste = (textInputRef, preHtmlPasteCallback, removeLi
...
         return () => {
-            if (removeListenerOnScreenBlur) {
-                unsubscribeFocus();
-                unsubscribeBlur();
-            }
             document.removeEventListener('paste', handlePaste, true);
         };
         // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
-    }, []);
+    }, [isActive]);
```
Comment (c3024) [inline src/hooks/useHtmlPaste/index.ts:154]: The changes needed to either add the handlePaste dependency here or retrigger this effect some way when handlePaste changes. Fixed here https://github.com/Expensify/App/issues/70279
