### PR TITLE
Do not show dualdropzone on approved requests

### LINKED ISSUE #63807: Split screen - "Hmm... it's not here" page is shown for approved expenses
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.1.63-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/62650
**Email or phone of affected tester (no customers):** applausetester+dave16@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 14.5/ Chrome
**App Component:** Other

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Login with applause email 
3. Create a workspace 
4. Go to WS chat > Create expense > submit and approve the expense.
5. Go to the approved expense report > Drag and drop a file on the scan drop zone 
6. Click the back button on the opened RHN

## Expected Result:
"Hmm... it's not here" page is not shown

## Actual Result:
"Hmm... it's not here" page is shown.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ac61f657-f371-4d46-bbf3-08bbe7b2d9f8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

### PR DESCRIPTION
**Pull request by koko57**
### Fixed Issues

$ https://github.com/Expensify/App/issues/63807
$ https://github.com/Expensify/App/issues/63312
PROPOSAL: - 

### Tests

PREREQUISITES: all betas / newDotMultiFilesDragAndDrop beta enabled 

ONLY ON WEB / DESKTOP

FIX https://github.com/Expensify/App/issues/63807

1. Create a workspace (optional)
2. Go to WS chat > Create expense > submit and approve the expense.
3. Go to the approved expense report > Drag a file on the scan drop zone
4. Verify that only Add Attachment dropzone appears and you can add a file as an attachment (not replace receipt)

FIX https://github.com/Expensify/App/pull/62650#discussion_r2120882537
1. Create new Expense -> Manual (for the workspace expense, do not approve it yet), in a workspace or DM you haven't created an expense in
2. Go to the money request view
3. Try to drag a file over the Report Screen
4. Verify that Dual Dropzone is displayed
5. Verify that you see Scan Receipts dropzone
6. Drop a single file
7. Verify that the receipt is added to the expense
8. Repeat steps 1-4, but now instead of Manual choose Scan request
9. Verify that you see Replace Receipts dropzone
10. Verify that after dropping the file the receipt is replaced

- [x] Verify that no errors appear in the JS console

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

same as above

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

Screenshot 2025-07-01 at 17 39 03

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by brunovjk** [comment]
I've started reviewing, and in web everything seems fine in initial testing:
<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/79c663f3-3a87-46bc-8f31-55515594b928


</details>

But getting deeper it seems like there are several bugs that we're dealing with [here](https://github.com/Expensify/App/issues/63312). I can continue reviewing, but maybe @getusha has more context. What do you think @getusha? Thanks.

**Comment by lakchote** [comment]
Assigning @getusha as they have the most context on this

**Comment by koko57** [comment]
I'm afraid that it's still something wrong with this.
Can someone please help me how can I easily differentiate between this views?

Single transaction:
Screenshot 2025-07-03 at 21 04 09


Transactions View
Screenshot 2025-07-03 at 21 04 47

Transaction Thread View
Screenshot 2025-07-03 at 21 04 57


some checks are true for 2 or all the views and I can't single out easily each view

**Comment by lakchote** [comment]
> Can someone please help me how can I easily differentiate between this views?
> 

I may be missing something, but couldn't we do for instance:

- Single transaction view -> transactions count === 1
- Transactions View -> transactions count > 1
- Transaction Thread View -> check the route name (ex: `/search/view/6092812616199005`)

File: src/pages/home/report/ReportFooter.tsx [hunk 1]
```diff
@@ -47,6 +47,9 @@ type ReportFooterProps = {
     /** Report metadata */
     reportMetadata?: OnyxEntry<OnyxTypes.ReportMetadata>;
 
+    /** Report transactions */
+    reportTransactions?: OnyxEntry<OnyxTypes.Transaction[]>;
```
Comment (DylanDylann) [inline src/pages/home/report/ReportFooter.tsx:51]: Please also pass this prop in other usage of ReportFooter

File: src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx [hunk 2]
```diff
@@ -219,28 +221,31 @@ function ReportActionCompose({
...
     const [transaction] = useOnyx(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {canBeMissing: true});
 
     const hasReceipt = useMemo(() => hasReceiptTransactionUtils(transaction), [transaction]);
+    const isSingleTransactionView = useMemo(() => !!transaction && reportTransactions && reportTransactions.length === 1, [transaction, reportTransactions]);
 
-    const isEditingReceipt = isTransactionThreadView && transactionID && hasReceipt;
+    const shouldDisplayDualDropZone = useMemo(() => {
+        const parentReport = getParentReport(report);
+        const isSettledOrApproved = isSettled(report) || isSettled(parentReport) || isReportApproved({report}) || isReportApproved({report: parentReport});
+        return (shouldAddOrReplaceReceipt && !isSettledOrApproved) || !!temporary_getMoneyRequestOptions(report, policy, reportParticipantIDs).length;
```
Comment (DylanDylann) [inline src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:242]: Why do we need this condition : temporary_getMoneyRequestOptions ?

File: src/pages/home/report/ReportFooter.tsx (hunk 1 above)
Comment (koko57) [reply src/pages/home/report/ReportFooter.tsx:51]: but it's optional

**Comment by DylanDylann** [comment]
BUG: We shouldn't allow replace receipt on distance request

https://github.com/user-attachments/assets/ca21cd77-b046-4cec-9f3e-d768a8579991

File: src/pages/home/report/ReportFooter.tsx (hunk 1 above)
Comment (koko57) [reply src/pages/home/report/ReportFooter.tsx:51]: @DylanDylann does it break anything?

**Comment by DylanDylann** [comment]
@koko57 BUG: When opening transaction view (manual request), It displays `scan receipts` instead of `scan receipt`

https://github.com/user-attachments/assets/6ed614c3-6eb7-4669-8ed2-29fe31c1c8a3

**Comment by koko57** [comment]
@DylanDylann @lakchote both bugs fixed!

File: src/pages/home/report/ReportFooter.tsx (hunk 1 above)
Comment (DylanDylann) [reply src/pages/home/report/ReportFooter.tsx:51]: @koko57 I think we also should apply this change to MoneyRequestReportView

**Comment by DylanDylann** [comment]
@koko57 we have conflicts

File: src/pages/home/report/ReportFooter.tsx (hunk 1 above)
Comment (DylanDylann) [reply src/pages/home/report/ReportFooter.tsx:51]: https://github.com/user-attachments/assets/6997c039-0a32-45bb-8694-b6e7f1a04475

File: src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx [hunk 3]
```diff
@@ -219,28 +221,31 @@ function ReportActionCompose({
...
+        canBeMissing: true,
+    });
+
+    const iouAction = reportActions ? Object.values(reportActions).find((action) => isMoneyRequestAction(action)) : null;
+    const linkedTransactionID = iouAction ? getLinkedTransactionID(iouAction) : undefined;
+    const transactionID = useMemo(() => getTransactionID(reportID) ?? linkedTransactionID, [reportID, linkedTransactionID]);
 
     const [transaction] = useOnyx(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {canBeMissing: true});
 
+    const shouldAddOrReplaceReceipt = (isTransactionThreadView || isIOUReport(report) || isExpenseReport(report)) && !isTransactionsView && !isDistanceRequest(transaction);
```
Comment (DylanDylann) [inline src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:239]:
```suggestion
    const shouldAddOrReplaceReceipt = (isTransactionThreadView || isIOUReport(report) || isExpenseReport(report)) && !isDistanceRequest(transaction);
```

&& !isTransactionsView condition is intentional

Comment (DylanDylann) [inline src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx]:
```suggestion
    const shouldAddOrReplaceReceipt = (isTransactionThreadView || isSingleTransactionView) && !isDistanceRequest(transaction);
```

Comment (DylanDylann) [reply src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx]: shouldAddOrReplaceReceipt should be true in two cases

1. isTransactionThreadView

Screenshot 2025-07-09 at 00 31 11

3. isSingleTransactionView

Screenshot 2025-07-09 at 00 31 21

File: src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx [hunk 4]
```diff
@@ -219,28 +221,31 @@ function ReportActionCompose({
...
+    const isTransactionsView = useMemo(() => reportTransactions && reportTransactions.length > 1, [reportTransactions]);
+
+    const [reportActions] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report?.reportID}`, {
+        canEvict: false,
+        canBeMissing: true,
+    });
+
+    const iouAction = reportActions ? Object.values(reportActions).find((action) => isMoneyRequestAction(action)) : null;
+    const linkedTransactionID = iouAction ? getLinkedTransactionID(iouAction) : undefined;
+    const transactionID = useMemo(() => getTransactionID(reportID) ?? linkedTransactionID, [reportID, linkedTransactionID]);
```
Comment (DylanDylann) [inline src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:232]: In the expense report, this transactionID is incorrect, It should be undefined. transactionID should only be available if it is transaction thread report or single transaction view

https://github.com/user-attachments/assets/c8e20d0a-de3c-476d-b60a-7b0884df33c1

File: src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx (hunk 2 above)
Comment (koko57) [reply src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:242]: it's much easier to check if we can create a transaction, so we can show the Receipt dropzone this way.

File: src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx (hunk 4 above)
Comment (koko57) [reply src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:232]: but if you have a single transaction (i.e. very first expense in a workspace) there is no transactionID and we need it to call replaceReceipt - you can chech this thread https://github.com/Expensify/App/pull/62650#discussion_r2120882537

**Comment by koko57** [comment]
@DylanDylann conflicts resolved, comments addressed

File: src/pages/home/report/ReportFooter.tsx (hunk 1 above)
Comment (DylanDylann) [reply src/pages/home/report/ReportFooter.tsx:51]: @koko57 please check my above video

File: src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx (hunk 4 above)
Comment (DylanDylann) [reply src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:232]: @koko57 In my above video, the expense report has 4 transactions and in this case, transactionID should be undefined. Otherwise, if it is a single transaction, It is correct

File: src/pages/home/report/ReportFooter.tsx (hunk 1 above)
Comment (koko57) [reply src/pages/home/report/ReportFooter.tsx:51]: I've added the prop in MoneyRequestReportView

**Review by DylanDylann — APPROVED** [review]

**Review by lakchote — APPROVED** [review]

File: src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx (hunk 4 above)
Comment (koko57) [reply src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:232]: yep, but this transactionID is only used for replacing receipt. As the dropzone for replacing receipt is not displayed having it not undefined for multiple transactions view won't cause any error. but curious what @lakchote thinks

Comment (lakchote) [reply src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:232]: I get what @DylanDylann is saying, it does make sense.

@koko57, were you unable to make it `undefined` in the case of multiple transaction views for replacing a receipt, because it added side effects difficult to handle?

Comment (koko57) [reply src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:232]: no, it's not that I were unable I can make it undefined for multiple transactions view

Comment (koko57) [reply src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:232]: I just haven't thought of making it undefined explicitly for this case

File: src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx [hunk 5]
```diff
@@ -219,28 +219,28 @@ function ReportActionCompose({
...
 
     const [transaction] = useOnyx(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {canBeMissing: true});
 
-    const hasReceipt = useMemo(() => hasReceiptTransactionUtils(transaction), [transaction]);
+    const isSingleTransactionView = useMemo(() => !!transaction && !!reportTransactions && reportTransactions.length === 1, [transaction, reportTransactions]);
+    const shouldAddOrReplaceReceipt = (isTransactionThreadView || isSingleTransactionView) && !isDistanceRequest(transaction);
 
-    const isEditingReceipt = isTransactionThreadView && transactionID && hasReceipt;
+    const shouldDisplayDualDropZone = useMemo(() => {
```
Comment (hoangzinh) [inline src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx:239]: Coming from https://github.com/Expensify/App/issues/66643. 
We should exclude `isChatRoom` and `isGroupChat`, same as the previous condition. Otherwise, it will display dual zone in group chat and chat room.
